import { QuizBlock, Slide } from '../types/session'

// Deutsch B2: Alexander der Große — dreißig Geschichten

export const alexanderAnecdotesSlidesDE: Slide[] = [
  { id: 'al1', title: "Vater fällt — Sohn kontert", content: "Beim Hochzeitsfest griff der betrunkene Philipp II. mit dem Schwert nach Alexander, stolperte und fiel. Der siebzehnjährige Alexander erwidert kalt: «Da will einer von Europa nach Asien — und kommt nicht einmal vom Lager zum Lager.»", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/01-philip-falls-sword.jpg', title: "Vater fällt — Sohn kontert" }] },
  { id: 'al2', title: "Unehelich?", content: "Der Verwandte Philipps, Attalos, trank und hob einen Toast auf einen «legitimen» Erben — eine Spitze gegen Alexander. Der schleuderte ihm einen Becher entgegen: «Meinst du, ich sei nicht legitim?!» Das Gelage war ruiniert.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/02-attalus-toast.jpg', title: "Unehelich?" }] },
  { id: 'al3', title: "Ägypten wie ein Bart", content: "Ein Soldat fragte am Feuer: «Wozu brauchst du Ägypten?» Alexander zupfte seinen Bart: «Den brauchst du nicht — und trägst ihn doch wie Schmuck. So ist es auch mit Ägypten.»", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/03-egypt-beard.jpg', title: "Ägypten wie ein Bart" }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-ale-1-1-de', text: "Wie alt war Alexander beim Streit mit dem betrunkenen Philipp (Größenordnung)?", type: 'multiple-choice', options: ["Etwa 17","Etwa 30","12","25"], correctAnswer: 0, explanation: "Überlieferung: siebzehnjährig." },
    { id: 'q-ale-1-2-de', text: "Wovon warf Alexander Attalos nach dem Toast?", type: 'multiple-choice', options: ["Einen Becher","einen Dolch","Panzer","Kranz"], correctAnswer: 0, explanation: "Nach dem «legitimen Erben»." },
    { id: 'q-ale-1-3-de', text: "Womit verglich Alexander Ägypten in der Bart-Anekdote?", type: 'multiple-choice', options: ["Mit einem unnötigen, aber getragenen Bart","mit einem Pferd","mit einem Schiff","mit einem Schild"], correctAnswer: 0, explanation: "Schmuck ohne Nutzen — wie Ägypten." }
    ] },
  { id: 'al4', title: "Tränen vor Kyros’ Statue", content: "In Spanien weinte der junge Alexander vor der Statue seines Idols Kyros des Großen. Zu Freunden: «Kyros hatte in meinem Alter schon ein Reich — ich noch nichts.» Er war etwa zwanzig.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/04-cyrus-statue-tears.jpg', title: "Tränen vor Kyros’ Statue" }] },
  { id: 'al5', title: "«Ich wäre auch Diogenes»", content: "Alexander besuchte Diogenes in der Tonne: «Wünsche dir etwas.» — «Tritt beiseite — du nimmst mir die Sonne.» Alexander zu seinem Gefolge: «Wäre ich nicht Alexander, wollte ich Diogenes sein.»", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/05-diogenes-sun.jpg', title: "«Ich wäre auch Diogenes»" }] },
  { id: 'al6', title: "Der Schwur als Falle", content: "Alexander hatte geschworen, keiner Bitte seines Lehrers Anaximenes nachzukommen, und wollte dessen Heimatstadt zerstören. Anaximenes bat: Brenne, plündere und vernichte sie — der Eid zwang Alexander zur Schonung.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/06-anaximenes-oath.jpg', title: "Der Schwur als Falle" }] },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-ale-2-1-de', text: "Vor wessen Statue weinte Alexander in Spanien in dieser Erzählung?", type: 'multiple-choice', options: ["Kyros dem Großen","Homer","Zeus","Hephaistos"], correctAnswer: 0, explanation: "Vorbild-Vergleich im Alter." },
    { id: 'q-ale-2-2-de', text: "Was forderte Diogenes von Alexander?", type: 'multiple-choice', options: ["Platz zu machen — die Sonne zu nehmen","Geld","eine Stadt","Truppen"], correctAnswer: 0, explanation: "Die Pointe mit der Sonne." },
    { id: 'q-ale-2-3-de', text: "Was bat Anaximenes, um die Stadt zu retten, trotz Alexanders Eid?", type: 'multiple-choice', options: ["Stadt zu verbrennen und zu zerstören","Gnade ohne Bedingung","Gold herauszugeben","abzuziehen"], correctAnswer: 0, explanation: "Der Eid zwingt zur Schonung." }
    ] },
  { id: 'al7', title: "«Ich stehle den Sieg nicht»", content: "Ein Feldherr schlug nächtlichen Überfall vor — leichter Sieg. Alexander: «Ich stehle den Sieg nicht» — er lehnte den «billigen» Erfolg ab.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/07-not-steal-victory.jpg', title: "«Ich stehle den Sieg nicht»" }] },
  { id: 'al8', title: "«Später — offene Schlacht»", content: "Vor Gaugamela wollte Parmenion nächtlich angreifen. Alexander lehnte ab, schlief ruhig und schlug Dareios am Tag in offener Feldschlacht — «keinen Sieg stehlen».", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/08-gaugamela-night-parminio.jpg', title: "«Später — offene Schlacht»" }] },
  { id: 'al9', title: "Der Gordische Knoten", content: "Der Knoten sollte mit Händen gelöst werden. Alexander zückte das Schwert und hieb — «der Knoten ist gelöst», erklärte er pragmatisch.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/09-gordian-knot.jpg', title: "Der Gordische Knoten" }] },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-ale-3-1-de', text: "Wie lehnte Alexander nächtlichen Überfall ab (Tenor)?", type: 'multiple-choice', options: ["«Ich stehle den Sieg nicht»","«Einverstanden»","«Wir warten»","«Wir verstecken uns»"], correctAnswer: 0, explanation: "Kein «gestohlener» Sieg." },
    { id: 'q-ale-3-2-de', text: "Was tat Alexander mit dem Gordischen Knoten?", type: 'multiple-choice', options: ["Er durchschnitt ihn mit dem Schwert","löste ihn mit Händen","verbrannte ihn","ließ ihn"], correctAnswer: 0, explanation: "Pragmatische «Lösung»." },
    { id: 'q-ale-3-3-de', text: "Was behielt Alexander sich selbst, laut Antwort an Perdikkas?", type: 'multiple-choice', options: ["Hoffnung","Gold","alle Länder","Pferde"], correctAnswer: 0, explanation: "Ein Wort: Hoffnung." }
    ] },
  { id: 'al10', title: "«Mir blieb die Hoffnung»", content: "Perdikkas fragte, was Alexander sich selbst lasse. «Hoffnung.» — «Dann teilen wir sie mit dir», erwiderte Perdikkas und lehnte das Geschenk ab.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/10-hope-perdiccas.jpg', title: "«Mir blieb die Hoffnung»" }] },
  { id: 'al11', title: "Der Bettler und die Stadt", content: "Ein Armer bat um eine Münze — Alexander schenkte eine ganze Stadt. «Dem Bettler steht Kleingeld zu; mir steht zu, Städte zu verschenken.»", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/11-beggar-city.jpg', title: "Der Bettler und die Stadt" }] },
  { id: 'al12', title: "«Bitte mehr»", content: "Ein Soldat bat zu wenig — der Schatzmeister wies ab. Alexander ärgerte sich: so wenig zu fordern, zweifle an seiner Freigiebigkeit.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/12-ask-more.jpg', title: "«Bitte mehr»" }] },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-ale-4-1-de', text: "Was versprach Alexander dem Bettler statt einer Münze?", type: 'multiple-choice', options: ["Eine ganze Stadt","ein Schiff","ein Pferd","ein Talent Gold"], correctAnswer: 0, explanation: "Großzügigkeit im Maßstab." },
    { id: 'q-ale-4-2-de', text: "Über wen ärgerte sich Alexander wegen der «zu kleinen» Bitte?", type: 'multiple-choice', options: ["Über den Schatzmeister","über den Soldaten","über Perdikkas","über Parmenion"], correctAnswer: 0, explanation: "Die Bitte krankte die Freigiebigkeit." },
    { id: 'q-ale-4-3-de', text: "Was geschah mit den «Kranken»-Listen vor der Wüste?", type: 'multiple-choice', options: ["Sie leerten sich sofort","man verbrannte sie","sie verdoppelten sich","man verlor sie"], correctAnswer: 0, explanation: "List mit der vordersten Reihe." }
    ] },
  { id: 'al13', title: "Wer ist am kränksten?", content: "Vor dem Wüstenmarsch meldeten sich Tausende als krank. Als «Kranke» vorne gehen sollten, um «schneller zur Ruhe» zu kommen — die Listen waren sofort leer.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/13-sick-list-desert.jpg', title: "Wer ist am kränksten?" }] },
  { id: 'al14', title: "Alexander und der Feigling", content: "Ein Deserteur hieß wie der König. Alexander: «Ändere den Namen — oder das Verhalten.»", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/14-coward-name-alexander.jpg', title: "Alexander und der Feigling" }] },
  { id: 'al15', title: "Arzt und Giftbrief", content: "Krank trank er die Arznei des Arztes Philipp — und reichte ihm gleichzeitig Parmenions Brief: «Trink nicht, er ist bestochen.» Er trank und hielt Blickkontakt.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/15-physician-letter-poison.jpg', title: "Arzt und Giftbrief" }] },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-ale-5-1-de', text: "Was riet Alexander dem feigen Namensvetter?", type: 'multiple-choice', options: ["Namen oder Verhalten ändern","auszuscheiden","bedingungslos zu vergeben","nichts"], correctAnswer: 0, explanation: "Der Name Alexander und Feigheit passen nicht." },
    { id: 'q-ale-5-2-de', text: "Von wem kam der Giftbrief zum Arzt Philipp?", type: 'multiple-choice', options: ["Von Parmenion","von Dareios","von Aristoteles","von Diogenes"], correctAnswer: 0, explanation: "Warnung und Vertrauensprobe." },
    { id: 'q-ale-5-3-de', text: "Was tat Alexander mit dem schlafenden Wächter?", type: 'multiple-choice', options: ["Deckte ihn mit seinem Mantel zu","ließ ihn sofort hinrichten","entließ ihn unbestraft","entließ ihn aus dem Dienst"], correctAnswer: 0, explanation: "Gnade statt sofortiger Hinrichtung." }
    ] },
  { id: 'al16', title: "Der schlafende Wächter", content: "Ein Wächter schlief — Todesstrafe. Alexander deckte ihn mit seinem Mantel zu. Am Morgen war die Moral klar: mehr kein Schlafen auf Posten.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/16-sentry-cloak.jpg', title: "Der schlafende Wächter" }] },
  { id: 'al17', title: "Die nackten Weisen", content: "In Indien saßen Philosophen nackt auf heißen Steinen. «Was wollt ihr?» — «Nichts — wir haben alles.» Alexander lachte: reicher als er.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/17-gymnosophists-india.jpg', title: "Die nackten Weisen" }] },
  { id: 'al18', title: "Leben, Tod und Gold", content: "Ein Weiser erklärte das Leben für wichtiger. Alexander bot Gold — der Weise lehnte ab: Ballast für den Geist.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/18-sage-life-death.jpg', title: "Leben, Tod und Gold" }] },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-ale-6-1-de', text: "Wen traf Alexander in Indien «reicher als sich selbst»?", type: 'multiple-choice', options: ["Gymnosophisten","Perser","Elefanten","Osirispriester"], correctAnswer: 0, explanation: "«Wir wollen nichts — wir haben alles.»" },
    { id: 'q-ale-6-2-de', text: "Warum lehnte der indische Weise Gold ab?", type: 'multiple-choice', options: ["Ballast für den Geist","Religionsverbot","Scham","Befehl der Schüler"], correctAnswer: 0, explanation: "Leichtigkeit des Denkens." },
    { id: 'q-ale-6-3-de', text: "Worauf antwortete Diogenes «Wer fürchtet schon das Gute?»?", type: 'multiple-choice', options: ["Ob er Alexander fürchte","was eine Stadt kostet","wo die Sonne steht","wer König ist"], correctAnswer: 0, explanation: "Gut oder böse — wer fürchtet Gutes?" }
    ] },
  { id: 'al19', title: "Diogenes: Gut und Böse", content: "Diogenes: «Bist du gut oder böse?» — «Gut.» — «Wer fürchtet schon das Gute?»", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/19-diogenes-good-evil.jpg', title: "Diogenes: Gut und Böse" }] },
  { id: 'al20', title: "Die Kiste und die Ilias", content: "In Dareios’ prunkvoller Goldtruhe legte Alexander die Ilias — das Einzige, das der Schatz würdig sei.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/20-homer-casket-darius.jpg', title: "Die Kiste und die Ilias" }] },
  { id: 'al21', title: "Dareios’ Mutter irrt sich", content: "Sisygambis hielt Hephaistion für Alexander. Alexander lachte: «Keine Sorge — auch er ist Alexander» (Wortspiel in der Überlieferung).", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/21-hephaestion-sisygambis.jpg', title: "Dareios’ Mutter irrt sich" }] },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-ale-7-1-de', text: "Was legte Alexander in Dareios’ goldene Truhe?", type: 'multiple-choice', options: ["Die Ilias","einen Dolch","das Diadem","einen Brief"], correctAnswer: 0, explanation: "Ehre für Homer." },
    { id: 'q-ale-7-2-de', text: "Wen hielt Sisygambis nach Issos irrtümlich für Alexander?", type: 'multiple-choice', options: ["Hephaistion","Parmenion","Kleitos","Ptolemaios"], correctAnswer: 0, explanation: "Der große Gefährte." },
    { id: 'q-ale-7-3-de', text: "Wo hieß es «Sohn des Zeus» (in dieser Erzähltradition)?", type: 'multiple-choice', options: ["Ammon-Orakel","Delphi","Dodona","Olympia"], correctAnswer: 0, explanation: "Ägypten / Siwa." }
    ] },
  { id: 'al22', title: "«Sohn des Zeus»", content: "Im Ammon-Orakel hieß es «Sohn des Zeus» — Alexander machte daraus Programm und Propaganda.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/22-zeus-son-ammon.jpg', title: "«Sohn des Zeus»" }] },
  { id: 'al23', title: "Persepolis in Flammen", content: "Nach dem Brand von Persepolis nannte Alexander es einen Fehler — selten öffentliche Reue, berichtet Arrian.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/23-persepolis-fire.jpg', title: "Persepolis in Flammen" }] },
  { id: 'al24', title: "«Dem Stärksten»", content: "«Dem Stärksten» — und große Begräbnisse, soll er gesagt haben; die Diadochenkriege folgten.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/24-strongest-successor.jpg', title: "«Dem Stärksten»" }] },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-ale-8-1-de', text: "Wie nutzte Alexander «Sohn des Zeus»?", type: 'multiple-choice', options: ["Als Teil von Image und Propaganda","ignorierte es","verbot Wiederholung","lachte nur einmal"], correctAnswer: 0, explanation: "Politisches Kapital." },
    { id: 'q-ale-8-2-de', text: "Wie bewertete Alexander den Brand von Persepolis am Morgen?", type: 'multiple-choice', options: ["Als Fehler","lobte Thais","schwieg","befahl weiteres Brennen"], correctAnswer: 0, explanation: "Seltene öffentliche Reue (Arrian-Stil)." },
    { id: 'q-ale-8-3-de', text: "Wem vermachte er das Reich — berühmte Formel?", type: 'multiple-choice', options: ["Dem Stärksten","dem Sohn","Perdikkas","Ptolemaios"], correctAnswer: 0, explanation: "Kein Erbe genannt." }
    ] },
  { id: 'al25', title: "Letztes Nicken", content: "Stumm nickte er Tausenden Soldaten zu — Abschied bis zuletzt inszeniert.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/25-last-nod-soldiers.jpg', title: "Letztes Nicken" }] },
  { id: 'al26', title: "«Nicht krank — sterben»", content: "«Ihr redet von Krankheit — ich sterbe, das ist etwas anderes.»", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/26-not-ill-dying.jpg', title: "«Nicht krank — sterben»" }] },
  { id: 'al27', title: "Schlaf vor Gaugamela", content: "Vor Gaugamela schlief er tief — «der Kampf ist schon gewonnen, Dareios stellt sich», meinte er.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/27-sleep-before-gaugamela.jpg', title: "Schlaf vor Gaugamela" }] },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-ale-9-1-de', text: "Was tat Alexander, wenn er nicht sprechen konnte (eine Version)?", type: 'multiple-choice', options: ["Nickte vorbeiziehenden Soldaten zu","schrieb ein Testament","schlief","regungslos"], correctAnswer: 0, explanation: "Abschied von der Armee." },
    { id: 'q-ale-9-2-de', text: "Worin unterschieden sich «Krankheit» und «Sterben» in seiner Replik?", type: 'multiple-choice', options: ["Er stirbt — etwas anderes als Kranksein","gar nicht","nur Fieber","nur Alter"], correctAnswer: 0, explanation: "«Ich sterbe — das ist anders.»" },
    { id: 'q-ale-9-3-de', text: "Warum schlief Alexander vor Gaugamela ruhig (Pointe)?", type: 'multiple-choice', options: ["Dareios stellt sich — Entscheidung fällt","war betrunken","war krank","desertierte"], correctAnswer: 0, explanation: "Ruhe vor der Entscheidungsschlacht." }
    ] },
  { id: 'al28', title: "«Wohlriechend»", content: "Plutarch erwähnt angenehmen Körperduft. Alexander: «Heißes Blut — Temperament, kein Wunder.»", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/28-body-scent-plutarch.jpg', title: "«Wohlriechend»" }] },
  { id: 'al29', title: "Bukephalas und der Schatten", content: "Das Pferd fürchtete den eigenen Schatten — der Junge drehte es zur Sonne. Philipp weinte: «Such dir ein Reich — Makedonien ist zu klein.»", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/29-bucephalus-shadow.jpg', title: "Bukephalas und der Schatten" }] },
  { id: 'al30', title: "Alexander im Spiegel", content: "Klein von Statur, vor Gesandten im Spiegel: «Genau das werden sie sehen» — Charisma schlägt Körpergröße.", duration: 3, media: [{ type: 'image', url: '/media/alexander-anecdotes/30-mirror-negotiations.jpg', title: "Alexander im Spiegel" }] },
  { id: 'q10', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-ale-10-1-de', text: "Wie erklärte Alexander den angenehmen Körperduft (Plutarch-Linie)?", type: 'multiple-choice', options: ["Heißes Blut / Temperament, kein Wunder","Götter","Myrrhe","Magie"], correctAnswer: 0, explanation: "Rationalisierung." },
    { id: 'q-ale-10-2-de', text: "Wovor fürchtete sich Bukephalas laut junger Alexander?", type: 'multiple-choice', options: ["Vor dem eigenen Schatten","Donner","Feuer","Wasser"], correctAnswer: 0, explanation: "Drehung zur Sonne." },
    { id: 'q-ale-10-3-de', text: "Was «sehen» die persischen Gesandten laut Spiegel-Anekdote?", type: 'multiple-choice', options: ["Was sie sehen — Charisma schlägt Größe","nur Kleinwuchs","Gold","nur Armee"], correctAnswer: 0, explanation: "Selbstbild schlägt Physik." }
    ] },
]

export const alexanderAnecdotesFinalQuizDE: QuizBlock = {
  id: 'quiz-alexander-anecdotes-de',
  title: 'Abschlussquiz: Alexander der Große — dreißig Geschichten',
  questions: [
  { id: 'q-ale-1-1-de', text: "Wie alt war Alexander beim Streit mit dem betrunkenen Philipp (Größenordnung)?", type: 'multiple-choice', options: ["Etwa 17","Etwa 30","12","25"], correctAnswer: 0, explanation: "Überlieferung: siebzehnjährig." },
  { id: 'q-ale-2-1-de', text: "Vor wessen Statue weinte Alexander in Spanien in dieser Erzählung?", type: 'multiple-choice', options: ["Kyros dem Großen","Homer","Zeus","Hephaistos"], correctAnswer: 0, explanation: "Vorbild-Vergleich im Alter." },
  { id: 'q-ale-3-1-de', text: "Wie lehnte Alexander nächtlichen Überfall ab (Tenor)?", type: 'multiple-choice', options: ["«Ich stehle den Sieg nicht»","«Einverstanden»","«Wir warten»","«Wir verstecken uns»"], correctAnswer: 0, explanation: "Kein «gestohlener» Sieg." },
  { id: 'q-ale-4-1-de', text: "Was versprach Alexander dem Bettler statt einer Münze?", type: 'multiple-choice', options: ["Eine ganze Stadt","ein Schiff","ein Pferd","ein Talent Gold"], correctAnswer: 0, explanation: "Großzügigkeit im Maßstab." },
  { id: 'q-ale-5-1-de', text: "Was riet Alexander dem feigen Namensvetter?", type: 'multiple-choice', options: ["Namen oder Verhalten ändern","auszuscheiden","bedingungslos zu vergeben","nichts"], correctAnswer: 0, explanation: "Der Name Alexander und Feigheit passen nicht." },
  { id: 'q-ale-6-1-de', text: "Wen traf Alexander in Indien «reicher als sich selbst»?", type: 'multiple-choice', options: ["Gymnosophisten","Perser","Elefanten","Osirispriester"], correctAnswer: 0, explanation: "«Wir wollen nichts — wir haben alles.»" },
  { id: 'q-ale-7-1-de', text: "Was legte Alexander in Dareios’ goldene Truhe?", type: 'multiple-choice', options: ["Die Ilias","einen Dolch","das Diadem","einen Brief"], correctAnswer: 0, explanation: "Ehre für Homer." },
  { id: 'q-ale-8-1-de', text: "Wie nutzte Alexander «Sohn des Zeus»?", type: 'multiple-choice', options: ["Als Teil von Image und Propaganda","ignorierte es","verbot Wiederholung","lachte nur einmal"], correctAnswer: 0, explanation: "Politisches Kapital." },
  { id: 'q-ale-9-1-de', text: "Was tat Alexander, wenn er nicht sprechen konnte (eine Version)?", type: 'multiple-choice', options: ["Nickte vorbeiziehenden Soldaten zu","schrieb ein Testament","schlief","regungslos"], correctAnswer: 0, explanation: "Abschied von der Armee." },
  { id: 'q-ale-10-1-de', text: "Wie erklärte Alexander den angenehmen Körperduft (Plutarch-Linie)?", type: 'multiple-choice', options: ["Heißes Blut / Temperament, kein Wunder","Götter","Myrrhe","Magie"], correctAnswer: 0, explanation: "Rationalisierung." },
  { id: 'q-ale-1-2-de', text: "Wovon warf Alexander Attalos nach dem Toast?", type: 'multiple-choice', options: ["Einen Becher","einen Dolch","Panzer","Kranz"], correctAnswer: 0, explanation: "Nach dem «legitimen Erben»." },
  { id: 'q-ale-2-2-de', text: "Was forderte Diogenes von Alexander?", type: 'multiple-choice', options: ["Platz zu machen — die Sonne zu nehmen","Geld","eine Stadt","Truppen"], correctAnswer: 0, explanation: "Die Pointe mit der Sonne." },
  { id: 'q-ale-3-2-de', text: "Was tat Alexander mit dem Gordischen Knoten?", type: 'multiple-choice', options: ["Er durchschnitt ihn mit dem Schwert","löste ihn mit Händen","verbrannte ihn","ließ ihn"], correctAnswer: 0, explanation: "Pragmatische «Lösung»." },
  { id: 'q-ale-4-2-de', text: "Über wen ärgerte sich Alexander wegen der «zu kleinen» Bitte?", type: 'multiple-choice', options: ["Über den Schatzmeister","über den Soldaten","über Perdikkas","über Parmenion"], correctAnswer: 0, explanation: "Die Bitte krankte die Freigiebigkeit." },
  { id: 'q-ale-5-2-de', text: "Von wem kam der Giftbrief zum Arzt Philipp?", type: 'multiple-choice', options: ["Von Parmenion","von Dareios","von Aristoteles","von Diogenes"], correctAnswer: 0, explanation: "Warnung und Vertrauensprobe." },
  { id: 'q-ale-6-2-de', text: "Warum lehnte der indische Weise Gold ab?", type: 'multiple-choice', options: ["Ballast für den Geist","Religionsverbot","Scham","Befehl der Schüler"], correctAnswer: 0, explanation: "Leichtigkeit des Denkens." },
  { id: 'q-ale-7-2-de', text: "Wen hielt Sisygambis nach Issos irrtümlich für Alexander?", type: 'multiple-choice', options: ["Hephaistion","Parmenion","Kleitos","Ptolemaios"], correctAnswer: 0, explanation: "Der große Gefährte." },
  { id: 'q-ale-8-2-de', text: "Wie bewertete Alexander den Brand von Persepolis am Morgen?", type: 'multiple-choice', options: ["Als Fehler","lobte Thais","schwieg","befahl weiteres Brennen"], correctAnswer: 0, explanation: "Seltene öffentliche Reue (Arrian-Stil)." },
  { id: 'q-ale-9-2-de', text: "Worin unterschieden sich «Krankheit» und «Sterben» in seiner Replik?", type: 'multiple-choice', options: ["Er stirbt — etwas anderes als Kranksein","gar nicht","nur Fieber","nur Alter"], correctAnswer: 0, explanation: "«Ich sterbe — das ist anders.»" },
  { id: 'q-ale-10-2-de', text: "Wovor fürchtete sich Bukephalas laut junger Alexander?", type: 'multiple-choice', options: ["Vor dem eigenen Schatten","Donner","Feuer","Wasser"], correctAnswer: 0, explanation: "Drehung zur Sonne." },
  { id: 'q-ale-1-3-de', text: "Womit verglich Alexander Ägypten in der Bart-Anekdote?", type: 'multiple-choice', options: ["Mit einem unnötigen, aber getragenen Bart","mit einem Pferd","mit einem Schiff","mit einem Schild"], correctAnswer: 0, explanation: "Schmuck ohne Nutzen — wie Ägypten." },
  { id: 'q-ale-2-3-de', text: "Was bat Anaximenes, um die Stadt zu retten, trotz Alexanders Eid?", type: 'multiple-choice', options: ["Stadt zu verbrennen und zu zerstören","Gnade ohne Bedingung","Gold herauszugeben","abzuziehen"], correctAnswer: 0, explanation: "Der Eid zwingt zur Schonung." },
  { id: 'q-ale-3-3-de', text: "Was behielt Alexander sich selbst, laut Antwort an Perdikkas?", type: 'multiple-choice', options: ["Hoffnung","Gold","alle Länder","Pferde"], correctAnswer: 0, explanation: "Ein Wort: Hoffnung." },
  { id: 'q-ale-4-3-de', text: "Was geschah mit den «Kranken»-Listen vor der Wüste?", type: 'multiple-choice', options: ["Sie leerten sich sofort","man verbrannte sie","sie verdoppelten sich","man verlor sie"], correctAnswer: 0, explanation: "List mit der vordersten Reihe." },
  { id: 'q-ale-5-3-de', text: "Was tat Alexander mit dem schlafenden Wächter?", type: 'multiple-choice', options: ["Deckte ihn mit seinem Mantel zu","ließ ihn sofort hinrichten","entließ ihn unbestraft","entließ ihn aus dem Dienst"], correctAnswer: 0, explanation: "Gnade statt sofortiger Hinrichtung." },
  { id: 'q-ale-6-3-de', text: "Worauf antwortete Diogenes «Wer fürchtet schon das Gute?»?", type: 'multiple-choice', options: ["Ob er Alexander fürchte","was eine Stadt kostet","wo die Sonne steht","wer König ist"], correctAnswer: 0, explanation: "Gut oder böse — wer fürchtet Gutes?" },
  { id: 'q-ale-7-3-de', text: "Wo hieß es «Sohn des Zeus» (in dieser Erzähltradition)?", type: 'multiple-choice', options: ["Ammon-Orakel","Delphi","Dodona","Olympia"], correctAnswer: 0, explanation: "Ägypten / Siwa." },
  { id: 'q-ale-8-3-de', text: "Wem vermachte er das Reich — berühmte Formel?", type: 'multiple-choice', options: ["Dem Stärksten","dem Sohn","Perdikkas","Ptolemaios"], correctAnswer: 0, explanation: "Kein Erbe genannt." },
  { id: 'q-ale-9-3-de', text: "Warum schlief Alexander vor Gaugamela ruhig (Pointe)?", type: 'multiple-choice', options: ["Dareios stellt sich — Entscheidung fällt","war betrunken","war krank","desertierte"], correctAnswer: 0, explanation: "Ruhe vor der Entscheidungsschlacht." },
  { id: 'q-ale-10-3-de', text: "Was «sehen» die persischen Gesandten laut Spiegel-Anekdote?", type: 'multiple-choice', options: ["Was sie sehen — Charisma schlägt Größe","nur Kleinwuchs","Gold","nur Armee"], correctAnswer: 0, explanation: "Selbstbild schlägt Physik." }
  ]
}

