import { QuizBlock, Slide } from '../types/session'

// Deutsch B2: Caesar — dreißig Geschichten

export const caesarAnecdotesSlidesDE: Slide[] = [
  { id: 'ca1', title: "Lösegeld zu niedrig", content: "Als die Piraten für Caesar 20 Talente forderten, fühlte er sich beleidigt und erklärte, sie hätten nicht begriffen, wen sie da hätten. Er schlug selbst 50 vor — die Piraten, ratlos, willigten ein und hielten ihn für einen merkwürdigen Reichen.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/01-pirate-ransom.jpg', title: "Lösegeld zu niedrig" }] },
  { id: 'ca2', title: "Kreuzigung als Versprechen", content: "In der Gefangenschaft spielte Caesar freundschaftlich mit den Piraten und versprach regelmäßig, sie alle zu kreuzigen — die lachten. Nach der Lösegeldzahlung fuhr er aus, fing sie und ließ sie kreuzigen, zuvor aber die Kehle durchschneiden, weil er sich mit ihnen angefreundet hatte.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/02-pirate-crucifixion.jpg', title: "Kreuzigung als Versprechen" }] },
  { id: 'ca3', title: "«Schweigt, ich schlafe»", content: "Bei den Piraten benahm er sich wie der Herr der Lage: Wollte er schlafen, befahl er Ruhe — und die Piraten gehorchten, zu ihrer eigenen Überraschung. Autorität entsteht offenbar unabhängig davon, wer wessen Gefangener ist.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/03-pirate-silence.jpg', title: "«Schweigt, ich schlafe»" }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cae-1-1-de', text: "Wie viele Talente forderten die Piraten zuerst für Caesar?", type: 'multiple-choice', options: ["20","50","30","100"], correctAnswer: 0, explanation: "Er hielt die Summe für zu niedrig und schlug 50 vor." },
    { id: 'q-cae-1-2-de', text: "Was tat Caesar den Piraten nach der Lösegeldzahlung laut Erzählung?", type: 'multiple-choice', options: ["Ließ sie frei","Stellte sie und ließ sie kreuzigen (nach Halsdurchschnitt)","nahm sie in die Legion","machte sie zu Magistraten"], correctAnswer: 1, explanation: "Er hielt Wort, schnitt aber zuerst die Kehle durch." },
    { id: 'q-cae-1-3-de', text: "Was befahl Caesar den Piraten, wenn er schlafen wollte?", type: 'multiple-choice', options: ["Ruhe / nicht lärmend","Lieder singen","schneller rudern","Abendessen kochen"], correctAnswer: 0, explanation: "Er gab sich als Herr der Lage." }
    ] },
  { id: 'ca4', title: "Lieber der Erste im Dorf", content: "In einem armen Alpendorf sagte er zu Freunden, er wolle lieber der Erste hier sein als der Zweite in Rom. Die lachten — er meinte es todernst, was komischer war als jeder Witz.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/04-alps-first-village.jpg', title: "Lieber der Erste im Dorf" }] },
  { id: 'ca5', title: "Tränen vor der Statue", content: "In einer spanischen Bibliothek sah er eine Statue Alexanders des Großen und weinte. Auf die Frage der Begleiter: In seinem Alter habe Alexander schon halb die Welt erobert, er selbst noch nichts Bemerkenswertes — er war etwa dreißig.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/05-alexander-statue-tears.jpg', title: "Tränen vor der Statue" }] },
  { id: 'ca6', title: "Der Kranz als beste Auszeichnung", content: "Unter allen Ehren des Senats schätzte Caesar am meisten das Recht, dauernd einen Lorbeerkranz zu tragen — Sueton: weil er die Glatze verbarg. Der Diktator kämpfte gegen Haarausfall so hart wie gegen Vercingetorix.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/06-laurel-baldness.jpg', title: "Der Kranz als beste Auszeichnung" }] },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cae-2-1-de', text: "Vor wessen Statue weinte Caesar in einer spanischen Bibliothek?", type: 'multiple-choice', options: ["Alexander der Große","Scipio","Hannibal","Pompeius"], correctAnswer: 0, explanation: "Vergleich mit Alexanders Alter." },
    { id: 'q-cae-2-2-de', text: "Warum schätzte Caesar den Lorbeerkranz besonders, laut Sueton?", type: 'multiple-choice', options: ["Er verbarg die Glatze","Er gab Immunität vor Gericht","Er war billig","Er ersetzte Eichenlaub"], correctAnswer: 0, explanation: "Der Kranz kaschierte Haarausfall." },
    { id: 'q-cae-2-3-de', text: "Wen wollte Caesar im armen Alpendorf lieber sein?", type: 'multiple-choice', options: ["Den Ersten hier statt den Zweiten in Rom","Den Zweiten hier","Dorfsenator","Jupiterpriester"], correctAnswer: 0, explanation: "Berühmtes Zitat." }
    ] },
  { id: 'ca7', title: "Soldatenlied beim Triumph", content: "Beim Triumph sangen die Soldaten Spottverse: «Versteckt die Frauen — wir führen den kahlen Schürzenjäger!» Caesar ging voraus und lächelte; den Ruf des Verführers störte ihn nicht, die Glatze hatte er längst akzeptiert.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/07-triumph-soldiers-song.jpg', title: "Soldatenlied beim Triumph" }] },
  { id: 'ca8', title: "Frisur des Diktators", content: "Er kämmte die spärlichen Haare vom Hinterkopf nach vorn. Sueton: Er reagierte heftig, wenn ihm im Senat der Kranz gerissen wurde — politische Provokation und persönliche Kränkung zugleich.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/08-caesar-hairstyle-wreath.jpg', title: "Frisur des Diktators" }] },
  { id: 'ca9', title: "«Du trägst Caesar»", content: "Im Sturm fuhr er inkognito in einem Fischerboot. Als der Steuermann die Wellen fürchtete, nannte er sich: «Mut! Du trägst Caesar und sein Glück!» — was den Mann vermutlich noch nervöser machte.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/09-storm-ship-caesar.jpg', title: "«Du trägst Caesar»" }] },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cae-3-1-de', text: "Wen «führten» die Soldaten im Spottlied beim Triumph?", type: 'multiple-choice', options: ["Den «kahlen Schürzenjäger»","Pompeius","Catilina","Cicero"], correctAnswer: 0, explanation: "Spott über Caesar und Glatze." },
    { id: 'q-cae-3-2-de', text: "Wie kaschierte Caesar dünnes Haar?", type: 'multiple-choice', options: ["Vom Hinterkopf nach vorn gekämmt","rasierte Kopf","trug Perücke","ließ es wachsen"], correctAnswer: 0, explanation: "Sueton zur Frisur." },
    { id: 'q-cae-3-3-de', text: "Was rief Caesar dem ängstlichen Steuermann im Sturm zu?", type: 'multiple-choice', options: ["«Du trägst Caesar und sein Glück!»","«Wende!»","«Anker werfen!»","«Ich bin nicht Caesar»"], correctAnswer: 0, explanation: "Nach der Namensnennung." }
    ] },
  { id: 'ca10', title: "Die Erde umarmen", content: "Beim Landgang in Afrika stolperte er und fiel flach hin — die Soldaten erstarrten. Er breitete die Arme aus, umarmte den Boden: «Ich halte dich, Afrika!» Die Armee lachte und ging mit neuem Schwung in den Kampf.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/10-africa-embrace.jpg', title: "Die Erde umarmen" }] },
  { id: 'ca11', title: "Schwimmen mit Akten", content: "In Alexandria schwamm er unter Pfeilen und hielt wichtige Papiere trocken über dem Kopf, den Mantel zwischen den Zähnen. Die Soldaten erzählten das später mit Bewunderung und leichtem Kopfschütteln.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/11-alexandria-swim-documents.jpg', title: "Schwimmen mit Akten" }] },
  { id: 'ca12', title: "Doppelbelagerung", content: "Bei Alesia belagerte er Vercingetorix innen und wurde außen von einer riesigen gallischen Armee belagert. Auf die Meldung von beiden Seiten antwortete er, in zwei Richtungen zu kämpfen spare Zeit.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/12-alesia-double-siege.jpg', title: "Doppelbelagerung" }] },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cae-4-1-de', text: "Was rief Caesar, als er in Afrika hinfiel?", type: 'multiple-choice', options: ["«Ich halte dich, Afrika!»","«Hilfe!»","«Zurück aufs Schiff!»","«Ruhm Rom!»"], correctAnswer: 0, explanation: "Er umarmte die Erde." },
    { id: 'q-cae-4-2-de', text: "Was hielt Caesar beim Schwimmen in Alexandria über dem Kopf?", type: 'multiple-choice', options: ["Papiere trocken","Schild","Gold","Schwert"], correctAnswer: 0, explanation: "Akten wichtiger als nasser Mantel." },
    { id: 'q-cae-4-3-de', text: "Welche Lage hatte Caesars Heer bei Alesia?", type: 'multiple-choice', options: ["Belagerte und wurde belagert","nur von außen angreifend","nur in der Stadt","zog nach Germanien ab"], correctAnswer: 0, explanation: "Doppelring der Belagerung." }
    ] },
  { id: 'ca13', title: "«Sulla konnte nicht lesen»", content: "Warum keine Proskriptionen wie Sulla? Caesar: «Sulla konnte nicht lesen» — ein Gebildeter weiß: ein lebender, dir verpflichteter Feind nützt mehr als ein toter.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/13-sulla-letters.jpg', title: "«Sulla konnte nicht lesen»" }] },
  { id: 'ca14', title: "Schulden als Strategie", content: "In der Jugend machte er riesige Schulden (~25 Mio. Sesterzen). Politik brauche Geld oder Schulden — letzteres sei besser, denn Gläubiger hätten ein vitales Interesse an deinem Aufstieg.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/14-debts-politics.jpg', title: "Schulden als Strategie" }] },
  { id: 'ca15', title: "Die Krone — dreimal Nein", content: "Bei den Luperkalien bot Antonius dreimal die Königskrone an — Caesar lehnte dreimal unter Applaus ab. Cicero meinte, es sei inszeniert: Caesar testete, ob das Volk die Monarchie wolle.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/15-lupercalia-crown.jpg', title: "Die Krone — dreimal Nein" }] },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cae-5-1-de', text: "Warum keine Proskriptionen wie Sulla, laut Pointe?", type: 'multiple-choice', options: ["«Sulla konnte nicht lesen» — lebender Feind nützt mehr","Angst vor dem Senat","Analphabet","Liebe zu Sulla"], correctAnswer: 0, explanation: "Berühmte Sentenz." },
    { id: 'q-cae-5-2-de', text: "Schuldenhöhe der Jugend Caesars (Größenordnung)?", type: 'multiple-choice', options: ["ca. 25 Millionen Sesterzen","1 Million","100 000","500 000"], correctAnswer: 0, explanation: "Riesige Summe in der Überlieferung." },
    { id: 'q-cae-5-3-de', text: "Wie oft bot man Caesar bei den Luperkalien die Krone an?", type: 'multiple-choice', options: ["Dreimal","Einmal","Zehnmal","Nie"], correctAnswer: 0, explanation: "Antonius und drei Ablehnungen." }
    ] },
  { id: 'ca16', title: "Pontius Aquila", content: "Der Tribun Pontius Aquila blieb sitzen, als Caesar vorbeifuhr. Caesar war wütend und ergänzte tagelang jedes öffentliche Versprechen mit: «…sofern Pontius Aquila einwilligt.»", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/16-pontius-aquila.jpg', title: "Pontius Aquila" }] },
  { id: 'ca17', title: "«Nicht ich — Pompeius»", content: "Bei Vorwürfen der Amtsmissbräuche in der Provinz erwiderte er kühl, er sei bescheiden — Pompeius habe halb die Welt mit nicht ganz legalen Methoden erobert.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/17-pompey-blame.jpg', title: "«Nicht ich — Pompeius»" }] },
  { id: 'ca18', title: "Veni, vidi, vici", content: "Nach dem Blitzsieg über Pharnaces schickte er den berühmten Dreizeiler nach Rom — eine gezielte Spitze gegen Feldherren mit seitenlangen Siegesberichten.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/18-veni-vidi-vici.jpg', title: "Veni, vidi, vici" }] },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cae-6-1-de', text: "Wer blieb sitzen, als Caesar an den Tribunen vorbeifuhr?", type: 'multiple-choice', options: ["Tribun Pontius Aquila","Cicero","Brutus","Kleopatra"], correctAnswer: 0, explanation: "Caesars Spott folgte tagelang." },
    { id: 'q-cae-6-2-de', text: "Wen nannte Caesar bei Provinzvorwürfen als «wirklichen» Eroberer?", type: 'multiple-choice', options: ["Pompeius","Crassus","Sulla","sich selbst"], correctAnswer: 0, explanation: "«Nicht ich — Pompeius»." },
    { id: 'q-cae-6-3-de', text: "Welche drei lateinischen Worte schickte Caesar nach dem Sieg über Pharnaces?", type: 'multiple-choice', options: ["Veni, vidi, vici","Ave Caesar","Carpe diem","Et tu, Brute"], correctAnswer: 0, explanation: "Der Siegesbericht." }
    ] },
  { id: 'ca19', title: "Antwort an den Neider", content: "Ein Senator sagte, Caesar habe alles mit unlauteren Mitteln erreicht. Caesar: «Schön, dass du meinen Weg als Erfolgsrezept anerkennst.»", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/19-envy-reply.jpg', title: "Antwort an den Neider" }] },
  { id: 'ca20', title: "Der schlechte Dichter", content: "Ein mittelmäßiger Dichter bot Verse gegen großzügige Belohnung an. Caesar ließ so viel zahlen, wie die Verse seiner Meinung nach wert waren — sehr wenig.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/20-bad-poet-coins.jpg', title: "Der schlechte Dichter" }] },
  { id: 'ca21', title: "Zu Cicero", content: "Nach einer langen glänzenden Rede Ciceros: «Die Argumente sind großartig — deshalb stimme ich nicht zu, sonst glaubst du, du hättest immer recht.»", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/21-cicero-speech.jpg', title: "Zu Cicero" }] },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cae-7-1-de', text: "Worauf zielte Caesars Antwort dem «Neider» über unlautere Mittel?", type: 'multiple-choice', options: ["Er bestätige den Weg zum Erfolg","Zum Duell","Senatsbeschwerde","Tränen"], correctAnswer: 0, explanation: "Ironische Anerkennung." },
    { id: 'q-cae-7-2-de', text: "Wie «honorierte» Caesar den aufdringlichen Dichter?", type: 'multiple-choice', options: ["Münzen nach Wert der Verse — sehr wenig","machte ihn zum Poetenlaureaten","verbrannte die Rolle","ernannte ihn zum Bibliothekar"], correctAnswer: 0, explanation: "Zahlung proportional zur Meinung." },
    { id: 'q-cae-7-3-de', text: "Warum wollte Caesar Cicero nach großer Rede nicht zustimmen?", type: 'multiple-choice', options: ["Sonst glaubt Cicero, immer recht zu haben","weil er taub war","weil er schlief","weil er kein Latein konnte"], correctAnswer: 0, explanation: "Geistreiche Absage." }
    ] },
  { id: 'ca22', title: "Spargel mit Myrrhe", content: "Spargel mit Myrrhe statt Öl — Caesar aß schweigend und tadelte Gäste, die sich rümpften: Man solle essen, was einem nicht schmeckt, ohne den Gastgeber zu kritisieren.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/22-asparagus-myrrh.jpg', title: "Spargel mit Myrrhe" }] },
  { id: 'ca23', title: "«Hüte dich vor den Iden»", content: "Der Seher Spurinna warnte vor den Iden des März. Am 15. rief Caesar: «Die Iden sind da!» — «Ja, aber sie sind noch nicht vorbei», antwortete Spurinna. Eine Stunde später war Caesar tot.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/23-ides-march-spurinna.jpg', title: "«Hüte dich vor den Iden»" }] },
  { id: 'ca24', title: "Der beste Tod", content: "Tage vor dem Mord fragte man nach einem guten Tod. Caesar: «Einen plötzlichen.» Am 15. März 44 v. Chr. traf genau das zu — 23 Dolchstiche.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/24-sudden-death.jpg', title: "Der beste Tod" }] },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cae-8-1-de', text: "Womit wurde der Spargel auf jenem Gastmahl gewürzt?", type: 'multiple-choice', options: ["Myrrhe statt Öl","Pfeffer","Essig","Honig"], correctAnswer: 0, explanation: "Fehler oder Geiz des Gastgebers." },
    { id: 'q-cae-8-2-de', text: "Wie antwortete Spurinna auf «Die Iden sind da»?", type: 'multiple-choice', options: ["«Ja — aber sie sind noch nicht vorbei»","«Alles wird gut»","«Geh nach Hause»","«Ich lag falsch»"], correctAnswer: 0, explanation: "Berühmter Dialog." },
    { id: 'q-cae-8-3-de', text: "Welchen Tod nannte Caesar kurz vor dem Mord als den besten?", type: 'multiple-choice', options: ["Einen plötzlichen","im Kampf","im Bett","im hohen Alter"], correctAnswer: 0, explanation: "Ironie des Schicksals." }
    ] },
  { id: 'ca25', title: "Letzte Geste", content: "Als die Stiche kamen, hörte er auf zu wehren, hüllte sich in die Toga und fiel so, dass die Beine bedeckt waren — selbst im Sterben achtete er auf das Bild.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/25-death-toga-fall.jpg', title: "Letzte Geste" }] },
  { id: 'ca26', title: "Das Testament als Rache", content: "Im Testament 300 Sesterzen pro Bürger und öffentliche Gärten. Als Antonius es verlas, stürmte das Volk zu den Häusern der Mörder — ein postumer Schlag.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/26-caesar-will-people.jpg', title: "Das Testament als Rache" }] },
  { id: 'ca27', title: "Sieben Diktate gleichzeitig", content: "Er diktierte gleichzeitig an mehrere Schreiber, in heißen Phasen bis zu sieben, berichtet Sueton — Zeitgenossen hielten das für übernatürlich.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/27-seven-secretaries.jpg', title: "Sieben Diktate gleichzeitig" }] },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cae-9-1-de', text: "Wie viele Dolchstiche nennt die Überlieferung oft für den 15. März 44 v. Chr.?", type: 'multiple-choice', options: ["23","7","1","40"], correctAnswer: 0, explanation: "Traditionelle Zahl in späterer Darstellung." },
    { id: 'q-cae-9-2-de', text: "Wie viele Sesterzen pro Bürger im Testament Caesars laut Erzählung?", type: 'multiple-choice', options: ["300","30","3000","0"], correctAnswer: 0, explanation: "Testament und Volkswut." },
    { id: 'q-cae-9-3-de', text: "Bis zu wie vielen Schreibern diktierte Caesar in heißen Phasen, laut Sueton?", type: 'multiple-choice', options: ["Sieben","Zwei","Drei","Zehn"], correctAnswer: 0, explanation: "Multitasking der Antike." }
    ] },
  { id: 'ca28', title: "Epilepsie kein Hindernis", content: "Anfälle mitten in Feldzügen — er verbarg sie nicht, kam zu sich und kommandierte weiter. Plutarch: Die Soldaten respektierten ihn dafür fast mehr als für Siege.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/28-epilepsy.jpg', title: "Epilepsie kein Hindernis" }] },
  { id: 'ca29', title: "«Ich bin nicht abergläubisch, aber…»", content: "Er spottete über Aberglauben, befolgte aber Riten, meidete ungünstige Tage und umging umgestürzte Wagen dreimal. «Ich glaube nicht an Zeichen — ich respektiere sie.»", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/29-superstition.jpg', title: "«Ich bin nicht abergläubisch, aber…»" }] },
  { id: 'ca30', title: "Kleopatra aus dem Teppich", content: "Kleopatra ließ sich in einen Teppich wickeln und als Fracht ins Palastinnere schmuggeln. Als man sie vor Caesar ausrollte, beeindruckte ihn vor allem die List.", duration: 3, media: [{ type: 'image', url: '/media/caesar-anecdotes/30-cleopatra-carpet.jpg', title: "Kleopatra aus dem Teppich" }] },
  { id: 'q10', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cae-10-1-de', text: "Wer schätzte Caesars Umgang mit Anfällen im Feld besonders, laut Plutarch-Linie?", type: 'multiple-choice', options: ["Die Soldaten","Senatoren","Priester","Piraten"], correctAnswer: 0, explanation: "Epilepsie im Feldzug." },
    { id: 'q-cae-10-2-de', text: "Wie fasste Caesar sein Verhältnis zu Omen zusammen?", type: 'multiple-choice', options: ["«Ich glaube nicht — ich respektiere»","«Ich glaube blind»","«Omen sind Quatsch»","«Nur griechische»"], correctAnswer: 0, explanation: "Widerspruch zu Riten." },
    { id: 'q-cae-10-3-de', text: "Wie gelangte Kleopatra laut Anekdote an Caesar vorbei an der Wache des Ptolemaios?", type: 'multiple-choice', options: ["Im Teppich als Fracht","im Fass","durch Geheimgang","nachts im Boot"], correctAnswer: 0, explanation: "Berühmter Trick." }
    ] },
]

export const caesarAnecdotesFinalQuizDE: QuizBlock = {
  id: 'quiz-caesar-anecdotes-de',
  title: 'Abschlussquiz: Caesar — dreißig Geschichten',
  questions: [
  { id: 'q-cae-1-1-de', text: "Wie viele Talente forderten die Piraten zuerst für Caesar?", type: 'multiple-choice', options: ["20","50","30","100"], correctAnswer: 0, explanation: "Er hielt die Summe für zu niedrig und schlug 50 vor." },
  { id: 'q-cae-2-1-de', text: "Vor wessen Statue weinte Caesar in einer spanischen Bibliothek?", type: 'multiple-choice', options: ["Alexander der Große","Scipio","Hannibal","Pompeius"], correctAnswer: 0, explanation: "Vergleich mit Alexanders Alter." },
  { id: 'q-cae-3-1-de', text: "Wen «führten» die Soldaten im Spottlied beim Triumph?", type: 'multiple-choice', options: ["Den «kahlen Schürzenjäger»","Pompeius","Catilina","Cicero"], correctAnswer: 0, explanation: "Spott über Caesar und Glatze." },
  { id: 'q-cae-4-1-de', text: "Was rief Caesar, als er in Afrika hinfiel?", type: 'multiple-choice', options: ["«Ich halte dich, Afrika!»","«Hilfe!»","«Zurück aufs Schiff!»","«Ruhm Rom!»"], correctAnswer: 0, explanation: "Er umarmte die Erde." },
  { id: 'q-cae-5-1-de', text: "Warum keine Proskriptionen wie Sulla, laut Pointe?", type: 'multiple-choice', options: ["«Sulla konnte nicht lesen» — lebender Feind nützt mehr","Angst vor dem Senat","Analphabet","Liebe zu Sulla"], correctAnswer: 0, explanation: "Berühmte Sentenz." },
  { id: 'q-cae-6-1-de', text: "Wer blieb sitzen, als Caesar an den Tribunen vorbeifuhr?", type: 'multiple-choice', options: ["Tribun Pontius Aquila","Cicero","Brutus","Kleopatra"], correctAnswer: 0, explanation: "Caesars Spott folgte tagelang." },
  { id: 'q-cae-7-1-de', text: "Worauf zielte Caesars Antwort dem «Neider» über unlautere Mittel?", type: 'multiple-choice', options: ["Er bestätige den Weg zum Erfolg","Zum Duell","Senatsbeschwerde","Tränen"], correctAnswer: 0, explanation: "Ironische Anerkennung." },
  { id: 'q-cae-8-1-de', text: "Womit wurde der Spargel auf jenem Gastmahl gewürzt?", type: 'multiple-choice', options: ["Myrrhe statt Öl","Pfeffer","Essig","Honig"], correctAnswer: 0, explanation: "Fehler oder Geiz des Gastgebers." },
  { id: 'q-cae-9-1-de', text: "Wie viele Dolchstiche nennt die Überlieferung oft für den 15. März 44 v. Chr.?", type: 'multiple-choice', options: ["23","7","1","40"], correctAnswer: 0, explanation: "Traditionelle Zahl in späterer Darstellung." },
  { id: 'q-cae-10-1-de', text: "Wer schätzte Caesars Umgang mit Anfällen im Feld besonders, laut Plutarch-Linie?", type: 'multiple-choice', options: ["Die Soldaten","Senatoren","Priester","Piraten"], correctAnswer: 0, explanation: "Epilepsie im Feldzug." },
  { id: 'q-cae-1-2-de', text: "Was tat Caesar den Piraten nach der Lösegeldzahlung laut Erzählung?", type: 'multiple-choice', options: ["Ließ sie frei","Stellte sie und ließ sie kreuzigen (nach Halsdurchschnitt)","nahm sie in die Legion","machte sie zu Magistraten"], correctAnswer: 1, explanation: "Er hielt Wort, schnitt aber zuerst die Kehle durch." },
  { id: 'q-cae-2-2-de', text: "Warum schätzte Caesar den Lorbeerkranz besonders, laut Sueton?", type: 'multiple-choice', options: ["Er verbarg die Glatze","Er gab Immunität vor Gericht","Er war billig","Er ersetzte Eichenlaub"], correctAnswer: 0, explanation: "Der Kranz kaschierte Haarausfall." },
  { id: 'q-cae-3-2-de', text: "Wie kaschierte Caesar dünnes Haar?", type: 'multiple-choice', options: ["Vom Hinterkopf nach vorn gekämmt","rasierte Kopf","trug Perücke","ließ es wachsen"], correctAnswer: 0, explanation: "Sueton zur Frisur." },
  { id: 'q-cae-4-2-de', text: "Was hielt Caesar beim Schwimmen in Alexandria über dem Kopf?", type: 'multiple-choice', options: ["Papiere trocken","Schild","Gold","Schwert"], correctAnswer: 0, explanation: "Akten wichtiger als nasser Mantel." },
  { id: 'q-cae-5-2-de', text: "Schuldenhöhe der Jugend Caesars (Größenordnung)?", type: 'multiple-choice', options: ["ca. 25 Millionen Sesterzen","1 Million","100 000","500 000"], correctAnswer: 0, explanation: "Riesige Summe in der Überlieferung." },
  { id: 'q-cae-6-2-de', text: "Wen nannte Caesar bei Provinzvorwürfen als «wirklichen» Eroberer?", type: 'multiple-choice', options: ["Pompeius","Crassus","Sulla","sich selbst"], correctAnswer: 0, explanation: "«Nicht ich — Pompeius»." },
  { id: 'q-cae-7-2-de', text: "Wie «honorierte» Caesar den aufdringlichen Dichter?", type: 'multiple-choice', options: ["Münzen nach Wert der Verse — sehr wenig","machte ihn zum Poetenlaureaten","verbrannte die Rolle","ernannte ihn zum Bibliothekar"], correctAnswer: 0, explanation: "Zahlung proportional zur Meinung." },
  { id: 'q-cae-8-2-de', text: "Wie antwortete Spurinna auf «Die Iden sind da»?", type: 'multiple-choice', options: ["«Ja — aber sie sind noch nicht vorbei»","«Alles wird gut»","«Geh nach Hause»","«Ich lag falsch»"], correctAnswer: 0, explanation: "Berühmter Dialog." },
  { id: 'q-cae-9-2-de', text: "Wie viele Sesterzen pro Bürger im Testament Caesars laut Erzählung?", type: 'multiple-choice', options: ["300","30","3000","0"], correctAnswer: 0, explanation: "Testament und Volkswut." },
  { id: 'q-cae-10-2-de', text: "Wie fasste Caesar sein Verhältnis zu Omen zusammen?", type: 'multiple-choice', options: ["«Ich glaube nicht — ich respektiere»","«Ich glaube blind»","«Omen sind Quatsch»","«Nur griechische»"], correctAnswer: 0, explanation: "Widerspruch zu Riten." },
  { id: 'q-cae-1-3-de', text: "Was befahl Caesar den Piraten, wenn er schlafen wollte?", type: 'multiple-choice', options: ["Ruhe / nicht lärmend","Lieder singen","schneller rudern","Abendessen kochen"], correctAnswer: 0, explanation: "Er gab sich als Herr der Lage." },
  { id: 'q-cae-2-3-de', text: "Wen wollte Caesar im armen Alpendorf lieber sein?", type: 'multiple-choice', options: ["Den Ersten hier statt den Zweiten in Rom","Den Zweiten hier","Dorfsenator","Jupiterpriester"], correctAnswer: 0, explanation: "Berühmtes Zitat." },
  { id: 'q-cae-3-3-de', text: "Was rief Caesar dem ängstlichen Steuermann im Sturm zu?", type: 'multiple-choice', options: ["«Du trägst Caesar und sein Glück!»","«Wende!»","«Anker werfen!»","«Ich bin nicht Caesar»"], correctAnswer: 0, explanation: "Nach der Namensnennung." },
  { id: 'q-cae-4-3-de', text: "Welche Lage hatte Caesars Heer bei Alesia?", type: 'multiple-choice', options: ["Belagerte und wurde belagert","nur von außen angreifend","nur in der Stadt","zog nach Germanien ab"], correctAnswer: 0, explanation: "Doppelring der Belagerung." },
  { id: 'q-cae-5-3-de', text: "Wie oft bot man Caesar bei den Luperkalien die Krone an?", type: 'multiple-choice', options: ["Dreimal","Einmal","Zehnmal","Nie"], correctAnswer: 0, explanation: "Antonius und drei Ablehnungen." },
  { id: 'q-cae-6-3-de', text: "Welche drei lateinischen Worte schickte Caesar nach dem Sieg über Pharnaces?", type: 'multiple-choice', options: ["Veni, vidi, vici","Ave Caesar","Carpe diem","Et tu, Brute"], correctAnswer: 0, explanation: "Der Siegesbericht." },
  { id: 'q-cae-7-3-de', text: "Warum wollte Caesar Cicero nach großer Rede nicht zustimmen?", type: 'multiple-choice', options: ["Sonst glaubt Cicero, immer recht zu haben","weil er taub war","weil er schlief","weil er kein Latein konnte"], correctAnswer: 0, explanation: "Geistreiche Absage." },
  { id: 'q-cae-8-3-de', text: "Welchen Tod nannte Caesar kurz vor dem Mord als den besten?", type: 'multiple-choice', options: ["Einen plötzlichen","im Kampf","im Bett","im hohen Alter"], correctAnswer: 0, explanation: "Ironie des Schicksals." },
  { id: 'q-cae-9-3-de', text: "Bis zu wie vielen Schreibern diktierte Caesar in heißen Phasen, laut Sueton?", type: 'multiple-choice', options: ["Sieben","Zwei","Drei","Zehn"], correctAnswer: 0, explanation: "Multitasking der Antike." },
  { id: 'q-cae-10-3-de', text: "Wie gelangte Kleopatra laut Anekdote an Caesar vorbei an der Wache des Ptolemaios?", type: 'multiple-choice', options: ["Im Teppich als Fracht","im Fass","durch Geheimgang","nachts im Boot"], correctAnswer: 0, explanation: "Berühmter Trick." }
  ]
}

