import { Slide, QuizBlock } from '../types/session'

// Deutsche Übersetzungen (B1-B2): Burgen — Kriegsarchitektur und Ruin
export const castleWarfareSlidesDE: Slide[] = [
  { id: 'c1', title: 'Burg — keine Romantik, sondern Finanzloch', content: 'Die mittelalterliche Burg — Symbol der Macht, aber vor allem — riesige Ausgaben. Der Bau einer großen Burg konnte das Jahreseinkommen eines Königs verschlingen. Garnison unterhalten, Reparaturen, Belagerungsgeräte — alles kostete ein Vermögen. Die Ritterromantik verdeckt das Wichtigste: Burgen ruinierten ihre Besitzer.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/castle-main.jpg', title: 'Mittelalterliche Burg' }] },
  { id: 'c2', title: 'Baukosten — Budget des Königreichs', content: 'Burg Conwy in Wales kostete 15.000 Pfund — das Jahresbudget der englischen Krone. Eduard I. gab für walisische Burgen 80.000 Pfund aus — mehr als für alle Kriege zusammen. Eine Burg = Ruin für Barone, mehrere Burgen = Probleme für den König.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/cost.jpg', title: 'Kosten' }] },
  { id: 'c3', title: 'Konzentrische Burg — am teuersten', content: 'Konzentrische Burg — zwei Mauerlinien, eine innerhalb der anderen. Doppelter Schutz — doppelter Preis. Caerphilly in Wales — 19.000 Pfund. Zum Vergleich: Ein einfacher Bergfried kostete 300–500 Pfund. Konzentrische Burgen — für Könige, nicht für Barone.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/concentric.jpg', title: 'Konzentrische Burg' }] },
  { id: 'c4', title: 'Caerphilly und Conwy — Beispiele für Ruin', content: 'Caerphilly — eine der größten Burgen Europas. Bauzeit: 30 Jahre. Besitzer Gilbert de Clare war fast ruiniert. Conwy — 4 Jahre Bau, 15.000 Pfund. Eduard I. nahm Kredite bei italienischen Bankiers auf. Burgen — Machtdemonstration, aber der Preis — Schulden.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/caerphilly.jpg', title: 'Caerphilly' }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-castle-1-1', text: 'Was kostete Burg Conwy?', type: 'multiple-choice', options: ['500 Pfund', '5.000 Pfund', '15.000 Pfund', '50.000 Pfund'], correctAnswer: 2, explanation: '15.000 Pfund — das Jahresbudget der Krone.' },
    { id: 'q-castle-1-2', text: 'Was ist eine konzentrische Burg?', type: 'multiple-choice', options: ['Runde Burg', 'Zwei Mauerlinien', 'Burg auf einem Berg', 'Holzburg'], correctAnswer: 1, explanation: 'Zwei Mauerlinien — doppelter Schutz.' },
    { id: 'q-castle-1-3', text: 'Was kostete ein einfacher Bergfried?', type: 'multiple-choice', options: ['50 Pfund', '300–500 Pfund', '5.000 Pfund', '15.000 Pfund'], correctAnswer: 1, explanation: 'Bergfried — 300–500 Pfund.' }
  ]},
  { id: 'c5', title: 'Humor: König ruiniert durch Burgen', content: 'Eduard I. baute 10 Burgen in Wales. Italienische Bankiers gaben Kredite. Der König zahlte sein Leben lang Schulden ab. Man sagte: «Der König hat mehr Mauern als Münzen.» Die Burgen standen — die Kasse war leer. Macht sichtbar, Schulden — nicht.', duration: 3 },
  { id: 'c6', title: 'Steinturm vs Holzturm — Preisunterschied', content: 'Holzturm (Motte und Bailey) — 20–50 Pfund, in Monaten gebaut. Steinturm — 300–1000 Pfund, jahrelanger Bau. Stein brennt nicht, kostet aber 10–20 mal mehr. Die meisten Barone bauten Holz, Könige — Stein.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/wood-vs-stone.jpg', title: 'Holz und Stein' }] },
  { id: 'c7', title: 'Arbeiter: Steinmetze, Zimmerleute — Jahre Arbeit', content: 'Beim Bau von Conwy arbeiteten 1.500 Menschen — Steinmetze, Zimmerleute, Erdarbeiter. Ein Steinmetz — 3 Pence pro Tag. 1.500 Arbeiter über 4 Jahre — 10.000 Pfund nur an Löhnen. Dazu Materialien, Transport, Verpflegung. Eine Burg = eine Arbeiterstadt über Jahre.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/workers.jpg', title: 'Arbeiter' }] },
  { id: 'c8', title: 'Steintransport — Straßen, Flüsse', content: 'Steine wurden über Dutzende Kilometer transportiert — auf Flüssen mit Lastkähnen, auf Straßen mit Karren. Der Transport konnte teurer sein als der Stein selbst. Conwy wurde aus lokalem Stein gebaut — Kosteneinsparung. Burgen fern von Steinbrüchen kosteten doppelt so viel.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/transport.jpg', title: 'Transport' }] },
  { id: 'c9', title: 'Garnison — ständige Ausgaben', content: 'Eine Burg bauen — halbe Sache. Garnison unterhalten — ständige Kosten. 20–50 Soldaten im Frieden, 100–300 im Krieg. Ein Ritter — 2 Shilling pro Tag, ein Bogenschütze — 6 Pence. Jahreskosten für die Garnison — 200–500 Pfund. Eine Burg ohne Garnison — nur eine leere Mauer.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/garrison.jpg', title: 'Garnison' }] },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-castle-2-1', text: 'Was kostete ein Holzturm?', type: 'multiple-choice', options: ['5 Pfund', '20–50 Pfund', '300 Pfund', '1000 Pfund'], correctAnswer: 1, explanation: 'Holzturm — 20–50 Pfund.' },
    { id: 'q-castle-2-2', text: 'Wie viele Arbeiter bauten Conwy?', type: 'multiple-choice', options: ['100', '500', '1.500', '5.000'], correctAnswer: 2, explanation: '1.500 Menschen — Steinmetze, Zimmerleute usw.' },
    { id: 'q-castle-2-3', text: 'Was kostete die Garnison pro Jahr?', type: 'multiple-choice', options: ['10 Pfund', '50 Pfund', '200–500 Pfund', '5.000 Pfund'], correctAnswer: 2, explanation: 'Garnison — 200–500 Pfund im Jahr.' }
  ]},
  { id: 'c10', title: 'Belagerung — monatelanges Warten', content: 'Burgbelagerung — kein schneller Sturm, sondern monatelange Blockade. Die Belagerer bauten ein Lager, gruben Schützengräben, warteten auf Hunger in der Burg. Belagerung von Château Gaillard — 6 Monate. Belagerung von Harlech — 7 Jahre. Zeit = Geld: Die Armee isst, jeden Tag muss bezahlt werden.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/siege.jpg', title: 'Belagerung' }] },
  { id: 'c11', title: 'Belagerungsgeräte — Trebuchet, Ballista', content: 'Trebuchet (Katapult) — warf Steine bis 100 kg auf 200 Meter. Bauzeit — 2 Monate, Kosten — 50–100 Pfund. Ballista — riesige Armbrust. Belagerungsturm — 100–200 Pfund. Belagerungsgeräte kosteten wie eine kleine Burg.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/trebuchet.jpg', title: 'Trebuchet' }] },
  { id: 'c12', title: 'Unterminierung — Ingenieurarbeit', content: 'Unterminierung einer Mauer — klassische Methode. Man grub einen Tunnel, stützte ihn mit Holz, zündete an — die Mauer stürzte ein. Ingenieure-Sappeure — teure Spezialisten. Unterminierung eines Turms in Rochester — 40 Schweine wurden für Fett verbrannt (Schweinefett brennt heiß). Technik löste, was Kraft nicht lösen konnte.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/undermining.jpg', title: 'Unterminierung' }] },
  { id: 'c13', title: 'Hunger in der Burg und im Belagererlager', content: 'Die Burg lagerte Essen für Monate. Aber die belagernde Armee aß auch — 1.000 Soldaten fraßen Tonnen Getreide pro Woche. Nachschub von hinten — Straßen, Tross. Manchmal hungerten die Belagerer früher als die Belagerten. Belagerung von Orléans — die Engländer zogen hungrig ab.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/hunger.jpg', title: 'Hunger' }] },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-castle-3-1', text: 'Wie lange dauerte die Belagerung von Château Gaillard?', type: 'multiple-choice', options: ['1 Monat', '3 Monate', '6 Monate', '1 Jahr'], correctAnswer: 2, explanation: 'Belagerung — 6 Monate.' },
    { id: 'q-castle-3-2', text: 'Was kostete ein Trebuchet?', type: 'multiple-choice', options: ['10 Pfund', '50–100 Pfund', '500 Pfund', '5.000 Pfund'], correctAnswer: 1, explanation: 'Trebuchet — 50–100 Pfund.' },
    { id: 'q-castle-3-3', text: 'Wie zerstörte man eine Mauer durch Unterminierung?', type: 'multiple-choice', options: ['Sprengen', 'Graben, Holzstützen, Anzünden', 'Rammbock', 'Mit Wasser übergießen'], correctAnswer: 1, explanation: 'Tunnel graben, Stützen anzünden — Mauer fällt.' }
  ]},
  { id: 'c14', title: 'Humor: Ratten teurer als Gold', content: 'Während der Belagerung von Paris (885) aßen sowohl Wikinger als auch Belagerte Ratten. Chroniken berichten: «Eine Ratte kostete wie ein Huhn, eine Maus wie ein Ei.» Der Hunger unterschied nicht zwischen Seiten. Belagerung — Wettbewerb, wer länger Hunger und Langeweile erträgt.', duration: 3 },
  { id: 'c15', title: 'Türme — Höhe = Geld', content: 'Hoher Turm — bessere Aussicht und Schutz. Aber jeder Meter Höhe — Tonnen Stein, Jahre Arbeit. Bergfried Rochester — 34 Meter, einer der höchsten Türme Englands. Bauzeit: 10 Jahre. Turmhöhe zeigte den Reichtum des Besitzers: «Mein Turm ist höher — ich bin reicher.»', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/tower-height.jpg', title: 'Hohe Türme' }] },
  { id: 'c16', title: 'Konzentrische Mauern — doppelter Schutz', content: 'Konzentrische Burgen — zwei Mauerlinien. Äußere Mauer — erste Verteidigungslinie. Innere Mauer — letzte Bastion. Zwischen den Mauern — Hof (Ward). Die Eroberung der äußeren Mauer brachte keinen Sieg — die innere wartete. Aber zwei Mauern bauen = doppelt zahlen.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/concentric-walls.jpg', title: 'Konzentrische Mauern' }] },
  { id: 'c17', title: 'Graben und Zugbrücke', content: 'Graben um die Burg — Hindernis für Belagerungstürme und Rammbock. Graben ausheben — Monate Arbeit der Erdarbeiter. Manchmal wurde der Graben mit Wasser gefüllt (wenn ein Fluss in der Nähe war). Zugbrücke — Holzkonstruktion mit Ketten. Hochgezogene Brücke — Burg isoliert. Ein Graben konnte 500–1.000 Pfund kosten.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/moat.jpg', title: 'Graben' }] },
  { id: 'c18', title: 'Mordlöcher (Murder Holes)', content: 'Über dem Tor — Öffnungen in der Decke («Murder Holes»). Durch sie goss man kochendes Wasser, Pech, warf Steine auf Feinde. Das Tor — die verletzlichste Stelle, daher maximaler Schutz. Manche Burgen hatten zwei bis drei Tore hintereinander — eine «Falle».', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/murder-holes.jpg', title: 'Murder Holes' }] },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-castle-4-1', text: 'Wie hoch ist der Bergfried Rochester?', type: 'multiple-choice', options: ['10 Meter', '20 Meter', '34 Meter', '50 Meter'], correctAnswer: 2, explanation: 'Bergfried Rochester — 34 Meter.' },
    { id: 'q-castle-4-2', text: 'Was ist eine konzentrische Burg?', type: 'multiple-choice', options: ['Runde Burg', 'Zwei Mauerlinien', 'Burg auf dem Wasser', 'Burg ohne Türme'], correctAnswer: 1, explanation: 'Zwei Mauerlinien — doppelter Schutz.' },
    { id: 'q-castle-4-3', text: 'Wozu dienen Murder Holes?', type: 'multiple-choice', options: ['Zur Belüftung', 'Kochendes Wasser und Pech gießen', 'Zum Bogenschießen', 'Zum Wasserabfluss'], correctAnswer: 1, explanation: 'Kochendes Wasser, Pech, Steine abwerfen.' }
  ]},
  { id: 'c19', title: 'Burg Château Gaillard — Richards Meisterwerk', content: 'Richard Löwenherz baute Château Gaillard in der Normandie in 2 Jahren (1196–1198). Kosten — 12.000 Pfund. Er nannte sie «meine schöne Einjährige». Konzentrische Mauern, Felsenfundament, strategische Lage an der Seine. Muster der Kriegsarchitektur — und Machtdemonstration des Königs.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/chateau-gaillard.jpg', title: 'Château Gaillard' }] },
  { id: 'c20', title: 'Fall von Château Gaillard — durch den Abort', content: 'Philipp II. August belagerte Château Gaillard 6 Monate. Stürme halfen nicht. Französische Sappeure fanden ein Kapellenfenster am Felsenfuß, drangen hindurch, dann — durch den Abort in der Mauer. Die Garnison kapitulierte. Die perfekte Festung fiel wegen der Toilette.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/fall-chateau.jpg', title: 'Fall von Château Gaillard' }] },
  { id: 'c21', title: 'Humor: Toilette — Schwachstelle', content: 'Mittelalterliche Toiletten (Garderoben) — Öffnung in der Mauer, Abfälle fielen hinunter. Bequem, aber verwundbar. In Château Gaillard kroch der Feind hindurch. Danach bauten Architekten Toiletten mit Gittern und Wendungen. Aber die Moral blieb: In einer Burg ist alles wichtig, sogar die Toilette.', duration: 3 },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-castle-5-1', text: 'Was kostete Château Gaillard?', type: 'multiple-choice', options: ['1.000 Pfund', '5.000 Pfund', '12.000 Pfund', '20.000 Pfund'], correctAnswer: 2, explanation: 'Château Gaillard — 12.000 Pfund.' },
    { id: 'q-castle-5-2', text: 'Wie nahmen die Franzosen Château Gaillard?', type: 'multiple-choice', options: ['Torsturm', 'Durch Kapellenfenster und Abort', 'Bestechung', 'Hunger'], correctAnswer: 1, explanation: 'Durch Fenster und Toilette — unerwarteter Weg.' },
    { id: 'q-castle-5-3', text: 'Wie lange dauerte die Belagerung von Château Gaillard?', type: 'multiple-choice', options: ['1 Monat', '3 Monate', '6 Monate', '1 Jahr'], correctAnswer: 2, explanation: 'Belagerung — 6 Monate.' }
  ]},
  { id: 'c22', title: 'Eduard I. — Burgenbauer von Wales', content: 'Eduard I. eroberte Wales (1277–1283) und baute einen Ring von Burgen zur Kontrolle: Conwy, Caernarfon, Harlech, Beaumaris. Insgesamt 10 Burgen in 20 Jahren. Gesamtkosten — 80.000 Pfund. Zum Vergleich: Jahresbudget der Krone — 30.000 Pfund. Burgen — Politik, aber ruinös.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/edward-castles.jpg', title: 'Eduards Burgen' }] },
  { id: 'c23', title: 'Caernarfon und Conwy — Machtsymbole', content: 'Caernarfon — Symbol englischer Macht in Wales. Dort wurde Eduard II. geboren, der erste «Prince of Wales». Caernarfons Mauern sind von Konstantinopel inspiriert — Demonstration kaiserlicher Ambitionen. Conwy — 4 Jahre Bau, 1.500 Arbeiter. Die Burgen sagten den Walisern: «Wir sind für immer hier.» Die Waliser waren anderer Meinung.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/caernarfon.jpg', title: 'Caernarfon' }] },
  { id: 'c24', title: 'Walisischer Aufstand — Burgen halfen nicht', content: 'Owain Glyndŵr führte 1400 einen Aufstand an. Die Waliser belagerten englische Burgen. Harlech und Aberystwyth fielen. Eduards Burgen hielten stand, verhinderten den Aufstand aber nicht. Mauern sind keine Politik. Burgen konnten Garnisonen halten, aber nicht das Volk.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/welsh-revolt.jpg', title: 'Walisischer Aufstand' }] },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-castle-6-1', text: 'Wie viele Burgen baute Eduard I. in Wales?', type: 'multiple-choice', options: ['3', '5', '10', '20'], correctAnswer: 2, explanation: 'Eduard baute 10 Burgen.' },
    { id: 'q-castle-6-2', text: 'Was kosteten die walisischen Burgen?', type: 'multiple-choice', options: ['10.000 Pfund', '30.000 Pfund', '80.000 Pfund', '150.000 Pfund'], correctAnswer: 2, explanation: '80.000 Pfund über 20 Jahre.' },
    { id: 'q-castle-6-3', text: 'Wer führte 1400 den Aufstand in Wales an?', type: 'multiple-choice', options: ['William Wallace', 'Robert Bruce', 'Owain Glyndŵr', 'Heinrich V.'], correctAnswer: 2, explanation: 'Owain Glyndŵr — Anführer des walisischen Aufstands.' }
  ]},
  { id: 'c25', title: 'Feuerwaffen — Ende der Burgenära', content: '15. Jh.: Aufkommen der Kanonen. Mauern, die Katapulte standhielten, hielten Kanonenkugeln nicht stand. Belagerung Konstantinopels (1453) — türkische Kanonen durchbrachen die Mauern in Wochen. In Europa begann man, Burgen zu modernisieren: niedrige dicke Mauern statt hoher dünner. Aber die Burgenära endete.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/cannons.jpg', title: 'Kanonen' }] },
  { id: 'c26', title: 'Kanonen durchbrechen Mauern', content: 'Eine Kanone kostete 100–500 Pfund, aber eine Kugel durchbrach eine Mauer, deren Bau Jahre gedauert hatte. Burg Bodiam fiel in einem Tag unter Kanonenfeuer. Burgen wurden anders gebaut: Bastionen, Erdwälle, niedrige Profile. Die mittelalterliche Burg mit Türmen war veraltet.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/cannon-impact.jpg', title: 'Kanonen vs Burgen' }] },
  { id: 'c27', title: 'Burgen werden zu Schlössern', content: '16.–17. Jh.: Burgen verlieren militärische Bedeutung. Besitzer bauen sie zu Schlössern um — große Fenster, Gärten, Komfort. Windsor, Versailles — ehemalige Burgen, die zu Residenzen wurden. Die Funktion änderte sich: nicht Verteidigung, sondern Repräsentation. Mauern blieben, aber die Tore standen offen.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/palace.jpg', title: 'Schloss' }] },
  { id: 'c28', title: 'Humor: von Festung zu Hotel', content: 'Viele Burgen sind heute Hotels. In Schottland kann man eine Burg fürs Wochenende mieten. Ehemalige Verteidigungsmauern — jetzt Touristenattraktion. Besitzer scherzen: «Früher wurden wir von Feinden belagert, jetzt von Touristen.» Die Burg wurde zum Geschäft, nicht zur Waffe.', duration: 3 },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-castle-7-1', text: 'Was veränderte Burgen im 15. Jh.?', type: 'multiple-choice', options: ['Pest', 'Feuerwaffen', 'Aufstände', 'Renaissance'], correctAnswer: 1, explanation: 'Kanonen durchbrachen Mauern — Ende der Burgenära.' },
    { id: 'q-castle-7-2', text: 'Was kostete eine Kanone?', type: 'multiple-choice', options: ['10 Pfund', '50 Pfund', '100–500 Pfund', '5.000 Pfund'], correctAnswer: 2, explanation: 'Kanone — 100–500 Pfund.' },
    { id: 'q-castle-7-3', text: 'Wozu wurden Burgen im 16.–17. Jh.?', type: 'multiple-choice', options: ['Zu Gefängnissen', 'Zu Schlössern und Residenzen', 'Zu Klöstern', 'Zu Ruinen'], correctAnswer: 1, explanation: 'Wurden zu Schlössern — Komfort statt Verteidigung.' }
  ]},
  { id: 'c29', title: 'Burg als Machtsymbol', content: 'Die Burg — nicht nur Festung, sondern Symbol. Ein Baron mit Burg — Macht, ohne Burg — niemand. Der König baute Burgen, um Macht zu zeigen. Aufständische Barone eroberten zuerst königliche Burgen. Burg = Legitimität der Macht. Deshalb gab man Vermögen dafür aus.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/symbol-power.jpg', title: 'Machtsymbol' }] },
  { id: 'c30', title: '«Meine Burg ist größer» — Baronen-Wettbewerb', content: 'Barone wetteiferten: Wessen Burg höher, stärker, schöner war. Die Burg zeigte Reichtum und Ambitionen. Gilbert de Clare baute Caerphilly, um königliche Burgen zu übertreffen. Ergebnis — fast Ruin, aber der Status stieg. Burgenwettbewerb = Ressourcenwettbewerb.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/competition.jpg', title: 'Wettbewerb' }] },
  { id: 'c31', title: 'Fazit: Architektur und Ruin', content: 'Burgen — Gipfel mittelalterlicher Architektur. Konzentrische Mauern, hohe Türme, technische Lösungen. Aber der Preis — ruinös. Der Bau einer Burg konnte das Jahreseinkommen eines Königs kosten. Belagerung — monatelange Ausgaben. Unterhalt — ständige Last für das Budget.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/summary.jpg', title: 'Fazit' }] },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-castle-8-1', text: 'Was symbolisierte die Burg im Mittelalter?', type: 'multiple-choice', options: ['Reichtum', 'Macht und Legitimität', 'Kultur', 'Handel'], correctAnswer: 1, explanation: 'Burg = Machtsymbol.' },
    { id: 'q-castle-8-2', text: 'Warum bauten Barone Burgen?', type: 'multiple-choice', options: ['Zur Verteidigung', 'Zur Statusdemonstration', 'Für Handel', 'Alles zusammen'], correctAnswer: 3, explanation: 'Verteidigung, Status, Wettbewerb.' },
    { id: 'q-castle-8-3', text: 'Was kostete der Bau einer großen Burg?', type: 'multiple-choice', options: ['100 Pfund', '500 Pfund', 'Jahreseinkommen des Königs', '10 Jahre Einkommen'], correctAnswer: 2, explanation: 'Konnte das Jahresbudget der Krone kosten.' }
  ]},
  { id: 'c32', title: 'Burgen heute — Tourismus', content: 'Heute sind Burgen Touristenobjekte. Windsor, Edinburgh, Neuschwanstein — Millionen Besucher pro Jahr. Eintrittspreise, Führungen, Souvenirs — Burgen verdienen Geld. Der Staat gibt Millionen für Restaurierung aus. Burgen sind keine Waffen mehr, bleiben aber Symbole.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/tourism.jpg', title: 'Tourismus' }] },
  { id: 'c33', title: 'Humor: jetzt zahlen Besitzer für Reparaturen', content: 'Private Burgbesitzer klagen: Dachreparatur — 100.000 Pfund, Heizung — wie für ein ganzes Dorf. Ein schottischer Graf sagte: «Meine Vorfahren bauten die Burg, um Feinde draußen zu halten. Ich zahle, um den Regen draußen zu halten.» Burg — kein Vermögen, sondern Verpflichtung.', duration: 3 },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-castle-9-1', text: 'Wozu dienen Burgen heute?', type: 'multiple-choice', options: ['Für Krieg', 'Für Tourismus', 'Für Landwirtschaft', 'Für Steinabbau'], correctAnswer: 1, explanation: 'Burgen — Touristenobjekte.' },
    { id: 'q-castle-9-2', text: 'Warum klagen private Besitzer?', type: 'multiple-choice', options: ['Wenige Besucher', 'Teure Reparatur und Unterhalt', 'Steuern', 'Geister'], correctAnswer: 1, explanation: 'Burgreparatur kostet ein Vermögen.' },
    { id: 'q-castle-9-3', text: 'Welche Burgen sind bei Touristen beliebt?', type: 'multiple-choice', options: ['Windsor, Edinburgh, Neuschwanstein', 'Nur in England', 'Nur Ruinen', 'Nur königliche'], correctAnswer: 0, explanation: 'Beliebte Burgen in ganz Europa.' }
  ]},
  { id: 'c34', title: 'Burgen-Erbe in der Kultur', content: 'Burgen — Symbol von Rittertum, Romantik, Mittelalter. Filme, Bücher, Spiele — die Burg steht immer im Zentrum. «Herr der Ringe», «Game of Thrones» — Burgen als Kulisse der Macht. Die Realität war prosaischer: kalte Mauern, teurer Unterhalt, ständige Belagerungsgefahr.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/culture.jpg', title: 'Kultur' }] },
  { id: 'c35', title: 'Schluss: Kriegsarchitektur = Wirtschaft', content: 'Burgen — nicht nur Mauern und Türme. Das ist Wirtschaft: Bau, Unterhalt, Belagerungen. Eine Burg konnte einen Baron oder König ruinieren. Belagerung — monatelange Kosten für beide Seiten. Kriegsarchitektur ist untrennbar von Finanzen. Burgen verstehen — heißt mittelalterliche Wirtschaft verstehen.', duration: 3, media: [{ type: 'image', url: '/media/castle-warfare/conclusion.jpg', title: 'Schluss' }] },
  { id: 'q10', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-castle-10-1', text: 'Was zeigen Burgen in der Kultur?', type: 'multiple-choice', options: ['Nur Krieg', 'Romantik und Rittertum', 'Nur Wirtschaft', 'Nichts'], correctAnswer: 1, explanation: 'Romantisches Bild des Mittelalters.' },
    { id: 'q-castle-10-2', text: 'Was ist wichtiger für Burgen?', type: 'multiple-choice', options: ['Architektur', 'Wirtschaft', 'Beide Aspekte', 'Nur Kriegsgeschichte'], correctAnswer: 2, explanation: 'Architektur und Wirtschaft untrennbar.' },
    { id: 'q-castle-10-3', text: 'Konnten Burgen Besitzer ruinieren?', type: 'multiple-choice', options: ['Nein, niemals', 'Ja, Bau und Unterhalt — riesige Ausgaben', 'Nur Könige', 'Nur Barone'], correctAnswer: 1, explanation: 'Burgen ruinierten Barone und Könige.' }
  ]}
]

export const castleWarfareFinalQuizDE: QuizBlock = {
  id: 'quiz-castle-warfare',
  title: 'Abschlussquiz: Burgen — Kriegsarchitektur und Ruin',
  questions: [
    { id: 'final-c1', text: 'Was kostete Burg Conwy?', type: 'multiple-choice', options: ['500 Pfund', '5.000 Pfund', '15.000 Pfund', '50.000 Pfund'], correctAnswer: 2, explanation: '15.000 Pfund — Jahresbudget.' },
    { id: 'final-c2', text: 'Was ist eine konzentrische Burg?', type: 'multiple-choice', options: ['Rund', 'Zwei Mauerlinien', 'Auf Berg', 'Aus Holz'], correctAnswer: 1, explanation: 'Zwei Mauerlinien.' },
    { id: 'final-c3', text: 'Was kostete ein einfacher Bergfried?', type: 'multiple-choice', options: ['50 Pfund', '300–500 Pfund', '5.000 Pfund', '15.000 Pfund'], correctAnswer: 1, explanation: '300–500 Pfund.' },
    { id: 'final-c4', text: 'Wie viele Arbeiter bauten Conwy?', type: 'multiple-choice', options: ['100', '500', '1.500', '5.000'], correctAnswer: 2, explanation: '1.500 Menschen.' },
    { id: 'final-c5', text: 'Was kostete die Garnison pro Jahr?', type: 'multiple-choice', options: ['10 Pfund', '50 Pfund', '200–500 Pfund', '5.000 Pfund'], correctAnswer: 2, explanation: '200–500 Pfund.' },
    { id: 'final-c6', text: 'Wie lange dauerte die Belagerung von Château Gaillard?', type: 'multiple-choice', options: ['1 Monat', '3 Monate', '6 Monate', '1 Jahr'], correctAnswer: 2, explanation: '6 Monate.' },
    { id: 'final-c7', text: 'Was kostete ein Trebuchet?', type: 'multiple-choice', options: ['10 Pfund', '50–100 Pfund', '500 Pfund', '5.000 Pfund'], correctAnswer: 1, explanation: '50–100 Pfund.' },
    { id: 'final-c8', text: 'Wie zerstörte man eine Mauer?', type: 'multiple-choice', options: ['Sprengen', 'Graben, stützen, anzünden', 'Rammen', 'Übergießen'], correctAnswer: 1, explanation: 'Unterminierung, Stützen, Feuer.' },
    { id: 'final-c9', text: 'Wie hoch ist Bergfried Rochester?', type: 'multiple-choice', options: ['10 m', '20 m', '34 m', '50 m'], correctAnswer: 2, explanation: '34 Meter.' },
    { id: 'final-c10', text: 'Wozu dienen Murder Holes?', type: 'multiple-choice', options: ['Belüftung', 'Kochendes Wasser gießen', 'Schießen', 'Abfluss'], correctAnswer: 1, explanation: 'Kochendes Wasser, Pech, Steine.' },
    { id: 'final-c11', text: 'Was kostete Château Gaillard?', type: 'multiple-choice', options: ['1.000 Pfund', '5.000 Pfund', '12.000 Pfund', '20.000 Pfund'], correctAnswer: 2, explanation: '12.000 Pfund.' },
    { id: 'final-c12', text: 'Wie fiel Château Gaillard?', type: 'multiple-choice', options: ['Sturm', 'Durch Fenster und Toilette', 'Bestechung', 'Hunger'], correctAnswer: 1, explanation: 'Durch Fenster und Abort.' },
    { id: 'final-c13', text: 'Wie viele Burgen baute Eduard I. in Wales?', type: 'multiple-choice', options: ['3', '5', '10', '20'], correctAnswer: 2, explanation: '10 Burgen.' },
    { id: 'final-c14', text: 'Was kosteten die walisischen Burgen?', type: 'multiple-choice', options: ['10.000', '30.000', '80.000', '150.000'], correctAnswer: 2, explanation: '80.000 Pfund.' },
    { id: 'final-c15', text: 'Wer führte 1400 Aufstand in Wales?', type: 'multiple-choice', options: ['Wallace', 'Bruce', 'Owain Glyndŵr', 'Heinrich V.'], correctAnswer: 2, explanation: 'Owain Glyndŵr.' },
    { id: 'final-c16', text: 'Was veränderte Burgen im 15. Jh.?', type: 'multiple-choice', options: ['Pest', 'Feuerwaffen', 'Aufstände', 'Renaissance'], correctAnswer: 1, explanation: 'Kanonen durchbrachen Mauern.' },
    { id: 'final-c17', text: 'Was kostete eine Kanone?', type: 'multiple-choice', options: ['10 Pfund', '50 Pfund', '100–500 Pfund', '5.000 Pfund'], correctAnswer: 2, explanation: '100–500 Pfund.' },
    { id: 'final-c18', text: 'Wozu wurden Burgen im 16.–17. Jh.?', type: 'multiple-choice', options: ['Gefängnisse', 'Schlösser', 'Klöster', 'Ruinen'], correctAnswer: 1, explanation: 'Schlösser und Residenzen.' },
    { id: 'final-c19', text: 'Was symbolisierte eine Burg?', type: 'multiple-choice', options: ['Reichtum', 'Macht', 'Kultur', 'Handel'], correctAnswer: 1, explanation: 'Macht und Legitimität.' },
    { id: 'final-c20', text: 'Warum bauten Barone Burgen?', type: 'multiple-choice', options: ['Verteidigung', 'Statusdemonstration', 'Handel', 'Verteidigung und Status'], correctAnswer: 3, explanation: 'Verteidigung und Wettbewerb.' },
    { id: 'final-c21', text: 'Wozu dienen Burgen heute?', type: 'multiple-choice', options: ['Krieg', 'Tourismus', 'Landwirtschaft', 'Steinabbau'], correctAnswer: 1, explanation: 'Touristenobjekte.' },
    { id: 'final-c22', text: 'Warum klagen Besitzer?', type: 'multiple-choice', options: ['Wenige Besucher', 'Teure Reparatur', 'Steuern', 'Geister'], correctAnswer: 1, explanation: 'Reparatur kostet Vermögen.' },
    { id: 'final-c23', text: 'Konnten Burgen ruinieren?', type: 'multiple-choice', options: ['Nein', 'Ja, riesige Ausgaben', 'Nur Könige', 'Nur Barone'], correctAnswer: 1, explanation: 'Bau und Unterhalt ruinierten.' },
    { id: 'final-c24', text: 'Was kostete ein Holzturm?', type: 'multiple-choice', options: ['5 Pfund', '20–50 Pfund', '300 Pfund', '1.000 Pfund'], correctAnswer: 1, explanation: '20–50 Pfund.' },
    { id: 'final-c25', text: 'Was ist teurer: Bau oder Unterhalt?', type: 'multiple-choice', options: ['Bau', 'Unterhalt', 'Beides teuer', 'Weder noch'], correctAnswer: 2, explanation: 'Beide Aspekte ruinös.' },
    { id: 'final-c26', text: 'Wie lange dauerte Bau einer großen Burg?', type: 'multiple-choice', options: ['1 Jahr', '2–4 Jahre', '10–20 Jahre', '50 Jahre'], correctAnswer: 1, explanation: 'Große Burgen — mindestens 2–4 Jahre.' },
    { id: 'final-c27', text: 'Was fraß eine Armee pro Woche?', type: 'multiple-choice', options: ['Wenig', 'Tonnen Getreide', 'Nur Fleisch', 'Nichts'], correctAnswer: 1, explanation: '1.000 Soldaten — Tonnen Getreide.' },
    { id: 'final-c28', text: 'Was ist wichtiger für Burgen?', type: 'multiple-choice', options: ['Architektur', 'Wirtschaft', 'Beides', 'Nur Krieg'], correctAnswer: 2, explanation: 'Architektur und Wirtschaft untrennbar.' },
    { id: 'final-c29', text: 'Wer baute Château Gaillard?', type: 'multiple-choice', options: ['Philipp II.', 'Richard Löwenherz', 'Eduard I.', 'Heinrich II.'], correctAnswer: 1, explanation: 'Richard Löwenherz.' },
    { id: 'final-c30', text: 'Welche Lehre geben Burgen?', type: 'multiple-choice', options: ['Schönheit wichtig', 'Kriegsarchitektur = Wirtschaft', 'Nur Krieg', 'Nichts'], correctAnswer: 1, explanation: 'Architektur untrennbar von Finanzen.' }
  ]
}
