import { Slide, QuizBlock } from '../types/session'

// Deutsche Übersetzungen (B1-B2): Kleopatra — Politikerin und Ökonomin
export const cleopatraEconomistSlidesDE: Slide[] = [
  { id: 'c1', title: 'Ägypten — Kornkammer des Mittelmeers', content: 'Ägypten lieferte Rom etwa ein Drittel des gesamten Getreides. Ohne ägyptisches Brot hätte die Millionenstadt gehungert. Die Ptolemäer kontrollierten diesen Handel — und die römischen Politiker wussten: Wer Ägypten besitzt, ernährt Rom.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/egypt-grain.jpg', title: 'Ägyptisches Getreide' }] },
  { id: 'c2', title: 'Kleopatra VII: nicht nur Schönheit', content: 'Kleopatra VII herrschte 22 Jahre über Ägypten. Sie sprach sieben Sprachen und studierte Wirtschaft und Medizin. Die römische Propaganda machte aus ihr eine «Verführerin» — aber sie war vor allem eine Politikerin, die ihr Land schützte.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/cleopatra-portrait.jpg', title: 'Kleopatra' }] },
  { id: 'c3', title: 'Ptolemäer: Griechen auf dem Nil-Thron', content: 'Die Dynastie der Ptolemäer herrschte 300 Jahre über Ägypten — seit Alexander dem Großen. Sie behielten das ägyptische Steuersystem und die Monopole, fügten aber griechische Bürokratie hinzu. Die Staatskasse war eine der vollsten in der antiken Welt.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/ptolemaic.jpg', title: 'Ptolemäer' }] },
  { id: 'c4', title: 'Monopole der Pharaonen', content: 'Die Ptolemäer hatten ein Monopol auf Öl, Papyrus, Salz und sogar Bier. Bauern lieferten die Ernte zu festen Preisen in die königlichen Lager. Der Staat verkaufte das Getreide mit Gewinn weiter. Das war eine frühe Form der Planwirtschaft.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/monopoly.jpg', title: 'Monopole' }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cleop-1-1', text: 'Wie viel Getreide lieferte Ägypten an Rom?', type: 'multiple-choice', options: ['Fast alles', 'Etwa ein Drittel', 'Weniger als ein Zehntel', 'Nichts'], correctAnswer: 1, explanation: 'Ägypten lieferte Rom etwa ein Drittel des Getreides.' },
    { id: 'q-cleop-1-2', text: 'Wie lange herrschte Kleopatra VII?', type: 'multiple-choice', options: ['5 Jahre', '12 Jahre', '22 Jahre', '35 Jahre'], correctAnswer: 2, explanation: 'Kleopatra herrschte 22 Jahre über Ägypten.' },
    { id: 'q-cleop-1-3', text: 'Wofür hatten die Ptolemäer Monopole?', type: 'multiple-choice', options: ['Nur Gold', 'Öl, Papyrus, Salz', 'Nur Getreide', 'Nichts'], correctAnswer: 1, explanation: 'Monopole auf Öl, Papyrus, Salz und Bier.' }
  ]},
  { id: 'c5', title: 'Humor: Teppich statt Thron', content: 'Als Kleopatra Caesar treffen wollte, hatte ihr Bruder Ptolemaios XIII den Palast umstellt. Kleopatra ließ sich in einen Teppich wickeln und als «Ware» hineintragen. Caesar war beeindruckt von ihrem Mut — und das Bündnis wurde geschlossen. Politik wichtiger als Etikette.', duration: 3 },
  { id: 'c6', title: 'Caesar in Ägypten: Geld und Krieg', content: 'Caesar kam nach Ägypten, um Pompeius zu verfolgen. Kleopatra brauchte einen Verbündeten im Kampf gegen ihren Bruder. Sie unterstützte Caesar mit Geld und Truppen. Dafür half er ihr, den Thron zurückzugewinnen — und Ägypten blieb unabhängig.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/caesar-egypt.jpg', title: 'Caesar in Ägypten' }] },
  { id: 'c7', title: 'Alexandria — Handelszentrum', content: 'Alexandria war die zweitgrößte Stadt der antiken Welt nach Rom. Durch den Hafen kamen Waren aus Indien, Arabien und Afrika. Die Zölle füllten die Staatskasse. Kleopatra wusste: Wer den Hafen kontrolliert, kontrolliert den Handel.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/alexandria-port.jpg', title: 'Hafen von Alexandria' }] },
  { id: 'c8', title: 'Schulden der Römer bei Ägypten', content: 'Römische Feldherren nahmen von den Ptolemäern große Kredite. Caesar schuldete 6000 Talente — eine Summe wie der Jahresertrag mehrerer Provinzen. Auch Antonius bekam Geld und Getreide aus Ägypten. Ägyptischer Kredit kaufte römische Treue.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/debts.jpg', title: 'Schulden' }] },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cleop-2-1', text: 'Wie gelangte Kleopatra zu Caesar, als der Palast umstellt war?', type: 'multiple-choice', options: ['Durch einen unterirdischen Gang', 'Sie ließ sich in einen Teppich wickeln', 'Sie verkleidete sich als Dienerin', 'Mit dem Schiff'], correctAnswer: 1, explanation: 'Sie wurde im Teppich als «Ware» hineingetragen.' },
    { id: 'q-cleop-2-2', text: 'Wie viele Talente schuldete Caesar Ägypten?', type: 'multiple-choice', options: ['100', '1000', '6000', '10000'], correctAnswer: 2, explanation: 'Caesar schuldete 6000 Talente.' },
    { id: 'q-cleop-2-3', text: 'Welche Stadt war die zweitgrößte der antiken Welt?', type: 'multiple-choice', options: ['Rom', 'Alexandria', 'Athen', 'Karthago'], correctAnswer: 1, explanation: 'Alexandria — zweite Stadt nach Rom.' }
  ]},
  { id: 'c9', title: 'Marcus Antonius und die Ostpolitik', content: 'Nach Caesars Tod teilte Antonius die Macht mit Octavian. Antonius bekam den Osten — und Ägypten. Kleopatra unterstützte ihn mit Geld und Flotte. Dafür erkannte er ihre Kinder als Erben an und übergab ihr Teile des Ostens.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/antony.jpg', title: 'Marcus Antonius' }] },
  { id: 'c10', title: 'Finanzierung des Krieges gegen Octavian', content: '32 v. Chr. erklärten Antonius und Kleopatra Octavian den Krieg. Ägypten gab 200 Schiffe und Geld für die Armee. Die ägyptische Wirtschaft hielt die östliche Koalition — aber die Schlacht bei Actium 31 v. Chr. entschied das Ergebnis.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/fleet.jpg', title: 'Flotte' }] },
  { id: 'c11', title: 'Vergabe von Land als «Donationen»', content: 'Antonius gab östliche Provinzen großzügig an Kleopatras Kinder. Octavian nutzte das in der Propaganda: «Ein Römer gibt römisches Land an eine Ägypterin!» Für Antonius war es ein Bündnis; für Rom — Verrat. Wirtschaft und Politik vermischten sich.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/donations.jpg', title: 'Donationen' }] },
  { id: 'c12', title: 'Humor: Abendessen und Gold', content: 'Der Überlieferung nach wettete Kleopatra mit Antonius, das teuerste Abendessen zu geben. Sie löste eine Perle in Essig auf und trank sie. Antonius gab auf. Historiker zweifeln an den Details — aber das Bild der «Königin, die mit Reichtum wirft» half der Propaganda.', duration: 3 },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cleop-3-1', text: 'Wie viele Schiffe gab Ägypten Antonius?', type: 'multiple-choice', options: ['50', '100', '200', '500'], correctAnswer: 2, explanation: 'Ägypten gab 200 Schiffe.' },
    { id: 'q-cleop-3-2', text: 'In welchem Jahr war die Schlacht bei Actium?', type: 'multiple-choice', options: ['44 v. Chr.', '31 v. Chr.', '27 v. Chr.', '30 v. Chr.'], correctAnswer: 1, explanation: 'Schlacht bei Actium — 31 v. Chr.' },
    { id: 'q-cleop-3-3', text: 'Was soll Kleopatra der Legende nach bei einer Wette aufgelöst und getrunken haben?', type: 'multiple-choice', options: ['Gold', 'Eine Perle in Essig', 'Smaragd', 'Koralle'], correctAnswer: 1, explanation: 'Die Legende von der Perle in Essig.' }
  ]},
  { id: 'c13', title: 'Der Nil — Schlagader der Wirtschaft', content: 'Die Nilüberschwemmung bestimmte die Ernte. Die Ptolemäer bauten Kanäle und Speicher. Steuern wurden in Getreide eingesammelt — und weiterverkauft. Kleopatra achtete persönlich auf die Ernten: Missernte bedeutete Hunger und Aufstände.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/nile.jpg', title: 'Nil' }] },
  { id: 'c14', title: 'Papyrus — ägyptischer Export', content: 'Ägypten war der einzige Hersteller von Papyrus — dem Material für Bücher und Dokumente. Das Monopol brachte große Einnahmen. Römische Beamte zahlten für die Rollen. Kleopatra kontrollierte diesen Handel.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/papyrus.jpg', title: 'Papyrus' }] },
  { id: 'c15', title: 'Caesarion — Caesars Sohn', content: 'Kleopatra gebar Caesar einen Sohn — Ptolemaios XV. Caesarion. Sie erklärte ihn zum Erben Ägyptens und «Sohn eines Gottes». Für Rom war das eine Herausforderung: Ein ägyptischer Prinz konnte Macht beanspruchen. Octavian sah in ihm eine Gefahr.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/caesarion.jpg', title: 'Caesarion' }] },
  { id: 'c16', title: 'Octavian: wirtschaftliche Motive der Eroberung', content: 'Octavian erklärte nicht Rom den Krieg, sondern der «ägyptischen Königin». Der echte Grund war die Staatskasse Ägyptens. Nach dem Sieg nahm er die Schätze der Ptolemäer und zahlte den Legionären ihre versprochenen Belohnungen. Ägypten wurde persönlicher Besitz des Kaisers — keine Senatsprovinz.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/octavian.jpg', title: 'Octavian' }] },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cleop-4-1', text: 'Was bestimmte die Ernte in Ägypten?', type: 'multiple-choice', options: ['Regen', 'Die Nilüberschwemmung', 'Bewässerung aus Brunnen', 'Import'], correctAnswer: 1, explanation: 'Die Nilüberschwemmung bestimmte die Ernte.' },
    { id: 'q-cleop-4-2', text: 'Wer war der Vater von Caesarion?', type: 'multiple-choice', options: ['Antonius', 'Ptolemaios XIII', 'Caesar', 'Octavian'], correctAnswer: 2, explanation: 'Caesarion — Sohn von Caesar und Kleopatra.' },
    { id: 'q-cleop-4-3', text: 'Warum wollte Octavian Ägypten erobern?', type: 'multiple-choice', options: ['Aus Rache', 'Wegen der Staatskasse und Schätze', 'Auf Wunsch des Senats', 'Wegen Kleopatra'], correctAnswer: 1, explanation: 'Die Staatskasse war nötig für die Legionäre.' }
  ]},
  { id: 'c17', title: 'Schlacht bei Actium', content: '31 v. Chr.: Octavians Flotte besiegte die Koalition von Antonius und Kleopatra. Ein Teil der ägyptischen Schiffe zog sich mit Kleopatra zurück. Antonius folgte ihr. Die Niederlage war nicht nur militärisch — die Wirtschaft des Ostens ging an Octavian über.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/actium.jpg', title: 'Actium' }] },
  { id: 'c18', title: 'Kleopatras Tod', content: '30 v. Chr. zog Octavian in Alexandria ein. Antonius nahm sich das Leben. Kleopatra versuchte zu verhandeln — aber Octavian wollte sie als Gefangene nach Rom bringen. Sie wählte den Tod — der Überlieferung nach durch einen Schlangenbiss. Ägypten wurde römische Provinz.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/death.jpg', title: 'Kleopatras Tod' }] },
  { id: 'c19', title: 'Humor: Gift-Test', content: 'Laut Plutarch experimentierte Kleopatra vor ihrem Tod mit Giften an Verurteilten. Sie suchte einen Weg, schmerzlos zu sterben. Grausam — aber es zeigt: Auch in den letzten Stunden dachte sie wie eine Herrscherin, die die Umstände kontrolliert.', duration: 3 },
  { id: 'c20', title: 'Ägypten — persönlicher Besitz des Kaisers', content: 'Octavian übergab Ägypten nicht dem Senat. Er regierte es persönlich durch einen Präfekten. Ägyptisches Getreide ging nach Rom. Die Einnahmen gingen in die Kaiserkasse. Die Kontrolle über Ägypten wurde zur Grundlage der Macht der römischen Kaiser.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/roman-egypt.jpg', title: 'Römisches Ägypten' }] },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cleop-5-1', text: 'In welchem Jahr zog Octavian in Alexandria ein?', type: 'multiple-choice', options: ['31 v. Chr.', '30 v. Chr.', '29 v. Chr.', '27 v. Chr.'], correctAnswer: 1, explanation: '30 v. Chr. — Fall von Alexandria.' },
    { id: 'q-cleop-5-2', text: 'Woran starb Kleopatra der Überlieferung nach?', type: 'multiple-choice', options: ['Am Schwert', 'Durch Schlangenbiss', 'Durch Gift im Wein', 'Durch Ertrinken'], correctAnswer: 1, explanation: 'Die Überlieferung vom Schlangenbiss.' },
    { id: 'q-cleop-5-3', text: 'Wem gehörte Ägypten nach der Eroberung?', type: 'multiple-choice', options: ['Dem Senat', 'Persönlich dem Kaiser', 'Dem römischen Volk', 'Den Legionären'], correctAnswer: 1, explanation: 'Ägypten — persönlicher Besitz des Kaisers.' }
  ]},
  { id: 'c21', title: 'Octavians Propaganda', content: 'Octavian stellte Kleopatra als «ägyptische Gefangene» dar, die Römer verführt habe. Die Wirklichkeit war anders: Sie war Königin eines mächtigen Landes und schloss Bündnisse auf Augenhöhe. Die Propaganda verdeckte die wirtschaftlichen Gründe des Krieges.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/propaganda.jpg', title: 'Propaganda' }] },
  { id: 'c22', title: 'Kleopatra und die Sprachen', content: 'Kleopatra sprach Ägyptisch, Griechisch, Latein, Aramäisch und andere Sprachen. Sie war die erste Ptolemäerin, die Ägyptisch lernte. Das half ihr, mit Untertanen und Priestern zu sprechen — ein wichtiges Werkzeug der Herrschaft.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/languages.jpg', title: 'Sprachen' }] },
  { id: 'c23', title: 'Münzreform', content: 'Kleopatra prägte Münzen mit ihrem Porträt — nicht idealisiert, sondern mit typischen Zügen. Das war Politik: Stärke und Legitimität zeigen. Die Münzen sind bis heute erhalten — eines der wenigen «echten» Bilder der Königin.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/coins.jpg', title: 'Kleopatras Münzen' }] },
  { id: 'c24', title: 'Humor: Esel und Salz', content: 'Plutarch erzählt: Antonius liebte das Angeln. Wenn der Fang schlecht war, ließ er Sklaven unter Wasser gesalzenen Fisch an den Haken stecken. Kleopatra sagte den Gästen: «Lasst die Angel dem Kaiser — ihr fischt im Hafen von Pharos, er im Palastteich.» Ironie über seine «Erfolge».', duration: 3 },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cleop-6-1', text: 'Wie stellte Octavian Kleopatra dar?', type: 'multiple-choice', options: ['Als weise Herrscherin', 'Als ägyptische Gefangene, Verführerin', 'Als Opfer', 'Als Verbündete'], correctAnswer: 1, explanation: 'Die Propaganda zeigte sie als «Verführerin».' },
    { id: 'q-cleop-6-2', text: 'Wie war Kleopatras Porträt auf den Münzen?', type: 'multiple-choice', options: ['Idealisiert', 'Mit typischen Zügen', 'Ohne Gesicht', 'Mit Antonius\' Profil'], correctAnswer: 1, explanation: 'Die Münzen zeigten typische Züge.' },
    { id: 'q-cleop-6-3', text: 'Warum war Ägyptisch wichtig für Kleopatra?', type: 'multiple-choice', options: ['Für Literatur', 'Für Gespräche mit Untertanen und Priestern', 'Für Handel', 'Nur für Verhandlungen'], correctAnswer: 1, explanation: 'Die erste Ptolemäerin, die Ägyptisch lernte.' }
  ]},
  { id: 'c25', title: 'Bibliothek von Alexandria', content: 'Die Bibliothek von Alexandria bewahrte bis zu 700 000 Schriftrollen. Kleopatra förderte Gelehrte. Eratosthenes, Archimedes arbeiteten dort. Wissen war eine wertvolle Ressource — und der königliche Hof kontrollierte sie.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/library.jpg', title: 'Bibliothek' }] },
  { id: 'c26', title: 'Handel mit Indien', content: 'Über das Rote Meer und Arabien lief der Handel mit Indien. Gewürze, Seide, Edelsteine — Waren kamen nach Alexandria. Zölle füllten die Kasse. Kleopatra baute Häfen und Handelswege wieder auf, die durch Kriege geschwächt waren.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/indian-trade.jpg', title: 'Handel mit Indien' }] },
  { id: 'c27', title: 'Steuersystem', content: 'Die Ptolemäer führten eine Kopfsteuer, Grundsteuer, Gewerbesteuer ein. Steuereintreiber waren überall. Bauern gaben bis zur Hälfte der Ernte ab. Ein hartes System — aber es erlaubte, Armee, Flotte und Hof zu unterhalten.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/taxes.jpg', title: 'Steuern' }] },
  { id: 'c28', title: 'Konkurrenz mit der Schwester', content: 'Kleopatra herrschte zuerst mit Bruder Ptolemaios XIII, dann mit Schwester Arsinoe. Arsinoe ließ Kleopatra hinrichten — sie hatte versucht, den Thron zu nehmen. Dynastiekriege verzehrten Ressourcen, aber Alleinherrschaft war es wert.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/arsinoe.jpg', title: 'Arsinoe' }] },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cleop-7-1', text: 'Wie viele Rollen bewahrte die Bibliothek von Alexandria?', type: 'multiple-choice', options: ['70 000', '200 000', 'Bis zu 700 000', '1 Million'], correctAnswer: 2, explanation: 'Bis zu 700 000 Rollen.' },
    { id: 'q-cleop-7-2', text: 'Wie viel Ernte gaben die Bauern als Steuer ab?', type: 'multiple-choice', options: ['Ein Zehntel', 'Ein Drittel', 'Bis zur Hälfte', 'Alles'], correctAnswer: 2, explanation: 'Bis zur Hälfte der Ernte.' },
    { id: 'q-cleop-7-3', text: 'Wer war Kleopatras Rivalin um den Thron?', type: 'multiple-choice', options: ['Nur der Bruder', 'Schwester Arsinoe', 'Octavian', 'Caesar'], correctAnswer: 1, explanation: 'Arsinoe — Schwester, auf Kleopatras Befehl hingerichtet.' }
  ]},
  { id: 'c29', title: 'Königskult', content: 'Die Ptolemäer erklärten sich zu Göttern. Kleopatra — «neue Isis». Priester bekamen Land und Privilegien — dafür rechtfertigten sie die Macht. Religion und Wirtschaft: Tempel waren große Grundbesitzer.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/isis.jpg', title: 'Isis-Kult' }] },
  { id: 'c30', title: 'Legionen mit ägyptischem Getreide', content: 'Die römischen Legionen im Osten lebten von ägyptischem Getreide. Als Kleopatra Antonius unterstützte, versorgte sie seine Armee. Gewöhnliches Brot — aber es entschied den Ausgang der Feldzüge. Logistik war Politik.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/legions.jpg', title: 'Legionen' }] },
  { id: 'c31', title: 'Kleopatras Erbe', content: 'Das Bild Kleopatras in der Kultur — romantisch. Die Wirklichkeit — eine kluge Herrscherin, die Wirtschaft und Diplomatie nutzte. Ägypten war unter ihr reich und unabhängig. Die Niederlage bei Actium machte dem ein Ende — aber es war nicht ihre Schuld.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/legacy.jpg', title: 'Erbe' }] },
  { id: 'c32', title: 'Humor: Kleopatra und der Philosoph', content: 'Der Überlieferung nach fragte Kleopatra einen Philosophen: «Kannst du die Form des Körpers ändern?» Er sagte: «Nein.» — «Dann urteile nicht über meine Schönheit — du hast sie nicht gesehen.» Der Witz der Königin: Sie kannte die Macht von Bild und Wort.', duration: 3 },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cleop-8-1', text: 'Als welche Göttin erklärte sich Kleopatra?', type: 'multiple-choice', options: ['Athene', 'Isis', 'Aphrodite', 'Artemis'], correctAnswer: 1, explanation: 'Kleopatra — «neue Isis».' },
    { id: 'q-cleop-8-2', text: 'Wovon lebten die Legionen im Osten?', type: 'multiple-choice', options: ['Gallischem Getreide', 'Ägyptischem Getreide', 'Spanischem Olivenöl', 'Griechischem Wein'], correctAnswer: 1, explanation: 'Ägypten versorgte die Legionen mit Getreide.' },
    { id: 'q-cleop-8-3', text: 'Wie war Ägypten unter Kleopatra?', type: 'multiple-choice', options: ['Ein armes Land', 'Reich und unabhängig', 'Römische Provinz', 'Eine Wüste'], correctAnswer: 1, explanation: 'Ägypten war reich und unabhängig.' }
  ]},
  { id: 'c33', title: 'Shakespeare und Hollywood', content: 'Shakespeare schrieb «Antonius und Cleopatra». Hollywood drehte Dutzende Filme. Das Bild — Leidenschaft, Schönheit, Tragödie. Die Wirtschaft verschwand aus der Geschichte. Aber ohne Ägyptens Geld hätte es weder das Bündnis mit Caesar noch den Krieg mit Octavian gegeben.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/shakespeare.jpg', title: 'Shakespeare' }] },
  { id: 'c34', title: 'Kleopatra heute', content: 'Gelehrte streiten über Kleopatras Aussehen — erhalten sind nur Münzen und Beschreibungen. Wichtiger: Sie war eine Politikerin, die Wirtschaft als Waffe nutzte. Eine Lehre für heute: Hinter Romantik verbergen sich oft Geld und Macht.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/modern.jpg', title: 'Heute' }] },
  { id: 'c35', title: 'Fazit: Politikerin und Ökonomin', content: 'Kleopatra nutzte Ägyptens Reichtum für Bündnisse mit Rom. Sie finanzierte Caesar und Antonius. Sie kontrollierte Handel und Steuern. Die Niederlage war militärisch — aber ihre Wirtschaftspolitik war erfolgreich, solange sie herrschte.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/summary.jpg', title: 'Fazit' }] },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cleop-9-1', text: 'Warum verschwand die Wirtschaft aus Kleopatras Bild in der Kultur?', type: 'multiple-choice', options: ['Sie war unwichtig', 'Romantik verdeckte die Wirtschaft', 'Dokumente sind verloren', 'Es wurde verboten'], correctAnswer: 1, explanation: 'Das Bild der Leidenschaft verdeckte die Wirtschaft.' },
    { id: 'q-cleop-9-2', text: 'War Kleopatras Wirtschaftspolitik erfolgreich?', type: 'multiple-choice', options: ['Nein, völliger Misserfolg', 'Ja, solange sie herrschte', 'Nur unter Caesar', 'Nur unter Antonius'], correctAnswer: 1, explanation: 'Erfolgreich, solange sie herrschte.' },
    { id: 'q-cleop-9-3', text: 'Wen finanzierte Kleopatra?', type: 'multiple-choice', options: ['Nur Ägypten', 'Caesar und Antonius', 'Octavian', 'Nur Priester'], correctAnswer: 1, explanation: 'Caesar und Antonius.' }
  ]},
  { id: 'c36', title: 'Königin und Frau', content: 'Kleopatra — eine der wenigen Herrscherinnen der Antike, von der wir viel wissen. Sie führte Truppen, schloss Verträge, sprach Recht. Die Römer waren Frauen an der Macht nicht gewohnt — das stärkte die Propaganda gegen sie.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/queen.jpg', title: 'Königin' }] },
  { id: 'c37', title: 'Ägypten nach Kleopatra', content: 'Rom lebte weiter von ägyptischem Getreide. Alexandria blieb Kulturzentrum. Aber die politische Unabhängigkeit Ägyptens endete. Kleopatra war die letzte Königin — danach nur noch römische Präfekten.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/after.jpg', title: 'Nach Kleopatra' }] },
  { id: 'c38', title: 'Mythos und Wirklichkeit', content: 'Mythos: Kleopatra — Schönheit, die Männer ins Verderben stürzte. Wirklichkeit: Königin, die Wirtschaft und Diplomatie nutzte. Sie verlor den Feldzug — nicht wegen «weiblicher Reize», sondern wegen Octavians Überlegenheit und dem Verrat der Verbündeten.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/myth-reality.jpg', title: 'Mythos und Wirklichkeit' }] },
  { id: 'c39', title: 'Lehre für die Geschichte', content: 'Kleopatras Geschichte zeigt: Hinter romantischen Geschichten stehen Geld, Getreide und Handelswege. Ägypten war der Preis — und Octavian nahm ihn. Wirtschaft verstehen hilft, Politik zu verstehen.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/lesson.jpg', title: 'Lehre' }] },
  { id: 'c40', title: 'Schluss', content: 'Kleopatra VII — Politikerin und Ökonomin. Sie nutzte Ägyptens Reichtum, um die Unabhängigkeit zu bewahren. Caesar und Antonius bekamen von ihr Geld und Getreide. Die Niederlage bei Actium änderte die Geschichte — aber ihre Strategie war logisch. Wirtschaft und Politik sind untrennbar.', duration: 3, media: [{ type: 'image', url: '/media/cleopatra-economist/conclusion.jpg', title: 'Schluss' }] },
  { id: 'q10', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cleop-10-1', text: 'Warum waren die Römer Frauen an der Macht nicht gewohnt?', type: 'multiple-choice', options: ['Es gab keine Tradition', 'Frauen konnten nicht', 'Religion verbot es', 'Nur in Ägypten'], correctAnswer: 0, explanation: 'In Rom gab es keine Tradition von Herrscherinnen.' },
    { id: 'q-cleop-10-2', text: 'Wer regierte Ägypten nach Kleopatra?', type: 'multiple-choice', options: ['Neue Ptolemäer', 'Römische Präfekten', 'Priester', 'Legionäre'], correctAnswer: 1, explanation: 'Römische Präfekten — Statthalter des Kaisers.' },
    { id: 'q-cleop-10-3', text: 'Warum verlor Kleopatra?', type: 'multiple-choice', options: ['Wegen weiblicher Reize', 'Wegen Octavians Überlegenheit und Verrat', 'Wegen Hunger', 'Wegen Krankheit'], correctAnswer: 1, explanation: 'Octavians Überlegenheit, Verrat der Verbündeten.' }
  ]}
]

export const cleopatraEconomistFinalQuizDE: QuizBlock = {
  id: 'quiz-cleopatra-economist',
  title: 'Abschlussquiz: Kleopatra — Politikerin und Ökonomin',
  questions: [
    { id: 'final-c1', text: 'Wie viel Getreide lieferte Ägypten an Rom?', type: 'multiple-choice', options: ['Fast alles', 'Etwa ein Drittel', 'Weniger als ein Zehntel', 'Nichts'], correctAnswer: 1, explanation: 'Ägypten lieferte etwa ein Drittel.' },
    { id: 'final-c2', text: 'Wie lange herrschte Kleopatra VII?', type: 'multiple-choice', options: ['5 Jahre', '12 Jahre', '22 Jahre', '35 Jahre'], correctAnswer: 2, explanation: '22 Jahre.' },
    { id: 'final-c3', text: 'Wofür hatten die Ptolemäer Monopole?', type: 'multiple-choice', options: ['Nur Gold', 'Öl, Papyrus, Salz', 'Nur Getreide', 'Nichts'], correctAnswer: 1, explanation: 'Öl, Papyrus, Salz.' },
    { id: 'final-c4', text: 'Wie gelangte Kleopatra zu Caesar?', type: 'multiple-choice', options: ['Unterirdischer Gang', 'Im Teppich gewickelt', 'Als Dienerin verkleidet', 'Mit dem Schiff'], correctAnswer: 1, explanation: 'Im Teppich als «Ware».' },
    { id: 'final-c5', text: 'Wie viele Talente schuldete Caesar?', type: 'multiple-choice', options: ['100', '1000', '6000', '10000'], correctAnswer: 2, explanation: '6000 Talente.' },
    { id: 'final-c6', text: 'Wie viele Schiffe gab Ägypten Antonius?', type: 'multiple-choice', options: ['50', '100', '200', '500'], correctAnswer: 2, explanation: '200 Schiffe.' },
    { id: 'final-c7', text: 'Wann war die Schlacht bei Actium?', type: 'multiple-choice', options: ['44 v. Chr.', '31 v. Chr.', '27 v. Chr.', '30 v. Chr.'], correctAnswer: 1, explanation: '31 v. Chr.' },
    { id: 'final-c8', text: 'Was bestimmte die Ernte in Ägypten?', type: 'multiple-choice', options: ['Regen', 'Nilüberschwemmung', 'Bewässerung', 'Import'], correctAnswer: 1, explanation: 'Nilüberschwemmung.' },
    { id: 'final-c9', text: 'Wer war der Vater von Caesarion?', type: 'multiple-choice', options: ['Antonius', 'Ptolemaios XIII', 'Caesar', 'Octavian'], correctAnswer: 2, explanation: 'Caesar.' },
    { id: 'final-c10', text: 'Wann zog Octavian in Alexandria ein?', type: 'multiple-choice', options: ['31 v. Chr.', '30 v. Chr.', '29 v. Chr.', '27 v. Chr.'], correctAnswer: 1, explanation: '30 v. Chr.' },
    { id: 'final-c11', text: 'Woran starb Kleopatra?', type: 'multiple-choice', options: ['Am Schwert', 'Schlangenbiss', 'Gift im Wein', 'Ertrinken'], correctAnswer: 1, explanation: 'Schlangenbiss.' },
    { id: 'final-c12', text: 'Wem gehörte Ägypten nach der Eroberung?', type: 'multiple-choice', options: ['Dem Senat', 'Dem Kaiser persönlich', 'Dem Volk', 'Legionären'], correctAnswer: 1, explanation: 'Persönlicher Besitz des Kaisers.' },
    { id: 'final-c13', text: 'Wie stellte Octavian Kleopatra dar?', type: 'multiple-choice', options: ['Weise Herrscherin', 'Ägyptische Gefangene, Verführerin', 'Opfer', 'Verbündete'], correctAnswer: 1, explanation: 'Als «Verführerin».' },
    { id: 'final-c14', text: 'Wie viele Rollen bewahrte die Bibliothek?', type: 'multiple-choice', options: ['70 000', '200 000', 'Bis zu 700 000', '1 Million'], correctAnswer: 2, explanation: 'Bis zu 700 000.' },
    { id: 'final-c15', text: 'Wie viel Ernte gaben Bauern ab?', type: 'multiple-choice', options: ['Ein Zehntel', 'Ein Drittel', 'Bis zur Hälfte', 'Alles'], correctAnswer: 2, explanation: 'Bis zur Hälfte.' },
    { id: 'final-c16', text: 'Als welche Göttin erklärte sich Kleopatra?', type: 'multiple-choice', options: ['Athene', 'Isis', 'Aphrodite', 'Artemis'], correctAnswer: 1, explanation: '«Neue Isis».' },
    { id: 'final-c17', text: 'Wovon lebten die Legionen im Osten?', type: 'multiple-choice', options: ['Gallischem Getreide', 'Ägyptischem Getreide', 'Spanischem Öl', 'Griechischem Wein'], correctAnswer: 1, explanation: 'Ägyptisches Getreide.' },
    { id: 'final-c18', text: 'Wen finanzierte Kleopatra?', type: 'multiple-choice', options: ['Nur Ägypten', 'Caesar und Antonius', 'Octavian', 'Nur Priester'], correctAnswer: 1, explanation: 'Caesar und Antonius.' },
    { id: 'final-c19', text: 'Wer regierte Ägypten nach Kleopatra?', type: 'multiple-choice', options: ['Neue Ptolemäer', 'Römische Präfekten', 'Priester', 'Legionäre'], correctAnswer: 1, explanation: 'Römische Präfekten.' },
    { id: 'final-c20', text: 'Warum verlor Kleopatra?', type: 'multiple-choice', options: ['Weibliche Reize', 'Octavians Überlegenheit und Verrat', 'Hunger', 'Krankheit'], correctAnswer: 1, explanation: 'Octavians Überlegenheit, Verrat.' },
    { id: 'final-c21', text: 'Welche Stadt war die zweitgrößte?', type: 'multiple-choice', options: ['Rom', 'Alexandria', 'Athen', 'Karthago'], correctAnswer: 1, explanation: 'Alexandria.' },
    { id: 'final-c22', text: 'Wer war Kleopatras Rivalin?', type: 'multiple-choice', options: ['Nur Bruder', 'Schwester Arsinoe', 'Octavian', 'Caesar'], correctAnswer: 1, explanation: 'Arsinoe.' },
    { id: 'final-c23', text: 'Warum wollte Octavian Ägypten erobern?', type: 'multiple-choice', options: ['Rache', 'Staatskasse und Schätze', 'Senatsbeschluss', 'Kleopatra'], correctAnswer: 1, explanation: 'Staatskasse für Legionäre.' },
    { id: 'final-c24', text: 'Was soll Kleopatra bei einer Wette aufgelöst haben?', type: 'multiple-choice', options: ['Gold', 'Perle in Essig', 'Smaragd', 'Koralle'], correctAnswer: 1, explanation: 'Perle in Essig.' },
    { id: 'final-c25', text: 'Wie war Ägypten unter Kleopatra?', type: 'multiple-choice', options: ['Arm', 'Reich und unabhängig', 'Römische Provinz', 'Wüste'], correctAnswer: 1, explanation: 'Reich und unabhängig.' },
    { id: 'final-c26', text: 'Warum war Ägyptisch wichtig?', type: 'multiple-choice', options: ['Literatur', 'Gespräche mit Untertanen', 'Handel', 'Nur Verhandlungen'], correctAnswer: 1, explanation: 'Erste Ptolemäerin mit Ägyptisch.' },
    { id: 'final-c27', text: 'War Kleopatras Wirtschaftspolitik erfolgreich?', type: 'multiple-choice', options: ['Nein', 'Ja, solange sie herrschte', 'Nur unter Caesar', 'Nur unter Antonius'], correctAnswer: 1, explanation: 'Erfolgreich unter ihrer Herrschaft.' },
    { id: 'final-c28', text: 'Warum verschwand die Wirtschaft aus Kleopatras Bild?', type: 'multiple-choice', options: ['Unwichtig', 'Romantik verdeckte sie', 'Dokumente verloren', 'Verboten'], correctAnswer: 1, explanation: 'Romantik verdeckte die Wirtschaft.' },
    { id: 'final-c29', text: 'Wer ist Caesarion?', type: 'multiple-choice', options: ['Antonius\' Sohn', 'Sohn von Caesar und Kleopatra', 'Kleopatras Bruder', 'Präfekt'], correctAnswer: 1, explanation: 'Sohn von Caesar und Kleopatra.' },
    { id: 'final-c30', text: 'Warum waren Römer Frauen an der Macht nicht gewohnt?', type: 'multiple-choice', options: ['Keine Tradition', 'Frauen konnten nicht', 'Religion verbot', 'Nur in Ägypten'], correctAnswer: 0, explanation: 'In Rom keine Tradition von Herrscherinnen.' }
  ]
}
