import { Slide, QuizBlock } from '../types/session'

// Deutsche Übersetzungen (B1-B2): Kreuzzüge — Finanzielle Ruinierung
export const crusadesFinanceSlidesDE: Slide[] = [
  { id: 'cr1', title: 'Kreuzzug — finanzielle Katastrophe', content: 'Kreuzzüge in Filmen — Heldentum und Glaube. Realität: finanzieller Selbstmord. Ritter verkauften Ländereien, nahmen Schulden auf, verpfändeten Burgen. Ein Kreuzzug kostete 5–10 Jahreseinkommen. Die meisten kehrten arm zurück oder gar nicht. Kreuzzüge = Massenruinierung des Adels.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/crusader-main.jpg', title: 'Kreuzritter' }] },
  { id: 'cr2', title: 'Was kostete ein Kreuzzug?', content: 'Ritterausrüstung — 300–500 Livre. Kriegspferd — 100 Livre. Rüstung — 50–100 Livre. Waffen — 30 Livre. Schiff ins Heilige Land — 50 Livre pro Person. Vorräte für ein Jahr — 100 Livre. Gesamt: mindestens 600 Livre = 5 Jahreseinkommen eines mittleren Ritters. Wie heute ein Haus kaufen.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/cost.jpg', title: 'Kosten' }] },
  { id: 'cr3', title: 'Landverkauf — Weg in die Armut', content: 'Ritter verkauften Land für Geld. Käufer wussten — Kreuzfahrer kommt nicht zurück. Preis — 30–50% des realen Werts. Ritter verlor alles. Bei Rückkehr fand er: Besitz verkauft, Familie arm. Kirche und Klöster kauften billig. Kreuzzüge bereicherten Kirche, ruinierten Ritter.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/land-sale.jpg', title: 'Landverkauf' }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cr-1-1', text: 'Was kostete ein Kreuzzug?', type: 'multiple-choice', options: ['1 Jahreseinkommen', '2 Jahreseinkommen', '5–10 Jahreseinkommen', '20 Jahreseinkommen'], correctAnswer: 2, explanation: '5–10 Jahreseinkommen — riesige Summe.' },
    { id: 'q-cr-1-2', text: 'Warum verkauften Ritter Land?', type: 'multiple-choice', options: ['Langeweile', 'Brauchten Geld für Kreuzzug', 'Königsbefehl', 'Kirchengeschenk'], correctAnswer: 1, explanation: 'Geld für Ausrüstung und Reise.' },
    { id: 'q-cr-1-3', text: 'Wer kaufte Ritterland?', type: 'multiple-choice', options: ['Bauern', 'Kirche und Klöster', 'Könige', 'Händler'], correctAnswer: 1, explanation: 'Kirche kaufte billig.' }
  ]},
  { id: 'cr4', title: 'Humor: «Verkaufe Burg, fahre Grab befreien»', content: 'Anzeige 12. Jh.: «Burg mit Türmen, 100 Hektar Land, 50 Leibeigene. Verkaufe dringend — fahre auf Kreuzzug. Preis verhandelbar». Käufer: «Gebe 30% des Werts, bar». Ritter: «Abgemacht, muss rechtzeitig zur Abfahrt». Spekulation mit Glauben.', duration: 3 },
  { id: 'cr5', title: 'Schulden — ewige Knechtschaft', content: 'Kein Geld für Kreuzzug? Auf Pump. Geldverleiher (oft Juden, Italiener) gaben Kredite zu 30–50% Jahreszins. Ritter reiste für 2–5 Jahre. Schuld wuchs enorm. Bei Rückkehr gab er alles — Land, Burg, Vieh. Kirche verbot Wucher, aber Kreuzfahrerschulden — Ausnahme.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/debt.jpg', title: 'Schulden' }] },
  { id: 'cr6', title: 'Beispiel: Gottfried von Bouillon', content: 'Gottfried von Bouillon — Held des Ersten Kreuzzugs. Verkaufte Burg Bouillon an Bischof von Lüttich für 1300 Mark. Verpfändete Herzogtum Niederlothringen. Nahm riesige Schulden auf. Eroberte Jerusalem, starb nach einem Jahr. Erben bekamen Ruinen und Schulden. Heldentum zahlte sich nicht aus.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/godfrey.jpg', title: 'Gottfried von Bouillon' }] },
  { id: 'cr7', title: 'Venedig — Bankier der Kreuzzüge', content: 'Venedig transportierte Kreuzfahrer auf Schiffen. Preis — Wucherpreise. Vierter Kreuzzug: Kreuzfahrer mieteten 500 Schiffe für 85.000 Mark Silber. Konnten nicht zahlen. Venedig: «Dann erobert für uns Zara (christliche Stadt)». Kreuzfahrer stimmten zu. Venedig machte Kreuzzug zum Geschäft.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/venice.jpg', title: 'Venedig' }] },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cr-2-1', text: 'Welcher Zinssatz für Kredite?', type: 'multiple-choice', options: ['5%', '10%', '30–50%', '100%'], correctAnswer: 2, explanation: '30–50% p.a. — Wucherzinsen.' },
    { id: 'q-cr-2-2', text: 'Was verkaufte Gottfried?', type: 'multiple-choice', options: ['Krone', 'Burg Bouillon und Herzogtum', 'Schwert', 'Pferd'], correctAnswer: 1, explanation: 'Burg und Herzogtum — ganzer Besitz.' },
    { id: 'q-cr-2-3', text: 'Was forderte Venedig für Schiffe?', type: 'multiple-choice', options: ['Gold', 'Zara erobern', 'Gebete', 'Nichts'], correctAnswer: 1, explanation: 'Christliche Stadt Zara erobern.' }
  ]},
  { id: 'cr8', title: 'Plünderung Konstantinopels — Venedigs Geschäft', content: '1204: Vierter Kreuzzug. Kreuzfahrer konnten Venedig nicht bezahlen. Doge Enrico Dandolo schlug vor: «Plündert Konstantinopel — teilen wir Beute». Kreuzfahrer stimmten zu. Hauptstadt des christlichen Byzanz geplündert. Venedig bekam Gold, Reliquien, Territorien. Kreuzfahrer — Reste. Kirche verurteilte nicht — Schulden wichtiger.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/constantinople-sack.jpg', title: 'Plünderung Konstantinopels' }] },
  { id: 'cr9', title: 'Dandolo — 90-jähriger blinder Geschäftsmann', content: 'Enrico Dandolo — Doge Venedigs, 90 Jahre, blind. Führte Vierten Kreuzzug an. Ziel — Profit, nicht Glaube. Konstantinopel geplündert, Venedig bekam Inseln, Häfen, Gold. Byzanz erholte sich nie. Dandolo starb mit 97, reichster Mann. Glaube — Vorwand, Geld — Ziel.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/dandolo.jpg', title: 'Enrico Dandolo' }] },
  { id: 'cr10', title: 'Humor: «Kreuzfahrer vergaßen, wohin sie wollten»', content: 'Ziel: Jerusalem befreien. Realität: erst Zara genommen (für Venedig), dann Konstantinopel geplündert (christliche Hauptstadt). Nach Jerusalem kamen nicht. Papst exkommunizierte, dann vergab. Venedig verdiente Millionen. Kreuzfahrer: «Wo ist Jerusalem?» Dandolo: «Ein andermal».', duration: 3 },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cr-3-1', text: 'Wann Plünderung Konstantinopels?', type: 'multiple-choice', options: ['1095', '1187', '1204', '1291'], correctAnswer: 2, explanation: '1204 — Vierter Kreuzzug.' },
    { id: 'q-cr-3-2', text: 'Wer schlug Plünderung vor?', type: 'multiple-choice', options: ['Papst', 'Enrico Dandolo', 'König Frankreichs', 'Kaiser Byzanz'], correctAnswer: 1, explanation: 'Dandolo — Doge Venedigs.' },
    { id: 'q-cr-3-3', text: 'Wie alt war Dandolo?', type: 'multiple-choice', options: ['50', '70', '90', '110'], correctAnswer: 2, explanation: '90 Jahre, blind, aber gierig.' }
  ]},
  { id: 'cr11', title: 'Beute aus Konstantinopel', content: 'Plünderung dauerte 3 Tage. Gold, Silber, Reliquien, Ikonen, Heiligentümer gestohlen. Bronzepferde vom Hippodrom — nach Venedig gebracht (stehen bis heute). Gesamtbeute — Millionen Livre. Byzantinisches Reich verlor Reichtum von Jahrhunderten. Konstantinopel erholte sich nie. Venedig wurde Supermacht.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/loot.jpg', title: 'Beute' }] },
  { id: 'cr12', title: 'Templer — Bankiers der Kreuzfahrer', content: 'Templerorden — Mönch-Krieger, aber vor allem — Bankiers. Templer gaben Kredite an Kreuzfahrer, Könige, Kirche. Bewahrten Gold in Burgen. Erfanden Scheck: Geld in Paris eingezahlt, in Jerusalem erhalten. Bis 13. Jh. — reichste Organisation Europas. Französischer König Philipp IV. war ruiniert und zerstörte Orden, um Schulden nicht zu zahlen.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/templars.jpg', title: 'Templer' }] },
  { id: 'cr13', title: 'König schuldete Templern — zerstörte Orden', content: '1307: Philipp IV. der Schöne (Frankreich) schuldete Templern riesige Summe. Lösung: alle Templer in Frankreich verhaften, der Häresie anklagen, durch Folter Geständnisse erpressen, auf Scheiterhaufen verbrennen. Orden zerstört, Besitz konfisziert, Schulden gelöscht. Papst Clemens V. stimmte zu — war selbst Schuldner. Finanzmord.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/templars-burn.jpg', title: 'Hinrichtung der Templer' }] },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cr-4-1', text: 'Was erfanden Templer?', type: 'multiple-choice', options: ['Schießpulver', 'Scheck', 'Kompass', 'Druckerpresse'], correctAnswer: 1, explanation: 'Scheck — in Paris zahlen, in Jerusalem erhalten.' },
    { id: 'q-cr-4-2', text: 'Wer zerstörte Templerorden?', type: 'multiple-choice', options: ['Papst', 'Philipp IV.', 'Kreuzfahrer', 'Sarazenen'], correctAnswer: 1, explanation: 'Philipp IV. — um Schulden nicht zu zahlen.' },
    { id: 'q-cr-4-3', text: 'Wann wurden Templer zerstört?', type: 'multiple-choice', options: ['1095', '1204', '1307', '1453'], correctAnswer: 2, explanation: '1307 — Verhaftungen und Hinrichtungen.' }
  ]},
  { id: 'cr14', title: 'Humor: «Schulde Bankier? Töte Bankier»', content: 'Philipp IV.: «Ich schulde Templern Million Livre». Berater: «Zahlen Sie». König: «Oder ich verhafte sie wegen Häresie und konfisziere Besitz». Berater: «Aber sie sind Mönche!» König: «Waren Mönche, jetzt — Ketzer». Papst: «Ich schulde auch Templern. Unterstütze». Profitabelster Bankrott der Geschichte.', duration: 3 },
  { id: 'cr15', title: 'Kreuzzugssteuer — «Saladin-Zehnt»', content: '1188: Saladin eroberte Jerusalem. Englischer König Heinrich II. führte Steuer ein — «Saladin-Zehnt» (10% aller Einkommen und Besitz). Sammlung für Dritten Kreuzzug. Volk empört — Steuer riesig. Könige Englands, Frankreichs, Deutschlands sammelten Millionen. Kreuzzug scheiterte, Jerusalem nicht befreit. Geld verschwand.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/saladin-tithe.jpg', title: 'Saladin-Zehnt' }] },
  { id: 'cr16', title: 'Richard Löwenherz — teuerster König', content: 'Richard I. (England) — Held der Kreuzzüge. Realität: ruinierte England. Verkaufte Ämter, Land, Titel. Sagte: «Würde London verkaufen, fände ich Käufer». Kreuzzug ins Heilige Land — riesige Ausgaben. Geriet in Gefangenschaft des österreichischen Herzogs. Lösegeld — 150.000 Mark (2 Jahreseinkommen Englands). England arm, König — bankrott.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/richard.jpg', title: 'Richard Löwenherz' }] },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cr-5-1', text: 'Was ist «Saladin-Zehnt»?', type: 'multiple-choice', options: ['Geschenk an Saladin', 'Steuer 10% für Kreuzzug', 'Zehn Krieger', 'Münze'], correctAnswer: 1, explanation: '10% Einkommen — riesige Steuer.' },
    { id: 'q-cr-5-2', text: 'Was sagte Richard über London?', type: 'multiple-choice', options: ['«Baue neu»', '«Verkaufe, fände ich Käufer»', '«Schönste Stadt»', '«Verkaufe nie»'], correctAnswer: 1, explanation: 'Bereit, Hauptstadt zu verkaufen.' },
    { id: 'q-cr-5-3', text: 'Was kostete Richards Lösegeld?', type: 'multiple-choice', options: ['1.000 Mark', '10.000 Mark', '150.000 Mark', '1 Million Mark'], correctAnswer: 2, explanation: '150.000 Mark — 2 Jahreseinkommen Englands.' }
  ]},
  { id: 'cr17', title: 'Ludwig IX. der Heilige — Bankrott für Glauben', content: 'Ludwig IX. (Frankreich) — einziger heiliger König. Organisierte zwei Kreuzzüge. Siebter Kreuzzug: geriet in ägyptische Gefangenschaft. Lösegeld — 400.000 Livre (riesige Summe). Frankreich sammelte Geld. Befreit, aber gab nicht auf. Achter Kreuzzug: starb an Ruhr in Tunesien. Frankreich ruiniert, Ergebnis — null. Heiligkeit rettete nicht vor Bankrott.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/louis.jpg', title: 'Ludwig IX.' }] },
  { id: 'cr18', title: 'Kinderkreuzzug — tragischer Betrug', content: '1212: «Kinderkreuzzug». Tausende Kinder zogen, um Jerusalem zu befreien. Legende: Meer teilt sich vor ihnen. Realität: Sklavenhändler und Betrüger organisierten. Kinder auf Schiffe in Marseille gesetzt, versprachen Heiliges Land. Schiffe fuhren nach Afrika. Kinder als Sklaven an muslimische Händler verkauft. Niemand kehrte zurück. Glaube als Ware.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/childrens-crusade.jpg', title: 'Kinderkreuzzug' }] },
  { id: 'cr19', title: 'Humor: «Kinder befreien, was Ritter nicht konnten»', content: 'Kirche: «Erwachsene sündig, deshalb Niederlagen. Kinder rein — Gott hilft ihnen». Kinder: «Ziehen nach Jerusalem!» Sklavenhändler: «Kostenlose Schiffe!» Eltern: «Gott schützt sie». Ergebnis: Tausende Kinder als Sklaven verkauft. Kirche: «Gottes Wege unergründlich». Betrüger verdienten Vermögen. Zynischster Kreuzzug.', duration: 3 },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cr-6-1', text: 'Wie viele Kreuzzüge organisierte Ludwig IX.?', type: 'multiple-choice', options: ['Einen', 'Zwei', 'Drei', 'Fünf'], correctAnswer: 1, explanation: 'Zwei Kreuzzüge — beide erfolglos.' },
    { id: 'q-cr-6-2', text: 'Wann war «Kinderkreuzzug»?', type: 'multiple-choice', options: ['1095', '1187', '1212', '1291'], correctAnswer: 2, explanation: '1212 — Tragödie.' },
    { id: 'q-cr-6-3', text: 'Was geschah mit Kindern?', type: 'multiple-choice', options: ['Befreiten Jerusalem', 'Kehrten heim', 'Als Sklaven verkauft', 'Wurden Ritter'], correctAnswer: 2, explanation: 'In Afrika an Muslime verkauft.' }
  ]},
  { id: 'cr20', title: 'Ablässe — Himmelfahrt für Geld', content: 'Kirche verkaufte Ablässe — Sündenvergebung für Geld. Werbung: «Nimm an Kreuzzug teil oder zahle — kommst in Himmel». Preis — 1 bis 1000 Livre. Arme zahlten Pfennige, Reiche — Tausende. Geld ging an Kirche, Papst, Bischöfe. Kreuzzüge — Einkommensquelle. Glaube monetarisiert.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/indulgences.jpg', title: 'Ablässe' }] },
  { id: 'cr21', title: 'Genua und Venedig — Krieg um Monopol', content: 'Genua und Venedig — Rivalen im Osthandel. Kreuzzüge — Chance, Häfen im Heiligen Land zu kontrollieren. Genua unterstützte eine Kreuzfahrer, Venedig — andere. Führten Krieg im Mittelmeer. Vier Kriege (1256–1381). Venedig siegte. Kreuzzüge — Vorwand für Handelskrieg.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/genoa-venice.jpg', title: 'Genua und Venedig' }] },
  { id: 'cr22', title: 'Kreuzfahrerstaaten — wirtschaftliche Kolonien', content: 'Kreuzfahrer schufen Staaten im Osten: Königreich Jerusalem, Tripolis, Antiochien. Ziel — nicht Glaube, sondern Handel. Venedig, Genua bekamen Lager, Häfen, Zollstellen. Zölle riesig. Einheimische arbeiteten, Italiener wurden reich. Kreuzfahrerstaaten = Handelsfaktoreien. Existierten 200 Jahre, dann holten Araber Land zurück.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/crusader-states.jpg', title: 'Kreuzfahrerstaaten' }] },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cr-7-1', text: 'Was ist Ablass?', type: 'multiple-choice', options: ['Waffe', 'Sündenvergebung für Geld', 'Gebet', 'Fasten'], correctAnswer: 1, explanation: 'Himmelfahrt für Geld.' },
    { id: 'q-cr-7-2', text: 'Wer führte Krieg um Monopol?', type: 'multiple-choice', options: ['England und Frankreich', 'Genua und Venedig', 'Spanien und Portugal', 'Rom und Konstantinopel'], correctAnswer: 1, explanation: 'Genua und Venedig — Handelsrivalen.' },
    { id: 'q-cr-7-3', text: 'Wie lange existierten Kreuzfahrerstaaten?', type: 'multiple-choice', options: ['50 Jahre', '100 Jahre', '200 Jahre', '500 Jahre'], correctAnswer: 2, explanation: 'Etwa 200 Jahre (1099–1291).' }
  ]},
  { id: 'cr23', title: 'Fall von Akkon — Ende der Ära', content: '1291: Muslime nahmen Festung Akkon — letzte Kreuzfahrerfestung. Belagerung dauerte 6 Wochen. Verteidiger kämpften bis zum letzten. Stadt fiel, alle getötet oder als Sklaven verkauft. Kreuzzüge endeten. Venedig und Genua verloren Häfen, fanden aber neue Märkte. Fazit: 200 Jahre Krieg, Millionen Opfer, Europa ruiniert, Osten nicht erobert.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/acre-fall.jpg', title: 'Fall von Akkon' }] },
  { id: 'cr24', title: 'Humor: «Kreuzzüge: 0:8 für Muslime»', content: 'Acht Kreuzzüge. Erster — Jerusalem genommen. Zweiter — gescheitert. Dritter — kamen nicht an. Vierter — Konstantinopel geplündert (christlich). Übrige — Katastrophe. Fazit: Verlust aller Eroberungen, Millionen Opfer, Europa verschuldet. Muslime: «Danke, dass ihr Byzanz für uns zerstört habt». Sinnlosester Krieg der Geschichte.', duration: 3 },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cr-8-1', text: 'Wann fiel Akkon?', type: 'multiple-choice', options: ['1099', '1187', '1291', '1453'], correctAnswer: 2, explanation: '1291 — Ende der Kreuzzüge.' },
    { id: 'q-cr-8-2', text: 'Wie viele Kreuzzüge?', type: 'multiple-choice', options: ['Drei', 'Fünf', 'Acht', 'Zehn'], correctAnswer: 2, explanation: 'Acht Hauptkreuzzüge.' },
    { id: 'q-cr-8-3', text: 'Welcher Kreuzzug plünderte Konstantinopel?', type: 'multiple-choice', options: ['Erster', 'Zweiter', 'Vierter', 'Siebter'], correctAnswer: 2, explanation: 'Vierter (1204) — Venedigs Schuld.' }
  ]},
  { id: 'cr25', title: 'Wirtschaftliche Folgen', content: 'Kreuzzüge ruinierten Adel, bereicherten Kirche und Handelsrepubliken. Venedig und Genua wurden Supermächte. Templer schufen Bankensystem (dann zerstört). Europäische Könige verschuldeten. Byzanz zerstört (erleichterte türkische Eroberung 1453). Osthandel ging an Italiener. Wirtschaft verändert, Glaube — nur Vorwand.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/consequences.jpg', title: 'Folgen' }] },
  { id: 'cr26', title: 'Kirche wurde reich', content: 'Kirche erhielt Land, von Kreuzfahrern verkauft. Ablässe brachten Millionen. Zehnten und Steuern für Kreuzzüge. Reliquien aus Konstantinopel (Gebeine, Ikonen). Bis 13. Jh. — Kirche reichste Organisation Europas. Papst reicher als Könige. Kreuzzüge = Investition der Kirche mit riesigem Gewinn.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/church-wealth.jpg', title: 'Kirchenreichtum' }] },
  { id: 'cr27', title: 'Erbe: Banken, Schecks, Schulden', content: 'Kreuzzüge erzeugten Bankensystem. Templer erfanden Scheck und internationalen Kredit. Venedig und Genua schufen erste Banken. Europäische Wirtschaft ging von Naturalwirtschaft zu Geldwirtschaft. Aber Rittertum ruiniert, Feudalismus geschwächt. Paradox: religiöser Krieg beschleunigte Kapitalismus.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/legacy.jpg', title: 'Erbe' }] },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-cr-9-1', text: 'Wer wurde reich an Kreuzzügen?', type: 'multiple-choice', options: ['Ritter', 'Kirche und Venedig', 'Bauern', 'Könige'], correctAnswer: 1, explanation: 'Kirche und Handelsstädte.' },
    { id: 'q-cr-9-2', text: 'Was wurde durch Kreuzzüge erfunden?', type: 'multiple-choice', options: ['Schießpulver', 'Bankensystem', 'Druck', 'Kompass'], correctAnswer: 1, explanation: 'Schecks, Kredite, Banken.' },
    { id: 'q-cr-9-3', text: 'Wann nahmen Türken Konstantinopel?', type: 'multiple-choice', options: ['1204', '1291', '1453', '1492'], correctAnswer: 2, explanation: '1453 — nach Ruinierung durch Kreuzfahrer.' }
  ]},
  { id: 'cr28', title: 'Humor: «Befreiten Jerusalem, ruinierten Europa»', content: 'Ziel: Grab des Herrn befreien. Ergebnis: Europa verschuldet, Byzanz zerstört, Jerusalem bei Muslimen, Rittertum ruiniert, Kirche reich, Venedig — Supermacht. Papst: «Alles läuft nach Plan». Kreuzfahrer: «Welchem Plan?» Papst: «Meinem». Glaube verkauft, Geld verdient.', duration: 3 },
  { id: 'cr29', title: 'Fazit: finanzielle Katastrophe für Glauben', content: 'Kreuzzüge — größte Tragödie des Mittelalters. 75–200 Millionen Opfer. Aber Wirtschaft kippte: Arbeitermangel, Lohnsteigerung um das Dreifache, Ende der Leibeigenschaft, Bauernaufstände, Geburt des Kapitalismus. Feudalismus starb. Europa verändert für immer. Lektion: Tragödie kann Wendepunkt sein.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/summary.jpg', title: 'Fazit' }] },
  { id: 'cr30', title: 'Schluss: Geld entscheidet alles', content: 'Kreuzzüge zeigten: Glaube ohne Geld — nichts. Gottfried verkaufte alles und starb in Armut. Richard ruinierte England. Ludwig wurde heilig, aber bankrott. Venedig verdiente Millionen. Kirche wurde reich. Wirtschaft entschied Kriegsausgang. Lektion: Geld wichtiger als Ideologie. Geschichte ohne Beschönigung — pure Ökonomie.', duration: 3, media: [{ type: 'image', url: '/media/crusades-finance/conclusion.jpg', title: 'Schluss' }] }
]

export const crusadesFinanceFinalQuizDE: QuizBlock = {
  id: 'quiz-crusades-finance',
  title: 'Abschlussquiz: Kreuzzüge — Finanzielle Ruinierung',
  questions: [
    { id: 'final-cr1', text: 'Was kostete Kreuzzug?', type: 'multiple-choice', options: ['1 Jahreseinkommen', '5–10 Jahreseinkommen', '20 Jahreseinkommen', '100 Jahreseinkommen'], correctAnswer: 1, explanation: '5–10 Jahreseinkommen.' },
    { id: 'final-cr2', text: 'Wer kaufte Ritterland?', type: 'multiple-choice', options: ['Bauern', 'Kirche', 'Könige', 'Händler'], correctAnswer: 1, explanation: 'Kirche — billig.' },
    { id: 'final-cr3', text: 'Welcher Zinssatz?', type: 'multiple-choice', options: ['5%', '10%', '30–50%', '100%'], correctAnswer: 2, explanation: '30–50% p.a.' }
  ]
}
