import { Slide, QuizBlock } from '../types/session'

// Компактная немецкая версия (B1-B2): Ганза
export const hansaMonopolySlidesDE: Slide[] = [
  { id: 'h1', title: 'Hanse — Kartell ohne Staat', content: 'Hanse (Hanseatic League) — Handelsbund norddeutscher Städte (13.–17. Jh.). Kein Staat, keine Armee — Kartell. 200 Städte, Hauptstadt — Lübeck. Kontrollierten Handel von London bis Nowgorod. Monopol auf Fisch, Pelze, Wachs, Getreide. Erstes transnationales Kartell der Geschichte.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/hansa-main.jpg', title: 'Hanse' }] },
  { id: 'h2', title: 'Lübeck — Hauptstadt des Handelsimperiums', content: 'Lübeck (Deutschland) — «Königin der Hanse». Gegründet 1143. Ostseehafen, Kontrolle der Handelswege. Bevölkerung 25.000 — riesige Stadt für die Zeit. Reicher als Könige. Motto: «Einigkeit im Inneren, Frieden draußen» (tatsächlich — Monopol und Druck).', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/lubeck.jpg', title: 'Lübeck' }] },
  { id: 'h3', title: 'Wie funktionierte Monopol?', content: 'Hanse kontrollierte Waren: Hering, Wachs, Pelze, Getreide, Bernstein, Holz. Kaufleute vereinbarten Preise — Kartell. Wer billiger verkaufte — wurde ausgeschlossen (= Bankrott). Konkurrenten bekamen Blockade. Könige fürchteten Hanse. Monopol ohne Armee, aber mit riesiger Macht.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/monopoly.jpg', title: 'Monopol' }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-h-1-1', text: 'Was ist Hanse?', type: 'multiple-choice', options: ['Staat', 'Handelskartell', 'Armee', 'Kirche'], correctAnswer: 1, explanation: 'Handelsbund, Kartell.' },
    { id: 'q-h-1-2', text: 'Hauptstadt der Hanse?', type: 'multiple-choice', options: ['Hamburg', 'Lübeck', 'Berlin', 'Köln'], correctAnswer: 1, explanation: 'Lübeck — «Königin».' },
    { id: 'q-h-1-3', text: 'Wie kämpfte Hanse?', type: 'multiple-choice', options: ['Krieg', 'Blockade', 'Gebete', 'Bestechung'], correctAnswer: 1, explanation: 'Blockade — wirtschaftliche Waffe.' }
  ]},
  { id: 'h4', title: 'Humor: «Tritt Hanse bei oder verhungere»', content: 'Stadt lehnte Beitritt ab. Hanse: «Blockade». Händler: «Handeln nicht mit euch». Häfen: «Nehmen eure Schiffe nicht». Nach einem Jahr Stadt: «Entschuldigung, treten bei». Hanse: «Jetzt zahlt Beitrag und Strafe». Freiwillig-erzwungene Mitgliedschaft.', duration: 3 },
  { id: 'h5', title: 'Kontor — Hansevertretung im Ausland', content: 'Hanse schuf «Kontore» — Handelsvertretungen in fremden Städten. Vier Hauptkontore: Nowgorod (Russland), Brügge (Flandern), London (England), Bergen (Norwegen). Kontor — separates Viertel, eigene Gesetze, Gericht, Lager, Wachen. Ausländer nicht zugelassen. Hanse lebte isoliert.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/kontor.jpg', title: 'Kontor' }] },
  { id: 'h6', title: 'Nowgoroder Kontor — «Peterhof»', content: 'Hanse handelte mit Nowgorod ab 12. Jh. Kontor hieß «Peterhof» (Hof des Heiligen Petrus). Deutsche Händler lebten hinter Zaun, bewacht, eigenes Gericht. Russen nicht reingelassen. Hanse kaufte Pelze, Wachs, Honig. Monopol bis 1494, als Iwan III. Kontor schloss.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/novgorod.jpg', title: 'Nowgorod' }] },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-h-2-1', text: 'Was ist «Kontor»?', type: 'multiple-choice', options: ['Schiff', 'Hansevertretung', 'Waffe', 'Münze'], correctAnswer: 1, explanation: 'Büro im Ausland.' },
    { id: 'q-h-2-2', text: 'Kontor in Nowgorod?', type: 'multiple-choice', options: ['Peterhof', 'Kreml', 'Markt', 'Gasthaus'], correctAnswer: 0, explanation: 'Peterhof — Petersgarten.' },
    { id: 'q-h-2-3', text: 'Wann schloss Iwan III. es?', type: 'multiple-choice', options: ['1300', '1400', '1494', '1600'], correctAnswer: 2, explanation: '1494 — Ende Hanse in Russland.' }
  ]},
  { id: 'h7', title: 'Krieg mit Dänemark — Blockade siegt', content: '1361: Dänischer König Waldemar IV. nahm Gotland (wichtiges Handelszentrum). Hanse erklärte Krieg. Keine Armee, aber Flotte. 1362–1370: Blockade Dänemarks. Dänische Häfen geschlossen, Handel gestoppt. Dänemark hungerte. 1370: Stralsunder Friede — Dänemark kapitulierte. Hanse bekam Kontrolle über Häfen, Handel, Fischerei. Kartell besiegte Königreich.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/denmark-war.jpg', title: 'Krieg mit Dänemark' }] },
  { id: 'h8', title: 'Kontrolle über Hering — Öl des Mittelalters', content: 'Hering — Hauptnahrung Europas (billig, lange haltbar). Hanse kontrollierte Heringfang in Ostsee und Nordsee. Monopol auf Salz (zum Pökeln). Preise diktierte Hanse. Wer ohne Erlaubnis fischte — Schiffe konfisziert. Europa hing von Hanseherring ab. Hering = Öl des Mittelalters.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/herring.jpg', title: 'Hering' }] },
  { id: 'h9', title: 'Humor: «Ohne Hanse kein Fisch, kein Fleisch»', content: 'König Englands: «Will Fisch». Hanse: «Zahlt unseren Preis». König: «Zu teuer!» Hanse: «Blockade». Einen Monat später: «Volk hungert». König: «Kaufe zu eurem Preis». Hanse: «Weise Entscheidung. Wollt Rabatt? Tretet Bund bei». Monopol schmeckt besser als jeder Fisch.', duration: 3 },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-h-3-1', text: 'Wann Krieg mit Dänemark?', type: 'multiple-choice', options: ['1300–1310', '1362–1370', '1400–1410', '1500–1510'], correctAnswer: 1, explanation: '1362–1370 — Blockade.' },
    { id: 'q-h-3-2', text: 'Was 1370 unterzeichnet?', type: 'multiple-choice', options: ['Friedensvertrag', 'Stralsunder Friede', 'Krieg', 'Handelsbund'], correctAnswer: 1, explanation: 'Stralsunder Friede — Kapitulation.' },
    { id: 'q-h-3-3', text: 'Was war «Öl des Mittelalters»?', type: 'multiple-choice', options: ['Gold', 'Hering', 'Pelze', 'Wein'], correctAnswer: 1, explanation: 'Hering — Hauptnahrung.' }
  ]},
  { id: 'h10', title: 'Brügge — Finanzzentrum', content: 'Brügge (Flandern, heute Belgien) — «Venedig des Nordens». Hansekontor ab 13. Jh. Brügge — Zentrum für Wolle, Stoffe, Gold. Banken, Börsen, Geldwechsler. Hanse kontrollierte Finanzen Nordeuropas. Bis 15. Jh. reichste Stadt. Dann versandete Hafen, Hanse zog nach Antwerpen.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/bruges.jpg', title: 'Brügge' }] },
  { id: 'h11', title: 'Stahlhof in London', content: 'Hansekontor in London hieß «Stahlhof» (Steelyard). Eingezäuntes Viertel an Themse, Lager, Häuser, Anlegestellen. Deutsche handelten Wolle, Stoffe, Wein, Metall. Englische Könige gaben Privilegien — zahlten keine Zölle (Engländer zahlten). Engländer empört, aber Könige fürchteten Blockade. Kontor bis 1598 — Elisabeth I. schloss es.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/steelyard.jpg', title: 'Stahlhof' }] },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-h-4-1', text: 'Wie nannte man Brügge?', type: 'multiple-choice', options: ['Rom des Nordens', 'Venedig des Nordens', 'Paris des Nordens', 'London des Nordens'], correctAnswer: 1, explanation: 'Venedig des Nordens — Reichtum.' },
    { id: 'q-h-4-2', text: 'Kontor in London?', type: 'multiple-choice', options: ['Stahlhof', 'Goldhaus', 'Silberturm', 'Kupferhafen'], correctAnswer: 0, explanation: 'Stahlhof (Steelyard).' },
    { id: 'q-h-4-3', text: 'Wann Stahlhof geschlossen?', type: 'multiple-choice', options: ['1400', '1500', '1598', '1700'], correctAnswer: 2, explanation: '1598 — Elisabeth I.' }
  ]},
  { id: 'h12', title: 'Bergen — Monopol auf Kabeljau', content: 'Bergen (Norwegen) — Hansekontor ab 14. Jh. Kontrolle über Kabeljaufang und -verkauf (Trockenfisch — «Stockfisch» — Nahrung für Seeleute und Armeen). Norweger fingen, Hanse kaufte billig, verkaufte teuer. Bergen — größter Fischmarkt. Hanse lebte dort generationenlang. Monopol bis 17. Jh.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/bergen.jpg', title: 'Bergen' }] },
  { id: 'h13', title: 'Humor: «Hanse — Mönche, die Geld zählen»', content: 'Hansekaufleute in Kontoren lebten streng: keine Frauen, kein Glücksspiel, kein Alkohol (offiziell). Ganze Zeit — Handel und Buchführung. Kirche billigte: «Wie Mönche!» Realität: tranken, spielten, hatten Mätressen. Aber Geld zählten genau. Mönchtum mit Gewinn.', duration: 3 },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-h-5-1', text: 'Was kontrollierte Hanse in Bergen?', type: 'multiple-choice', options: ['Gold', 'Kabeljau (Stockfisch)', 'Pelze', 'Getreide'], correctAnswer: 1, explanation: 'Kabeljau — Nahrung für Seeleute.' },
    { id: 'q-h-5-2', text: 'Wie lebten Kaufleute?', type: 'multiple-choice', options: ['Luxuriös', 'Streng wie Mönche (offiziell)', 'In Armut', 'Mit Familien'], correctAnswer: 1, explanation: 'Strenges Regime, aber Geld wichtiger.' },
    { id: 'q-h-5-3', text: 'Wie viele Hauptkontore?', type: 'multiple-choice', options: ['Zwei', 'Vier', 'Zehn', 'Zwanzig'], correctAnswer: 1, explanation: 'Vier: Nowgorod, Brügge, London, Bergen.' }
  ]},
  { id: 'h14', title: 'Krieg mit Piraten — «Vitalienbrüder»', content: '1390er: Piraten «Vitalienbrüder» plünderten Hanseschiffe. Hanse mietete Flotte, vernichtete Piraten. Aber manche Städte (z.B. Rostock) unterstützten Piraten — Konkurrenz innerhalb Hanse. Lübeck organisierte Strafexpedition, besiegte Rostock. Hanse zeigte: Wer gegen Monopol — wird vernichtet.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/pirates.jpg', title: 'Piraten' }] },
  { id: 'h15', title: 'Salz — Kontrolle über Konservierung', content: 'Salz — notwendig zum Pökeln von Fisch, Fleisch. Hanse kontrollierte Salzbergwerke in Lüneburg (Deutschland). Monopol auf Salz = Kontrolle über Lebensmittelindustrie. Preis diktierte Hanse. Ohne Salz — Fisch verfault, Fleisch verdirbt. Europa hing von Hanse ab. Salz = weißes Gold.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/salt.jpg', title: 'Salz' }] },
  { id: 'h16', title: 'Wachs und Pelze — Monopol aus Osten', content: 'Hanse kaufte Wachs (für Kerzen) und Pelze (Zobel, Marder) in Nowgorod und Pskow. Europa zahlte riesige Preise. Hanse — Vermittler, Aufschlag 200–300%. Russen verkauften billig, Europäer kauften teuer. Hanse verdiente an Differenz. Als Iwan III. 1494 Kontor schloss, verlor Hanse Millionen.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/wax-furs.jpg', title: 'Wachs und Pelze' }] },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-h-6-1', text: '«Vitalienbrüder»?', type: 'multiple-choice', options: ['Mönche', 'Piraten', 'Händler', 'Könige'], correctAnswer: 1, explanation: 'Piraten, die Hanse plünderten.' },
    { id: 'q-h-6-2', text: 'Woher kam Salz?', type: 'multiple-choice', options: ['Aus Meer', 'Aus Lüneburg', 'Aus Rom', 'Aus Afrika'], correctAnswer: 1, explanation: 'Lüneburg — Salzbergwerke.' },
    { id: 'q-h-6-3', text: 'Aufschlag auf Pelze?', type: 'multiple-choice', options: ['10%', '50%', '200–300%', '1000%'], correctAnswer: 2, explanation: '200–300% — riesiger Gewinn.' }
  ]},
  { id: 'h17', title: 'Humor: «Hanse verkauft Luft, wenn möglich»', content: 'Händler: «Was kann man noch monopolisieren?» Hanse: «Salz, Fisch, Wachs, Pelze, Getreide, Bernstein…» Händler: «Und Luft?» Hanse: «Noch keine Technologie. Aber arbeiten daran». Mittelalterliches Amazon.', duration: 3 },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-h-7-1', text: 'Was kontrollierte Hanse aus Nowgorod?', type: 'multiple-choice', options: ['Gold', 'Wachs und Pelze', 'Wein', 'Stoffe'], correctAnswer: 1, explanation: 'Wachs und Pelze — aus Osten.' },
    { id: 'q-h-7-2', text: 'Warum verlor Hanse Osten?', type: 'multiple-choice', options: ['Krieg', 'Iwan III. schloss Kontor', 'Pest', 'Bankrott'], correctAnswer: 1, explanation: '1494 — Iwan III. schloss Peterhof.' },
    { id: 'q-h-7-3', text: 'Wozu Salz?', type: 'multiple-choice', options: ['Essen', 'Pökeln von Fisch und Fleisch', 'Bau', 'Medizin'], correctAnswer: 1, explanation: 'Konservierung — ohne Kühlschränke.' }
  ]},
  { id: 'h18', title: 'Blockade Brügge — Stadt kapitulierte', content: '1450er: Brügge führte neue Steuern auf Hanse ein. Hanse: «Blockade». Händler gingen, Hafen leerte sich, Handel stoppte. Brügge verlor Geld. Nach zwei Jahren: «Entschuldigung, streichen Steuern». Hanse kehrte zurück. Lektion: Kämpfe nicht mit Kartell, wenn du davon abhängst.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/blockade.jpg', title: 'Blockade' }] },
  { id: 'h19', title: 'Bernstein — Monopol der Ostsee', content: 'Bernstein wurde an Ostseeküsten gewonnen (hauptsächlich Preußen). Hanse kontrollierte Abbau und Verkauf. Bernstein — Schmuck, Medizin, Weihrauch. Europa zahlte Gold. Illegaler Abbau mit Tod bestraft. Monopol bis 16. Jh. Bernstein = baltisches Gold.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/amber.jpg', title: 'Bernstein' }] },
  { id: 'h20', title: 'Hanse und Deutschritterorden — Monopolisten-Allianz', content: 'Deutschritterorden (Kreuzritter in Preußen) kontrollierte Bernstein und Getreide. Hanse — Handel. Allianz: Orden gewinnt, Hanse verkauft. Gewinn geteilt. Zusammen kontrollierten sie Ostsee. Als Orden schwächte (15. Jh.), ließ Hanse ihn fallen. Freundschaft für Geld.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/teutonic.jpg', title: 'Deutschritterorden' }] },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-h-8-1', text: 'Was tat Hanse mit Brügge?', type: 'multiple-choice', options: ['Verbrannte', 'Blockierte', 'Kaufte', 'Ignorierte'], correctAnswer: 1, explanation: 'Blockade — Stadt kapitulierte.' },
    { id: 'q-h-8-2', text: 'Woher kam Bernstein?', type: 'multiple-choice', options: ['Afrika', 'Ostsee (Preußen)', 'Rom', 'China'], correctAnswer: 1, explanation: 'Ostsee — Bernsteinküste.' },
    { id: 'q-h-8-3', text: 'Mit wem Allianz in Preußen?', type: 'multiple-choice', options: ['König', 'Deutschritterorden', 'Kirche', 'Bauern'], correctAnswer: 1, explanation: 'Deutschritterorden — Ritter-Monopolisten.' }
  ]},
  { id: 'h21', title: 'Humor: «Handeln? Zahle Hanse»', content: 'Händler versucht Fisch im Hafen zu verkaufen. Hanse: «Hast du Lizenz?» Händler: «Nein». Hanse: «Dann Warenbeschlagnahme». Händler: «Ich bin freier Mann!» Hanse: «Warst frei. Jetzt — bankrott». Handelsfreiheit endet, wo Hanse beginnt.', duration: 3 },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-h-9-1', text: 'Strafe für illegalen Bernstein?', type: 'multiple-choice', options: ['Geldstrafe', 'Tod', 'Gefängnis', 'Nichts'], correctAnswer: 1, explanation: 'Todesstrafe — Monopol heilig.' },
    { id: 'q-h-9-2', text: 'Warum ließ Hanse Orden fallen?', type: 'multiple-choice', options: ['Verrat', 'Orden schwächte — nicht profitabel', 'Krieg', 'Religion'], correctAnswer: 1, explanation: 'Freundschaft für Geld.' },
    { id: 'q-h-9-3', text: 'Hauptwaffe der Hanse?', type: 'multiple-choice', options: ['Armee', 'Flotte', 'Blockade', 'Gebete'], correctAnswer: 2, explanation: 'Blockade — effektiver als Krieg.' }
  ]},
  { id: 'h22', title: 'Niedergang — neue Konkurrenten', content: '16. Jh.: Konkurrenten erschienen. Holländer bauten billige Schiffe, handelten billiger. England und Spanien schufen eigene Flotten. Entdeckung Amerikas — Handel verlagerte sich in Atlantik. Hanse verlor Monopol. Städte traten aus Bund aus. 1669: letzte Hansetagung — 9 Städte anwesend (waren 200). Kartell brach zusammen.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/decline.jpg', title: 'Niedergang' }] },
  { id: 'h23', title: 'Erbe der Hanse', content: 'Hanse schuf Handelsstandards: Verträge, Schiedsgerichtsbarkeit, Seerecht. Lübeck, Hamburg, Bremen behielten Reichtum. Deutsches Wort «Hanse» = Bund. Fluggesellschaft Lufthansa nach Hanse benannt. Moderne EU ähnelt Hanse — Wirtschaftsbund ohne Imperium. Hanse — Prototyp der Globalisierung.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/legacy.jpg', title: 'Erbe' }] },
  { id: 'h24', title: 'Humor: «Hanse starb, aber Lufthansa lebt»', content: 'Hanse: «Wir kontrollieren Ostsee». 17. Jh.: «Konkurrenten siegten». Hanse: «Schließen». 20. Jh.: «Gründen Fluggesellschaft Lufthansa». 21. Jh.: «Fliegen weltweit». Monopol ewig, nur Transport ändert sich.', duration: 3 },
  { id: 'q10', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-h-10-1', text: 'Warum brach Hanse zusammen?', type: 'multiple-choice', options: ['Krieg', 'Konkurrenten und Amerika', 'Pest', 'Revolution'], correctAnswer: 1, explanation: 'Holländer, Engländer, Atlantik.' },
    { id: 'q-h-10-2', text: 'Wann letzte Tagung?', type: 'multiple-choice', options: ['1500', '1600', '1669', '1700'], correctAnswer: 2, explanation: '1669 — 9 Städte anwesend.' },
    { id: 'q-h-10-3', text: 'Was nach Hanse benannt?', type: 'multiple-choice', options: ['Bank', 'Lufthansa', 'Universität', 'Schiff'], correctAnswer: 1, explanation: 'Lufthansa — Fluggesellschaft.' }
  ]},
  { id: 'h25', title: 'Fazit: Kartell besiegt Könige', content: 'Hanse — erstes transnationales Kartell. Ohne Armee besiegte Dänemark, blockierte England, kontrollierte Ostsee. Monopol auf Fisch, Salz, Pelze, Wachs. Könige fürchteten Blockade. 400 Jahre Herrschaft. Brach wegen Konkurrenz zusammen, aber schuf Standards des Welthandels. Lektion: Wirtschaft stärker als Waffen.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/summary.jpg', title: 'Fazit' }] },
  { id: 'h26', title: 'Vergleich: Hanse vs moderne Kartelle', content: 'Hanse kontrollierte Preise — wie OPEC (Öl). Blockierte Konkurrenten — wie US-Sanktionen. Monopol ohne Staat — wie Google, Amazon. Unterschied: Hanse war Städtebund, moderne Kartelle — Konzerne. Aber Prinzip gleich: Marktkontrolle = Macht.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/comparison.jpg', title: 'Vergleich' }] },
  { id: 'h27', title: 'Wirtschaftslektionen der Hanse', content: 'Monopol profitabel für Besitzer, verheerend für Verbraucher. Blockade effektiver als Krieg. Kartell funktioniert, solange keine Konkurrenz. Entdeckung neuer Märkte (Amerika) zerstört alte Monopole. Wirtschaft ohne Staat möglich (aber ungerecht). Hanse — Lehrbuch des Kapitalismus ohne Beschönigung.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/lessons.jpg', title: 'Lektionen' }] },
  { id: 'h28', title: 'Humor: «Hanse — OPEC des Mittelalters»', content: 'OPEC: «Wir kontrollieren Öl». Hanse (aus Vergangenheit): «Wir kontrollierten Hering, Salz, Wachs. Öl — für Anfänger». OPEC: «Aber ihr brachtzisammen». Hanse: «Aber 400 Jahre regierten. Und ihr?» OPEC: «Noch halten wir durch». Hanse: «Abwarten».', duration: 3 },
  { id: 'h29', title: 'Schluss: Handel als Waffe', content: 'Hanse bewies: Handel — stärkste Waffe. Blockade tötet Wirtschaft ohne Schuss. Monopol gibt Macht über Könige. Kartell ohne Armee kontrollierte Nordeuropa 400 Jahre. Brach wegen Konkurrenz zusammen, aber schuf Grundlagen modernen Handels. Geschichte ohne Romantik — reine Kalkulation.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/conclusion.jpg', title: 'Schluss' }] },
  { id: 'h30', title: 'Final: Monopol ewig, Form ändert sich', content: 'Hanse — mittelalterliches Kartell. Heute — Google, Amazon, OPEC. Prinzip gleich: Marktkontrolle, Konkurrenzvernichtung, Preisdiktat. Form ändert sich, Wesen nicht. Hanse zeigte: Wirtschaft entscheidet alles. Hanse verstehen = modernen Kapitalismus verstehen. Lektionen des Mittelalters heute aktuell.', duration: 3, media: [{ type: 'image', url: '/media/hansa-monopoly/final.jpg', title: 'Final' }] }
]

export const hansaMonopolyFinalQuizDE: QuizBlock = {
  id: 'quiz-hansa-monopoly',
  title: 'Abschlussquiz: Hanse — Kartell und Monopol',
  questions: [
    { id: 'final-h1', text: 'Was ist Hanse?', type: 'multiple-choice', options: ['Staat', 'Handelskartell', 'Armee', 'Kirche'], correctAnswer: 1, explanation: 'Handelsbund.' },
    { id: 'final-h2', text: 'Hauptstadt?', type: 'multiple-choice', options: ['Hamburg', 'Lübeck', 'Berlin', 'Köln'], correctAnswer: 1, explanation: 'Lübeck — Königin.' },
    { id: 'final-h3', text: 'Wie kämpfte Hanse?', type: 'multiple-choice', options: ['Krieg', 'Blockade', 'Gebete', 'Bestechung'], correctAnswer: 1, explanation: 'Wirtschaftswaffe.' }
  ]
}
