import { Slide, QuizBlock } from '../types/session'

export const medievalBattleTacticsSlidesDE: Slide[] = [
  { id: 'mbt1', title: 'Schildwand: Phalanx ohne Aristoteles', content: 'Germanische und skandinavische Staemme gelangten unabhaengig von den Griechen zu demselben Schluss: Schild an Schild bedeutet Ueberleben. Die skandinavische Skjaldborg unterschied sich von der griechischen Phalanx vor allem dadurch, dass die Griechen standen und den Stoss erwarteten, die Wikinger in der Linie ebenfalls standen - dahinter aber Bogenschuetzen verbargen, die Wurfspeere schleuderten. Die Formation war ein Instrument der Verteidigung, nicht des Angriffs.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/01-shield-wall-barbarian.jpg', title: 'Schildwand' }] },
  { id: 'mbt2', title: 'Die «Schweinekopf»-Formation - Wikingerkeil', content: 'Svinfylking ist ein angreifender Keil, dessen Spitze aus den erfahrensten Kaempfern gebildet wurde. Aufgabe war es, die gegnerische Schildmauer an einer einzigen Stelle zu durchbrechen; danach zerfiel der Verband, und es beginnt ein allgemeines Gemetzel, in dem individuelle Staerke mehr zaehlt. Strukturell handelt es sich um ein direktes Pendant zum makedonischen Hetairoi-Keil - nur zu Fuss und ohne Koordination mit der Infanterie.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/02-svinfylking.jpg', title: 'Schweinekopf' }] },
  { id: 'mbt3', title: 'Hastings 1066: Mauer gegen Reiterei', content: 'Die englische Schildmauer Haralds auf dem Senlac-Huegel wehrte sieben Stunden lang die Angriffe der normannischen Reiterei ab; diese vermochte den dichten Verband am Hang nicht zu durchstossen. Gebrochen wurde die Linie nicht durch einen Treffer, sondern durch Disziplinverlust: Ein Teil der Angelsachsen verliess die Stellung, um scheinbar fliehende Normannen zu verfolgen, riss eine Bresche - und alles brach zusammen. Scheinrueckzug hatte bereits Alexander bei Gaugamela eingesetzt.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/03-hastings.jpg', title: 'Schlacht bei Hastings' }] },
  {
    id: 'q1',
    title: 'Quiz',
    content: '',
    duration: 2,
    questions: [
      { id: 'q-mbt-1-1-de', text: 'Welchem Merkmal der Phalanx kommt die Skjaldborg inhaltlich am naechsten?', type: 'multiple-choice', options: ['Reiterkeil', 'Geschlossene Schildfront', 'Aufgeloester Bogenschuetzenverband', 'Belagerungswall'], correctAnswer: 1, explanation: 'Entscheidend ist die dichte Linie mit gegenseitiger Deckung.' },
      { id: 'q-mbt-1-2-de', text: 'Was geschieht nach dem Durchbruch bei Svinfylking typischerweise?', type: 'multiple-choice', options: ['Geordneter Rueckzug ins Lager', 'Uebergang zum Nahkampf ausserhalb der Formation', 'Festungsbau', 'Belagerung einer Burg'], correctAnswer: 1, explanation: 'Nach dem Riss verkommt der Kampf zu einem Handgemenge ohne klare Linie.' },
      { id: 'q-mbt-1-3-de', text: 'Warum zerbrach die angelsaechsische Linie bei Hastings?', type: 'multiple-choice', options: ['Reiterei durchstoss das Zentrum', 'Teile der Infanterie verfolgten einen Scheinrueckzug und verloren die Ordnung', 'Speermangel', 'Mongolengriff'], correctAnswer: 1, explanation: 'Ohne Disziplin wurde die Front verwundbar.' }
    ]
  },

  { id: 'mbt4', title: 'Hird - das professionelle Kernkontingent', content: 'Skandinavische Konige unterhielten eine persoenliche Dienstgemeinschaft - die Hird, woertlich «Hof». Das war keine Jahresmiliz, sondern staendige Krieger auf Sold, die das ganze Jahr trainierten. Funktionell entspricht sie den roemischen Legionaren oder den makedonischen Hetairoi: einer Elite, die den Verband haelt, wenn das Aufgebot bereits gewichen ist.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/04-hird.jpg', title: 'Hird' }] },
  { id: 'mbt5', title: 'Ritterkeil: 800 kg bei Tempo', content: 'Ein schwerer Ritter in voller Ruestung auf dem Schlachtross brachte zusammen rund 600 bis 800 kg auf die Waage. Im Galopp war die kinetische Energie des Schlages derart hoch, dass ein geschlossener Keil aus zwanzig Rittern formungslose Infanterie regelrecht wegfegte. Arabische Chronisten, die bei Tours erstmals auf fraenkische Reiterei trafen, beschrieben sie als «eiserne Lawine», die nichts mehr aufhaelt.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/05-knight-charge.jpg', title: 'Ritterkeil' }] },
  { id: 'mbt6', title: 'Warum der Keil frontal schlug, nicht in die Flanke', content: 'Alexander fuehrte seine Kavallerie gegen Flanke und Nahtstelle - dorthin, wo die Formation schwaecher wurde. Der mittelalterliche Ritter aber preschte frontal vor: Tempo aufnehmen, Lanze einsetzen, durchbrechen. Der Grund ist einfach: Der feudalen Reiterei fehlte die Koordination fuer komplexe Manoever. Ein direkter Angriff erforderte vor allem Schnelligkeit und Mut; ein Flankenstoss erforderte hingegen eine zuverlaessige Verbindung zwischen den Abteilungen.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/06-knight-frontal-flank.jpg', title: 'Frontalangriff' }] },
  {
    id: 'q2',
    title: 'Quiz',
    content: '',
    duration: 2,
    questions: [
      { id: 'q-mbt-2-1-de', text: 'Was charakterisiert die Hird skandinavischer Herrscher?', type: 'multiple-choice', options: ['Saisonales Aufgebot', 'Staendige Soldtruppe auf Jahrlohn', 'Wikingerflotte', 'Kaufmannsgilde'], correctAnswer: 1, explanation: 'Es handelt sich um ein professionelles Kernkontingent.' },
      { id: 'q-mbt-2-2-de', text: 'Welche Wirkung entfaltete ein schwerer Ritterkeil gegen ungeuebte Infanterie?', type: 'multiple-choice', options: ['Ueberlegenheit nur im Bogenschiessen', 'Geschlossener Keil raeumte durch Masse und Geschwindigkeit auf', 'Der Feind wich immer kampflos', 'Lanzen konnten keine Kettenhemden durchschlagen'], correctAnswer: 1, explanation: 'Tempo und Gewicht erzeugten den physischen Durchbruch.' },
      { id: 'q-mbt-2-3-de', text: 'Warum griffen mittelalterliche Ritter oft frontal an?', type: 'multiple-choice', options: ['Flankenangriffe waren kirchlich verboten', 'Komplexen Manoevern fehlte die Absprache zwischen Kontingenten', 'Schlachtrosse konnten nicht wenden', 'Der Gegner zeigte immer den Ruecken'], correctAnswer: 1, explanation: 'Ohne klare Fuehrungsstruktur bleibt der Frontalstoss das einfachere Mittel.' }
    ]
  },

  { id: 'mbt7', title: 'Courtrai 1302: Ende einer Illusion', content: 'Bei Courtrai stellten sich flaemische Weber-Infanteristen mit Piken und Goedendagen - einer Kombination aus Pike und Streitkolben - dicht geschlossen auf sumpfigem Gelaende auf. Die franzoesische Ritterreiterei stuermte an und versank im Schlamm. Die Fusskraefte vollendeten methodisch die Arbeit an gestuerzten Reitern. Auf dem Feld wurden 700 goldene Sporen gesammelt - daher der Name «Schlacht der goldenen Sporen». Erstmals seit zweihundert Jahren schlug Infanterie die beste Reiterei Europas.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/07-courtrai.jpg', title: 'Courtrai' }] },
  { id: 'mbt8', title: 'Abgestiegene Ritter - eine erzwungene Taktik', content: 'Nach mehreren Katastrophen gegen Eidgenossen und Flaeminger begannen franzoesische und englische Befehlshaber, Ritter bewusst abzusteigen und in die erste Linie zu Fuss zu stellen: schwere Ruestung, Kampferfahrung, hoher Kampfgeist - plus die Standfestigkeit der Infanterie. Bei Azincourt taten die Franzosen genau das - und verloren dennoch, weil sie durch aufgeweichten Schlamm unter Pfeilregen vorwaertsdrueckten.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/08-dismounted-knights.jpg', title: 'Abgestiegene Ritter' }] },
  { id: 'mbt9', title: 'Englischer Langbogen: zehn Jahre Ausbildung', content: 'Eibenholzbogen von 1,8 m Laenge, Zuggewichte von 80 bis 100 kg, zwoelf Pfeile pro Minute - dreimal schneller als die Armbrust. Die Ausbildung begann jedoch in der Kindheit und dauerte zehn Jahre und laenger. Skelette englischer Bogenschuetzen des 14. und 15. Jahrhunderts zeigen typische Deformationen: vergroesserte linke Arme, gekruemmte Wirbelsaeulen. Die Koerper formten sich buchstaeblich dem Werkzeug an.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/09-longbow.jpg', title: 'Langbogen' }] },
  {
    id: 'q3',
    title: 'Quiz',
    content: '',
    duration: 2,
    questions: [
      { id: 'q-mbt-3-1-de', text: 'Welcher Faktor war fuer den flaemischen Sieg bei Courtrai entscheidend?', type: 'multiple-choice', options: ['Gebirgsstellung', 'Dichter Pikenverband auf Moorboden', 'Flottenunterstuetzung', 'Belagerung von Paris'], correctAnswer: 1, explanation: 'Morast und Pikendichte neutralisierten die Reiterei.' },
      { id: 'q-mbt-3-2-de', text: 'Warum stiegen Kommandanten spaeter Ritter vor der Schlacht ab?', type: 'multiple-choice', options: ['Futter zu sparen', 'Um Elitekaempfer in einer haltbaren Infanterielinie zu buendeln', 'Weil die Kirche Reiten verbot', 'Um durch einen Fluss zu waten'], correctAnswer: 1, explanation: 'Man suchte die Staerke schwerer Ruestung mit Formation zu verbinden.' },
      { id: 'q-mbt-3-3-de', text: 'Was kennzeichnet die Ausbildung englischer Langbogenschuetzen?', type: 'multiple-choice', options: ['Zweiwoechiger Kurs', 'Langjaehriges Training ab der Jugend', 'Ausschliesslich Adel', 'Verbot regulueren Schiessens'], correctAnswer: 1, explanation: 'Meisterschaft setzte jahrzehntelange Praxis voraus.' }
    ]
  },

  { id: 'mbt10', title: 'Crecy 1346: Regen und Genuesen', content: 'Vor der Schlacht bei Crecy ging ein heftiger Regen nieder. Englische Bogenschuetzen nahmen die Sehnen ab und steckten sie unter die Kopfbedeckung - genuesische Armbrustschuetzen auf franzoesischer Seite taten dies nicht durchweg. Als der Kampf begann, waren die genuesischen Armbrueste feucht und versagten mit Fehlschuessen. Die englischen Bogen funktionierten normal. Das Wetter entschied den Ausgang noch vor dem ersten Reiterangriff.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/10-crecy.jpg', title: 'Crecy' }] },
  { id: 'mbt11', title: 'Mongolischer Kompositbogen: 300 Meter vom Pferd', content: 'Der mongolische Kompositbogen aus Holz, Knochen und Sehnen war kuerzer als der englische, aber kraeftiger und handlicher im Sattel. Effektive Schussweite 200 bis 300 m, bis zu zehn Schuss pro Minute im Vollgalopp. Der mongolische Krieger konnte im «parthischen Schuss», tausend Jahre nach Crassus von den Steppenvoelkern weitergegeben, rueckwaerts reitend treffen.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/11-mongol-bow.jpg', title: 'Mongolenbogen' }] },
  { id: 'mbt12', title: 'Armbrust: Wucht gegen Tempo', content: 'Die Armbrust durchschlug Ruestungen, die der Langbogen nicht immer durchschlug - Bolzen mit quadratischer Spitze drangen in Kettenhemden wie mit einer Ahle ein. Die Nachladung dauerte jedoch 30 bis 60 Sekunden. Daher arbeiteten Armbrustschuetzen stets paarweise mit Pavise-Traegern: Waehrend der eine schoss, deckte der andere mit dem grossen Schild. Ein frueher Vorlaeufer der «Feuergruppe».', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/12-crossbow.jpg', title: 'Armbrust' }] },
  {
    id: 'q4',
    title: 'Quiz',
    content: '',
    duration: 2,
    questions: [
      { id: 'q-mbt-4-1-de', text: 'Was schwaechte die genuesischen Armbruestschuetzen bei Crecy?', type: 'multiple-choice', options: ['Bolzenmangel', 'Durchnaesste Sehnen und Fehlschuesse nach dem Regen', 'Massenhafte Desertion', 'Fehlende Schilde'], correctAnswer: 1, explanation: 'Feuchtigkeit beeintraechtigte die Armbrustsehnen.' },
      { id: 'q-mbt-4-2-de', text: 'Worin liegt der Kernvorteil des mongolischen Bogens im Feld?', type: 'multiple-choice', options: ['Reine Repraesentation', 'Kombination aus Durchschlagskraft und Handhabung im Galopp', 'Bedienung ohne Schuetzen', 'Ausschliesslich Belagerung'], correctAnswer: 1, explanation: 'Der Kompositbogen ist auf Steppenreiterei zugeschnitten.' },
      { id: 'q-mbt-4-3-de', text: 'Wie wurde die langsame Armbrustnachladung ausgeglichen?', type: 'multiple-choice', options: ['Verzicht auf Ruestung', 'Zweierteam mit Schildtraeger', 'Salvenfeuer ohne Zielen', 'Nachtkaempfe allein'], correctAnswer: 1, explanation: 'Die Pavise schuetzte waehrend der Nachladung.' }
    ]
  },

  { id: 'mbt13', title: 'Die Bataille: eine Phalanx, die angreift', content: 'Die schweizerische Bataille - ein dichter Block von 50 mal 50 Mann mit vier bis fuenf Meter langen Piken - erinnerte formell an die sumerische Phalanx vor 3000 Jahren. Entscheidend war jedoch: Die Schweizer warteten nicht auf den Stoss, sondern gingen selbst fast im Lauf vor. Drei Bataillen rueckten im Staffelformat vor - gross in der Mitte, kleiner an den Flanken. Tempo und Aggression ersetzten ihnen die Feldartillerie.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/13-swiss-pike.jpg', title: 'Schweizer Bataille' }] },
  { id: 'mbt14', title: 'Morgarten 1315: Hinterhalt im Gebirge', content: 'Schweizer Bauern lockten oesterreichische Ritter in eine enge Schlucht zwischen Berg und See. Die Reiterei konnte sich nicht formieren, nicht ordentlich zurueckweichen und nicht im Verband angreifen. Von oben flogen Steine, von unten trafen Hellebarden - es war keine Schlacht, sondern ein Massaker. Panzerreiterei wird im Gebirge zur Zielscheibe.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/14-morgarten.jpg', title: 'Morgarten' }] },
  { id: 'mbt15', title: 'Hellebarde: universelle Antwort auf den Ritter', content: 'Die schweizerische Hellebarde vereinte Axt, Spies und Haken auf einem langen Schaft. Mit dem Haken zog man Reiter vom Pferd, mit der Axt hieb man gegen die Ruestung, mit der Spitze stach man ins Visiergitter. Spezialisiertes Instrument gegen Ritter - wie das roemische Pilum auf das Problem «Schild» zugeschnitten war. Beide Waffen loesten dieselbe Aufgabe: die Kernstaerke des Gegners zu neutralisieren.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/15-halberd.jpg', title: 'Hellebarde' }] },
  {
    id: 'q5',
    title: 'Quiz',
    content: '',
    duration: 2,
    questions: [
      { id: 'q-mbt-5-1-de', text: 'Worin unterschied sich die schweizerische Bataille von einer «wartenden» Phalanx?', type: 'multiple-choice', options: ['Kuerzere Piken', 'Aggressiver Vorstoss statt Abwarten', 'Ausschliesslich Reiterei', 'Mangelnde Disziplin'], correctAnswer: 1, explanation: 'Die Eidgenossen diktierten selbst das Tempo des Angriffs.' },
      { id: 'q-mbt-5-2-de', text: 'Warum versagten die Ritter bei Morgarten?', type: 'multiple-choice', options: ['Lanzen fehlten', 'Die enge Schlucht verwehrte Manoever und Schwung', 'Ueberlauf zum Gegner', 'Seekampf'], correctAnswer: 1, explanation: 'Das Gelaende machte klassische Reitertaktik unmoeglich.' },
      { id: 'q-mbt-5-3-de', text: 'Welche drei Funktionen erfuellt die Hellebarde gegen Reiter?', type: 'multiple-choice', options: ['Ausschliesslich Gebet', 'Haken, Hieb, Stoss', 'Nur Wurfwaffe', 'Signalhorn'], correctAnswer: 1, explanation: 'Das System ist explizit gegen Panzerreiter gerichtet.' }
    ]
  },

  { id: 'mbt16', title: '«Keine Gefangenen»', content: 'Schweizer machten grundsaetzlich keine Ritter zu Gefangenen - obwohl das Loesegeld fuer einen adligen Gefangenen ein Vermoegen haette einbringen koennen. Die pragmatische Ursache: Wer einen Gefangenen eskortiert, entzieht der Schlacht einen Kaempfer. Ein Gegner in Panik flieht wirksamer als einer, der auf Gnade hofft. Dieser Ruf wirkte als psychologische Waffe.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/16-no-prisoners.jpg', title: 'Keine Gefangenen' }] },
  { id: 'mbt17', title: 'Tuemen: Armee steuern in Echtzeit', content: 'Die mongolische Armee gliederte sich in Zehner, Hunderter, Tausender und Tuemen zu je 10 000 Mann. Befehle liefen ueber Fahnen, Trommeln und Hoerner - ein mehrstufiges Signalsystem, das es erlaubte, innerhalb von Minuten einen Tuemen auf einen anderen Fluegel zu verlegen. Das naechste historische Pendant waere die roemische Kohortenordnung - die jedoch zu jener Zeit seit acht Jahrhunderten verschwunden war.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/17-tumen.jpg', title: 'Tuemen' }] },
  { id: 'mbt18', title: 'Scheinrueckzug: den Ritter in die Falle locken', content: 'Der mongolische «Scheinrueckzug» - tulughma - funktionierte gegen die Rittermentalitaet nahezu zuverlaessig. Die Reiterei gab den Anschein der Flucht; Ritter setzten zur Verfolgung an, zerbrachen ihren Verband und dehnten sich - und gerieten aus allen Richtungen in einen Kessel. Bei Liegnitz (1241) ging das polnisch-deutsche Heer genauso unter. Denselben Trick hatte Miltiades schon 490 v. Chr. bei Marathon angewandt - 1700 Jahre vor den Mongolen.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/18-feigned-retreat.jpg', title: 'Scheinrueckzug' }] },
  {
    id: 'q6',
    title: 'Quiz',
    content: '',
    duration: 2,
    questions: [
      { id: 'q-mbt-6-1-de', text: 'Welcher pragmatische Grund sprach gegen Rittergefangene?', type: 'multiple-choice', options: ['Paepstliches Verbot', 'Gefangenentransport bindet Kaempfer', 'Unkenntnis hoher Loesgelder', 'Ritter ergaben sich nie'], correctAnswer: 1, explanation: 'Jeder fuer Eskorte eingesetzte Mann fehlte in der Linie.' },
      { id: 'q-mbt-6-2-de', text: 'Welche Sollstaerke hatte ein Tuemen?', type: 'multiple-choice', options: ['1.000', '10.000', '50.000', '100'], correctAnswer: 1, explanation: 'Die Einheit entsprach nominell «tausend mal tausend».' },
      { id: 'q-mbt-6-3-de', text: 'Welchen Effekt hatte der mongolische Scheinrueckzug?', type: 'multiple-choice', options: ['Der Feind erholt sich immer', 'Verfolgung zerstoerte die Ordnung und eroeffnete Umzingelung', 'Mongolenpferde ermuedeten zuerst', 'Schuesse wurden eingestellt'], correctAnswer: 1, explanation: 'Das Nachsetzen lockerte den Verband fuer die Falle.' }
    ]
  },

  { id: 'mbt19', title: 'Mohi 1241: Uebergang in der Nacht', content: 'Koenig Bela IV der Ungarn nahm hinter der Sajo eine Verteidigungsposition ein - mit einer etwa 60 000 Mann starken Armee, doppelt so stark wie die mongolische. Subedei liess noch in derselben Nacht einen Tuemen 30 km flussabwaerts uebersetzen und ging den Ungarn bei Morgendaemmerung in den Ruecken. Waehrend das mongolische Zentrum die Bruecke attackierte, schloss Subedeis Tuemen den Ring. Die Ungarn verloren bis zu 40 000 Mann. Subedei war damals bereits ueber siebzig Jahre alt.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/19-mohi.jpg', title: 'Mohi' }] },
  { id: 'mbt20', title: 'Warum die Mongolen einen Fluchtkorridor liessen', content: 'Bei Umzingelungen liessen die Mongolen absichtlich einen Durchbruch offen - eine «goldene Bruecke». Der eingeschlossene Gegner, der einen Ausweg sah, begann zu fliehen statt bis zur letzten Hand zu kaempfen. Aus der dichten Formation wurde eine fliehende Masse, die die Kavallerie nahezu verlustarm niederreiten und niederschiessen konnte. Ein demoralisierter Feind ist wirksamer als ein toter: Er traegt die Panik bis zur naechsten Stadt.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/20-golden-bridge.jpg', title: 'Fluchtkorridor' }] },
  { id: 'mbt21', title: 'Die Burg als taktische Waffe', content: 'Wilhelm I. errichtete nach Hastings innerhalb von zehn Jahren 36 Burgen - etwa eine pro zwei bis drei Grafschaften. Jede Garnison von 50 bis 100 Rittern lahmte den Aufstand einer ganzen Region: Territorialkontrolle ist kaum moeglich, solange im Ruecken ein feindlicher Festpunkt steht. Die Logik entspricht roemischen Legionslagern - nur dauerhaft und aus Stein.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/21-norman-castle.jpg', title: 'Normannenburg' }] },
  {
    id: 'q7',
    title: 'Quiz',
    content: '',
    duration: 2,
    questions: [
      { id: 'q-mbt-7-1-de', text: 'Welcher Schluesselzug Subedeis entschied die Schlacht bei Mohi?', type: 'multiple-choice', options: ['Massenangriff auf die Bruecke', 'Nachtuebergang und Schlag in den Ruecken', 'Verzicht auf die Schlacht', 'Seeblockade'], correctAnswer: 1, explanation: 'Umgehung und Einkesselung brachen die Verteidigung.' },
      { id: 'q-mbt-7-2-de', text: 'Welchen Zweck hatte die «goldene Bruecke»?', type: 'multiple-choice', options: ['Humanitaere Gruende', 'Flucht ausloesen und Formation aufloesen', 'Handel mit dem Feind', 'Wasserversorgung'], correctAnswer: 1, explanation: 'Fliehende sind leichter zu vernichten als eine geschlossene Linie.' },
      { id: 'q-mbt-7-3-de', text: 'Welche strategische Rolle spielte das normannische Burgennetz?', type: 'multiple-choice', options: ['Nur adlige Wohnstaette', 'Knoten zur Kontrolle der Region und Unterdrueckung von Aufstaenden', 'Getreidelager fuer Kloester', 'Schutz der Fischer'], correctAnswer: 1, explanation: 'Burgen verankerten herrschaftliche Kontrolle im Land.' }
    ]
  },

  { id: 'mbt22', title: 'Trebuchet: 150 kg Stein auf 300 Meter', content: 'Trebuchets des 13. Jahrhunderts schleuderten Steine von 100 bis 150 kg bis zu 300 m weit mit einer Streuung von etwa 10 m. Um einen Turm zu zerstoeren, waren typischerweise 10 bis 30 Treffer auf dieselbe Stelle noetig. Bei der Belagerung von Stirling (1304) liess Eduard I. ein Trebuchet «Warwolf» errichten - derart gewaltig, dass der Kommandant kapitulierte, noch bevor der erste Stein flog, um wenigstens die Maschine in Aktion zu sehen.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/22-trebuchet.jpg', title: 'Trebuchet' }] },
  { id: 'mbt23', title: 'Griechisches Feuer: brennt auf dem Wasser', content: 'Byzantinisches Griechisches Feuer wurde aus messingenen Rohr-Siphonen von Schiffen gespritzt. Die genaue Mischung ist bis heute unbekannt - vermutlich Erdoel, Pech, Kalk und weitere Bestandteile, die Brennen auf dem Wasser ermoeglichen. Versuche, es mit Wasser zu loeschen, konnten die Flammen sogar anfachen. Es rettete Konstantinopel 674-678 vor arabischen Flotten. Das Geheimnis starb mit Byzanz 1453.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/23-greek-fire.jpg', title: 'Griechisches Feuer' }] },
  { id: 'mbt24', title: 'Unterwuehlung unter die Mauer', content: 'Klassischer Weg, eine Burg ohne Sturm zu nehmen: Stollen unter den Eckturm treiben, die Decke mit Balken abstuetzen, den Gang mit Brennmaterial fuellen und zuenden. Brennende Balken geben nach, die Decke sackt ein, der Turm kippt. Verteidiger hoerten den Unterbau auf gespannte Trommelfelle oder an der Wellenbildung in Kupferschuesseln mit Wasser; Gegenmassnahme war der Gegenstollen.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/24-undermining.jpg', title: 'Unterwuehlung' }] },
  {
    id: 'q8',
    title: 'Quiz',
    content: '',
    duration: 2,
    questions: [
      { id: 'q-mbt-8-1-de', text: 'Welche Rolle spielte der Riesen-Trebuchet bei Stirling?', type: 'multiple-choice', options: ['Er passte nicht ins Gelaende', 'Psychologischer Druck und Prestige der Maschine', 'Paepstliches Belagerungsverbot', 'Ersatz fuer Kavallerie'], correctAnswer: 1, explanation: 'Einschuechterung konnte die Belagerung vor dem ersten Schuss beenden.' },
      { id: 'q-mbt-8-2-de', text: 'Was ist das Besondere am Griechischen Feuer?', type: 'multiple-choice', options: ['Es brannte nur an Land', 'Eine Mischung, die sich nicht wie normales Feuer mit Wasser loeschen laesst', 'Nur kulinarischer Zweck', 'Kein maritimer Einsatz'], correctAnswer: 1, explanation: 'Das Brennen auf dem Wasser war sein Kern.' },
      { id: 'q-mbt-8-3-de', text: 'Wie entdeckte man feindliche Unterwuehlung?', type: 'multiple-choice', options: ['Nur am Geruch', 'Vibrationen auf Membran oder im Wasser', 'Gar nicht', 'Vogelflug'], correctAnswer: 1, explanation: 'Fruehe Form der seismischen Aufklaerung.' }
    ]
  },

  { id: 'mbt25', title: 'Der englische «duenne rote Linie» des 14. Jahrhunderts', content: 'Englische Taktik im Hundertjaehrigen Krieg: Bogenschuetzen in Winkelstellung an den Flanken, abgestiegene Ritter im Zentrum, vor der gesamten Linie ein Pfahlriegel gegen die Reiterei. Der Gegner musste entweder frontal unter Pfeilen hindurch oder versuchen, den Fluegel zu umgehen - wo erneut Pfeile warteten. Die Taktik hatte kaum Schwachstellen, erforderte aber Disziplin und guenstiges Gelaende. Die Franzosen rueckten wiederholt frontal vor - und verloren wiederholt.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/25-agincourt-tactics.jpg', title: 'Azincourt' }] },
  { id: 'mbt26', title: 'Janitscharen: erste stehende Infanterie nach Rom', content: 'Osmanische Janitscharen - als Sklavensoldaten ueber die Devshirme aus christlicher Bevoelkerung ausgelesen - waren die erste professionelle Infanterie in Europa nach dem Zerfall Roms. Staendiger Sold, Kasernierung, einheitliche Bewaffnung, Drill. Im Kampf enge Verbaende mit Armbruesten und Yatagan. Bei Nikopolis (1396) erledigten sie die Kreuzfahrer, nachdem deren Ordnung bereits gebrochen war.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/26-janissaries.jpg', title: 'Janitscharen' }] },
  { id: 'mbt27', title: 'Terzio: Pike plus Arkebuse', content: 'Das spanische Terzio des 15. und 16. Jahrhunderts verband Pikeniere und Arkebusiere erstmals systematisch in einer Formation. Die Schuetzen gaben eine Salve ab, wichen hinter die Piken zurueck und luden nach - die Pikeniere hielten den Nahkampf. Das Prinzip «Feuer deckt das Herankommen» stammte von den Spaniern und blieb bis zum Ersten Weltkrieg nahezu unveraendert.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/27-tercio.jpg', title: 'Terzio' }] },
  {
    id: 'q9',
    title: 'Quiz',
    content: '',
    duration: 2,
    questions: [
      { id: 'q-mbt-9-1-de', text: 'Was bildete typischerweise die Vorderkante der englischen Aufstellung?', type: 'multiple-choice', options: ['Nur berittene Ritter', 'Pfahlriegel gegen Kavallerie, Fluegelbogenschuetzen', 'Ein einziger grosser Keil', 'Nur Schleudern'], correctAnswer: 1, explanation: 'Pfaehle und Bogen sicherten Front und Flanken.' },
      { id: 'q-mbt-9-2-de', text: 'Wofuer stehen die osmanischen Janitscharen in der Militaergeschichte?', type: 'multiple-choice', options: ['Seeherrschaft', 'Erste grosse stehende Infanterie nach der Antike', 'Reiterschuetzen ohne Kasernierung', 'Verzicht auf Bewaffnung'], correctAnswer: 1, explanation: 'Staendiger Drill und normierte Ausruestung waren neu.' },
      { id: 'q-mbt-9-3-de', text: 'Was ist das Kernmerkmal des spanischen Terzio?', type: 'multiple-choice', options: ['Nur Reiterei', 'Integration von Pike und Feuerwaffe im selben Verband', 'Ausschliesslich Belagerungsgeraete', 'Verbindung von Flotte und Landheer'], correctAnswer: 1, explanation: 'Feuer und Spiesse stabilisierten gemeinsam die Linie.' }
    ]
  },

  { id: 'mbt28', title: 'Hussitische Wagenburg - Festung aus Wagen', content: 'Die boehmischen Hussiten unter Jan Zizka erfanden in den 1420er Jahren die «Wagenburg» - ein verschanztes Lager aus kettenweise verbundenen Wagen. Innen Bogenschuetzen, Armbrustschuetzen und die ersten Handfeuerwaffen Europas. Ritterreiterei prallte ab und wurde aus kurzer Distanz niedergeschossen. Zizka war auf beiden Augen blind und kommandierte nur akustisch - und verlor dennoch keine Schlacht.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/28-wagenburg.jpg', title: 'Wagenburg' }] },
  { id: 'mbt29', title: 'Jedes Jahrhundert entdeckt dasselbe neu', content: 'Ein dichter Pikenverband stoppt Reiterei - das wussten die Griechen, wurde im fruehen Mittelalter vergessen und bei Courtrai erneut erprobt. Bogenschuetzen vernichten Infanterie vor dem Nahkampf - das kannten die Parther, nutzten die Englaender bei Crecy. Scheinrueckzug zerstoert Ordnung - genutzt von Miltiades, Hannibal und den Mongolen. Die Prinzipien blieben konstant - nur die Waffen wechselten.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/29-repeated-tactics.jpg', title: 'Wiederkehrende Lehren' }] },
  { id: 'mbt30', title: 'Pulver toetete nicht den Ritter - sondern die mittelalterliche Kampflogik', content: 'Der Ritter starb nicht zuerst an der Arkebusenkugel - gute Ruestung widerstand ihr noch lange. Pulver zerstoerte die Burg als strategisches Fundament des Feudalismus: Die Artillerie Karls VIII. im Italienfeldzug 1494 sprengte Festungen in Stunden, die zuvor Jahre gehalten hatten. Ohne Burgen keine feudale Landesverteidigung. Ohne feudale Verteidigung wenig Sinn fuer den Ritter als Systemfigur. Das Mittelalter endete nicht 1453 - es endete mit dem ersten Kanonenschlag gegen einen Steinbau.', duration: 3, media: [{ type: 'image', url: '/media/medieval-battle-tactics/30-gunpowder-castles.jpg', title: 'Pulver und Burgen' }] },
  {
    id: 'q10',
    title: 'Quiz',
    content: '',
    duration: 2,
    questions: [
      { id: 'q-mbt-10-1-de', text: 'Was versteht man unter einer Wagenburg?', type: 'multiple-choice', options: ['Segelschiff', 'Verschanztes Lager aus angeketteten Wagen', 'Ritterorden', 'Stadtmauer'], correctAnswer: 1, explanation: 'Mobile Festung der Hussiten.' },
      { id: 'q-mbt-10-2-de', text: 'Welches Fazit formuliert die Folie zu wiederkehrenden Taktiken?', type: 'multiple-choice', options: ['Alles geht unwiederbringlich verloren', 'Grundsaetze wiederholen sich, Technik entwickelt sich', 'Nur China kannte Taktik', 'Das Mittelalter verbannte Flanken'], correctAnswer: 1, explanation: 'Militaerische Grundsaetze sind zyklisch, Material nicht.' },
      { id: 'q-mbt-10-3-de', text: 'Was zerstoerte Pulver in diesem Kurs in erster Linie?', type: 'multiple-choice', options: ['Duellkodex', 'Die strategische Rolle langfristig haltbarer Burgen', 'Seekompass', 'Devshirme'], correctAnswer: 1, explanation: 'Schnelle Zerschlagung der Mauern wandelte die Strategie.' }
    ]
  }
]

export const medievalBattleTacticsFinalQuizDE: QuizBlock = {
  id: 'quiz-medieval-battle-tactics-de',
  title: 'Abschlussquiz: mittelalterliche Schlachtordnung (Niveau B2)',
  questions: [
    { id: 'q-mbt-f-1-de', text: 'Welchem Merkmal der Phalanx kommt die Skjaldborg inhaltlich am naechsten?', type: 'multiple-choice', options: ['Reiterkeil', 'Geschlossene Schildfront', 'Aufgeloester Bogenschuetzenverband', 'Belagerungswall'], correctAnswer: 1, explanation: 'Entscheidend ist die dichte Linie mit gegenseitiger Deckung.' },
    { id: 'q-mbt-f-2-de', text: 'Was geschieht nach dem Durchbruch bei Svinfylking typischerweise?', type: 'multiple-choice', options: ['Geordneter Rueckzug ins Lager', 'Uebergang zum Nahkampf ausserhalb der Formation', 'Festungsbau', 'Belagerung einer Burg'], correctAnswer: 1, explanation: 'Nach dem Riss verkommt der Kampf zu einem Handgemenge ohne klare Linie.' },
    { id: 'q-mbt-f-3-de', text: 'Warum zerbrach die angelsaechsische Linie bei Hastings?', type: 'multiple-choice', options: ['Reiterei durchstoss das Zentrum', 'Teile der Infanterie verfolgten einen Scheinrueckzug und verloren die Ordnung', 'Speermangel', 'Mongolengriff'], correctAnswer: 1, explanation: 'Ohne Disziplin wurde die Front verwundbar.' },
    { id: 'q-mbt-f-4-de', text: 'Was charakterisiert die Hird skandinavischer Herrscher?', type: 'multiple-choice', options: ['Saisonales Aufgebot', 'Staendige Soldtruppe auf Jahrlohn', 'Wikingerflotte', 'Kaufmannsgilde'], correctAnswer: 1, explanation: 'Es handelt sich um ein professionelles Kernkontingent.' },
    { id: 'q-mbt-f-5-de', text: 'Welche Wirkung entfaltete ein schwerer Ritterkeil gegen ungeuebte Infanterie?', type: 'multiple-choice', options: ['Ueberlegenheit nur im Bogenschiessen', 'Geschlossener Keil raeumte durch Masse und Geschwindigkeit auf', 'Der Feind wich immer kampflos', 'Lanzen konnten keine Kettenhemden durchschlagen'], correctAnswer: 1, explanation: 'Tempo und Gewicht erzeugten den physischen Durchbruch.' },
    { id: 'q-mbt-f-6-de', text: 'Warum griffen mittelalterliche Ritter oft frontal an?', type: 'multiple-choice', options: ['Flankenangriffe waren kirchlich verboten', 'Komplexen Manoevern fehlte die Absprache zwischen Kontingenten', 'Schlachtrosse konnten nicht wenden', 'Der Gegner zeigte immer den Ruecken'], correctAnswer: 1, explanation: 'Ohne klare Fuehrungsstruktur bleibt der Frontalstoss das einfachere Mittel.' },
    { id: 'q-mbt-f-7-de', text: 'Welcher Faktor war fuer den flaemischen Sieg bei Courtrai entscheidend?', type: 'multiple-choice', options: ['Gebirgsstellung', 'Dichter Pikenverband auf Moorboden', 'Flottenunterstuetzung', 'Belagerung von Paris'], correctAnswer: 1, explanation: 'Morast und Pikendichte neutralisierten die Reiterei.' },
    { id: 'q-mbt-f-8-de', text: 'Warum stiegen Kommandanten spaeter Ritter vor der Schlacht ab?', type: 'multiple-choice', options: ['Futter zu sparen', 'Um Elitekaempfer in einer haltbaren Infanterielinie zu buendeln', 'Weil die Kirche Reiten verbot', 'Um durch einen Fluss zu waten'], correctAnswer: 1, explanation: 'Man suchte die Staerke schwerer Ruestung mit Formation zu verbinden.' },
    { id: 'q-mbt-f-9-de', text: 'Was kennzeichnet die Ausbildung englischer Langbogenschuetzen?', type: 'multiple-choice', options: ['Zweiwoechiger Kurs', 'Langjaehriges Training ab der Jugend', 'Ausschliesslich Adel', 'Verbot regulueren Schiessens'], correctAnswer: 1, explanation: 'Meisterschaft setzte jahrzehntelange Praxis voraus.' },
    { id: 'q-mbt-f-10-de', text: 'Was schwaechte die genuesischen Armbruestschuetzen bei Crecy?', type: 'multiple-choice', options: ['Bolzenmangel', 'Durchnaesste Sehnen und Fehlschuesse nach dem Regen', 'Massenhafte Desertion', 'Fehlende Schilde'], correctAnswer: 1, explanation: 'Feuchtigkeit beeintraechtigte die Armbrustsehnen.' },
    { id: 'q-mbt-f-11-de', text: 'Worin liegt der Kernvorteil des mongolischen Bogens im Feld?', type: 'multiple-choice', options: ['Reine Repraesentation', 'Kombination aus Durchschlagskraft und Handhabung im Galopp', 'Bedienung ohne Schuetzen', 'Ausschliesslich Belagerung'], correctAnswer: 1, explanation: 'Der Kompositbogen ist auf Steppenreiterei zugeschnitten.' },
    { id: 'q-mbt-f-12-de', text: 'Wie wurde die langsame Armbrustnachladung ausgeglichen?', type: 'multiple-choice', options: ['Verzicht auf Ruestung', 'Zweierteam mit Schildtraeger', 'Salvenfeuer ohne Zielen', 'Nachtkaempfe allein'], correctAnswer: 1, explanation: 'Die Pavise schuetzte waehrend der Nachladung.' },
    { id: 'q-mbt-f-13-de', text: 'Worin unterschied sich die schweizerische Bataille von einer «wartenden» Phalanx?', type: 'multiple-choice', options: ['Kuerzere Piken', 'Aggressiver Vorstoss statt Abwarten', 'Ausschliesslich Reiterei', 'Mangelnde Disziplin'], correctAnswer: 1, explanation: 'Die Eidgenossen diktierten selbst das Tempo des Angriffs.' },
    { id: 'q-mbt-f-14-de', text: 'Warum versagten die Ritter bei Morgarten?', type: 'multiple-choice', options: ['Lanzen fehlten', 'Die enge Schlucht verwehrte Manoever und Schwung', 'Ueberlauf zum Gegner', 'Seekampf'], correctAnswer: 1, explanation: 'Das Gelaende machte klassische Reitertaktik unmoeglich.' },
    { id: 'q-mbt-f-15-de', text: 'Welche drei Funktionen erfuellt die Hellebarde gegen Reiter?', type: 'multiple-choice', options: ['Ausschliesslich Gebet', 'Haken, Hieb, Stoss', 'Nur Wurfwaffe', 'Signalhorn'], correctAnswer: 1, explanation: 'Das System ist explizit gegen Panzerreiter gerichtet.' },
    { id: 'q-mbt-f-16-de', text: 'Welcher pragmatische Grund sprach gegen Rittergefangene?', type: 'multiple-choice', options: ['Paepstliches Verbot', 'Gefangenentransport bindet Kaempfer', 'Unkenntnis hoher Loesgelder', 'Ritter ergaben sich nie'], correctAnswer: 1, explanation: 'Jeder fuer Eskorte eingesetzte Mann fehlte in der Linie.' },
    { id: 'q-mbt-f-17-de', text: 'Welche Sollstaerke hatte ein Tuemen?', type: 'multiple-choice', options: ['1.000', '10.000', '50.000', '100'], correctAnswer: 1, explanation: 'Die Einheit entsprach nominell «tausend mal tausend».' },
    { id: 'q-mbt-f-18-de', text: 'Welchen Effekt hatte der mongolische Scheinrueckzug?', type: 'multiple-choice', options: ['Der Feind erholt sich immer', 'Verfolgung zerstoerte die Ordnung und eroeffnete Umzingelung', 'Mongolenpferde ermuedeten zuerst', 'Schuesse wurden eingestellt'], correctAnswer: 1, explanation: 'Das Nachsetzen lockerte den Verband fuer die Falle.' },
    { id: 'q-mbt-f-19-de', text: 'Welcher Schluesselzug Subedeis entschied die Schlacht bei Mohi?', type: 'multiple-choice', options: ['Massenangriff auf die Bruecke', 'Nachtuebergang und Schlag in den Ruecken', 'Verzicht auf die Schlacht', 'Seeblockade'], correctAnswer: 1, explanation: 'Umgehung und Einkesselung brachen die Verteidigung.' },
    { id: 'q-mbt-f-20-de', text: 'Welchen Zweck hatte die «goldene Bruecke»?', type: 'multiple-choice', options: ['Humanitaere Gruende', 'Flucht ausloesen und Formation aufloesen', 'Handel mit dem Feind', 'Wasserversorgung'], correctAnswer: 1, explanation: 'Fliehende sind leichter zu vernichten als eine geschlossene Linie.' },
    { id: 'q-mbt-f-21-de', text: 'Welche strategische Rolle spielte das normannische Burgennetz?', type: 'multiple-choice', options: ['Nur adlige Wohnstaette', 'Knoten zur Kontrolle der Region und Unterdrueckung von Aufstaenden', 'Getreidelager fuer Kloester', 'Schutz der Fischer'], correctAnswer: 1, explanation: 'Burgen verankerten herrschaftliche Kontrolle im Land.' },
    { id: 'q-mbt-f-22-de', text: 'Welche Rolle spielte der Riesen-Trebuchet bei Stirling?', type: 'multiple-choice', options: ['Er passte nicht ins Gelaende', 'Psychologischer Druck und Prestige der Maschine', 'Paepstliches Belagerungsverbot', 'Ersatz fuer Kavallerie'], correctAnswer: 1, explanation: 'Einschuechterung konnte die Belagerung vor dem ersten Schuss beenden.' },
    { id: 'q-mbt-f-23-de', text: 'Was ist das Besondere am Griechischen Feuer?', type: 'multiple-choice', options: ['Es brannte nur an Land', 'Eine Mischung, die sich nicht wie normales Feuer mit Wasser loeschen laesst', 'Nur kulinarischer Zweck', 'Kein maritimer Einsatz'], correctAnswer: 1, explanation: 'Das Brennen auf dem Wasser war sein Kern.' },
    { id: 'q-mbt-f-24-de', text: 'Wie entdeckte man feindliche Unterwuehlung?', type: 'multiple-choice', options: ['Nur am Geruch', 'Vibrationen auf Membran oder im Wasser', 'Gar nicht', 'Vogelflug'], correctAnswer: 1, explanation: 'Fruehe Form der seismischen Aufklaerung.' },
    { id: 'q-mbt-f-25-de', text: 'Was bildete typischerweise die Vorderkante der englischen Aufstellung?', type: 'multiple-choice', options: ['Nur berittene Ritter', 'Pfahlriegel gegen Kavallerie, Fluegelbogenschuetzen', 'Ein einziger grosser Keil', 'Nur Schleudern'], correctAnswer: 1, explanation: 'Pfaehle und Bogen sicherten Front und Flanken.' },
    { id: 'q-mbt-f-26-de', text: 'Wofuer stehen die osmanischen Janitscharen in der Militaergeschichte?', type: 'multiple-choice', options: ['Seeherrschaft', 'Erste grosse stehende Infanterie nach der Antike', 'Reiterschuetzen ohne Kasernierung', 'Verzicht auf Bewaffnung'], correctAnswer: 1, explanation: 'Staendiger Drill und normierte Ausruestung waren neu.' },
    { id: 'q-mbt-f-27-de', text: 'Was ist das Kernmerkmal des spanischen Terzio?', type: 'multiple-choice', options: ['Nur Reiterei', 'Integration von Pike und Feuerwaffe im selben Verband', 'Ausschliesslich Belagerungsgeraete', 'Verbindung von Flotte und Landheer'], correctAnswer: 1, explanation: 'Feuer und Spiesse stabilisierten gemeinsam die Linie.' },
    { id: 'q-mbt-f-28-de', text: 'Was versteht man unter einer Wagenburg?', type: 'multiple-choice', options: ['Segelschiff', 'Verschanztes Lager aus angeketteten Wagen', 'Ritterorden', 'Stadtmauer'], correctAnswer: 1, explanation: 'Mobile Festung der Hussiten.' },
    { id: 'q-mbt-f-29-de', text: 'Welches Fazit formuliert die Folie zu wiederkehrenden Taktiken?', type: 'multiple-choice', options: ['Alles geht unwiederbringlich verloren', 'Grundsaetze wiederholen sich, Technik entwickelt sich', 'Nur China kannte Taktik', 'Das Mittelalter verbannte Flanken'], correctAnswer: 1, explanation: 'Militaerische Grundsaetze sind zyklisch, Material nicht.' },
    { id: 'q-mbt-f-30-de', text: 'Was zerstoerte Pulver in diesem Kurs in erster Linie?', type: 'multiple-choice', options: ['Duellkodex', 'Die strategische Rolle langfristig haltbarer Burgen', 'Seekompass', 'Devshirme'], correctAnswer: 1, explanation: 'Schnelle Zerschlagung der Mauern wandelte die Strategie.' }
  ]
}
