import { QuizBlock, Slide } from '../types/session'

// Deutsch B2: Napoleon Bonaparte — dreißig Geschichten

export const napoleonAnecdotesSlidesDE: Slide[] = [
  { id: 'np1', title: "Größe als Staatsgeheimnis", content: "Napoleon maß etwa 168 cm — für seine Zeit nicht klein. Die Legende vom «kleinen Korporal» näherten englische Gillray-Karikaturen und eine Leibgarde ab 180 cm heran; daneben wirkte er winzig. Er selbst ignorierte das Thema demonstrativ — und befeuerte die Gerüchte.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/01-height-state-secret.jpg', title: "Größe als Staatsgeheimnis" }] },
  { id: 'np2', title: "«Ich mache mich selbst»", content: "Als Papst Pius VII. zur Krönung kam, nahm Napoleon die Krone und setzte sie sich selbst auf, danach krönte er Joséphine — der Papst schaute zu. Inszeniert: Macht wird nicht geschenkt, sie wird genommen.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/02-self-coronation.jpg', title: "«Ich mache mich selbst»" }] },
  { id: 'np3', title: "Die Mathematikprüfung", content: "In Brienne bestand der junge Napoleon eine Prüfung bei Laplace, löste eine Aufgabe auf ungewohnte Weise und erklärte sie. Laplace hörte zu, errötete und gab die Richtigkeit zu — der Vierzehnjährige brachte den Gelehrten in Verlegenheit.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/03-laplace-exam.jpg', title: "Die Mathematikprüfung" }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-nap-1-1-de', text: "Welche Körpergröße wird Napoleon in der Überlieferung oft genannt (Größenordnung)?", type: 'multiple-choice', options: ["etwa 190 cm","etwa 150 cm","Etwa 168 cm","etwa 175 cm"], correctAnswer: 2, explanation: "Für die Zeit normal; die Legende kam anders zustande." },
    { id: 'q-nap-1-2-de', text: "Was tat Napoleon bei der Krönung 1804 mit der Krone?", type: 'multiple-choice', options: ["Er setzte sie sich selbst auf","er ließ nur den Papst handeln","er verweigerte die Krone","er zerbrach sie"], correctAnswer: 0, explanation: "Macht wird genommen, nicht geschenkt." },
    { id: 'q-nap-1-3-de', text: "Mit wem verbindet die Anekdote die Mathematikprüfung in Brienne?", type: 'multiple-choice', options: ["mit Lagrange","mit Cauchy","mit Fourier","Mit Laplace"], correctAnswer: 3, explanation: "Der junge Napoleon und die Lösung." }
    ] },
  { id: 'np4', title: "«Unmöglich» — kein französisches Wort", content: "Als ein Marschall «unmöglich» meldete, erwiderte Napoleon: «Unmöglich steht im Wörterbuch der Toren.» Der ging und führte aus — bei anderen wiederholte sich der Satz mit anderem Ton.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/04-impossible-not-french.jpg', title: "«Unmöglich» — kein französisches Wort" }] },
  { id: 'np5', title: "Napoleon und der Spiegel", content: "Vor der Audienz erinnerte ein Berater an die Erwartung der Gesandten. Napoleon blickte in den Spiegel, richtete den Hut: «Genau das werden sie sehen.» Er trat ein — alle standen auf.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/05-mirror-audience.jpg', title: "Napoleon und der Spiegel" }] },
  { id: 'np6', title: "«Le petit caporal»", content: "Die Soldaten nannten ihn «le petit caporal» zärtlich. Er aß am Feuer, kannte Hunderte beim Namen, erinnerte sich an Taten. Ein Veteran: «Er nannte mich beim Namen — ich folgte ihm in die Hölle.»", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/06-petit-caporal.jpg', title: "«Le petit caporal»" }] },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-nap-2-1-de', text: "Welcher Ausspruch wird Napoleon zum «Unmöglichen» und zum Wörterbuch zugeschrieben?", type: 'multiple-choice', options: ["«Nichts ist unmöglich»","«Unmöglich steht im Wörterbuch der Toren»","«Befehl ist Befehl»","«Rückzug verboten»"], correctAnswer: 1, explanation: "Antwort an einen Marschall." },
    { id: 'q-nap-2-2-de', text: "Was sagte Napoleon vor der Audienz zum Spiegel (Pointe)?", type: 'multiple-choice', options: ["«Ich bin zu klein»","«Genau das werden sie sehen»","«Wir verschieben»","«Wechselt die Gesandten»"], correctAnswer: 1, explanation: "Charisma vor Körpermaß." },
    { id: 'q-nap-2-3-de', text: "Wie nannten Soldaten Napoleon liebevoll («kleiner Korporal»)?", type: 'multiple-choice', options: ["le grand empereur","le petit général","le caporal noir","le petit caporal"], correctAnswer: 3, explanation: "Nähe zu den Mannschaften." }
    ] },
  { id: 'np7', title: "Namen auswendig", content: "Vor der Parade paukte er Listen. Auf der Revue trat er an: «Dupont — Austerlitz, 2. Zug …» Der Mann erstarrte. Geheimnis: Gedächtnis und Vorbereitung — Wirkung: Zauber.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/07-names-parade.jpg', title: "Namen auswendig" }] },
  { id: 'np8', title: "Die Wache und das Parole", content: "Nachts erkannte die Wache ihn nicht und forderte die Parole — ohne sie kein Durchlass. Am Morgen Lob und Beförderung: «So versteht man Dienst.»", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/08-sentry-password.jpg', title: "Die Wache und das Parole" }] },
  { id: 'np9', title: "Marschallstab im Tornister", content: "«In jedem Tornister steckt ein Marschallstab» — keine Floskel: Viele Marschälle stiegen vom Mannschaften auf — Murat, Ney, Lefebvre aus einfachen Verhältnissen.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/09-marshal-baton-sack.jpg', title: "Marschallstab im Tornister" }] },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-nap-3-1-de', text: "Womit beeindruckte Napoleon den Soldaten bei der «Dupont»-Szene?", type: 'multiple-choice', options: ["Er kannte Namen und Schlachtdetails","er verlieh ohne Grund einen Orden","er entließ ihn","er erkannte das Regiment nicht"], correctAnswer: 0, explanation: "Gedächtnis und Vorbereitung." },
    { id: 'q-nap-3-2-de', text: "Was geschah mit dem Wächter ohne Parole?", type: 'multiple-choice', options: ["Arrest","Erschießung","Lob und Beförderung","Versetzung"], correctAnswer: 2, explanation: "Dienst hat Vorrang vor dem Gesicht." },
    { id: 'q-nap-3-3-de', text: "Wo lag nach Napoleon-Metapher der Marschallstab beim Gemeinen?", type: 'multiple-choice', options: ["Im Tornister","in der Tasche","in der Kaserne","im Stab"], correctAnswer: 0, explanation: "Aufstieg aus der Reihe möglich." }
    ] },
  { id: 'np10', title: "«Ich werde dich mir merken»", content: "Ein Soldat erwartete Strafe. Napoleon schwieg, dann: «Ich werde dich mir merken.» Das war schlimmer als Strafe — jahrelang makelloser Dienst in Erwartung des Schlimmen.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/10-remember-you.jpg', title: "«Ich werde dich mir merken»" }] },
  { id: 'np11', title: "«Beim Frühstück entscheide ich»", content: "Ein Gesandter brachte ein dickes Memorandum. Napoleon blätterte kurz: «Ich entscheide beim Frühstück — in einer Stunde.» Anderswo hätte es Monate gedauert.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/11-breakfast-decision.jpg', title: "«Beim Frühstück entscheide ich»" }] },
  { id: 'np12', title: "Antwort an den Kritiker", content: "Ein Pamphletist griff an. Napoleon: «Lasst ihn. Wen Feinde hassen, tut etwas Richtiges.» Der Autor wartete vergeblich auf den Knall.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/12-pamphlet-critic.jpg', title: "Antwort an den Kritiker" }] },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-nap-4-1-de', text: "Was sagte Napoleon zum Soldaten statt harter Strafe?", type: 'multiple-choice', options: ["«Erschießen morgen»","«Verziehen»","«Ich werde dich mir merken»","«Entlassen»"], correctAnswer: 2, explanation: "Psychologischer Druck." },
    { id: 'q-nap-4-2-de', text: "Wie reagierte Napoleon auf das dicke Memorandum des Gesandten?", type: 'multiple-choice', options: ["las nicht","Löst es beim Frühstück / sehr schnell","gab es Talleyrand ungelesen","ritt ins Feld"], correctAnswer: 1, explanation: "Schnelle Entscheidung." },
    { id: 'q-nap-4-3-de', text: "Wie deutete Napoleon den gehässigen Pamphletisten?", type: 'multiple-choice', options: ["Autor ins Gefängnis","zum Duell","Auflage verbrennen","Feinde hassen — man tut etwas Richtiges"], correctAnswer: 3, explanation: "Gelassenheit als Stärke." }
    ] },
  { id: 'np13', title: "«Nur das fürchte ich»", content: "Auf die Frage nach dem Tod: Er fürchte nicht den Tod — nur Langeweile. Auf St. Helena wurde sie zur Qual, das wusste er.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/13-fear-boredom.jpg', title: "«Nur das fürchte ich»" }] },
  { id: 'np14', title: "Talleyrand und die Seidenstrümpfe", content: "Nach neuem Verrat beschimpfte Napoleon Talleyrand öffentlich als «seidenen Strumpf voll Mist». Talleyrand im Gang: «Schade, dass so ein großer Mann so schlecht erzogen ist.»", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/14-talleyrand-silk.jpg', title: "Talleyrand und die Seidenstrümpfe" }] },
  { id: 'np15', title: "«Ich bin nicht «glücklich»»", content: "Bei Lob fürs Glück runzelte er die Stirn: Glück sei, wenn man bereit ist und der Moment kommt. «Ich bin immer bereit — deshalb immer «glücklich».»", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/15-luck-ready.jpg', title: "«Ich bin nicht «glücklich»»" }] },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-nap-5-1-de', text: "Wovor hatte Napoleon «Angst» statt vor dem Tod (Anekdote)?", type: 'multiple-choice', options: ["vor Kugeln","vor dem Meer","vor Krankheit","Vor Langeweile"], correctAnswer: 3, explanation: "St. Helena als Langeweile." },
    { id: 'q-nap-5-2-de', text: "Wen nannte Napoleon «seidene Strümpfe voll Mist»?", type: 'multiple-choice', options: ["Fouché","Talleyrand","Metternich","Kutusow"], correctAnswer: 1, explanation: "Berühmte Beschimpfung." },
    { id: 'q-nap-5-3-de', text: "Wie definierte Napoleon «Glück»?", type: 'multiple-choice', options: ["Religion","Größe","Vorbereitung, wenn der Moment kommt","Geld"], correctAnswer: 2, explanation: "Immer bereit — immer «Glück»." }
    ] },
  { id: 'np16', title: "Eifersucht aus Ägypten", content: "In Ägypten, nach Neuigkeiten über Joséphine, schrieb er an Joseph: «Joséphine … — egal.» Ein Satz, der mehr sagt als ein Band. Zurück folgte eine Affäre — symmetrisch.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/16-egypt-jealousy.jpg', title: "Eifersucht aus Ägypten" }] },
  { id: 'np17', title: "«Sie sitzen zu lange»", content: "Auf einem Ball sprach eine Dame zu lange. Napoleon: «Sie sitzen sehr schön — aber schon sehr lange.» Sie stand — die Audienz war zu Ende.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/17-ball-too-long.jpg', title: "«Sie sitzen zu lange»" }] },
  { id: 'np18', title: "Scheidung als Staatsakt", content: "Die Scheidung von Joséphine für Marie-Louise war nach Zeugen in Tränen — von beiden. Die Hochzeit mit der Österreicherin folgte ohne solche Tränen.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/18-divorce-josephine.jpg', title: "Scheidung als Staatsakt" }] },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-nap-6-1-de', text: "Wie beginnt der berühmte Satz im Brief über Joséphine aus Ägypten?", type: 'multiple-choice', options: ["«Joséphine… — egal» (unvollendet)","«Joséphine hat recht»","«Ich komme bald»","«Keine Scheidung»"], correctAnswer: 0, explanation: "Stillschweigende Anspielung." },
    { id: 'q-nap-6-2-de', text: "Wie wies Napoleon die Dame am Ball zum Gehen hin?", type: 'multiple-choice', options: ["«Gehen Sie»","«Ich bin müde»","«Sie sitzen schön, aber zu lange»","«Sie werden gerufen»"], correctAnswer: 2, explanation: "Höfliches Ende der Audienz." },
    { id: 'q-nap-6-3-de', text: "Von wem ließ sich Napoleon für eine politische Heirat scheiden?", type: 'multiple-choice', options: ["von Marie-Louise","Von Joséphine","von Maria Walewska","von Désirée Clary"], correctAnswer: 1, explanation: "Tränen bei der Scheidung." }
    ] },
  { id: 'np19', title: "«Die Revolution ist vorbei»", content: "An der Macht sagte er: «Die Revolution ist vorbei.» Auf «Und dann?» — «Ordnung.» Zwei Wörter als Programm für Jahre.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/19-revolution-over.jpg', title: "«Die Revolution ist vorbei»" }] },
  { id: 'np20', title: "Das Gesetzbuch", content: "Tausende Artikel des Zivilgesetzbuchs studierte er persönlich, stritt über Formulierungen. «Warum dem Kaiser Details?» — «Ich baue für Jahrhunderte — das Fundament muss stimmen.»", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/20-civil-code.jpg', title: "Das Gesetzbuch" }] },
  { id: 'np21', title: "Erster Diener des Staates", content: "Anders als Ludwig XIV. sagte Napoleon sachlich: «Erster Diener des Staates.» Der Ton weicht ab — das Ergebnis oft ähnlich.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/21-first-servant-state.jpg', title: "Erster Diener des Staates" }] },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-nap-7-1-de', text: "Was erklärte Napoleon zur Revolution an der Macht?", type: 'multiple-choice', options: ["«Die Revolution ist vorbei»","«Die Revolution ist ewig»","«Sie beginnt erst»","«Sie war ein Fehler»"], correctAnswer: 0, explanation: "Dann Ordnung." },
    { id: 'q-nap-7-2-de', text: "Warum mischte Napoleon sich in den Zivilcode ein?", type: 'multiple-choice', options: ["Juristen allein","Code unwichtig","nur Dekrete","Er baut für Jahrhunderte — Fundament muss stimmen"], correctAnswer: 3, explanation: "Code Napoléon." },
    { id: 'q-nap-7-3-de', text: "Wie nannte Napoleon seine Rolle zum Staat (Gegenstück zu «L’État, c’est moi»)?", type: 'multiple-choice', options: ["«Einziger Herr»","«Erster Diener des Staates»","«Über dem Staat»","«Außerhalb des Gesetzes»"], correctAnswer: 1, explanation: "Dienst-Rhetorik." }
    ] },
  { id: 'np22', title: "Zensur mit Humor", content: "Nach Hinweis auf ein anti-bonapartistisches Stück ging er selbst, lachte am lautesten, schüttelte dem Autor die Hand: «Gut geschrieben — morgen macht das Theater zu.»", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/22-censorship-theater.jpg', title: "Zensur mit Humor" }] },
  { id: 'np23', title: "Moskau in Flammen", content: "In der leeren, brennenden Moskau schwieg er: «Das kündigt großes Unheil an.» Sonst keine bösen Omen — dann weiter.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/23-moscow-fire.jpg', title: "Moskau in Flammen" }] },
  { id: 'np24', title: "Waterloo — fünfzehn Minuten", content: "Auf St. Helena analysierte er Waterloo: fünfzehn Minuten Grouchys Verspätung. «Fünfzehn Minuten ändern Europas Geschichte» — oft ändern eben fünfzehn Minuten Geschichte.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/24-waterloo-fifteen.jpg', title: "Waterloo — fünfzehn Minuten" }] },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-nap-8-1-de', text: "Was tat Napoleon nach der «antibonapartistischen» Vorstellung?", type: 'multiple-choice', options: ["Lob für den Autor — Theater morgen zu","Subvention","ewiger Zensor","nichts"], correctAnswer: 0, explanation: "Humor und Zensur." },
    { id: 'q-nap-8-2-de', text: "Was geschah mit Moskau bei Napoleons Einzug (Erzählung)?", type: 'multiple-choice', options: ["kapitulierte leer","große Parade","Brunnen vergiftet","Stadt wurde angezündet / brannte"], correctAnswer: 3, explanation: "Leere Stadt, Feuer." },
    { id: 'q-nap-8-3-de', text: "Wie viele Minuten Verspätung Grouchys verband Napoleon mit Waterloo?", type: 'multiple-choice', options: ["dreißig","fünf","Fünfzehn","sechzig"], correctAnswer: 2, explanation: "«Fünfzehn Minuten Geschichte»." }
    ] },
  { id: 'np25', title: "Schach mit Lowe", content: "Gegen Gefängnisdirektor Lowe verlor er oft absichtlich im Schach, meinten Zeugen: «Er ist der Wärter — soll wenigstens dort siegen.»", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/25-chess-lowe.jpg', title: "Schach mit Lowe" }] },
  { id: 'np26', title: "«Ich schuf die Legende»", content: "Zu Las Cases diktierte er Memoiren. «Geschichte oder Propaganda?» — «Gibt es da einen Unterschied?» — völlig ernst.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/26-memoirs-propaganda.jpg', title: "«Ich schuf die Legende»" }] },
  { id: 'np27', title: "Das Bad als Kabinett", content: "Stundenlang heiß badend hielt er Rat: Minister standen am Rand und berichteten. Mit der Zeit fand das niemand mehr seltsam.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/27-bath-cabinet.jpg', title: "Das Bad als Kabinett" }] },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-nap-9-1-de', text: "Warum soll Napoleon gegen Lowe im Schach absichtlich verloren haben?", type: 'multiple-choice', options: ["er konnte nicht spielen","um Geld","aus Müdigkeit","Damit der Gefängniswärter Sieger fühlt"], correctAnswer: 3, explanation: "Psychologie des Aufsehers." },
    { id: 'q-nap-9-2-de', text: "Antwort Napoleons auf «Geschichte oder Propaganda» in den Memoiren?", type: 'multiple-choice', options: ["«Nur Geschichte»","«Nur Propaganda»","«Gibt es da einen Unterschied?»","«Entwurf verbrennen»"], correctAnswer: 2, explanation: "Las Cases als Gesprächspartner." },
    { id: 'q-nap-9-3-de', text: "Wo fand laut Anekdote lange Beratung statt?", type: 'multiple-choice', options: ["in der Kutsche","Im heißen Bad","in der Kirche","auf dem Schiff"], correctAnswer: 1, explanation: "Bad als Arbeitszimmer." }
    ] },
  { id: 'np28', title: "Schnelles Lesen", content: "Er las einen Roman in einer Stunde und kaum zweimal. «Wie merken Sie Details?» — «Ich lese keine Wörter — ich lese Gedanken.»", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/28-speed-reading.jpg', title: "Schnelles Lesen" }] },
  { id: 'np29', title: "Schnupftabak auf dem Rock", content: "Schnupftabak auf den weißen Rock — Kammerdiener Constant putzte täglich. «Er bemerkte es kaum — der Kopf war woanders.»", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/29-snuff-uniform.jpg', title: "Schnupftabak auf dem Rock" }] },
  { id: 'np30', title: "Letzte Worte", content: "Letzte Worte gelten «Frankreich … Armee … Joséphine». Der Arzt deutete Prioritäten — oder Delirium. Beides passt zu Napoleon.", duration: 3, media: [{ type: 'image', url: '/media/napoleon-anecdotes/30-last-words.jpg', title: "Letzte Worte" }] },
  { id: 'q10', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-nap-10-1-de', text: "Was las Napoleon lieber: Wörter oder Gedanken?", type: 'multiple-choice', options: ["Gedanken","nur Wörter","nur Zahlen","nur Karten"], correctAnswer: 0, explanation: "Schnelles Lesen im Sinn." },
    { id: 'q-nap-10-2-de', text: "Was streute Napoleon oft auf den weißen Rock?", type: 'multiple-choice', options: ["Schnupftabak","Zucker","Mehl","Sand"], correctAnswer: 0, explanation: "Constant und die Reinigung." },
    { id: 'q-nap-10-3-de', text: "Welche drei Wörter gelten als letzte (eine Version)?", type: 'multiple-choice', options: ["Europa… Ruhm… Frieden","Mutter… Vater… Sohn","Arzt… Wasser… Licht","Frankreich… Armee… Joséphine"], correctAnswer: 3, explanation: "Augenzeugenberichte." }
    ] },
]

export const napoleonAnecdotesFinalQuizDE: QuizBlock = {
  id: 'quiz-napoleon-anecdotes-de',
  title: 'Abschlussquiz: Napoleon — dreißig Geschichten',
  questions: [
  { id: 'q-nap-1-1-de', text: "Welche Körpergröße wird Napoleon in der Überlieferung oft genannt (Größenordnung)?", type: 'multiple-choice', options: ["etwa 190 cm","etwa 150 cm","Etwa 168 cm","etwa 175 cm"], correctAnswer: 2, explanation: "Für die Zeit normal; die Legende kam anders zustande." },
  { id: 'q-nap-2-1-de', text: "Welcher Ausspruch wird Napoleon zum «Unmöglichen» und zum Wörterbuch zugeschrieben?", type: 'multiple-choice', options: ["«Nichts ist unmöglich»","«Unmöglich steht im Wörterbuch der Toren»","«Befehl ist Befehl»","«Rückzug verboten»"], correctAnswer: 1, explanation: "Antwort an einen Marschall." },
  { id: 'q-nap-3-1-de', text: "Womit beeindruckte Napoleon den Soldaten bei der «Dupont»-Szene?", type: 'multiple-choice', options: ["Er kannte Namen und Schlachtdetails","er verlieh ohne Grund einen Orden","er entließ ihn","er erkannte das Regiment nicht"], correctAnswer: 0, explanation: "Gedächtnis und Vorbereitung." },
  { id: 'q-nap-4-1-de', text: "Was sagte Napoleon zum Soldaten statt harter Strafe?", type: 'multiple-choice', options: ["«Erschießen morgen»","«Verziehen»","«Ich werde dich mir merken»","«Entlassen»"], correctAnswer: 2, explanation: "Psychologischer Druck." },
  { id: 'q-nap-5-1-de', text: "Wovor hatte Napoleon «Angst» statt vor dem Tod (Anekdote)?", type: 'multiple-choice', options: ["vor Kugeln","vor dem Meer","vor Krankheit","Vor Langeweile"], correctAnswer: 3, explanation: "St. Helena als Langeweile." },
  { id: 'q-nap-6-1-de', text: "Wie beginnt der berühmte Satz im Brief über Joséphine aus Ägypten?", type: 'multiple-choice', options: ["«Joséphine… — egal» (unvollendet)","«Joséphine hat recht»","«Ich komme bald»","«Keine Scheidung»"], correctAnswer: 0, explanation: "Stillschweigende Anspielung." },
  { id: 'q-nap-7-1-de', text: "Was erklärte Napoleon zur Revolution an der Macht?", type: 'multiple-choice', options: ["«Die Revolution ist vorbei»","«Die Revolution ist ewig»","«Sie beginnt erst»","«Sie war ein Fehler»"], correctAnswer: 0, explanation: "Dann Ordnung." },
  { id: 'q-nap-8-1-de', text: "Was tat Napoleon nach der «antibonapartistischen» Vorstellung?", type: 'multiple-choice', options: ["Lob für den Autor — Theater morgen zu","Subvention","ewiger Zensor","nichts"], correctAnswer: 0, explanation: "Humor und Zensur." },
  { id: 'q-nap-9-1-de', text: "Warum soll Napoleon gegen Lowe im Schach absichtlich verloren haben?", type: 'multiple-choice', options: ["er konnte nicht spielen","um Geld","aus Müdigkeit","Damit der Gefängniswärter Sieger fühlt"], correctAnswer: 3, explanation: "Psychologie des Aufsehers." },
  { id: 'q-nap-10-1-de', text: "Was las Napoleon lieber: Wörter oder Gedanken?", type: 'multiple-choice', options: ["Gedanken","nur Wörter","nur Zahlen","nur Karten"], correctAnswer: 0, explanation: "Schnelles Lesen im Sinn." },
  { id: 'q-nap-1-2-de', text: "Was tat Napoleon bei der Krönung 1804 mit der Krone?", type: 'multiple-choice', options: ["Er setzte sie sich selbst auf","er ließ nur den Papst handeln","er verweigerte die Krone","er zerbrach sie"], correctAnswer: 0, explanation: "Macht wird genommen, nicht geschenkt." },
  { id: 'q-nap-2-2-de', text: "Was sagte Napoleon vor der Audienz zum Spiegel (Pointe)?", type: 'multiple-choice', options: ["«Ich bin zu klein»","«Genau das werden sie sehen»","«Wir verschieben»","«Wechselt die Gesandten»"], correctAnswer: 1, explanation: "Charisma vor Körpermaß." },
  { id: 'q-nap-3-2-de', text: "Was geschah mit dem Wächter ohne Parole?", type: 'multiple-choice', options: ["Arrest","Erschießung","Lob und Beförderung","Versetzung"], correctAnswer: 2, explanation: "Dienst hat Vorrang vor dem Gesicht." },
  { id: 'q-nap-4-2-de', text: "Wie reagierte Napoleon auf das dicke Memorandum des Gesandten?", type: 'multiple-choice', options: ["las nicht","Löst es beim Frühstück / sehr schnell","gab es Talleyrand ungelesen","ritt ins Feld"], correctAnswer: 1, explanation: "Schnelle Entscheidung." },
  { id: 'q-nap-5-2-de', text: "Wen nannte Napoleon «seidene Strümpfe voll Mist»?", type: 'multiple-choice', options: ["Fouché","Talleyrand","Metternich","Kutusow"], correctAnswer: 1, explanation: "Berühmte Beschimpfung." },
  { id: 'q-nap-6-2-de', text: "Wie wies Napoleon die Dame am Ball zum Gehen hin?", type: 'multiple-choice', options: ["«Gehen Sie»","«Ich bin müde»","«Sie sitzen schön, aber zu lange»","«Sie werden gerufen»"], correctAnswer: 2, explanation: "Höfliches Ende der Audienz." },
  { id: 'q-nap-7-2-de', text: "Warum mischte Napoleon sich in den Zivilcode ein?", type: 'multiple-choice', options: ["Juristen allein","Code unwichtig","nur Dekrete","Er baut für Jahrhunderte — Fundament muss stimmen"], correctAnswer: 3, explanation: "Code Napoléon." },
  { id: 'q-nap-8-2-de', text: "Was geschah mit Moskau bei Napoleons Einzug (Erzählung)?", type: 'multiple-choice', options: ["kapitulierte leer","große Parade","Brunnen vergiftet","Stadt wurde angezündet / brannte"], correctAnswer: 3, explanation: "Leere Stadt, Feuer." },
  { id: 'q-nap-9-2-de', text: "Antwort Napoleons auf «Geschichte oder Propaganda» in den Memoiren?", type: 'multiple-choice', options: ["«Nur Geschichte»","«Nur Propaganda»","«Gibt es da einen Unterschied?»","«Entwurf verbrennen»"], correctAnswer: 2, explanation: "Las Cases als Gesprächspartner." },
  { id: 'q-nap-10-2-de', text: "Was streute Napoleon oft auf den weißen Rock?", type: 'multiple-choice', options: ["Schnupftabak","Zucker","Mehl","Sand"], correctAnswer: 0, explanation: "Constant und die Reinigung." },
  { id: 'q-nap-1-3-de', text: "Mit wem verbindet die Anekdote die Mathematikprüfung in Brienne?", type: 'multiple-choice', options: ["mit Lagrange","mit Cauchy","mit Fourier","Mit Laplace"], correctAnswer: 3, explanation: "Der junge Napoleon und die Lösung." },
  { id: 'q-nap-2-3-de', text: "Wie nannten Soldaten Napoleon liebevoll («kleiner Korporal»)?", type: 'multiple-choice', options: ["le grand empereur","le petit général","le caporal noir","le petit caporal"], correctAnswer: 3, explanation: "Nähe zu den Mannschaften." },
  { id: 'q-nap-3-3-de', text: "Wo lag nach Napoleon-Metapher der Marschallstab beim Gemeinen?", type: 'multiple-choice', options: ["Im Tornister","in der Tasche","in der Kaserne","im Stab"], correctAnswer: 0, explanation: "Aufstieg aus der Reihe möglich." },
  { id: 'q-nap-4-3-de', text: "Wie deutete Napoleon den gehässigen Pamphletisten?", type: 'multiple-choice', options: ["Autor ins Gefängnis","zum Duell","Auflage verbrennen","Feinde hassen — man tut etwas Richtiges"], correctAnswer: 3, explanation: "Gelassenheit als Stärke." },
  { id: 'q-nap-5-3-de', text: "Wie definierte Napoleon «Glück»?", type: 'multiple-choice', options: ["Religion","Größe","Vorbereitung, wenn der Moment kommt","Geld"], correctAnswer: 2, explanation: "Immer bereit — immer «Glück»." },
  { id: 'q-nap-6-3-de', text: "Von wem ließ sich Napoleon für eine politische Heirat scheiden?", type: 'multiple-choice', options: ["von Marie-Louise","Von Joséphine","von Maria Walewska","von Désirée Clary"], correctAnswer: 1, explanation: "Tränen bei der Scheidung." },
  { id: 'q-nap-7-3-de', text: "Wie nannte Napoleon seine Rolle zum Staat (Gegenstück zu «L’État, c’est moi»)?", type: 'multiple-choice', options: ["«Einziger Herr»","«Erster Diener des Staates»","«Über dem Staat»","«Außerhalb des Gesetzes»"], correctAnswer: 1, explanation: "Dienst-Rhetorik." },
  { id: 'q-nap-8-3-de', text: "Wie viele Minuten Verspätung Grouchys verband Napoleon mit Waterloo?", type: 'multiple-choice', options: ["dreißig","fünf","Fünfzehn","sechzig"], correctAnswer: 2, explanation: "«Fünfzehn Minuten Geschichte»." },
  { id: 'q-nap-9-3-de', text: "Wo fand laut Anekdote lange Beratung statt?", type: 'multiple-choice', options: ["in der Kutsche","Im heißen Bad","in der Kirche","auf dem Schiff"], correctAnswer: 1, explanation: "Bad als Arbeitszimmer." },
  { id: 'q-nap-10-3-de', text: "Welche drei Wörter gelten als letzte (eine Version)?", type: 'multiple-choice', options: ["Europa… Ruhm… Frieden","Mutter… Vater… Sohn","Arzt… Wasser… Licht","Frankreich… Armee… Joséphine"], correctAnswer: 3, explanation: "Augenzeugenberichte." }
  ]
}

