import { Slide, QuizBlock } from '../types/session'

// Deutsche Übersetzungen: Philosophie als Geschäft — Schulen Athens
export const philosophyAthensSlidesDE: Slide[] = [
  { id: 'p1', title: 'Philosophische Schulen Athens', content: 'Im 5.–4. Jh. v. Chr. wurde Athen zum Zentrum der Philosophie. Platons Akademie, Aristoteles\' Lykeion, die Stoa der Stoiker und der Garten der Epikureer — jede Schule bot ihren Weg zur Wahrheit und Weisheit.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/athens-schools.jpg', title: 'Schulen Athens' }] },
  { id: 'p2', title: 'Sokrates: lehrte kostenlos', content: 'Sokrates nahm kein Geld und führte Gespräche auf Straßen und Plätzen. Er meinte, Weisheit lasse sich nicht verkaufen. Dafür respektierten ihn die einen, kritisierten die anderen — die Sophisten sahen in ihm einen Konkurrenten, der «umsonst» arbeitete.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/socrates.jpg', title: 'Sokrates' }] },
  { id: 'p3', title: 'Sophisten: erste bezahlte Lehrer', content: 'Sophisten — Protagoras, Gorgias und andere — nahmen Geld für Rhetorik und die Kunst der Debatte. Sie sagten offen: Wissen hat seinen Preis. Für die Athener war das neu und umstritten.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/sophists.jpg', title: 'Sophisten' }] },
  { id: 'p4', title: 'Platon und die Akademie', content: 'Platon gründete die Akademie in einem Hain außerhalb der Stadtmauern. Die Schule lebte von Spenden und vielleicht bescheidenen Beiträgen. Platon machte aus Philosophie kein Geschäft, aber eine Schule ohne Mittel zu unterhalten war unmöglich.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/academy.jpg', title: 'Akademie' }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-phil-1-1', text: 'Nahm Sokrates Geld für den Unterricht?', type: 'multiple-choice', options: ['Ja, hohe Summen', 'Nein, er lehrte kostenlos', 'Nur von Reichen', 'Nur Geschenke'], correctAnswer: 1, explanation: 'Sokrates nahm kein Geld und führte Gespräche auf den Plätzen.' },
    { id: 'q-phil-1-2', text: 'Wer nahm zuerst offen Geld für den Unterricht?', type: 'multiple-choice', options: ['Sokrates', 'Platon', 'Sophisten', 'Aristoteles'], correctAnswer: 2, explanation: 'Sophisten — Protagoras, Gorgias — nahmen Honorar für Rhetorik.' },
    { id: 'q-phil-1-3', text: 'Wo lag Platons Schule?', type: 'multiple-choice', options: ['Auf der Agora', 'Im Hain außerhalb der Mauern — Akademie', 'Im Piräus', 'Auf der Akropolis'], correctAnswer: 1, explanation: 'Die Akademie lag in einem Hain außerhalb der Stadtmauern.' }
  ]},
  { id: 'p5', title: 'Aristoteles und das Lykeion', content: 'Aristoteles gründete das Lykeion beim Tempel des Apollon Lykeios. Die Schüler gingen mit dem Lehrer spazieren und diskutierten — man nannte sie «Peripatetiker», «Spaziergänger». Die Schule lebte von Mäzenen und wohl Beiträgen der Schüler.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/lyceum.jpg', title: 'Lykeion' }] },
  { id: 'p6', title: 'Stoiker und Epikureer', content: 'Stoiker lehrten in der Bemalten Stoa auf der Agora, Epikureer im Garten Epikurs. Beide Schulen zogen Anhänger auf unterschiedliche Weise an: Stoiker durch öffentliche Vorträge, Epikureer durch zurückgezogene Gespräche. Auch die Finanzierung unterschied sich.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/stoa.jpg', title: 'Stoa' }] },
  { id: 'p7', title: 'Konkurrenz der Schulen', content: 'Die Schulen konkurrierten um Schüler und Einfluss. Der Erfolg hing vom Ruf des Lehrers, der Klarheit der Lehre und — in gewissem Maße — davon ab, wie zugänglich die Schule war. Reiche Schüler brachten Geschenke und Unterstützung.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/competition.jpg', title: 'Konkurrenz' }] },
  { id: 'p8', title: 'Humor: Diogenes und das Honorar', content: 'Diogenes von Sinope, Kyniker, lebte in einer Tonne und verachtete Reichtum. Als man ihn fragte, warum Philosophen Geld von Schülern nehmen und er nicht, antwortete er: «Weil sie glauben, ihre Lehre sei etwas wert. Ich nicht.» Ironie über die, die Weisheit verkauften.', duration: 3 },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-phil-2-1', text: 'Warum nannte man Aristoteles\' Schüler Peripatetiker?', type: 'multiple-choice', options: ['Sie lebten in Höhlen', 'Sie gingen mit dem Lehrer spazieren', 'Sie trugen besondere Kleidung', 'Sie kamen aus Pera'], correctAnswer: 1, explanation: '«Peripatetiker» — «Spaziergänger», sie diskutierten beim Gehen.' },
    { id: 'q-phil-2-2', text: 'Wo lehrten die Stoiker?', type: 'multiple-choice', options: ['Im Garten', 'In der Bemalten Stoa auf der Agora', 'In der Akademie', 'Im Lykeion'], correctAnswer: 1, explanation: 'Stoiker — in der Stoa Poikile.' },
    { id: 'q-phil-2-3', text: 'Wer lebte in einer Tonne?', type: 'multiple-choice', options: ['Sokrates', 'Platon', 'Diogenes', 'Epikur'], correctAnswer: 2, explanation: 'Diogenes von Sinope — Kyniker.' }
  ]},
  { id: 'p9', title: 'Honorare für den Unterricht', content: 'Genaue Preislisten sind nicht überliefert. Sophisten nahmen hohe Summen — Protagoras soll verlangt haben, was ein Handwerker in Jahren verdiente. In Akademie und Lykeion gab es wohl Beiträge oder großzügige Gaben wohlhabender Schüler.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/fees.jpg', title: 'Honorare' }] },
  { id: 'p10', title: 'Wer konnte studieren', content: 'Vollständige philosophische Bildung war vor allem Wohlhabenden zugänglich. Arme konnten öffentliche Reden auf der Agora hören. Einige Philosophen — wie Sokrates oder die Kyniker — lehrten alle, ohne Geld zu verlangen.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/students.jpg', title: 'Schüler' }] },
  { id: 'p11', title: 'Sophisten und Honorare', content: 'Protagoras schloss einen Vertrag: die Hälfte vor dem ersten gewonnenen Prozess des Schülers, die Hälfte danach. Als der junge Euathlos den ersten Prozess hinauszögerte, drohte Protagoras mit Klage. Euathlos erwiderte: «Gewinne ich, zahle ich nicht laut Urteil; verliere ich, zahle ich nicht laut Vertrag.» Das Paradoxon ging in die Geschichte ein.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/protagoras.jpg', title: 'Protagoras' }] },
  { id: 'p12', title: 'Humor: Gorgias und das lange Leben', content: 'Gorgias wurde fast 110 Jahre alt. Auf die Frage nach dem Geheimnis eines langen Lebens antwortete er: «Ich habe nie etwas für Geld getan.» Ironie: Er nahm gerade hohe Honorare für den Unterricht. Vielleicht meinte er — nichts gegen die Seele.', duration: 3 },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-phil-3-1', text: 'Wie teilte Protagoras die Zahlung mit Euathlos?', type: 'multiple-choice', options: ['Alles sofort', 'Hälfte vor dem ersten gewonnenen Prozess, Hälfte danach', 'Nur nach dem Prozess', 'Nach Belieben'], correctAnswer: 1, explanation: 'Hälfte vor, Hälfte nach dem ersten gewonnenen Fall.' },
    { id: 'q-phil-3-2', text: 'Wer konnte sich philosophische Bildung leisten?', type: 'multiple-choice', options: ['Nur Sklaven', 'Vor allem Wohlhabende', 'Alle kostenlos', 'Nur Athener'], correctAnswer: 1, explanation: 'Vollständige Bildung war vor allem Reichen zugänglich.' },
    { id: 'q-phil-3-3', text: 'Wie alt wurde Gorgias der Überlieferung nach?', type: 'multiple-choice', options: ['Etwa 70', 'Etwa 90', 'Fast 110', 'Etwa 60'], correctAnswer: 2, explanation: 'Gorgias wurde fast 110 Jahre alt.' }
  ]},
  { id: 'p13', title: 'Philosophie und Politik', content: 'Philosophen bildeten Politiker und Redner aus. Alkibiades, Kritias und andere lernten bei Sokrates. Platon träumte vom Philosophen-Herrscher. Die Verbindung der Schulen mit der Elite brachte Einfluss, machte Philosophen aber in unruhigen Zeiten auch zum Ziel.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/politics.jpg', title: 'Philosophie und Politik' }] },
  { id: 'p14', title: 'Verbannungen von Philosophen', content: 'Anaxagoras wurde wegen «Gottlosigkeit» verbannt, Aristoteles floh aus Athen und sagte, er werde den Athenern nicht «ein zweites Mal gegen die Philosophie sündigen» lassen (nach Sokrates\' Hinrichtung). Die Schulen hingen vom politischen Klima ab.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/exile.jpg', title: 'Verbannung' }] },
  { id: 'p15', title: 'Philosophen an Höfen', content: 'Platon reiste zu Tyrann Dionysios nach Syrakus, Aristoteles erzog Alexander den Großen. An Höfen zahlte man gut — aber das Risiko war hoch. Platon entging in Syrakus knapp dem Tod.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/court.jpg', title: 'Am Hof' }] },
  { id: 'p16', title: 'Humor: Diogenes und Alexander', content: 'Alexander der Große kam zu Diogenes und fragte, was er wünsche. Diogenes antwortete: «Geh zur Seite, du verdeckst die Sonne.» Alexander sagte: «Wäre ich nicht Alexander, wollte ich Diogenes sein.» Zwei verschiedene Auffassungen von Glück — Macht und Unabhängigkeit.', duration: 3 },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-phil-4-1', text: 'Wen erzog Aristoteles?', type: 'multiple-choice', options: ['Sokrates', 'Platon', 'Alexander den Großen', 'Cicero'], correctAnswer: 2, explanation: 'Aristoteles war Alexanders Lehrer.' },
    { id: 'q-phil-4-2', text: 'Wohin reiste Platon zum Tyrannen?', type: 'multiple-choice', options: ['Nach Rom', 'Nach Syrakus', 'Nach Sparta', 'Nach Persien'], correctAnswer: 1, explanation: 'Platon reiste zu Dionysios nach Syrakus.' },
    { id: 'q-phil-4-3', text: 'Was bat Diogenes Alexander?', type: 'multiple-choice', options: ['Um Geld', '«Geh zur Seite, du verdeckst die Sonne»', 'Um ein Amt', 'Um Hilfe'], correctAnswer: 1, explanation: 'Diogenes bat nur, von der Sonne wegzugehen.' }
  ]},
  { id: 'p17', title: 'Frauen in der Philosophie', content: 'Pythagoreerinnen — Frauen in der Schule des Pythagoras — nahmen an philosophischen Gesprächen teil. Hypatia lehrte im Alexandria des 4. Jh. den Neuplatonismus. In den klassischen Athener Schulen war Philosophie aber im Wesentlichen männlich.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/women.jpg', title: 'Philosophinnen' }] },
  { id: 'p18', title: 'Handschriften und Bibliotheken', content: 'Schulen sammelten Bücher. Aristoteles hinterließ eine Bibliothek, die später nach Rom gebracht wurde. Texte wurden abgeschrieben und weitergegeben — das war teuer. Wissen überdauerte dank Mäzenen und dem Eifer der Schüler.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/library.jpg', title: 'Bibliothek' }] },
  { id: 'p19', title: 'Ende der Akademie', content: '529 n. Chr. schloss Kaiser Justinian die heidnische Akademie in Athen. Die Philosophen zogen fort. Die Ära der antiken Schulen endete — ihr Erbe überlebte aber durch Handschriften und arabische Kommentatoren.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/justinian.jpg', title: 'Justinian' }] },
  { id: 'p20', title: 'Humor: Kyniker und Bad', content: 'Diogenes wurde gefragt, warum er nicht in die Badeanstalt gehe. Er antwortete: «Ich war gestern in der Badeanstalt.» — «Aber gestern ist lange her!» — «Dafür habe ich mich heute nicht schmutzig gemacht.» Kyniker lehnten Konventionen ab, auch hygienische — zum Entsetzen der Bürger.', duration: 3 },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-phil-5-1', text: 'Wer lehrte Philosophie in Alexandria im 4. Jh.?', type: 'multiple-choice', options: ['Platon', 'Hypatia', 'Aristoteles', 'Epikur'], correctAnswer: 1, explanation: 'Hypatia — Philosophin, Lehrerin des Neuplatonismus.' },
    { id: 'q-phil-5-2', text: 'Wer schloss die Akademie 529?', type: 'multiple-choice', options: ['Nero', 'Konstantin', 'Justinian', 'Augustus'], correctAnswer: 2, explanation: 'Kaiser Justinian schloss die heidnische Akademie.' },
    { id: 'q-phil-5-3', text: 'In welcher Schule wirkten Frauen?', type: 'multiple-choice', options: ['Nur in der Akademie', 'Pythagoreerinnen bei Pythagoras', 'Nirgends', 'Nur bei Sophisten'], correctAnswer: 1, explanation: 'Pythagoreerinnen — Frauen in der Schule des Pythagoras.' }
  ]},
  { id: 'p21', title: 'Öffentliche Vorträge', content: 'Viele Philosophen hielten öffentliche Vorträge — kostenlos oder gegen Eintritt. Das zog Zuhörer und Schüler an. Der Ruhm eines Philosophen wuchs durch mündliche Überlieferung: je interessanter die Vorträge, desto mehr Anhänger und Gaben.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/lecture.jpg', title: 'Vortrag' }] },
  { id: 'p22', title: 'Geschenke und Mäzenatentum', content: 'Reiche Schüler brachten Gaben: Land, Geld, Sklaven. Platon erhielt von Dion ein Grundstück für die Akademie. Aristoteles wurde von Alexander unterstützt. Ohne Mäzene hätten die Schulen nicht überlebt — Honorare deckten nicht alle Kosten.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/patronage.jpg', title: 'Mäzenatentum' }] },
  { id: 'p23', title: 'Streit um «Verkäuflichkeit»', content: 'Sokrates und Platon kritisierten die Sophisten dafür, dass sie «Weisheit verkaufen». Aber auch Akademie und Lykeion brauchten Mittel. Der Unterschied lag darin, wie sich die Schule darstellte: als Handel mit Fertigkeiten oder als gemeinsame Suche nach Wahrheit.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/debate.jpg', title: 'Debatte' }] },
  { id: 'p24', title: 'Epikur und der Garten', content: 'Epikur gründete seine Schule in einem Garten — «Der Garten» wurde zum Synonym seiner Lehre. Er nahm Frauen und Sklaven auf, was ungewöhnlich war. Die Schule lebte bescheiden von gemeinsamen Beiträgen. Epikur vermachte den Garten seinen Freunden — Philosophie als Gemeinschaft, nicht als Geschäft.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/epicurus-garden.jpg', title: 'Epikurs Garten' }] },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-phil-6-1', text: 'Wer gab Platon das Grundstück für die Akademie?', type: 'multiple-choice', options: ['Sokrates', 'Dion von Syrakus', 'Aristoteles', 'Alexander'], correctAnswer: 1, explanation: 'Dion überließ Platon das Grundstück.' },
    { id: 'q-phil-6-2', text: 'Wen nahm Epikur in die Schule auf?', type: 'multiple-choice', options: ['Nur Männer', 'Auch Frauen und Sklaven', 'Nur Athener', 'Nur Reiche'], correctAnswer: 1, explanation: 'Epikur nahm Frauen und Sklaven auf — ungewöhnlich.' },
    { id: 'q-phil-6-3', text: 'Wie zogen Philosophen Schüler an?', type: 'multiple-choice', options: ['Nur durch Honorare', 'Durch öffentliche Vorträge, Ruhm', 'Mit Zwang', 'Nur durch Tempel'], correctAnswer: 1, explanation: 'Öffentliche Vorträge und Ruf zogen Zuhörer an.' }
  ]},
  { id: 'p25', title: 'Zenon und die Stoa', content: 'Zenon von Kition begründete den Stoizismus und lehrte in der Bemalten Stoa. Er nahm kein Geld von Schülern — lebte bescheiden. Der Stoizismus zog die an, die Standhaftigkeit und Tugend suchten, nicht Karriere. Die Schule lebte von freiwilligen Gaben.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/zeno.jpg', title: 'Zenon' }] },
  { id: 'p26', title: 'Pythagoras und die Gemeinschaft', content: 'Pythagoras schuf keine bloße Schule, sondern eine Gemeinschaft mit gemeinsamem Besitz. Schüler gaben ihr Vermögen in die gemeinsame Kasse. Nach Pythagoras\' Tod zerfiel die Gemeinschaft, aber die Idee «Philosophie als Lebensweise» blieb.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/pythagoras.jpg', title: 'Pythagoras' }] },
  { id: 'p27', title: 'Rhetorik als Ware', content: 'Sophisten lehrten Rhetorik — die Kunst zu überzeugen. Im demokratischen Athen brauchte man das für Gerichte und Volksversammlung. Reden zu können war teuer: ein guter Redner konnte einen Prozess gewinnen und Vermögen retten. Nachfrage schuf Angebot.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/rhetoric.jpg', title: 'Rhetorik' }] },
  { id: 'p28', title: 'Platon über die Sophisten', content: 'Platon zeichnete die Sophisten in seinen Dialogen als Menschen, die «Wissen über Tugend verkaufen», ohne sie selbst zu besitzen. Aber auch Platon war auf wohlhabende Freunde angewiesen. Der Unterschied lag in den Zielen: Sophisten bereiteten auf Erfolg vor, Platon auf die Erkenntnis der Wahrheit.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/plato-sophists.jpg', title: 'Platon und Sophisten' }] },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-phil-7-1', text: 'Nahm Zenon Honorar von Schülern?', type: 'multiple-choice', options: ['Ja, hohes', 'Nein, lebte bescheiden', 'Nur von Reichen', 'Nur Geschenke'], correctAnswer: 1, explanation: 'Zenon nahm kein Geld, lebte bescheiden.' },
    { id: 'q-phil-7-2', text: 'Wie lebte die Gemeinschaft des Pythagoras?', type: 'multiple-choice', options: ['Jeder für sich', 'Gemeinsamer Besitz', 'Sie zahlten Pythagoras', 'Nur Frauen zahlten'], correctAnswer: 1, explanation: 'Pythagoreer gaben Vermögen in die gemeinsame Kasse.' },
    { id: 'q-phil-7-3', text: 'Was lehrten die Sophisten hauptsächlich?', type: 'multiple-choice', options: ['Mathematik', 'Rhetorik — Kunst zu überzeugen', 'Musik', 'Medizin'], correctAnswer: 1, explanation: 'Sophisten lehrten Rhetorik für Gerichte und Versammlungen.' }
  ]},
  { id: 'p29', title: 'Athen — Anziehungspunkt', content: 'Nach Athen kamen Schüler aus der ganzen griechischen Welt. Die Stadt bot Redefreiheit und eine Fülle von Schulen. Junge Aristokraten aus Makedonien, Kleinasien, Sizilien kamen zum Studium — und gaben Geld für Leben und Unterricht aus.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/athens-center.jpg', title: 'Athen' }] },
  { id: 'p30', title: 'Philosoph als Berühmtheit', content: 'Bekannte Philosophen wurden «Stars»: Herrscher kamen zu ihnen, sie wurden an Höfe eingeladen. Ruhm brachte Schüler und Gönner. Aber auch Gefahr: Sokrates wurde hingerichtet, Aristoteles verbannt.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/celebrity.jpg', title: 'Philosoph als Berühmtheit' }] },
  { id: 'p31', title: 'Erbe der Schulen', content: 'Die Texte Platons, Aristoteles\', der Stoiker und Epikureer überdauerten die Antike. Sie wurden abgeschrieben, kommentiert, übersetzt. Die Ökonomie der Schulen ist längst vergessen — die Ideen blieben. Philosophie erwies sich als wertvoller als Honorare.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/manuscripts.jpg', title: 'Handschriften' }] },
  { id: 'p32', title: 'Humor: Sokrates und die Gattin', content: 'Xanthippe, Sokrates\' Frau, galt als zänkisch. Einmal schüttete sie ihm Wasser über den Kopf. Sokrates sagte: «Nach Donner kommt immer Regen.» Ein Freund fragte, warum er so eine heirate. Sokrates antwortete: «Wer Xanthippe aushält, hält jeden aus.» Geduldsübung als philosophische Praxis.', duration: 3 },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-phil-8-1', text: 'Woher kamen die Schüler nach Athen?', type: 'multiple-choice', options: ['Nur aus Athen', 'Aus der ganzen griechischen Welt', 'Nur aus Sparta', 'Nur aus Rom'], correctAnswer: 1, explanation: 'Schüler kamen aus Makedonien, Kleinasien, Sizilien.' },
    { id: 'q-phil-8-2', text: 'Wie hieß Sokrates\' Gattin?', type: 'multiple-choice', options: ['Aspasia', 'Xanthippe', 'Theodora', 'Hypatia'], correctAnswer: 1, explanation: 'Xanthippe — Sokrates\' Frau, bekannt für ihr Temperament.' },
    { id: 'q-phil-8-3', text: 'Was überdauerte die Antike vom Erbe der Schulen?', type: 'multiple-choice', options: ['Nur Gebäude', 'Texte Platons, Aristoteles\', Stoiker', 'Nur Namen', 'Nichts'], correctAnswer: 1, explanation: 'Texte wurden über Jahrhunderte abgeschrieben und kommentiert.' }
  ]},
  { id: 'p33', title: 'Skeptiker und die Akademie', content: 'Die späte Akademie wurde skeptisch: «wir wissen nichts mit Sicherheit». Karneades trat in Rom auf — an einem Tag für, am nächsten gegen Gerechtigkeit. Die Römer waren beeindruckt, aber beunruhigt: solche Rhetorik konnte die Grundlagen untergraben.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/skeptics.jpg', title: 'Skeptiker' }] },
  { id: 'p34', title: 'Römer und griechische Philosophie', content: 'Die römische Elite studierte griechische Philosophie. Cicero übersetzte und adaptierte griechische Texte. Seneca, Epiktet, Mark Aurel schrieben auf Latein und stützten sich auf den Stoizismus. Philosophie wurde Teil der Bildung der Oberschicht.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/cicero.jpg', title: 'Cicero' }] },
  { id: 'p35', title: 'Schule als Lebensweise', content: 'Für viele war Philosophie keine Profession, sondern Lebensweise. Kyniker, Stoiker, Epikureer — jeder wählte seinen Weg. Die Schule bot Gemeinschaft, Sinn und Regeln. Geld war Mittel, nicht Ziel.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/way-of-life.jpg', title: 'Lebensweise' }] },
  { id: 'p36', title: 'Balance von Ideal und Realität', content: 'Philosophen sprachen von Tugend und Wahrheit — aber Schulen mussten unterhalten werden. Platon verkaufte keine Weisheit, nahm aber Gaben an. Aristoteles diente am Hof. Ideal und Praxis koexistierten — wie heute in der Bildung.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/balance.jpg', title: 'Balance' }] },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-phil-9-1', text: 'Wer trat in Rom für und gegen Gerechtigkeit auf?', type: 'multiple-choice', options: ['Platon', 'Karneades', 'Aristoteles', 'Epikur'], correctAnswer: 1, explanation: 'Karneades demonstrierte die Kraft skeptischer Rhetorik.' },
    { id: 'q-phil-9-2', text: 'Wer übersetzte griechische Philosophie für die Römer?', type: 'multiple-choice', options: ['Seneca', 'Cicero', 'Mark Aurel', 'Epiktet'], correctAnswer: 1, explanation: 'Cicero übersetzte und adaptierte griechische Texte.' },
    { id: 'q-phil-9-3', text: 'Was war für Philosophen wichtiger als Geld?', type: 'multiple-choice', options: ['Nur Geld', 'Lebensweise, Gemeinschaft, Sinn', 'Nur Ruhm', 'Nur Macht'], correctAnswer: 1, explanation: 'Philosophie war Lebensweise, Geld — Mittel.' }
  ]},
  { id: 'p37', title: 'Lehrer und Schüler', content: 'Das Verhältnis von Lehrer und Schüler beruhte auf Vertrauen und Weitergabe. Aristoteles war Platons Schüler, Alexander Aristoteles\' Schüler. Wissen wurde durch persönlichen Kontakt vermittelt. Honorar oder Gabe — nur eine Form der Dankbarkeit.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/teacher-student.jpg', title: 'Lehrer und Schüler' }] },
  { id: 'p38', title: 'Kritik an «verkäuflicher» Weisheit', content: 'Sokrates fragte: Lässt sich Tugend für Geld lehren? Wenn ja — warum sind die Lehrer nicht immer tugendhaft? Die Frage bleibt offen. Der Unterschied zwischen Fertigkeit (Rhetorik) und Tugend (Ethik) war zentral in den antiken Debatten.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/virtue.jpg', title: 'Tugend' }] },
  { id: 'p39', title: 'Philosophie heute', content: 'Auch Universitäten verbinden Wissensideal und Ökonomie: Studiengebühren, Stipendien, Mäzene. Die Frage, ob «Weisheit verkauft» wird, ist nicht veraltet. Die antiken Schulen gaben Vorbild — und Warnung.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/modern.jpg', title: 'Moderne' }] },
  { id: 'p40', title: 'Fazit: vielschichtiges Bild', content: 'Die philosophischen Schulen Athens — weder «Geschäft» noch «Wohltätigkeit». Es ist Ökonomie (Honorare, Mäzene, Konkurrenz), Ideale (Wahrheit, Tugend) und lebendige Geschichten (Diogenes, Sokrates, Protagoras). Das Bild ist vielschichtig — wie die Philosophie selbst.', duration: 3, media: [{ type: 'image', url: '/media/philosophy-athens/summary.jpg', title: 'Fazit' }] },
  { id: 'q10', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-phil-10-1', text: 'Wer war Platons Schüler?', type: 'multiple-choice', options: ['Sokrates', 'Aristoteles', 'Epikur', 'Diogenes'], correctAnswer: 1, explanation: 'Aristoteles studierte bei Platon.' },
    { id: 'q-phil-10-2', text: 'Welche Frage stellte Sokrates zur Tugend?', type: 'multiple-choice', options: ['Was kostet sie', 'Lässt sie sich für Geld lehren', 'Wer hat sie erfunden', 'Wo wohnt sie'], correctAnswer: 1, explanation: 'Sokrates fragte: Lässt sich Tugend für Geld lehren?' },
    { id: 'q-phil-10-3', text: 'Was waren die Schulen Athens?', type: 'multiple-choice', options: ['Nur Geschäft', 'Nur Wohltätigkeit', 'Vielschichtiges Phänomen: Ökonomie + Ideale + Geschichte', 'Nur Tempel'], correctAnswer: 2, explanation: 'Schulen verbanden Ökonomie, Ideale und lebendige Traditionen.' }
  ]}
]

export const philosophyAthensFinalQuizDE: QuizBlock = {
  id: 'quiz-philosophy-athens',
  title: 'Abschlussquiz: Philosophie als Geschäft — Schulen Athens',
  questions: [
    { id: 'final-p1', text: 'Nahm Sokrates Honorar?', type: 'multiple-choice', options: ['Ja', 'Nein', 'Nur von Reichen', 'Nur Geschenke'], correctAnswer: 1, explanation: 'Sokrates lehrte kostenlos.' },
    { id: 'final-p2', text: 'Wer nahm zuerst Honorar?', type: 'multiple-choice', options: ['Sokrates', 'Platon', 'Sophisten', 'Aristoteles'], correctAnswer: 2, explanation: 'Sophisten — Protagoras, Gorgias.' },
    { id: 'final-p3', text: 'Wo lag Platons Akademie?', type: 'multiple-choice', options: ['Auf der Agora', 'Im Hain außerhalb der Mauern', 'Im Piräus', 'Auf der Akropolis'], correctAnswer: 1, explanation: 'Im Hain außerhalb der Stadtmauern.' },
    { id: 'final-p4', text: 'Warum hießen Aristoteles\' Schüler Peripatetiker?', type: 'multiple-choice', options: ['Sie lebten in Höhlen', 'Sie gingen mit dem Lehrer', 'Sie trugen besondere Kleidung', 'Sie kamen aus Pera'], correctAnswer: 1, explanation: '«Spaziergänger» — diskutierten beim Gehen.' },
    { id: 'final-p5', text: 'Wo lehrten die Stoiker?', type: 'multiple-choice', options: ['Im Garten', 'In der Bemalten Stoa', 'In der Akademie', 'Im Lykeion'], correctAnswer: 1, explanation: 'Stoa Poikile auf der Agora.' },
    { id: 'final-p6', text: 'Wer lebte in einer Tonne?', type: 'multiple-choice', options: ['Sokrates', 'Platon', 'Diogenes', 'Epikur'], correctAnswer: 2, explanation: 'Diogenes von Sinope — Kyniker.' },
    { id: 'final-p7', text: 'Wie teilte Protagoras die Zahlung mit Euathlos?', type: 'multiple-choice', options: ['Alles sofort', 'Hälfte vor dem ersten Prozess, Hälfte danach', 'Nur danach', 'Nach Belieben'], correctAnswer: 1, explanation: 'Hälfte vor, Hälfte nach dem ersten gewonnenen Fall.' },
    { id: 'final-p8', text: 'Wen erzog Aristoteles?', type: 'multiple-choice', options: ['Sokrates', 'Platon', 'Aristoteles', 'Epikur'], correctAnswer: 2, explanation: 'Aristoteles war Alexanders Lehrer.' },
    { id: 'final-p9', text: 'Wohin reiste Platon zum Tyrannen?', type: 'multiple-choice', options: ['Nach Rom', 'Nach Syrakus', 'Nach Sparta', 'Nach Persien'], correctAnswer: 1, explanation: 'Zu Dionysios nach Syrakus.' },
    { id: 'final-p10', text: 'Was sagte Diogenes zu Alexander?', type: 'multiple-choice', options: ['Gib Geld', 'Geh zur Seite, du verdeckst die Sonne', 'Nimm mich mit', 'Besiege die Perser'], correctAnswer: 1, explanation: '«Geh zur Seite, du verdeckst die Sonne.»' },
    { id: 'final-p11', text: 'Wer lehrte in Alexandria?', type: 'multiple-choice', options: ['Platon', 'Hypatia', 'Aristoteles', 'Epikur'], correctAnswer: 1, explanation: 'Hypatia — Philosophin.' },
    { id: 'final-p12', text: 'Wer schloss die Akademie 529?', type: 'multiple-choice', options: ['Nero', 'Konstantin', 'Justinian', 'Augustus'], correctAnswer: 2, explanation: 'Kaiser Justinian.' },
    { id: 'final-p13', text: 'Wer gab Platon das Grundstück?', type: 'multiple-choice', options: ['Sokrates', 'Dion', 'Aristoteles', 'Alexander'], correctAnswer: 1, explanation: 'Dion von Syrakus.' },
    { id: 'final-p14', text: 'Wen nahm Epikur auf?', type: 'multiple-choice', options: ['Nur Männer', 'Auch Frauen und Sklaven', 'Nur Athener', 'Nur Reiche'], correctAnswer: 1, explanation: 'Epikur nahm Frauen und Sklaven auf.' },
    { id: 'final-p15', text: 'Nahm Zenon Honorar?', type: 'multiple-choice', options: ['Ja', 'Nein', 'Nur von Reichen', 'Nur Geschenke'], correctAnswer: 1, explanation: 'Zenon lebte bescheiden.' },
    { id: 'final-p16', text: 'Wie lebte Pythagoras\' Gemeinschaft?', type: 'multiple-choice', options: ['Jeder für sich', 'Gemeinsamer Besitz', 'Sie zahlten Pythagoras', 'Nur Frauen'], correctAnswer: 1, explanation: 'Gemeinsame Kasse.' },
    { id: 'final-p17', text: 'Was lehrten die Sophisten?', type: 'multiple-choice', options: ['Mathematik', 'Rhetorik', 'Musik', 'Medizin'], correctAnswer: 1, explanation: 'Rhetorik — Kunst zu überzeugen.' },
    { id: 'final-p18', text: 'Wie hieß Sokrates\' Gattin?', type: 'multiple-choice', options: ['Aspasia', 'Xanthippe', 'Theodora', 'Hypatia'], correctAnswer: 1, explanation: 'Xanthippe.' },
    { id: 'final-p19', text: 'Wer trat in Rom für und gegen Gerechtigkeit auf?', type: 'multiple-choice', options: ['Platon', 'Karneades', 'Aristoteles', 'Epikur'], correctAnswer: 1, explanation: 'Karneades — Skeptiker.' },
    { id: 'final-p20', text: 'Wer übersetzte für die Römer?', type: 'multiple-choice', options: ['Seneca', 'Cicero', 'Mark Aurel', 'Epiktet'], correctAnswer: 1, explanation: 'Cicero.' },
    { id: 'final-p21', text: 'Wie alt wurde Gorgias?', type: 'multiple-choice', options: ['Etwa 70', 'Etwa 90', 'Fast 110', 'Etwa 60'], correctAnswer: 2, explanation: 'Gorgias wurde fast 110.' },
    { id: 'final-p22', text: 'Wer war Platons Schüler?', type: 'multiple-choice', options: ['Sokrates', 'Aristoteles', 'Epikur', 'Diogenes'], correctAnswer: 1, explanation: 'Aristoteles.' },
    { id: 'final-p23', text: 'Welche Frage stellte Sokrates zur Tugend?', type: 'multiple-choice', options: ['Was kostet sie', 'Lässt sie sich für Geld lehren', 'Wer erfand sie', 'Wo wohnt sie'], correctAnswer: 1, explanation: 'Lässt sich Tugend für Geld lehren?' },
    { id: 'final-p24', text: 'Woher kamen die Schüler?', type: 'multiple-choice', options: ['Nur aus Athen', 'Aus der ganzen griechischen Welt', 'Nur aus Sparta', 'Nur aus Rom'], correctAnswer: 1, explanation: 'Aus Makedonien, Kleinasien, Sizilien.' },
    { id: 'final-p25', text: 'Was überdauerte die Antike?', type: 'multiple-choice', options: ['Nur Gebäude', 'Texte der Philosophen', 'Nur Namen', 'Nichts'], correctAnswer: 1, explanation: 'Texte Platons, Aristoteles\', Stoiker.' },
    { id: 'final-p26', text: 'Was waren die Schulen Athens?', type: 'multiple-choice', options: ['Nur Geschäft', 'Nur Wohltätigkeit', 'Vielschichtiges Phänomen', 'Nur Tempel'], correctAnswer: 2, explanation: 'Ökonomie + Ideale + Traditionen.' },
    { id: 'final-p27', text: 'Wo lehrte Epikur?', type: 'multiple-choice', options: ['Auf der Agora', 'Im Garten', 'In der Akademie', 'Im Lykeion'], correctAnswer: 1, explanation: 'Epikurs Garten.' },
    { id: 'final-p28', text: 'Wen verbannte man wegen Gottlosigkeit?', type: 'multiple-choice', options: ['Sokrates', 'Anaxagoras', 'Platon', 'Aristoteles'], correctAnswer: 1, explanation: 'Anaxagoras.' },
    { id: 'final-p29', text: 'Wer sagte «nicht ein zweites Mal sündigen»?', type: 'multiple-choice', options: ['Sokrates', 'Platon', 'Aristoteles', 'Diogenes'], correctAnswer: 2, explanation: 'Aristoteles vor der Flucht aus Athen.' },
    { id: 'final-p30', text: 'Was kritisierte Platon an den Sophisten?', type: 'multiple-choice', options: ['Armut', 'Verkauf von Weisheit', 'Zu viele Schüler', 'Ausländer'], correctAnswer: 1, explanation: '«Verkaufen Wissen über Tugend».' }
  ]
}
