import { Slide, QuizBlock } from '../types/session'

// Deutsche Übersetzungen für Rom: Insulae und Armut
export const romeInsulaeSlidesDE: Slide[] = [
  { id: 'r1', title: 'Was ist eine Insula', content: 'Eine Insula war ein mehrstöckiges Mietshaus, in dem die Mehrheit der Römer wohnte. Kein Palast, keine Villa: enge Zimmer, die vermietet wurden. In einem solchen Gebäude konnten Hunderte Menschen hausen.', duration: 3, media: [{ type: 'image', url: '/media/rome/insula-model.jpg', title: 'Insula' }] },
  { id: 'r2', title: 'Höhenbegrenzung', content: 'Nach Einstürzen begrenzte Augustus die Höhe der Insulae auf 21 Meter, später Trajan auf 18 Meter. Bauherren brachen die Regeln oft: Boden in der Mitte war teuer, es lohnte sich, in die Höhe zu bauen.', duration: 3, media: [{ type: 'image', url: '/media/rome/insula-height.jpg', title: 'Höhe der Insulae' }] },
  { id: 'r3', title: 'Wasser nur unten', content: 'Obere Stockwerke hatten kein fließendes Wasser. Wasser wurde von öffentlichen Brunnen geholt oder bei Wasserträgern gekauft — Sklaven oder Tagelöhnern. Ein Aufstieg in den fünften Stock konnte einen Bruchteil des Tageslohns kosten.', duration: 3, media: [{ type: 'image', url: '/media/rome/water-carrier.jpg', title: 'Wasserträger' }] },
  { id: 'r4', title: 'Keine Toiletten in den Wohnungen', content: 'Latrinen gab es auf der Straße oder im Hof. In den Zimmern nutzte man Nachttöpfe, deren Inhalt aus dem Fenster geschüttet wurde — daher die Warnung «cave canem» und die Gefahr für Passanten.', duration: 3, media: [{ type: 'image', url: '/media/rome/latrine.jpg', title: 'Öffentliche Latrine' }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-rome-1-1', text: 'Was ist eine Insula?', type: 'multiple-choice', options: ['Kaiserpalast', 'Mehrstöckiges Mietshaus', 'Tempel', 'Thermen'], correctAnswer: 1, explanation: 'Insula — mehrstöckiges Mietshaus, in dem die Mehrheit der Stadtbevölkerung wohnte.' },
    { id: 'q-rome-1-2', text: 'Wer begrenzte die Höhe der Insulae auf 21 Meter?', type: 'multiple-choice', options: ['Nero', 'Augustus', 'Caesar', 'Trajan'], correctAnswer: 1, explanation: 'Augustus führte die Begrenzung nach Einstürzen ein.' },
    { id: 'q-rome-1-3', text: 'Woher kam das Wasser in den oberen Stockwerken?', type: 'multiple-choice', options: ['Aus dem Wasserhahn', 'Von Brunnen oder Wasserträgern', 'Aus dem Hofbrunnen', 'Sklaven brachten es'], correctAnswer: 1, explanation: 'Oben gab es kein Leitungswasser — Wasser wurde getragen oder gekauft.' }
  ]},
  { id: 'r5', title: 'Brände', content: 'Brände in Insulae waren üblich: Öfen, Kerzen, Enge. In armen Vierteln gab es keine eigene Feuerwehr. Nach dem Brand von 64 baute Nero die Mitte neu, aber die Slums am Rand brannten weiter.', duration: 3, media: [{ type: 'image', url: '/media/rome/fire.jpg', title: 'Brand in Rom' }] },
  { id: 'r6', title: 'Einstürze', content: 'Juvenal schrieb: Wir leben in einer Stadt, «von Stangen gestützt» — Häuser stürzten ein wegen Eile und Gier der Bauherren. Die Toten unter den Trümmern zählte kaum jemand.', duration: 3, media: [{ type: 'image', url: '/media/rome/collapse.jpg', title: 'Einsturz' }] },
  { id: 'r7', title: 'Tagesmiete', content: 'Viele zahlten täglich Miete. Kein Vertrag, kein Schutz: Rauswurf jederzeit möglich. Bei Zahlungsverzug — Sachen auf die Straße.', duration: 3, media: [{ type: 'image', url: '/media/rome/rent.jpg', title: 'Miete' }] },
  { id: 'r8', title: 'Erdgeschoss — Läden', content: 'Unten lagen Tabernae (Läden) und Popinae (billige Tavernen). Darüber — Wohnräume: je höher, desto billiger und dunkler. Unter dem Dach oft winzige Kammern.', duration: 3, media: [{ type: 'image', url: '/media/rome/taberna.jpg', title: 'Taberna' }] },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-rome-2-1', text: 'Wie oft zahlten viele Arme Miete?', type: 'multiple-choice', options: ['Einmal im Jahr', 'Täglich', 'Monatlich', 'Wöchentlich'], correctAnswer: 1, explanation: 'Tagesmiete bot keinen Schutz vor Rauswurf.' },
    { id: 'q-rome-2-2', text: 'Was war im Erdgeschoss der Insula?', type: 'multiple-choice', options: ['Wohnungen der Reichen', 'Läden und Tavernen', 'Lager', 'Ställe'], correctAnswer: 1, explanation: 'Unten Tabernae und Popinae, darüber Wohnungen.' },
    { id: 'q-rome-2-3', text: 'Wer schrieb von der Stadt «von Stangen gestützt»?', type: 'multiple-choice', options: ['Cicero', 'Juvenal', 'Vergil', 'Tacitus'], correctAnswer: 1, explanation: 'Juvenal beschrieb Einstürze und wackelige Bauten.' }
  ]},
  { id: 'r9', title: 'Domus — Haus des Reichen', content: 'Reiche wohnten im Domus — Einfamilienhaus mit Atrium und Garten. Ein solches Haus konnte die Fläche eines ganzen Insula-Blocks einnehmen. Darin lebten Herr, Familie und Sklaven.', duration: 3, media: [
    { type: 'image', url: '/media/rome/domus.jpg', title: 'Domus' },
    { type: 'video', url: 'https://www.youtube.com/watch?v=Ame2qd9v_ok', title: 'Video: römischer Domus' }
  ] },
  { id: 'r10', title: 'Brotverteilung', content: 'Die Plebs erhielt kostenloses Getreide, später Brot. Die Verteilung diente dazu, die Stadt von Aufruhr abzuhalten und war Instrument der Politik: «Brot und Spiele» kauften Loyalität.', duration: 3, media: [{ type: 'image', url: '/media/rome/dole.jpg', title: 'Brotverteilung' }] },
  { id: 'r11', title: 'Aquädukte und Brunnen', content: 'Wasser kam über Aquädukte zu Brunnen und Thermen. In die Wohnungen der Insulae wurden keine Leitungen gelegt. Arme standen an öffentlichen Brunnen mit Krügen Schlange.', duration: 3, media: [{ type: 'image', url: '/media/rome/aqueduct.jpg', title: 'Aquädukt' }] },
  { id: 'r12', title: 'Thermen — Bad für alle', content: 'Eintritt in die öffentlichen Bäder kostete wenig. Dort wusch man sich, wärmte sich, tratschte und schloss Geschäfte ab. Thermen waren einer der wenigen Orte, an denen Stände sich mischten.', duration: 3, media: [{ type: 'image', url: '/media/rome/thermae.jpg', title: 'Thermen' }] },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-rome-3-1', text: 'Wo wohnten reiche Römer?', type: 'multiple-choice', options: ['Oben in Insulae', 'Im Domus — Einfamilienhaus', 'In Tabernae', 'In Thermen'], correctAnswer: 1, explanation: 'Domus — Haus mit Atrium und Garten für eine Familie.' },
    { id: 'q-rome-3-2', text: 'Wozu wurde Brot an die Plebs verteilt?', type: 'multiple-choice', options: ['Aus Nächstenliebe', 'Um Aufruhr zu verhindern und Loyalität zu kaufen', 'Gesetzlich', 'Nur bei Hungersnot'], correctAnswer: 1, explanation: '«Brot und Spiele» — Mittel, die Stadt unter Kontrolle zu halten.' },
    { id: 'q-rome-3-3', text: 'Wohin wurde in Insulae kein Wasser gelegt?', type: 'multiple-choice', options: ['In Tabernae', 'In die oberen Stockwerke', 'In den Hof', 'In den Keller'], correctAnswer: 1, explanation: 'Leitungen gab es nur zu Brunnen und in reiche Häuser.' }
  ]},
  { id: 'r13', title: 'Straßenlärm', content: 'Juvenal klagte: In Rom schlafen — unmöglich. Wagen, Händlergeschrei, Prügeleien. Fuhrverkehr in der Stadt wurde tags eingeschränkt, aber das nächtliche Treiben in den Slums hörte nicht auf.', duration: 3, media: [{ type: 'image', url: '/media/rome/street-noise.jpg', title: 'Straße in Rom' }] },
  { id: 'r14', title: 'Nacht ohne Laternen', content: 'Straßen in armen Vierteln waren nicht beleuchtet. Nachts raus — gefährlich: Räuber, Betrunkene, Müll unter den Füßen. Reiche gingen mit Fackeln und Sklaven-Trägern.', duration: 3, media: [{ type: 'image', url: '/media/rome/night.jpg', title: 'Nächtliches Rom' }] },
  { id: 'r15', title: 'Subura und Esquilin', content: 'Subura und Hänge des Esquilin — die bekanntesten Slums. Enge Gassen, Gestank, Kriminalität. Cicero und andere Reiche besaßen dort Mietshäuser, wohnten aber nicht dort.', duration: 3, media: [{ type: 'image', url: '/media/rome/subura.jpg', title: 'Subura' }] },
  { id: 'r16', title: 'Ein Zimmer pro Familie', content: 'Arme hatten oft ein Zimmer für die ganze Familie. Mehrere Familien teilten eine Etage ohne Wände. Keine Privatsphäre — Streit, Krankheit, Geburt vor den Nachbarn.', duration: 3, media: [{ type: 'image', url: '/media/rome/cramped.jpg', title: 'Enge' }] },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-rome-4-1', text: 'Warum war es nachts in armen Vierteln gefährlich?', type: 'multiple-choice', options: ['Es war kalt', 'Keine Beleuchtung, Räuber', 'Wilde Tiere', 'Ausgangssperre'], correctAnswer: 1, explanation: 'Straßen waren dunkel, Räuber und Betrunkene bedrohten.' },
    { id: 'q-rome-4-2', text: 'Wo lagen die Slums der Subura?', type: 'multiple-choice', options: ['Auf dem Kapitol', 'In der Mitte, zwischen den Hügeln', 'Jenseits des Tibers', 'Nur in Ostia'], correctAnswer: 1, explanation: 'Subura und Esquilin — arme Viertel in der Mitte Roms.' },
    { id: 'q-rome-4-3', text: 'Wie wohnten arme Familien in Insulae?', type: 'multiple-choice', options: ['In getrennten Wohnungen mit Komfort', 'Oft ein Zimmer pro Familie', 'Im Hof unter einem Vordach', 'In Thermen'], correctAnswer: 1, explanation: 'Ein Zimmer pro Familie, manchmal Etage ohne Trennwände.' }
  ]},
  { id: 'r17', title: 'Graffiti an den Wänden', content: 'Wände waren vollgeschrieben: Werbung für Läden, Ankündigungen, Schimpfwörter und politische Parolen. Wie in Pompeji — Graffiti zeigen die Stimme der einfachen Leute, nicht nur der Elite.', duration: 3, media: [{ type: 'image', url: '/media/rome/graffiti.jpg', title: 'Graffiti' }] },
  { id: 'r18', title: 'Popinae — billige Tavernen', content: 'In Popinae gab es Wein und einfaches Essen. Man spielte Würfel, stritt und prügelte sich manchmal. Für die Elite «Saufhöhlen», für die Plebs der einzige öffentliche Treffpunkt.', duration: 3, media: [
    { type: 'image', url: '/media/rome/popina.jpg', title: 'Popina' },
    { type: 'video', url: 'https://www.youtube.com/watch?v=SdBcXGYxVhc', title: 'Video: römische Taverne (Popina)' }
  ] },
  { id: 'r19', title: 'Humor: Schlaf in der Insula', content: 'Martial beschreibt einen Dichter, der unter dem Dach wohnte: oben Tauben, unten Lärm der Taverne, nebenan weinendes Baby und Mühlengeräusch. Er fragt: «Wer sagte, in Rom schläft man schlecht? Ich schlafe gar nicht.»', duration: 3 },
  { id: 'r20', title: 'Prostitution und Recht', content: 'Prostitution war legal, Prostituierte wurden registriert. Der Preis für einen Besuch konnte dem Tageslohn eines Tagelöhners entsprechen — für Arme teuer, für wohlhabende Kunden Kleingeld.', duration: 3, media: [{ type: 'image', url: '/media/rome/lupanar.jpg', title: 'Lupanar' }] },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-rome-5-1', text: 'Was stand an den Wänden in Rom?', type: 'multiple-choice', options: ['Nur Gesetze', 'Werbung, Schimpfwörter, Politik', 'Nur Namen', 'Nichts'], correctAnswer: 1, explanation: 'Graffiti — Werbung, Ankündigungen, Beleidigungen, Parolen.' },
    { id: 'q-rome-5-2', text: 'Was ist eine Popina?', type: 'multiple-choice', options: ['Tempel', 'Billige Taverne', 'Thermen', 'Schule'], correctAnswer: 1, explanation: 'Popina — Lokal mit Wein und Essen fürs einfache Volk.' },
    { id: 'q-rome-5-3', text: 'Wer beklagte, in Rom nicht schlafen zu können?', type: 'multiple-choice', options: ['Caesar', 'Martial', 'Nero', 'Cicero'], correctAnswer: 1, explanation: 'Martial schilderte Tauben, Lärm und Nachbarn unter dem Dach.' }
  ]},
  { id: 'r21', title: 'Sklaven bei Armen', content: 'Auch weniger wohlhabende Familien konnten ein, zwei Sklaven haben: Kindermädchen, Wasserträger. Freigelassene trieben oft Handel und Handwerk und wurden manchmal reicher als freie Plebejer.', duration: 3, media: [{ type: 'image', url: '/media/rome/slaves.jpg', title: 'Sklaven' }] },
  { id: 'r22', title: 'Wie man die Zeit erfuhr', content: 'Taschenuhren gab es nicht. Arme orientierten sich an Sonne und Rufen der Händler. Reiche hatten Sonnen- und Wasseruhren; in der Stadt wurde die Zeit per Sonnenuhr bekanntgegeben.', duration: 3, media: [{ type: 'image', url: '/media/rome/sundial.jpg', title: 'Sonnenuhr' }] },
  { id: 'r23', title: 'Gerüche der Stadt', content: 'Abwasser floss in den Straßen, aber Abfälle aus Wohnungen wurden oft aus dem Fenster geschüttet. Öffentliche Latrinen standen bei Brunnen und Thermen. Der Gestank in engen Gassen war ständig.', duration: 3, media: [{ type: 'image', url: '/media/rome/sewage.jpg', title: 'Abwasser' }] },
  { id: 'r24', title: 'Humor: Einsturz', content: 'Historiker überliefern: Bei einem Einsturz einer Insula starben Dutzende. Dem Kaiser meldete man nur «einige». Er antwortete: «Ich hätte Angst gehabt, wenn etwas von meinem Palast eingestürzt wäre.» Der Gegensatz zwischen Elite und Plebs war offensichtlich.', duration: 3 },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-rome-6-1', text: 'Konnten Arme Sklaven haben?', type: 'multiple-choice', options: ['Nein, nur Reiche', 'Ja, ein, zwei — Kindermädchen, Wasserträger', 'Nur Freigelassene', 'Nur Kinder'], correctAnswer: 1, explanation: 'Auch weniger reiche Familien hatten manchmal 1–2 Sklaven.' },
    { id: 'q-rome-6-2', text: 'Wie erfuhren Arme die Zeit?', type: 'multiple-choice', options: ['Mit Taschenuhren', 'Durch Sonne und Händlergeschrei', 'Durch Tempelglocken', 'Gar nicht'], correctAnswer: 1, explanation: 'Uhren hatten Arme nicht — Orientierung an Sonne und Stadt.' },
    { id: 'q-rome-6-3', text: 'Wohin mit dem Inhalt der Nachttöpfe in Insulae?', type: 'multiple-choice', options: ['In die Toilette in der Wohnung', 'Oft aus dem Fenster', 'Auf die Müllhalde', 'Verbrennen'], correctAnswer: 1, explanation: 'Nachttöpfe wurden aus dem Fenster geleert — Gefahr für Passanten.' }
  ]},
  { id: 'r25', title: 'Bettler an Tempeln', content: 'An Tempeln und auf dem Forum saßen Bettler, Krüppel und Bittsteller. Ihnen zu geben galt als Frömmigkeit. Viele lebten nur von Almosen — «Sozialprogramme» im heutigen Sinne gab es nicht.', duration: 3, media: [{ type: 'image', url: '/media/rome/beggars.jpg', title: 'Bettler' }] },
  { id: 'r26', title: 'Kinder und Findelkinder', content: 'Kindersterblichkeit war hoch. Unerwünschte Säuglinge wurden ausgesetzt — an der Säule der Laktaria ließ man Kinder zurück, einen Teil holten Sklavenhändler. Das war üblich, keine Ausnahme.', duration: 3, media: [{ type: 'image', url: '/media/rome/children.jpg', title: 'Kinder' }] },
  { id: 'r27', title: 'Patron und Klienten', content: 'Klienten kamen jeden Morgen zur Salutatio — zum Gruß beim Patron. Dafür erhielten sie die Sportula: eine Portion Essen oder Kleingeld. Das ersetzte vielen Tagelohn. Loyalität und Dienste im Tausch gegen Unterstützung.', duration: 3, media: [{ type: 'image', url: '/media/rome/salutatio.jpg', title: 'Salutatio' }] },
  { id: 'r28', title: 'Was kostete Brot', content: 'Einfaches Brot war erschwinglich: Tagesration Getreide aus der Verteilung oder Kauf. Ein Tagelöhner verdiente etwa genug, um eine Familie karg zu ernähren — Brot nahm einen großen Teil des Budgets ein, wie bei Armen heute.', duration: 3, media: [{ type: 'image', url: '/media/rome/bread.jpg', title: 'Brot' }] },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-rome-7-1', text: 'Wo bettelten Arme?', type: 'multiple-choice', options: ['Nur vor der Stadt', 'An Tempeln und auf dem Forum', 'In Thermen', 'In Insulae'], correctAnswer: 1, explanation: 'An Tempeln und Forum galt Almosen als fromm.' },
    { id: 'q-rome-7-2', text: 'Was ist die Sportula?', type: 'multiple-choice', options: ['Sportart', 'Essensportion oder Geld vom Patron an den Klienten', 'Steuer', 'Schule'], correctAnswer: 1, explanation: 'Sportula — morgendliche «Gabe» an den Klienten für Treue.' },
    { id: 'q-rome-7-3', text: 'Wo setzte man unerwünschte Säuglinge aus?', type: 'multiple-choice', options: ['Im Tiber', 'An der Säule der Laktaria', 'Im Tempel', 'In Thermen'], correctAnswer: 1, explanation: 'An der Säule der Laktaria; einen Teil holten Sklavenhändler.' }
  ]},
  { id: 'r29', title: 'Posca und Wein', content: 'Arme tranken Posca — saure Mischung aus Wasser und Essig oder schlechtem Wein. Richtiger Wein war teurer. Der Unterschied zwischen Posca und Wein aus Kellern der Reichen — wie zwischen billigem Bier und teurem Wein heute.', duration: 3, media: [{ type: 'image', url: '/media/rome/posca.jpg', title: 'Posca' }] },
  { id: 'r30', title: 'Einsturz einer Insula', content: 'Es gab Fälle, in denen ganze Häuser einstürzten: Dutzende Tote. Besitzer kamen oft straffrei davon. Juvenal und andere schrieben: Man lebt wie in der Falle — zwischen Feuer und Einsturz.', duration: 3, media: [{ type: 'image', url: '/media/rome/disaster.jpg', title: 'Katastrophe' }] },
  { id: 'r31', title: 'Ostia — Rom im Kleinen', content: 'Im Hafen Ostia sind Insulae besser erhalten als in Rom. Mehrstöckige Häuser, Tabernae, enge Gassen. An ihnen lässt sich erahnen, wie eine normale römische Stadt für die Mehrheit der Bewohner aussah.', duration: 3, media: [{ type: 'image', url: '/media/rome/ostia.jpg', title: 'Ostia' }] },
  { id: 'r32', title: 'Humor: Bad und Dieb', content: 'In einer Satire wird jemand geschildert, der in den Thermen seinen Mantel unter die Obhut eines «Freunds» stellte — und ohne Mantel dastand. Moral: In öffentlichen Bädern lässt man nichts liegen. Solche Szenen zeigen Alltag und Misstrauen in der Menge.', duration: 3 },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-rome-8-1', text: 'Was tranken Arme statt gutem Wein?', type: 'multiple-choice', options: ['Nur Wasser', 'Posca — Wasser mit Essig oder schlechtem Wein', 'Milch', 'Bier'], correctAnswer: 1, explanation: 'Posca — billiges saures Getränk für Soldaten und Plebs.' },
    { id: 'q-rome-8-2', text: 'Wo sind römische Insulae am besten erhalten?', type: 'multiple-choice', options: ['Auf dem Forum in Rom', 'In Ostia', 'Nur in Pompeji', 'In Griechenland'], correctAnswer: 1, explanation: 'In Ostia sind Insulae besser erhalten als in Rom.' },
    { id: 'q-rome-8-3', text: 'Wer wurde bei Einsturz einer Insula meist nicht belangt?', type: 'multiple-choice', options: ['Der Kaiser', 'Die Hauseigentümer', 'Die Mieter', 'Die Bauleute'], correctAnswer: 1, explanation: 'Eigentümer kamen oft straffrei davon.' }
  ]},
  { id: 'r33', title: 'Tag eines Reichen, Tag eines Armen', content: 'Reicher: morgens Klientenempfang, Bäder, Mittag mit Gästen, Spiele. Armer: bei Tagesanbruch Arbeitssuche oder Sportula, Schlange für Brot, Popina oder früher Schlaf im lauten Zimmer. Zwei Städte in einer.', duration: 3, media: [{ type: 'image', url: '/media/rome/contrast.jpg', title: 'Kontrast' }] },
  { id: 'r34', title: 'Krankheiten und Seuchen', content: 'Malaria, Typhus, Darminfektionen — wegen Enge und mangelnder Hygiene. Seuchen trafen arme Viertel härter: Reiche konnten auf Landgüter fliehen. «Pest des Antoninus» und andere trafen zuerst die Plebs.', duration: 3, media: [{ type: 'image', url: '/media/rome/disease.jpg', title: 'Seuche' }] },
  { id: 'r35', title: 'Begräbnis der Armen', content: 'Arme wurden in Gemeinschaftsgruben bestattet oder billig verbrannt. Etwas Wohlhabendere — Kolumbarien, Nischen für Urnen. Prunkbegräbnisse und Mausoleen nur für die Elite.', duration: 3, media: [{ type: 'image', url: '/media/rome/columbarium.jpg', title: 'Kolumbarium' }] },
  { id: 'r36', title: 'Frauen in den Slums', content: 'Frauen spannen, verkauften in Läden im Erdgeschoss, trugen Wasser, erzogen Kinder. Viele arbeiteten wie Männer — sonst überlebte die Familie nicht. Reiche Matronen wohnten im Domus und kamen nicht in Popinae.', duration: 3, media: [{ type: 'image', url: '/media/rome/women.jpg', title: 'Frauen' }] },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-rome-9-1', text: 'Warum trafen Seuchen arme Viertel härter?', type: 'multiple-choice', options: ['Arme heilten nicht', 'Enge und mangelnde Hygiene', 'Götter straften', 'Nur dort Kranke'], correctAnswer: 1, explanation: 'Enge und fehlende Hygiene begünstigten Krankheiten.' },
    { id: 'q-rome-9-2', text: 'Wo wurden Arme bestattet?', type: 'multiple-choice', options: ['In Mausoleen', 'In Gemeinschaftsgruben oder billig verbrannt', 'In Tempeln', 'In Gärten'], correctAnswer: 1, explanation: 'Gemeinschaftsgruben oder Kolumbarien für Urnen.' },
    { id: 'q-rome-9-3', text: 'Womit beschäftigten sich Frauen in armen Familien?', type: 'multiple-choice', options: ['Nur mit dem Haus', 'Spinnen, Handel, Wassertragen', 'Nur mit Kindern', 'Mit nichts'], correctAnswer: 1, explanation: 'Sie arbeiteten wie Männer — sonst überlebte die Familie nicht.' }
  ]},
  { id: 'r37', title: 'Humor: Wahlen und Bewirtung', content: 'Bei Wahlen bewirteten Kandidaten und versprachen Spiele. Ein Satiriker bemerkte: Das Volk verkauft Stimmen für Wurst und Brei. «Brot und Spiele» — keine Metapher, sondern Beschreibung des Tauschs zwischen Elite und Plebs.', duration: 3 },
  { id: 'r38', title: 'Ein Domus — Hunderte in Insulae', content: 'Ein reiches Haus mit Garten konnte die Fläche einnehmen, auf der in Insulae Hunderte hausten. Soziale Ungleichheit zeigte sich an der Höhe: Je höher das Stockwerk, desto ärmer die Bewohner.', duration: 3, media: [{ type: 'image', url: '/media/rome/inequality.jpg', title: 'Ungleichheit' }] },
  { id: 'r39', title: 'Zirkus und Gladiatoren', content: 'Spiele lenkten die Plebs von Aufruhr ab. Zirkusspiele und Gladiatorenkämpfe bezahlten Politiker und Kaiser. Kritiker schrieben: Solange das Volk Blut sieht, sieht es die leere Kasse nicht.', duration: 3, media: [{ type: 'image', url: '/media/rome/circus.jpg', title: 'Zirkus' }] },
  { id: 'r40', title: 'Erbe der Insulae', content: 'Das Wort «insula» bedeutet im Italienischen noch heute Mehrfamilienhaus. Städtische Armut, Slums und der Kontrast zu reichen Vierteln wiederholten sich über die Jahrhunderte. Rom setzte das Muster, wie eine große Stadt «von unten» lebt.', duration: 3, media: [{ type: 'image', url: '/media/rome/legacy.jpg', title: 'Erbe' }] },
  { id: 'q10', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-rome-10-1', text: 'Warum bewirteten Kandidaten vor Wahlen?', type: 'multiple-choice', options: ['Aus Güte', 'Um Stimmen der Plebs zu kaufen', 'Gesetzlich', 'Nur bei Hungersnot'], correctAnswer: 1, explanation: '«Brot und Spiele» — Bewirtung gegen Loyalität.' },
    { id: 'q-rome-10-2', text: 'Wozu veranstaltete die Elite Spiele für das Volk?', type: 'multiple-choice', options: ['Aus Kunstliebe', 'Um von Aufruhr und leerer Kasse abzulenken', 'Auf Druck der Priester', 'Nur an Feiertagen'], correctAnswer: 1, explanation: 'Spiele hielten das Volk in Schach.' },
    { id: 'q-rome-10-3', text: 'Was bedeutet «insula» im heutigen Italienisch?', type: 'multiple-choice', options: ['Insel', 'Mehrfamilienhaus', 'Tempel', 'Taverne'], correctAnswer: 1, explanation: 'Das Wort bezeichnet noch heute ein Mehrfamilienhaus.' }
  ]}
]

export const romeInsulaeFinalQuizDE: QuizBlock = {
  id: 'quiz-rome-insulae',
  title: 'Abschlussquiz: Alltag in Rom',
  questions: [
    { id: 'final-r1', text: 'Was ist eine Insula?', type: 'multiple-choice', options: ['Palast', 'Mehrstöckiges Mietshaus', 'Tempel', 'Thermen'], correctAnswer: 1, explanation: 'Insula — Mietshaus, in dem die Mehrheit der Römer wohnte.' },
    { id: 'final-r2', text: 'Wer begrenzte die Höhe der Insulae?', type: 'multiple-choice', options: ['Nero', 'Augustus und Trajan', 'Caesar', 'Nur Trajan'], correctAnswer: 1, explanation: 'Augustus 21 m, später Trajan 18 m.' },
    { id: 'final-r3', text: 'Woher kam Wasser in den oberen Stockwerken?', type: 'multiple-choice', options: ['Aus dem Hahn', 'Von Brunnen oder Wasserträgern', 'Aus dem Hofbrunnen', 'Gar nicht'], correctAnswer: 1, explanation: 'Oben gab es kein Leitungswasser.' },
    { id: 'final-r4', text: 'Wohin mit dem Inhalt der Nachttöpfe?', type: 'multiple-choice', options: ['In die Toilette in der Wohnung', 'Oft aus dem Fenster', 'Vor die Stadt', 'In die Wände'], correctAnswer: 1, explanation: 'Aus dem Fenster — daher «cave canem».' },
    { id: 'final-r5', text: 'Wie oft zahlten viele Miete?', type: 'multiple-choice', options: ['Einmal im Jahr', 'Täglich', 'Monatlich', 'Wöchentlich'], correctAnswer: 1, explanation: 'Tagesmiete — kein Schutz vor Rauswurf.' },
    { id: 'final-r6', text: 'Was war im Erdgeschoss der Insula?', type: 'multiple-choice', options: ['Wohnungen', 'Läden und Tavernen', 'Lager', 'Ställe'], correctAnswer: 1, explanation: 'Tabernae und Popinae unten.' },
    { id: 'final-r7', text: 'Wo wohnten Reiche?', type: 'multiple-choice', options: ['Oben in Insulae', 'Im Domus', 'In Tabernae', 'In Thermen'], correctAnswer: 1, explanation: 'Domus — Einfamilienhaus mit Atrium.' },
    { id: 'final-r8', text: 'Wozu wurde Brot an die Plebs verteilt?', type: 'multiple-choice', options: ['Aus Liebe', 'Um Aufruhr zu verhindern', 'Gesetzlich', 'Nur bei Hungersnot'], correctAnswer: 1, explanation: '«Brot und Spiele» — Loyalität.' },
    { id: 'final-r9', text: 'Wer schrieb von der Stadt «von Stangen gestützt»?', type: 'multiple-choice', options: ['Cicero', 'Juvenal', 'Vergil', 'Martial'], correctAnswer: 1, explanation: 'Juvenal — über Einstürze.' },
    { id: 'final-r10', text: 'Was ist eine Popina?', type: 'multiple-choice', options: ['Tempel', 'Billige Taverne', 'Thermen', 'Schule'], correctAnswer: 1, explanation: 'Popina — Taverne für die Plebs.' },
    { id: 'final-r11', text: 'Was ist die Sportula?', type: 'multiple-choice', options: ['Sport', 'Gabe vom Patron an den Klienten', 'Steuer', 'Brotverteilung'], correctAnswer: 1, explanation: 'Morgendliche Portion Essen oder Geld an den Klienten.' },
    { id: 'final-r12', text: 'Was tranken Arme?', type: 'multiple-choice', options: ['Nur Wasser', 'Posca', 'Nur Wein', 'Bier'], correctAnswer: 1, explanation: 'Posca — Wasser mit Essig oder schlechtem Wein.' },
    { id: 'final-r13', text: 'Wo sind Insulae am besten erhalten?', type: 'multiple-choice', options: ['Auf dem Forum', 'In Ostia', 'Nur in Pompeji', 'In Griechenland'], correctAnswer: 1, explanation: 'In Ostia — Hafenstadt mit Insulae.' },
    { id: 'final-r14', text: 'Wo setzte man Säuglinge aus?', type: 'multiple-choice', options: ['Im Tiber', 'An der Säule der Laktaria', 'Im Tempel', 'In Thermen'], correctAnswer: 1, explanation: 'An der Säule der Laktaria.' },
    { id: 'final-r15', text: 'Warum war es nachts gefährlich?', type: 'multiple-choice', options: ['Kälte', 'Keine Beleuchtung', 'Tiere', 'Ausgangssperre'], correctAnswer: 1, explanation: 'Straßen waren nicht beleuchtet.' },
    { id: 'final-r16', text: 'Was ist Salutatio?', type: 'multiple-choice', options: ['Krieg', 'Morgendlicher Besuch der Klienten beim Patron', 'Bad', 'Brotverteilung'], correctAnswer: 1, explanation: 'Klienten begrüßten den Patron morgens.' },
    { id: 'final-r17', text: 'Wo lagen die Slums der Subura?', type: 'multiple-choice', options: ['Jenseits des Tibers', 'In der Mitte Roms', 'Nur in Ostia', 'Auf dem Kapitol'], correctAnswer: 1, explanation: 'Subura und Esquilin — arme Viertel.' },
    { id: 'final-r18', text: 'Womit beschäftigten sich Frauen in armen Familien?', type: 'multiple-choice', options: ['Nur mit dem Haus', 'Spinnen, Handel, Wassertragen', 'Nur mit Kindern', 'Mit nichts'], correctAnswer: 1, explanation: 'Sie arbeiteten wie Männer.' },
    { id: 'final-r19', text: 'Wo wurden Arme bestattet?', type: 'multiple-choice', options: ['In Mausoleen', 'In Gemeinschaftsgruben, Kolumbarien', 'In Tempeln', 'In Gärten'], correctAnswer: 1, explanation: 'Gemeinschaftsgruben oder Urnen in Kolumbarien.' },
    { id: 'final-r20', text: 'Wozu veranstaltete die Elite Spiele?', type: 'multiple-choice', options: ['Kunst', 'Um das Volk von Aufruhr abzulenken', 'Priester', 'Fest'], correctAnswer: 1, explanation: '«Brot und Spiele» — Kontrolle.' },
    { id: 'final-r21', text: 'Wer beklagte, in Rom nicht schlafen zu können?', type: 'multiple-choice', options: ['Caesar', 'Martial', 'Nero', 'Cicero'], correctAnswer: 1, explanation: 'Martial schilderte Lärm unter dem Dach.' },
    { id: 'final-r22', text: 'War Prostitution legal?', type: 'multiple-choice', options: ['Nein', 'Ja, mit Registrierung', 'Nur für Soldaten', 'Nur in Lupanaren'], correctAnswer: 1, explanation: 'Legal, Prostituierte wurden registriert.' },
    { id: 'final-r23', text: 'Konnten Arme Sklaven haben?', type: 'multiple-choice', options: ['Nein', 'Ja, 1–2', 'Nur Freigelassene', 'Plebs hatte keine Sklaven'], correctAnswer: 1, explanation: 'Manchmal ein, zwei — Kindermädchen, Wasserträger.' },
    { id: 'final-r24', text: 'Was ist ein Domus?', type: 'multiple-choice', options: ['Insula', 'Einfamilienhaus eines Reichen', 'Taverne', 'Tempel'], correctAnswer: 1, explanation: 'Haus mit Atrium und Garten.' },
    { id: 'final-r25', text: 'Warum trafen Seuchen Arme härter?', type: 'multiple-choice', options: ['Sie heilten nicht', 'Enge und mangelnde Hygiene', 'Götter', 'Nur dort Kranke'], correctAnswer: 1, explanation: 'Enge und fehlende Hygiene.' },
    { id: 'final-r26', text: 'Was stand an den Wänden?', type: 'multiple-choice', options: ['Nur Gesetze', 'Werbung, Schimpfwörter, Politik', 'Nur Namen', 'Nichts'], correctAnswer: 1, explanation: 'Graffiti wie in Pompeji.' },
    { id: 'final-r27', text: 'Was bedeutet «insula» im heutigen Italienisch?', type: 'multiple-choice', options: ['Insel', 'Mehrfamilienhaus', 'Tempel', 'Taverne'], correctAnswer: 1, explanation: 'Das Wort bezeichnet noch heute ein Mehrfamilienhaus.' },
    { id: 'final-r28', text: 'Wer begrenzte die Höhe auf 18 m?', type: 'multiple-choice', options: ['Augustus', 'Trajan', 'Nero', 'Caesar'], correctAnswer: 1, explanation: 'Trajan verschärfte auf 18 m.' },
    { id: 'final-r29', text: 'Wo mischten sich die Stände?', type: 'multiple-choice', options: ['Im Domus', 'In Thermen', 'Oben in Insulae', 'Im Senat'], correctAnswer: 1, explanation: 'Thermen — Eintritt für wenig Geld.' },
    { id: 'final-r30', text: 'Ein Domus entsprach flächenmäßig...', type: 'multiple-choice', options: ['Einer Insula', 'Einem ganzen Insula-Block mit Hunderten Bewohnern', 'Zwei Tabernae', 'Einem Tempel'], correctAnswer: 1, explanation: 'Ein reiches Haus — Hunderte Menschen in Insulae.' }
  ]
}
