import { Slide, QuizBlock } from '../types/session'

// Deutsche Übersetzungen (B1-B2): Stonehenge — Astronomie und Macht
export const stonehengeAstronomySlidesDE: Slide[] = [
  { id: 's1', title: 'Stonehenge — nicht «alte Druiden»', content: 'Stonehenge wurde 2000 Jahre vor den Druiden gebaut. Der Bau begann um 3000 v. Chr. — in der Jungsteinzeit. Druiden kamen erst in der Eisenzeit. Ein beliebter Mythos verdeckt die echte Geschichte.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/stonehenge-main.jpg', title: 'Stonehenge' }] },
  { id: 's2', title: 'Astronomische Präzision', content: 'Die Achse von Stonehenge zeigt auf den Sonnenaufgang zur Sommersonnenwende. Die Strahlen gehen zwischen den Steinen hindurch ins Zentrum. Wintersonnenwende — untergehende Sonne in der anderen Richtung. Präzision — ohne Teleskope und Kompasse.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/solstice.jpg', title: 'Sonnenwende' }] },
  { id: 's3', title: 'Bauphasen', content: 'Stonehenge wurde 1500 Jahre lang — in mehreren Phasen — gebaut. Zuerst Graben und Wall, dann Holzbauten, dann die ersten Steine. Die endgültige Form entstand um 2500 v. Chr. Kein einmaliges Projekt, sondern ein über viele Generationen gewachsenes Bauwerk.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/phases.jpg', title: 'Bauphasen' }] },
  { id: 's4', title: 'Sarsen — riesige Steine', content: 'Der äußere Kreis — Sarsen, Sandsteine bis 30 Tonnen. Sie wurden aus den Marlborough Downs, 30 km entfernt, herangebracht. Die Steine wurden auf Rollen gezogen und ohne Kräne aufgerichtet. Ein Stein — die Arbeit von Hunderten Menschen über Monate.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/sarsens.jpg', title: 'Sarsen' }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-stone-1-1', text: 'Wann begann man mit dem Bau von Stonehenge?', type: 'multiple-choice', options: ['In der Eisenzeit', 'Um 3000 v. Chr.', 'Im Mittelalter', 'Im 18. Jh.'], correctAnswer: 1, explanation: 'Der Bau begann um 3000 v. Chr.' },
    { id: 'q-stone-1-2', text: 'Worauf ist die Achse von Stonehenge ausgerichtet?', type: 'multiple-choice', options: ['Auf den Polarstern', 'Auf Sonnenaufgang zur Sommersonnenwende', 'Auf Vollmond', 'Auf Westen'], correctAnswer: 1, explanation: 'Auf Sonnenaufgang zur Sommersonnenwende.' },
    { id: 'q-stone-1-3', text: 'Haben Druiden Stonehenge gebaut?', type: 'multiple-choice', options: ['Ja', 'Nein — es ist 2000 Jahre älter als Druiden', 'Teilweise', 'Unbekannt'], correctAnswer: 1, explanation: 'Stonehenge ist 2000 Jahre älter als die Druiden.' }
  ]},
  { id: 's5', title: 'Humor: Heinrich VIII und «Steine»', content: 'Im 16. Jh. schrieb ein Antiquar, Stonehenge habe Merlin — der Zauberer König Arthurs — gebaut, «indem er die Steine aus Irland durch die Luft transportierte». Ein anderer dachte, es sei ein römischer Tempel. Die wissenschaftliche Archäologie begann erst im 20. Jh.', duration: 3 },
  { id: 's6', title: 'Blausteine aus Wales', content: 'Die inneren Steine — blau, aus den Preseli Hills in Wales. 250 km über Land und Wasser. Jeder Stein — 2–4 Tonnen. Warum so weit transportieren? Vielleicht schrieb man ihnen Heilkraft zu. Oder es war ein Zeichen der Macht — «wir brachten heilige Steine».', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/bluestones.jpg', title: 'Blausteine' }] },
  { id: 's7', title: 'Logistik ohne Räder', content: 'Wagen mit Rädern kamen in Britannien erst später. Die Steine wurden auf Holzrollen oder Schlitten über geschmiertem Lehm gezogen. 30 Tonnen über 30 km — ein Jahr Arbeit für Hunderte. Organisation der Verpflegung, Koordination — das ist bereits Politik.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/transport.jpg', title: 'Transport' }] },
  { id: 's8', title: 'Wer hatte die Macht?', content: 'Ein solches Projekt brauchte einen Anführer oder Priester, der Tausende zusammenbringen konnte. Kontrolle über das Wissen um die Sonnenwenden bedeutete Macht: «Ich weiß, wann das neue Jahr beginnt.» Astronomie — ein Werkzeug der Politik.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/power.jpg', title: 'Macht' }] },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-stone-2-1', text: 'Woher kamen die Blausteine?', type: 'multiple-choice', options: ['Aus lokalen Steinbrüchen', 'Aus Wales (Preseli)', 'Aus Irland', 'Aus Schottland'], correctAnswer: 1, explanation: 'Aus den Preseli Hills in Wales — 250 km.' },
    { id: 'q-stone-2-2', text: 'Wie schwer war der größte Sarsen?', type: 'multiple-choice', options: ['5 Tonnen', '15 Tonnen', 'Bis 30 Tonnen', '100 Tonnen'], correctAnswer: 2, explanation: 'Sarsen — bis 30 Tonnen.' },
    { id: 'q-stone-2-3', text: 'Warum gab Kenntnis der Sonnenwenden Macht?', type: 'multiple-choice', options: ['Weil es schön aussieht', 'Kontrolle über den Kalender — «ich weiß, wann Neujahr»', 'Weil die Sonne wichtig ist', 'Gar keine Macht'], correctAnswer: 1, explanation: 'Kalenderkontrolle — Werkzeug der Macht.' }
  ]},
  { id: 's9', title: 'Mondzyklen', content: 'Stonehenge ist nicht nur auf die Sonne ausgerichtet. Manche Forscher finden Bezüge zu Mondzyklen — vielleicht die 56 Aubrey-Löcher. Vorhersage von Finsternissen? Rituale? Die Debatte geht weiter. Klar ist: Die neolithischen Bauherren beobachteten den Himmel.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/moon.jpg', title: 'Mond' }] },
  { id: 's10', title: 'Aubrey — rätselhafte Löcher', content: '56 runde Löcher im Kreis — «Aubrey-Löcher». Vielleicht für Holzpfosten oder Steine. Manche sehen in 56 Löchern einen Finsterniszyklus (3 Zyklen à 18–19 Jahre). Andere — Zähleinheiten. Eine sichere Antwort gibt es nicht.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/aubrey.jpg', title: 'Aubrey-Löcher' }] },
  { id: 's11', title: 'Bestattungen und Rituale', content: 'In Stonehenge fand man kremierte Überreste — Dutzende Menschen. Vielleicht ein Heiligtum für die Toten oder ein Elitefriedhof. Verbindung zur Sonnenwende: Tod und Wiedergeburt der Sonne. Ritual und Macht waren eng verknüpft.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/burials.jpg', title: 'Bestattungen' }] },
  { id: 's12', title: 'Humor: Restaurierung im 20. Jh.', content: 'Ein Teil von Stonehenge stammt aus der Restaurierung im 20. Jh. 1958 fielen drei Steine — sie wurden mit Beton wieder aufgerichtet. 1901 richtete man einen Stein mit einem Kran «gerade». Das «antike» Monument ist teils ein Werk der Moderne.', duration: 3 },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-stone-3-1', text: 'Wie viele Aubrey-Löcher hat Stonehenge?', type: 'multiple-choice', options: ['28', '42', '56', '100'], correctAnswer: 2, explanation: '56 Löcher im Kreis.' },
    { id: 'q-stone-3-2', text: 'Was fand man in Stonehenge?', type: 'multiple-choice', options: ['Nur Steine', 'Kremierte Überreste von Menschen', 'Einen Goldschatz', 'Nichts'], correctAnswer: 1, explanation: 'Kremierte Überreste von Dutzenden Menschen.' },
    { id: 'q-stone-3-3', text: 'Wurde Stonehenge im 20. Jh. restauriert?', type: 'multiple-choice', options: ['Nein, es blieb unberührt', 'Ja, manche Steine wurden wieder aufgerichtet', 'Nur die Umzäunung', 'Komplett neu gebaut'], correctAnswer: 1, explanation: 'Manche Steine wurden mit Beton aufgerichtet.' }
  ]},
  { id: 's13', title: 'Durrington Walls — Stadt der Bauleute', content: '3 km von Stonehenge — Durrington Walls, die größte neolithische Siedlung Britanniens. Dort lebten die Bauleute. Schweineknochen zeigen: im Winter — Feste, im Sommer — Arbeit. Saisonale Arbeitsorganisation.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/durrington.jpg', title: 'Durrington' }] },
  { id: 's14', title: 'Jungsteinzeit — Ackerbau und Sesshaftigkeit', content: 'Um 3000 v. Chr. gab es in Britannien bereits Ackerbau. Sesshafte Gemeinschaften, Getreideüberschüsse. Stonehenge — ein Produkt einer Gesellschaft, die Nicht-Bauern ernähren konnte. Ohne Landwirtschaft keine Megalithen.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/neolithic.jpg', title: 'Jungsteinzeit' }] },
  { id: 's15', title: 'Netzwerk der Megalithen', content: 'Stonehenge ist nicht der einzige. In Britannien und Irland gibt es Hunderte von Kreisen und Grabhügeln. Avebury, Callanish, Newgrange. Gemeinsame Kultur, Austausch von Ideen. Stonehenge — Spitze eines Netzwerks, kein Einzelphänomen.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/network.jpg', title: 'Megalithen-Netzwerk' }] },
  { id: 's16', title: 'Der Fersenstein', content: 'Der «Fersenstein» (Heel Stone) steht außen, auf der Achse des Sonnenaufgangs. Zur Sommersonnenwende geht die Sonne genau über ihm auf. Der Name — aus einer Legende: Der Teufel warf einen Stein auf einen Mönch, die Ferse hinterließ einen Abdruck. Wissenschaft: Er markiert die astronomische Achse.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/heel-stone.jpg', title: 'Fersenstein' }] },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-stone-4-1', text: 'Wo lebten die Bauleute von Stonehenge?', type: 'multiple-choice', options: ['In Stonehenge selbst', 'In Durrington Walls in der Nähe', 'In Wales', 'Unbekannt'], correctAnswer: 1, explanation: 'Durrington Walls — 3 km entfernt.' },
    { id: 'q-stone-4-2', text: 'War Stonehenge der einzige Megalith?', type: 'multiple-choice', options: ['Ja, einzigartig', 'Nein — Teil eines Netzwerks von Kreisen', 'Nur in Britannien', 'Es gab nur zwei solche'], correctAnswer: 1, explanation: 'Teil eines Megalithen-Netzwerks.' },
    { id: 'q-stone-4-3', text: 'Was zeigt der Fersenstein?', type: 'multiple-choice', options: ['Teufelsspur', 'Achse des Sonnenaufgangs zur Sonnenwende', 'Grenze des Grundstücks', 'Grab eines Anführers'], correctAnswer: 1, explanation: 'Markierung der astronomischen Achse.' }
  ]},
  { id: 's17', title: 'Soziale Hierarchie', content: 'Wer konnte Tausenden befehlen, Steine zu ziehen? Eine Elite — Anführer, Priester, Älteste. Funde: In Gräbern bei Stonehenge — Gegenstände aus fernen Landen. Handel, Verbindungen, Macht. Die Jungsteinzeit kannte Ungleichheit.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/elite.jpg', title: 'Elite' }] },
  { id: 's18', title: 'Zinn und Kupfer — Metalle der Epoche', content: 'Gegen Ende des Baus gab es in Britannien Bronze. Zinn — auf den Inseln. Kupfer — vom Kontinent. Stonehenge könnte Zentrum von Handel oder Ritualen mit den neuen Technologien gewesen sein. Macht und Metalle.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/metal.jpg', title: 'Metalle' }] },
  { id: 's19', title: 'Humor: Copenhaeg und die Theorie', content: '1655 behauptete der Architekt John Webb, Stonehenge hätten die Römer gebaut — als Tempel des Gottes Coelus. Andere suchten die Erbauer in Dänemark, Ägypten, Atlantis. Die Radiokohlenstoffdatierung im 20. Jh. zeigte: Jungsteinzeit, lokal. Die einfache Erklärung war die richtige.', duration: 3 },
  { id: 's20', title: 'Vergessen und neu entdeckt', content: 'Nach der Bronzezeit verlor Stonehenge an Bedeutung. Steine wurden weggetragen, das Gelände wurde mit Friedhöfen bebaut. Im Mittelalter hielt man es für ein Werk von Riesen oder Merlin. Wissenschaftliche Erforschung — ab dem 18. Jh. Heute — UNESCO-Welterbe.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/abandoned.jpg', title: 'Vergessen' }] },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-stone-5-1', text: 'Was zeigen die Funde in Gräbern bei Stonehenge?', type: 'multiple-choice', options: ['Nur lokale Gegenstände', 'Dinge aus fernen Landen — Handel', 'Nichts Besonderes', 'Nur Waffen'], correctAnswer: 1, explanation: 'Handel, Verbindungen, Elite.' },
    { id: 'q-stone-5-2', text: 'Wer galt früher als Erbauer von Stonehenge?', type: 'multiple-choice', options: ['Nur die Jungsteinzeit', 'Römer, Merlin, Dänen', 'Wikinger', 'Nur Ägypter'], correctAnswer: 1, explanation: 'Verschiedene Theorien — Römer, Merlin usw.' },
    { id: 'q-stone-5-3', text: 'Ist Stonehenge UNESCO-Welterbe?', type: 'multiple-choice', options: ['Nein', 'Ja', 'Nur in Britannien', 'War es, wurde aber gestrichen'], correctAnswer: 1, explanation: 'In der UNESCO-Liste eingetragen.' }
  ]},
  { id: 's21', title: 'Sonnenwende heute', content: 'Jedes Jahr kommen Tausende zur Sommersonnenwende. Druiden führen Rituale durch. Tanzen, Musik, Übernachten. Die Verbindung zu den Alten — mythisch, aber das Gefühl ist echt. Das Monument lebt in der Kultur weiter.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/modern-solstice.jpg', title: 'Moderne Sonnenwende' }] },
  { id: 's22', title: 'Archeoastronomie', content: 'Die Archeoastronomie erforscht astronomisches Wissen der Alten. Stonehenge — ein zentrales Objekt. Diskussion: Wie genau ist die Ausrichtung? Zufall oder Berechnung? Die meisten Forscher gehen von bewusster Orientierung aus.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/archaeoastronomy.jpg', title: 'Archeoastronomie' }] },
  { id: 's23', title: 'Zapfen und Nuten', content: 'Die Steine von Stonehenge sind «verzapft» — Zapfen passen in Nuten. Das erfordert präzise Bearbeitung. Steinerne Äxte und Hämmer — einfache Werkzeuge. Zeit und Geduld ersetzten Technik.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/joinery.jpg', title: 'Steinverbindungen' }] },
  { id: 's24', title: 'Humor: Schafe und Steine', content: 'Im 19. Jh. stand Stonehenge auf Privatland. Der Besitzer verlangte Eintritt. Schafe weideten zwischen den Steinen. Ein Besucher beschwerte sich: «Shilling gezahlt — und die Schafe versperrten die Sicht.» Heute ist das Gelände staatlich.', duration: 3 },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-stone-6-1', text: 'Wie sind die Steine von Stonehenge verbunden?', type: 'multiple-choice', options: ['Schlicht aufeinander', '«Verzapft» — Zapfen in Nuten', 'Verklebt', 'Einfach nebeneinander'], correctAnswer: 1, explanation: 'Präzise Bearbeitung — «verzapft».' },
    { id: 'q-stone-6-2', text: 'Was erforscht die Archeoastronomie?', type: 'multiple-choice', options: ['Nur Sterne', 'Astronomisches Wissen der Alten', 'Nur die Sonne', 'Nur den Mond'], correctAnswer: 1, explanation: 'Astronomisches Wissen der Alten.' },
    { id: 'q-stone-6-3', text: 'Wer kommt heute zur Sonnenwende?', type: 'multiple-choice', options: ['Nur Wissenschaftler', 'Tausende Menschen, Druiden', 'Niemand', 'Nur Einheimische'], correctAnswer: 1, explanation: 'Tausende, Druiden führen Rituale durch.' }
  ]},
  { id: 's25', title: 'Avebury — der Nachbar-Riese', content: 'Avebury — ein Steinkreis 40 km von Stonehenge. Größer in der Fläche, aber weniger Steine sind erhalten. Auch dort astronomische Ausrichtungen. Teil derselben Kulturzone. Stonehenge — nicht isoliert.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/avebury.jpg', title: 'Avebury' }] },
  { id: 's26', title: 'Grabhügel — Gräber der Elite', content: 'Rund um Stonehenge — Hunderte Grabhügel. Manche «glockenform» mit reicher Ausstattung. Elitebestattungen beim Heiligtum. Macht und Tod: Anführer wollten am «Mittelpunkt der Welt» liegen.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/barrows.jpg', title: 'Grabhügel' }] },
  { id: 's27', title: 'Rekonstruktion — wie gebaut wurde', content: 'Archäologen führten Experimente durch: Rollen, Seile, Hebel. 200 Menschen konnten einen 30-Tonnen-Stein bewegen. Einen senkrechten Stein aufrichten — mit Hebeln und Erdaufschüttung. Primitiv — aber es funktionierte.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/experiment.jpg', title: 'Experiment' }] },
  { id: 's28', title: 'Warum genau hier?', content: 'Der Ort wurde nicht zufällig gewählt. In der Nähe — zusammenlaufende alte Wege. Freie Sicht zum Horizont — wichtig für die Beobachtung des Aufgangs. Grundwasser? Heiliger Hain? Eine sichere Antwort gibt es nicht. Landschaft und Astronomie trafen zusammen.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/location.jpg', title: 'Ort' }] },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-stone-7-1', text: 'Wo liegt Avebury?', type: 'multiple-choice', options: ['In Wales', '40 km von Stonehenge', 'In Irland', 'In Schottland'], correctAnswer: 1, explanation: '40 km — dieselbe Kulturzone.' },
    { id: 'q-stone-7-2', text: 'Wie viele Menschen konnten laut Experimenten einen 30-Tonnen-Stein bewegen?', type: 'multiple-choice', options: ['20', '100', 'Etwa 200', '1000'], correctAnswer: 2, explanation: 'Etwa 200 Menschen mit Rollen und Seilen.' },
    { id: 'q-stone-7-3', text: 'Was umgibt Stonehenge?', type: 'multiple-choice', options: ['Nur Feld', 'Hunderte Grabhügel — Elitegräber', 'Wald', 'Ein Dorf'], correctAnswer: 1, explanation: 'Hunderte Grabhügel — Elitebestattungen.' }
  ]},
  { id: 's29', title: 'Kalender und Ernte', content: 'Die Sonnenwende — Wendepunkt des Jahres. Das Datum zu kennen — Aussaat und Ernte planen. Ein Priester oder Anführer, der den Himmel «liest», kontrolliert den Kalender. Wissen — Macht über die Gemeinschaft.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/calendar.jpg', title: 'Kalender' }] },
  { id: 's30', title: 'Debatten um die Funktion', content: 'Observatorium? Tempel? Friedhof? Heilstätte? Wahrscheinlich alles zusammen. Rituale, Astronomie, Bestattungen — wurden nicht getrennt. Stonehenge — ein vieldeutiges Symbol. Vereinfachen — bedeutet Verlust.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/purpose.jpg', title: 'Funktion' }] },
  { id: 's31', title: 'Erhaltung und Tourismus', content: 'Stonehenge besuchen über eine Million Menschen pro Jahr. Eine Straße verläuft in der Nähe — Lärm, Erschütterungen. Diskussion: Soll die Straße verlegt werden? Die Steine leiden unter Erosion. Gleichgewicht zwischen Zugänglichkeit und Erhalt — ein dauerhaftes Problem.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/tourism.jpg', title: 'Tourismus' }] },
  { id: 's32', title: 'Humor: «fliegende Untertassen»', content: 'In den 1960ern behaupteten Ufologen: Stonehenge sei eine Landeplattform für UFOs. Die Steine seien «magnetisiert». Wissenschaftler prüften — keine Anomalie. Aber Verschwörungstheorien sind hartnäckig: Im Internet findet man noch «Beweise».', duration: 3 },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-stone-8-1', text: 'Warum war Kenntnis der Sonnenwende für den Ackerbau wichtig?', type: 'multiple-choice', options: ['Sieht schön aus', 'Aussaat und Ernte planen', 'Nur für Rituale', 'Unwichtig'], correctAnswer: 1, explanation: 'Kalender — Planung der Feldarbeit.' },
    { id: 'q-stone-8-2', text: 'Wie viele Touristen besuchen Stonehenge pro Jahr?', type: 'multiple-choice', options: ['100.000', '500.000', 'Über eine Million', '10.000'], correctAnswer: 2, explanation: 'Über eine Million pro Jahr.' },
    { id: 'q-stone-8-3', text: 'War Stonehenge eine «UFO-Landeplattform»?', type: 'multiple-choice', options: ['Ja, bewiesen', 'Nein — ufologische Theorie', 'Vielleicht', 'Wissenschaftler haben nicht geprüft'], correctAnswer: 1, explanation: 'Geprüft — keine Anomalien.' }
  ]},
  { id: 's33', title: 'Kulturelles Erbe', content: 'Stonehenge — Symbol von Altertum, Geheimnis, «keltischem» Geist. Musik, Filme, Bücher. Die Realität — Jungsteinzeit, Ackerbau, Macht — ist weniger romantisch. Aber das Monument sagt: Menschen vor 5000 Jahren konnten Großes leisten.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/culture.jpg', title: 'Kultur' }] },
  { id: 's34', title: 'Fazit: Astronomie und Macht', content: 'Stonehenge — astronomische Präzision ohne Werkzeuge. Ausrichtung auf die Sonnenwenden. Der Bau — Arbeit von Tausenden, Koordination — Macht der Elite. Kalender, Rituale, Bestattungen — Himmelswissen als Instrument der Politik.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/summary.jpg', title: 'Fazit' }] },
  { id: 's35', title: 'Lehre für uns', content: 'Megaprojekte brauchen soziale Organisation. Jemand muss Menschen sammeln, sie ernähren, koordinieren. Stonehenge — eine Erinnerung: Hinter der «Magie» der Alten steht Pragmatik — Macht, Kalender, Ritual.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/lesson.jpg', title: 'Lehre' }] },
  { id: 's36', title: 'Schluss', content: 'Stonehenge — weder Rätsel von Außerirdischen noch «alte Druiden». Es ist ein Denkmal des neolithischen Britanniens: Astronomie, Macht, Organisation. Den Kontext verstehen ist wichtiger als Mythen.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/conclusion.jpg', title: 'Schluss' }] },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-stone-9-1', text: 'Was verdeckt die echte Geschichte von Stonehenge?', type: 'multiple-choice', options: ['Nichts', 'Mythen über Druiden, Außerirdische', 'Nur die Wissenschaft', 'Tourismus'], correctAnswer: 1, explanation: 'Mythen über Druiden, UFOs usw.' },
    { id: 'q-stone-9-2', text: 'Was verlangte ein Megaprojekt wie Stonehenge?', type: 'multiple-choice', options: ['Nur Steine', 'Soziale Organisation, Macht', 'Nur Astronomie', 'Nur Religion'], correctAnswer: 1, explanation: 'Koordination von Tausenden — Macht der Elite.' },
    { id: 'q-stone-9-3', text: 'Wer baute Stonehenge?', type: 'multiple-choice', options: ['Druiden', 'Außerirdische', 'Neolithische Gemeinschaften Britanniens', 'Römer'], correctAnswer: 2, explanation: 'Neolithische Gemeinschaften.' }
  ]},
  { id: 's37', title: 'Stonehenge und die Wissenschaft', content: 'Moderne Methoden — Dendrochronologie, Radiokohlenstoff, Lidar — verfeinern Daten und Struktur. Neue Funde verändern das Bild. Stonehenge — lebendige Archäologie. Weniger Rätsel, mehr Fragen.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/science.jpg', title: 'Wissenschaft' }] },
  { id: 's38', title: 'Mythos vs Realität', content: 'Mythos: Druiden, Magie, Außerirdische. Realität: Neolithische Bauern, astronomisches Wissen, soziale Hierarchie. Mythen zerstören — heißt nicht, dem Monument Geheimnis nehmen. Die echte Geschichte ist komplexer.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/myth-reality.jpg', title: 'Mythos und Realität' }] },
  { id: 's39', title: '5000 Jahre später', content: 'Stonehenge überstand den Wechsel der Epochen. Bronze, Eisen, Römer, Sachsen, Normannen, Moderne. Die Steine stehen. Was wollten die Bauherren sagen? Vielleicht: «Wir waren hier, wir kannten den Himmel, wir hatten Macht.»', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/5000-years.jpg', title: '5000 Jahre' }] },
  { id: 's40', title: 'Schlusswort', content: 'Stonehenge — ein Denkmal der Astronomie ohne Instrumente und der Macht ohne Kanone. Die Jungsteinzeit zeigte: Die Menschheit ist zu Megaprojekten fähig. Herauszufinden, wie — Aufgabe der Wissenschaft. Bewahren — Aufgabe der Gesellschaft.', duration: 3, media: [{ type: 'image', url: '/media/stonehenge-astronomy/final.jpg', title: 'Schlusswort' }] },
  { id: 'q10', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-stone-10-1', text: 'Hat Stonehenge den Wechsel der Epochen überstanden?', type: 'multiple-choice', options: ['Nein, es zerfiel', 'Ja — Bronze, Eisen, Römer, bis heute', 'Nur Jungsteinzeit', 'Nur Mittelalter'], correctAnswer: 1, explanation: 'Steht seit 5000 Jahren.' },
    { id: 'q-stone-10-2', text: 'Was nutzen moderne Archäologen?', type: 'multiple-choice', options: ['Nur Spaten', 'Radiokohlenstoff, Lidar, Dendrochronologie', 'Nur Vermutungen', 'Nur Dokumente'], correctAnswer: 1, explanation: 'Moderne Datierungsmethoden.' },
    { id: 'q-stone-10-3', text: 'Wer «las» den Himmel in der Jungsteinzeit?', type: 'multiple-choice', options: ['Niemand', 'Priester oder Anführer — Kalenderkontrolle', 'Nur Astronomen', 'Alle'], correctAnswer: 1, explanation: 'Die Elite kontrollierte das Wissen.' }
  ]}
]

export const stonehengeAstronomyFinalQuizDE: QuizBlock = {
  id: 'quiz-stonehenge-astronomy',
  title: 'Abschlussquiz: Stonehenge — Astronomie und Macht',
  questions: [
    { id: 'final-s1', text: 'Wann begann man mit dem Bau von Stonehenge?', type: 'multiple-choice', options: ['In der Eisenzeit', 'Um 3000 v. Chr.', 'Im Mittelalter', 'Im 18. Jh.'], correctAnswer: 1, explanation: 'Um 3000 v. Chr.' },
    { id: 'final-s2', text: 'Worauf ist die Achse ausgerichtet?', type: 'multiple-choice', options: ['Auf den Polarstern', 'Auf Sonnenaufgang zur Sommersonnenwende', 'Auf Vollmond', 'Auf Westen'], correctAnswer: 1, explanation: 'Auf Sonnenaufgang zur Sommersonnenwende.' },
    { id: 'final-s3', text: 'Haben Druiden Stonehenge gebaut?', type: 'multiple-choice', options: ['Ja', 'Nein — 2000 Jahre älter', 'Teilweise', 'Unbekannt'], correctAnswer: 1, explanation: '2000 Jahre älter als die Druiden.' },
    { id: 'final-s4', text: 'Woher kamen die Blausteine?', type: 'multiple-choice', options: ['Lokal', 'Aus Wales (Preseli)', 'Aus Irland', 'Aus Schottland'], correctAnswer: 1, explanation: 'Aus Wales — 250 km.' },
    { id: 'final-s5', text: 'Wie schwer war der größte Sarsen?', type: 'multiple-choice', options: ['5 Tonnen', '15 Tonnen', 'Bis 30 Tonnen', '100 Tonnen'], correctAnswer: 2, explanation: 'Bis 30 Tonnen.' },
    { id: 'final-s6', text: 'Wie viele Aubrey-Löcher?', type: 'multiple-choice', options: ['28', '42', '56', '100'], correctAnswer: 2, explanation: '56 Löcher.' },
    { id: 'final-s7', text: 'Wo lebten die Bauleute?', type: 'multiple-choice', options: ['In Stonehenge', 'In Durrington Walls', 'In Wales', 'Unbekannt'], correctAnswer: 1, explanation: 'Durrington Walls.' },
    { id: 'final-s8', text: 'Was fand man in Stonehenge?', type: 'multiple-choice', options: ['Nur Steine', 'Kremierte Überreste', 'Schatz', 'Nichts'], correctAnswer: 1, explanation: 'Kremierte Überreste.' },
    { id: 'final-s9', text: 'Restauriert im 20. Jh.?', type: 'multiple-choice', options: ['Nein', 'Ja, manche Steine', 'Nur Umzäunung', 'Komplett'], correctAnswer: 1, explanation: 'Manche Steine wurden aufgerichtet.' },
    { id: 'final-s10', text: 'Woher kamen die Sarsen?', type: 'multiple-choice', options: ['Aus Wales', 'Von den Marlborough Downs, 30 km', 'Aus Irland', 'Vollständig lokal'], correctAnswer: 1, explanation: 'Marlborough Downs — 30 km.' },
    { id: 'final-s11', text: 'Wie sind die Steine verbunden?', type: 'multiple-choice', options: ['Aufliegend', '«Verzapft»', 'Verklebt', 'Einfach stehend'], correctAnswer: 1, explanation: 'Zapfen in Nuten.' },
    { id: 'final-s12', text: 'Wer kommt zur Sonnenwende?', type: 'multiple-choice', options: ['Nur Wissenschaftler', 'Tausende, Druiden', 'Niemand', 'Nur Einheimische'], correctAnswer: 1, explanation: 'Tausende Menschen, Druiden.' },
    { id: 'final-s13', text: 'Wo liegt Avebury?', type: 'multiple-choice', options: ['In Wales', '40 km von Stonehenge', 'In Irland', 'In Schottland'], correctAnswer: 1, explanation: '40 km.' },
    { id: 'final-s14', text: 'Wie viele Menschen bewegten einen 30-Tonnen-Stein?', type: 'multiple-choice', options: ['20', '100', 'Etwa 200', '1000'], correctAnswer: 2, explanation: 'Etwa 200.' },
    { id: 'final-s15', text: 'Warum bedeutet Kenntnis der Sonnenwende = Macht?', type: 'multiple-choice', options: ['Sieht schön aus', 'Kontrolle des Kalenders', 'Nur Ritual', 'Keine Macht'], correctAnswer: 1, explanation: 'Kalenderkontrolle.' },
    { id: 'final-s16', text: 'Ist Stonehenge UNESCO-Welterbe?', type: 'multiple-choice', options: ['Nein', 'Ja', 'Nur in Britannien', 'Gestrichen'], correctAnswer: 1, explanation: 'In der UNESCO-Liste.' },
    { id: 'final-s17', text: 'Wie viele Touristen pro Jahr?', type: 'multiple-choice', options: ['100.000', '500.000', 'Über eine Million', '10.000'], correctAnswer: 2, explanation: 'Über eine Million.' },
    { id: 'final-s18', text: 'Wer baute Stonehenge?', type: 'multiple-choice', options: ['Druiden', 'Außerirdische', 'Neolithische Gemeinschaften', 'Römer'], correctAnswer: 2, explanation: 'Neolithische Gemeinschaften.' },
    { id: 'final-s19', text: 'Was verlangte das Megaprojekt?', type: 'multiple-choice', options: ['Nur Steine', 'Soziale Organisation', 'Nur Astronomie', 'Nur Religion'], correctAnswer: 1, explanation: 'Koordination von Tausenden.' },
    { id: 'final-s20', text: 'Was umgibt Stonehenge?', type: 'multiple-choice', options: ['Nur Feld', 'Hunderte Grabhügel', 'Wald', 'Dorf'], correctAnswer: 1, explanation: 'Grabhügel — Elitegräber.' },
    { id: 'final-s21', text: 'Welcher Stein markiert den Sonnenaufgang?', type: 'multiple-choice', options: ['Sarsen', 'Fersenstein', 'Blaustein', 'Aubrey-Loch'], correctAnswer: 1, explanation: 'Der Fersenstein (Heel Stone).' },
    { id: 'final-s22', text: 'Wie lange wurde gebaut?', type: 'multiple-choice', options: ['10 Jahre', '100 Jahre', 'Etwa 1500 Jahre', '50 Jahre'], correctAnswer: 2, explanation: '1500 Jahre in mehreren Phasen.' },
    { id: 'final-s23', text: 'Was erforscht die Archeoastronomie?', type: 'multiple-choice', options: ['Nur Sterne', 'Astronomisches Wissen der Alten', 'Nur die Sonne', 'Nur den Mond'], correctAnswer: 1, explanation: 'Astronomisches Wissen der Alten.' },
    { id: 'final-s24', text: 'War Stonehenge eine «UFO-Landeplattform»?', type: 'multiple-choice', options: ['Ja', 'Nein — ufologische Theorie', 'Vielleicht', 'Nicht geprüft'], correctAnswer: 1, explanation: 'Geprüft — keine Anomalien.' },
    { id: 'final-s25', text: 'Was zeigen die Funde in Gräbern?', type: 'multiple-choice', options: ['Nur Lokales', 'Dinge aus fernen Landen', 'Nichts', 'Nur Waffen'], correctAnswer: 1, explanation: 'Handel, Elite.' },
    { id: 'final-s26', text: 'Wer «las» den Himmel in der Jungsteinzeit?', type: 'multiple-choice', options: ['Niemand', 'Priester oder Anführer', 'Nur Astronomen', 'Alle'], correctAnswer: 1, explanation: 'Die Elite kontrollierte den Kalender.' },
    { id: 'final-s27', text: 'Wie viele km von Wales bis Stonehenge?', type: 'multiple-choice', options: ['50', '100', 'Etwa 250', '500'], correctAnswer: 2, explanation: 'Etwa 250 km.' },
    { id: 'final-s28', text: 'Was verdeckt die echte Geschichte?', type: 'multiple-choice', options: ['Nichts', 'Mythen über Druiden, UFOs', 'Nur Wissenschaft', 'Tourismus'], correctAnswer: 1, explanation: 'Mythen über Druiden, Außerirdische.' },
    { id: 'final-s29', text: 'Welche Methoden nutzen Archäologen?', type: 'multiple-choice', options: ['Nur Spaten', 'Radiokohlenstoff, Lidar', 'Nur Vermutungen', 'Nur Dokumente'], correctAnswer: 1, explanation: 'Radiokohlenstoff, Lidar.' },
    { id: 'final-s30', text: 'Wie lange steht Stonehenge?', type: 'multiple-choice', options: ['1000', '2000', 'Etwa 5000', '10000'], correctAnswer: 2, explanation: 'Etwa 5000 Jahre.' }
  ]
}
