import { Slide, QuizBlock } from '../types/session'

// Deutsche Übersetzungen (B1-B2): Wikinger — Sklavenhandel und Silber
export const vikingsTradeSlidesDE: Slide[] = [
  { id: 'v1', title: 'Wikinger — nicht nur Krieger, sondern Händler', content: 'Wikinger in Filmen — Berserker mit Äxten. Die Realität: Sie waren Händler. Ihre Schiffe trugen nicht nur Waffen, sondern Waren — Pelze, Bernstein, Honig, Wachs. Die Hauptware — Sklaven. Ein Raubzug lohnte sich, wenn man Menschen gefangen hatte. Handel wichtiger als Krieg.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/viking-ship.jpg', title: 'Wikingerschiff' }] },
  { id: 'v2', title: 'Sklaven — Hauptware', content: 'Das mittelalterliche Europa — ein Sklavenmarkt. Wikinger fingen Slawen, Angelsachsen, Iren, Franken. Sklaven kosteten 3–12 Unzen Silber. Ein erfolgreicher Raubzug = 50–200 Sklaven. Gewinn — Hunderte Unzen Silber. Sklavenhandel finanzierte die Wikinger.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/slave-market.jpg', title: 'Sklavenmarkt' }] },
  { id: 'v3', title: 'Wort «Sklave» von «Slawe»', content: 'Lateinisch «sclavus» (Sklave) — von «Slawe». Wikinger und Franken fingen Slawen Osteuropas und verkauften sie nach Süden — nach Byzanz und in arabische Länder. Slawen — Massenware des 9.–10. Jh. Die Etymologie des Wortes — Spur des Sklavenhandels.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/etymology.jpg', title: 'Etymologie' }] },
  { id: 'v4', title: 'Haithabu und Birka — Sklavenhandelszentren', content: 'Haithabu (Dänemark) und Birka (Schweden) — größte Handelsstädte der Wikinger. Dort gab es Sklavenmärkte. Archäologen fanden Ketten, Fesseln, Käfige. Sklaven kamen aus West und Ost, wurden in Skandinavien und weiter südlich verkauft.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/hedeby.jpg', title: 'Haithabu' }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-viking-1-1', text: 'Was war die Hauptware der Wikinger?', type: 'multiple-choice', options: ['Pelze', 'Sklaven', 'Bernstein', 'Waffen'], correctAnswer: 1, explanation: 'Sklaven — Hauptware, größter Gewinn.' },
    { id: 'q-viking-1-2', text: 'Woher kommt das Wort «Sklave» (sclavus)?', type: 'multiple-choice', options: ['Von «Arbeit»', 'Von «Slawe»', 'Von «Verwundeter»', 'Von «Arbeiter»'], correctAnswer: 1, explanation: 'Sclavus — von «Slawe», Spur des Sklavenhandels.' },
    { id: 'q-viking-1-3', text: 'Welche Städte waren Sklavenhandelszentren?', type: 'multiple-choice', options: ['London und Paris', 'Haithabu und Birka', 'Rom und Konstantinopel', 'Bagdad und Kairo'], correctAnswer: 1, explanation: 'Haithabu und Birka — Handelszentren.' }
  ]},
  { id: 'v5', title: 'Humor: Sklave teurer als Kuh', content: 'Ein Sklave kostete 3–12 Unzen Silber. Eine Kuh — 1 Unze. Sklave = 3–12 Kühe. Ein guter Arbeiter kostete mehr als Vieh. Wikinger rechneten: «Warum eine Kuh stehlen, wenn man einen Menschen nehmen kann?» Kalte Ökonomie der Raubzüge.', duration: 3 },
  { id: 'v6', title: 'Silber — Währung der Wikinger', content: 'Wikinger prägten bis zum 10. Jh. keine Münzen. Währung — Silber nach Gewicht. Stücke arabischer Dirhems, byzantinischer Solidi, fränkischer Denare. Waage und Gewichte — Pflicht für Händler. Silber = Geld. Raubzüge = Silbergewinnung.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/silver.jpg', title: 'Silber' }] },
  { id: 'v7', title: 'Wolga-Weg — Silber aus Bagdad', content: 'Wikinger (in Russland — Waräger) fuhren die Wolga hinab zum Kaspischen Meer, handelten mit Chasarien und weiter — mit der arabischen Welt. Araber zahlten mit Silber-Dirhems. Tausende Dirhems fand man in Skandinavien. Der Weg «von den Warägern zu den Arabern» — Silberader des 9.–10. Jh.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/volga-route.jpg', title: 'Wolga-Weg' }] },
  { id: 'v8', title: 'Dirhems in skandinavischen Schätzen', content: 'In Schweden fand man über 80.000 arabische Dirhems. In Dänemark, Norwegen — Tausende. Schätze wurden vergraben — «Bank» des Wikingers. Münzen aus dem 8.–10. Jh. aus Bagdad, Samarkand, Buchara. Handel mit dem Osten bereicherte Skandinavien.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/dirhems.jpg', title: 'Dirhems' }] },
  { id: 'v9', title: 'Sklaven nach Osten — Silber nach Westen', content: 'Wikinger fingen Slawen und Balten, brachten sie über Wolga und Dnjepr, verkauften sie in Chasarien, Bagdad, Byzanz. Bekamen Silber. Brachten es nach Skandinavien. Sklavenhandel = Silberimport. Ökonomie einfach: Menschen gegen Metall.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/trade-route.jpg', title: 'Handelswege' }] },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-viking-2-1', text: 'Welche Währung hatten Wikinger?', type: 'multiple-choice', options: ['Goldmünzen', 'Silber nach Gewicht', 'Kupferbarren', 'Pelze'], correctAnswer: 1, explanation: 'Silber nach Gewicht — Münzstücke gewogen.' },
    { id: 'q-viking-2-2', text: 'Woher kam das Silber in Skandinavien?', type: 'multiple-choice', options: ['Aus lokalen Minen', 'Aus der arabischen Welt (Bagdad)', 'Aus China', 'Aus Afrika'], correctAnswer: 1, explanation: 'Arabische Dirhems — über den Wolga-Weg.' },
    { id: 'q-viking-2-3', text: 'Wie viele Dirhems fand man in Schweden?', type: 'multiple-choice', options: ['100', '1.000', '10.000', 'Über 80.000'], correctAnswer: 3, explanation: 'Über 80.000 arabische Münzen.' }
  ]},
  { id: 'v10', title: 'Dublin — Sklavenmarkt', content: 'Dublin wurde 841 von Wikingern gegründet. Es war der größte Sklavenmarkt Nordeuropas. Wikinger fingen Iren, Schotten, Angelsachsen, brachten sie nach Dublin, verkauften sie weiter. Dublin = Hauptstadt des Sklavenhandels im 9.–10. Jh.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/dublin.jpg', title: 'Dublin' }] },
  { id: 'v11', title: 'Überfall auf Lindisfarne — Beginn der Ära', content: '793: Wikinger überfielen das Kloster Lindisfarne (England). Schätze gestohlen, Mönche getötet oder gefangen. Chroniken: «Heiden entweihten das Heiligtum.» Realität: Es war ein Handels-Raub-Feldzug. Klöster — leichte Beute, Reichtum ohne Armee.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/lindisfarne.jpg', title: 'Lindisfarne' }] },
  { id: 'v12', title: 'Klöster — Banken des Mittelalters', content: 'Klöster bewahrten Gold, Silber, Schmuck, Reliquien. Schutz schwach — Mönche waren keine Krieger. Wikinger wussten: Kloster = Tresor ohne Schloss. Klosterüberfälle — kein «Krieg gegen Christentum», sondern Bankraub.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/monastery.jpg', title: 'Kloster' }] },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-viking-3-1', text: 'Wann gründeten Wikinger Dublin?', type: 'multiple-choice', options: ['700', '793', '841', '900'], correctAnswer: 2, explanation: 'Dublin gegründet 841.' },
    { id: 'q-viking-3-2', text: 'Welches Kloster — Symbol des Beginns der Raubzüge?', type: 'multiple-choice', options: ['Rom', 'Lindisfarne', 'Paris', 'Canterbury'], correctAnswer: 1, explanation: 'Lindisfarne, 793 — erster großer Überfall.' },
    { id: 'q-viking-3-3', text: 'Warum plünderten Wikinger Klöster?', type: 'multiple-choice', options: ['Hass auf Christen', 'Leichte Beute — Reichtum ohne Armee', 'Befehl der Könige', 'Zufall'], correctAnswer: 1, explanation: 'Klöster = Tresore ohne Schutz.' }
  ]},
  { id: 'v13', title: 'Humor: «Danegeld» — Lösegeld an Wikinger', content: 'Angelsachsen zahlten «Danegeld» — Tribut an Wikinger, damit diese nicht plünderten. Hunderte Pfund Silber. Aber Wikinger kamen zurück: «Wenn sie zahlen — gibt es mehr.» Danegeld stoppte Raubzüge nicht, sondern förderte sie. Erpressung funktionierte.', duration: 3 },
  { id: 'v14', title: 'Weg «von den Warägern zu den Griechen»', content: 'Wikinger fuhren den Dnjepr von der Ostsee zum Schwarzen Meer hinab, erreichten Konstantinopel. Handel mit Pelzen, Wachs, Honig, Sklaven. Byzanz zahlte mit Gold und Silber. Der Weg funktionierte im 9.–12. Jh. Grundlage des Reichtums der Kiewer Rus.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/route-greeks.jpg', title: 'Weg zu den Griechen' }] },
  { id: 'v15', title: 'Konstantinopel — Sklavenmarkt', content: 'Byzanz — größter Sklavenkäufer. Wikinger brachten Slawen, Balten, Gefangene. In Konstantinopel gab es einen riesigen Markt. Preise hoch — Nachfrage groß. Sklaven gingen in Haushalte, auf Galeeren, in Harems. Byzanz — Endpunkt des «Wegs zu den Griechen».', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/constantinople.jpg', title: 'Konstantinopel' }] },
  { id: 'v16', title: 'Warägergarde — von Räubern zu Söldnern', content: 'Waräger (Skandinavier) dienten ab dem 10. Jh. in der byzantinischen Armee. Warägergarde — Elite-Söldner des Kaisers. Bezahlt mit Gold. Manche Wikinger bevorzugten Dienst statt Raub — stabiles Gehalt. Harald der Harte diente in der Garde, wurde dann König Norwegens.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/varangian-guard.jpg', title: 'Warägergarde' }] },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-viking-4-1', text: 'Was ist «Danegeld»?', type: 'multiple-choice', options: ['Schiffsname', 'Tribut der Angelsachsen an Wikinger', 'Waffenart', 'Handelsvertrag'], correctAnswer: 1, explanation: 'Lösegeld, damit Wikinger nicht plünderten.' },
    { id: 'q-viking-4-2', text: 'Wohin führte der Weg zu den Griechen?', type: 'multiple-choice', options: ['Nach Rom', 'Nach Konstantinopel', 'Nach Bagdad', 'Nach Kairo'], correctAnswer: 1, explanation: 'Den Dnjepr nach Konstantinopel.' },
    { id: 'q-viking-4-3', text: 'Was ist die Warägergarde?', type: 'multiple-choice', options: ['Wikinger-Räuber', 'Elite-Söldner von Byzanz', 'Händler', 'Piraten'], correctAnswer: 1, explanation: 'Söldner des byzantinischen Kaisers.' }
  ]},
  { id: 'v17', title: 'Sklaven in Skandinavien — «Thralls»', content: 'Wikinger hielten Sklaven zu Hause — «Thralls». Sie arbeiteten auf Höfen, im Haushalt. Status niedrigste — fast wie Vieh. Kinder von Thralls — auch Sklaven. Freilassung selten. Skandinavische Gesellschaft: Freie (Karle), Adel (Jarle), Sklaven (Thralls).', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/thralls.jpg', title: 'Thralls' }] },
  { id: 'v18', title: 'Sklavenpreis — 3–12 Unzen Silber', content: 'Kind — 3 Unzen, erwachsener Arbeiter — 8 Unzen, Spezialist (Schmied) — 12 Unzen. Zum Vergleich: Schwert — 16 Unzen, Kuh — 1 Unze. Sklave = teure Ware, aber rentabel. Wikinger rechneten Gewinn.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/prices.jpg', title: 'Preise' }] },
  { id: 'v19', title: 'Humor: «Sklave floh — kauf einen neuen»', content: 'Sklaven flohen manchmal. Aber einfangen schwer — Wikinger verschwendeten keine Zeit. Einfacher, einen neuen auf dem Markt zu kaufen. Sklavenhandel so aktiv, dass «Ersatzteile» immer verfügbar waren. Mensch als Ware — kalte Logik.', duration: 3 },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-viking-5-1', text: 'Wie nannten man Sklaven in Skandinavien?', type: 'multiple-choice', options: ['Karle', 'Thralls', 'Jarle', 'Bonde'], correctAnswer: 1, explanation: 'Thralls — Sklaven.' },
    { id: 'q-viking-5-2', text: 'Was kostete ein erwachsener Sklave?', type: 'multiple-choice', options: ['1 Unze', '3 Unzen', '8 Unzen', '20 Unzen'], correctAnswer: 2, explanation: 'Erwachsener Arbeiter — 8 Unzen Silber.' },
    { id: 'q-viking-5-3', text: 'Was kostete eine Kuh?', type: 'multiple-choice', options: ['1 Unze', '5 Unzen', '10 Unzen', '20 Unzen'], correctAnswer: 0, explanation: 'Kuh — 1 Unze Silber.' }
  ]},
  { id: 'v20', title: 'Große Heidenarmee — Plünderung Englands', content: '865: Die «Große Heidenarmee» der Wikinger fiel in England ein. Nicht nur ein Raubzug — Eroberung. Sie nahmen York, Ostanglien. Ziel: Land, Silber, Sklaven. Angelsächsische Königreiche zahlten Danegeld, aber Wikinger blieben, gründeten Danelaw — Wikingergebiet in England.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/great-army.jpg', title: 'Große Armee' }] },
  { id: 'v21', title: 'Danelaw — skandinavisches England', content: 'Danelaw — Ost- und Nordengland unter Wikingerherrschaft (9.–10. Jh.). Skandinavische Gesetze, Sprache, Handel. York (Jorvik) — Wikingerhauptstadt. Dort war ein Sklavenmarkt. Die englische Sprache nahm Hunderte skandinavischer Wörter aus Danelaw auf.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/danelaw.jpg', title: 'Danelaw' }] },
  { id: 'v22', title: 'York (Jorvik) — Handelszentrum', content: 'York unter Wikingern — Jorvik. Bevölkerung 10.000 — riesige Stadt für die Zeit. Markt, Handwerk, Handel. Archäologen fanden Spuren des Sklavenhandels: Ketten, Fesseln, fremde Münzen. Jorvik = Wirtschaftszentrum von Danelaw.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/york.jpg', title: 'York' }] },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-viking-6-1', text: 'Wann fiel die Große Heidenarmee ein?', type: 'multiple-choice', options: ['793', '841', '865', '900'], correctAnswer: 2, explanation: '865 — Einfall in England.' },
    { id: 'q-viking-6-2', text: 'Was ist Danelaw?', type: 'multiple-choice', options: ['Schiff', 'Wikingergebiet in England', 'Münze', 'Waffe'], correctAnswer: 1, explanation: 'Danelaw — Gebiet unter skandinavischem Recht.' },
    { id: 'q-viking-6-3', text: 'Wie nannten Wikinger York?', type: 'multiple-choice', options: ['Londinium', 'Jorvik', 'Haithabu', 'Birka'], correctAnswer: 1, explanation: 'Jorvik — skandinavischer Name.' }
  ]},
  { id: 'v23', title: 'Ibn Fadlan — arabischer Zeuge', content: '922: Der arabische Diplomat Ibn Fadlan traf Wikinger (Rus) an der Wolga. Er beschrieb sie: «Schmutzig, aber reich. Handeln mit Sklaven. Bringen Götzen Opfer.» Seine Aufzeichnungen — einzigartiges Zeugnis über Wikingerhandel im Osten.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/ibn-fadlan.jpg', title: 'Ibn Fadlan' }] },
  { id: 'v24', title: 'Häuptlingsbegräbnis — Sklavin lebendig verbrannt', content: 'Ibn Fadlan beschrieb das Begräbnis eines Rus-Häuptlings. Eine Sklavin wurde getötet, um den Herrn ins Jenseits zu «begleiten». Auf einem Schiff mit ihm verbrannt. Grausames Ritual, aber es zeigt: Sklaven = Eigentum, das man selbst nach dem Tod des Besitzers «verwenden» kann.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/funeral.jpg', title: 'Begräbnis' }] },
  { id: 'v25', title: 'Humor: «ich bin sauberer als Götzen» — Wikinger und Hygiene', content: 'Ibn Fadlan schrieb: «Sie sind die schmutzigsten Geschöpfe Allahs. Waschen sich nicht nach Essen und Notdurft, wie Esel.» Aber Archäologie zeigt: Wikinger wuschen sich öfter als Europäer (Bäder, Kämme). Dem Araber erschien es schmutzig — unterschiedliche Standards. Kulturschock wirkt beidseitig.', duration: 3 },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-viking-7-1', text: 'Wer war Ibn Fadlan?', type: 'multiple-choice', options: ['Wikinger', 'Arabischer Diplomat', 'Byzantinischer Kaiser', 'Slawischer Fürst'], correctAnswer: 1, explanation: 'Arabischer Diplomat, traf Wikinger an der Wolga.' },
    { id: 'q-viking-7-2', text: 'Was taten sie mit der Sklavin beim Begräbnis?', type: 'multiple-choice', options: ['Freilassen', 'Töten und mit ihm verbrennen', 'Verkaufen', 'Freilassen'], correctAnswer: 1, explanation: 'Getötet — «begleiten» ins Jenseits.' },
    { id: 'q-viking-7-3', text: 'Was schrieb Ibn Fadlan über Wikinger-Hygiene?', type: 'multiple-choice', options: ['Sehr sauber', 'Am schmutzigsten', 'Durchschnittlich', 'Erwähnte nicht'], correctAnswer: 1, explanation: 'Nannte sie schmutzig — Kulturschock.' }
  ]},
  { id: 'v26', title: 'Pelze — zweitwichtigste Ware', content: 'Nach Sklaven — Pelze. Zobel, Marder, Biber, Fuchs. Skandinavien und Russland — Pelzquelle. Nachfrage in Europa und im Osten riesig. Pelze = Währung und Luxus. Wikinger handelten mit Pelzen gleichrangig mit Sklaven. Aber Sklaven waren profitabler.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/furs.jpg', title: 'Pelze' }] },
  { id: 'v27', title: 'Bernstein — «Gold des Nordens»', content: 'Bernstein von den Ostseeküsten war seit römischen Zeiten geschätzt. Wikinger handelten Bernstein nach Süden — nach Byzanz, Bagdad. Machten Schmuck, Amulette. Bernstein leicht, teuer, kompakt — ideale Handelsware. Aber wieder: Sklaven profitabler.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/amber.jpg', title: 'Bernstein' }] },
  { id: 'v28', title: 'Ende des Sklavenhandels — Christianisierung', content: '10.–11. Jh.: Skandinavien nimmt Christentum an. Die Kirche verbot Handel mit Christen. Sklavenhandel verschwand nicht, schrumpfte aber. Bis zum 12. Jh. war der Sklavenhandel aus Skandinavien fast beendet. Wirtschaft änderte sich — Wikinger wurden christliche Königreiche.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/christianization.jpg', title: 'Christianisierung' }] },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-viking-8-1', text: 'Was war die zweitwichtigste Ware?', type: 'multiple-choice', options: ['Waffen', 'Pelze', 'Getreide', 'Wein'], correctAnswer: 1, explanation: 'Pelze — nach Sklaven.' },
    { id: 'q-viking-8-2', text: 'Woher kam Bernstein?', type: 'multiple-choice', options: ['Aus Afrika', 'Von Ostseeküsten', 'Aus Indien', 'Aus China'], correctAnswer: 1, explanation: 'Ostsee — Bernsteinquelle.' },
    { id: 'q-viking-8-3', text: 'Was stoppte den Sklavenhandel?', type: 'multiple-choice', options: ['Krieg', 'Christianisierung', 'Pest', 'Hunger'], correctAnswer: 1, explanation: 'Kirche verbot Handel mit Christen.' }
  ]},
  { id: 'v29', title: 'Erbe: Wörter, Gene, Handelswege', content: 'Wikinger hinterließen Spuren. Englische Sprache: sky, knife, law, they — skandinavische Wörter. DNA: In Irland, Schottland, Island — skandinavische Gene. Handelswege: Wolga, Dnjepr — Basis mittelalterlichen Handels. Sklavenhandel endete, aber Erbe blieb.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/legacy.jpg', title: 'Erbe' }] },
  { id: 'v30', title: 'Humor: Wikinger in Amerika — auch dort Handel', content: 'Wikinger erreichten Amerika (Vinland, ca. 1000). Trafen Einheimische — Skrælingar. Versuchten zu handeln. Chroniken: «Skrælingar verstehen den Wert von Pelzen nicht.» Handel scheiterte — Wikinger gingen. Selbst in der Neuen Welt versuchten sie Geschäfte zu machen.', duration: 3 },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-viking-9-1', text: 'Welche Wörter im Englischen von Wikingern?', type: 'multiple-choice', options: ['Sky, knife, law', 'Cat, dog, house', 'Sun, moon, star', 'King, queen, prince'], correctAnswer: 0, explanation: 'Sky, knife, law, they — skandinavisch.' },
    { id: 'q-viking-9-2', text: 'Wo hinterließen Wikinger Gene?', type: 'multiple-choice', options: ['Nur Skandinavien', 'Irland, Schottland, Island', 'Nur Afrika', 'Nur Asien'], correctAnswer: 1, explanation: 'Irland, Schottland, Island — skandinavische Gene.' },
    { id: 'q-viking-9-3', text: 'Wie nannten Wikinger Amerika?', type: 'multiple-choice', options: ['Neue Welt', 'Vinland', 'Grönland', 'Island'], correctAnswer: 1, explanation: 'Vinland — «Weinland».' }
  ]},
  { id: 'v31', title: 'Ökonomie der Raubzüge: Risiko und Gewinn', content: 'Raubzug = Investition. Schiff, Mannschaft, Vorräte — Kosten. Gewinn — Silber, Waren, Sklaven. Ein erfolgreicher Zug zahlte sich ein Jahr lang aus. Erfolgloser — Tod. Wikinger rechneten Risiken. Raub = Geschäft mit hohem Risiko und hohem Gewinn.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/raid-economy.jpg', title: 'Ökonomie der Raubzüge' }] },
  { id: 'v32', title: 'Warum begannen Wikinger Raubzüge?', content: '8. Jh.: Überbevölkerung Skandinaviens, wenig Land, hartes Klima. Junge Männer ohne Erbe suchten Reichtum. Schiffe wurden besser — Fernfahrten möglich. Europa reich, Schutz schwach. Raubzüge = Ausweg aus Armut. Wirtschaft trieb sie aufs Meer.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/reasons.jpg', title: 'Gründe' }] },
  { id: 'v33', title: 'Fazit: Sklavenhandel = Wikingerökonomie', content: 'Wikinger — nicht nur Krieger. Sie waren Händler, Sklavenhändler, Vermittler. Sklaven — Hauptware, Silber — Hauptwährung. Raubzüge finanziert durch Sklavenhandel. Wege Wolga und Dnjepr — Handelsadern. Christianisierung stoppte es, aber 200 Jahre kontrollierten Wikinger den Sklavenhandel des Nordens.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/summary.jpg', title: 'Fazit' }] },
  { id: 'q10', title: 'Quiz', content: '', duration: 2, questions: [
    { id: 'q-viking-10-1', text: 'Was war ein Raubzug für Wikinger?', type: 'multiple-choice', options: ['Krieg', 'Investition mit Risiko und Gewinn', 'Sport', 'Religion'], correctAnswer: 1, explanation: 'Raubzug = Geschäft mit hohem Risiko.' },
    { id: 'q-viking-10-2', text: 'Warum begannen Wikinger Raubzüge?', type: 'multiple-choice', options: ['Langeweile', 'Überbevölkerung, Armut, bessere Schiffe', 'Götterbefehl', 'Zufall'], correctAnswer: 1, explanation: 'Wirtschaftliche Gründe — Armut, wenig Land.' },
    { id: 'q-viking-10-3', text: 'Was stoppte Wikinger-Sklavenhandel?', type: 'multiple-choice', options: ['Krieg', 'Christianisierung', 'Pest', 'Klima'], correctAnswer: 1, explanation: 'Kirche verbot Handel mit Christen.' }
  ]},
  { id: 'v34', title: 'Wikinger heute — Romantik vs Realität', content: 'Filme: Wikinger — edle Krieger. Realität: Sklavenhändler und Geschäftsleute. Raubzüge — kein Heldentum, sondern Raub. Sklavenhandel — Wirtschaftsbasis. Romantisierung verdeckt Wahrheit. Wikinger verstehen = mittelalterliche Wirtschaft verstehen.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/modern.jpg', title: 'Heute' }] },
  { id: 'v35', title: 'Schluss: Handel, Silber, Sklaven', content: 'Wikinger bauten ein Handelsimperium auf Sklavenhandel und Silber. Wolga-Weg, Weg zu den Griechen, Danelaw, Dublin — alles Wirtschaft. Sklaven nach Süden, Silber nach Norden. Christianisierung beendete es, aber 200 Jahre waren Wikinger Schlüsselglied im europäischen Sklavenhandel. Geschichte ohne Beschönigung.', duration: 3, media: [{ type: 'image', url: '/media/vikings-trade/conclusion.jpg', title: 'Schluss' }] }
]

export const vikingsTradeFinalQuizDE: QuizBlock = {
  id: 'quiz-vikings-trade',
  title: 'Abschlussquiz: Wikinger — Sklavenhandel und Silber',
  questions: [
    { id: 'final-v1', text: 'Was war die Hauptware der Wikinger?', type: 'multiple-choice', options: ['Pelze', 'Sklaven', 'Bernstein', 'Waffen'], correctAnswer: 1, explanation: 'Sklaven — größter Gewinn.' },
    { id: 'final-v2', text: 'Woher kommt «Sklave»?', type: 'multiple-choice', options: ['Von «Arbeit»', 'Von «Slawe»', 'Von «Verwundet»', 'Von «Arbeiter»'], correctAnswer: 1, explanation: 'Sclavus — von «Slawe».' },
    { id: 'final-v3', text: 'Welche Städte Sklavenhandelszentren?', type: 'multiple-choice', options: ['London', 'Haithabu und Birka', 'Rom', 'Bagdad'], correctAnswer: 1, explanation: 'Haithabu und Birka.' },
    { id: 'final-v4', text: 'Welche Währung?', type: 'multiple-choice', options: ['Gold', 'Silber nach Gewicht', 'Kupfer', 'Pelze'], correctAnswer: 1, explanation: 'Silber nach Gewicht.' },
    { id: 'final-v5', text: 'Woher Silber?', type: 'multiple-choice', options: ['Minen', 'Bagdad (Dirhems)', 'China', 'Afrika'], correctAnswer: 1, explanation: 'Arabische Dirhems über Wolga.' },
    { id: 'final-v6', text: 'Wie viele Dirhems in Schweden?', type: 'multiple-choice', options: ['100', '1.000', '10.000', 'Über 80.000'], correctAnswer: 3, explanation: 'Über 80.000 Münzen.' },
    { id: 'final-v7', text: 'Wann Dublin gegründet?', type: 'multiple-choice', options: ['700', '793', '841', '900'], correctAnswer: 2, explanation: 'Dublin 841.' },
    { id: 'final-v8', text: 'Lindisfarne — was?', type: 'multiple-choice', options: ['Stadt', 'Kloster — erster Überfall', 'Schiff', 'Münze'], correctAnswer: 1, explanation: 'Kloster, 793.' },
    { id: 'final-v9', text: 'Was ist Danegeld?', type: 'multiple-choice', options: ['Schiff', 'Tribut an Wikinger', 'Waffe', 'Münze'], correctAnswer: 1, explanation: 'Lösegeld.' },
    { id: 'final-v10', text: 'Wohin Weg zu Griechen?', type: 'multiple-choice', options: ['Rom', 'Konstantinopel', 'Bagdad', 'Kairo'], correctAnswer: 1, explanation: 'Dnjepr nach Konstantinopel.' },
    { id: 'final-v11', text: 'Was ist Warägergarde?', type: 'multiple-choice', options: ['Räuber', 'Söldner Byzanz', 'Händler', 'Piraten'], correctAnswer: 1, explanation: 'Elite-Söldner.' },
    { id: 'final-v12', text: 'Wie hießen Sklaven?', type: 'multiple-choice', options: ['Karle', 'Thralls', 'Jarle', 'Bonde'], correctAnswer: 1, explanation: 'Thralls.' },
    { id: 'final-v13', text: 'Sklavenpreis?', type: 'multiple-choice', options: ['1 Unze', '3 Unzen', '8 Unzen', '20 Unzen'], correctAnswer: 2, explanation: '8 Unzen Silber.' },
    { id: 'final-v14', text: 'Kuhpreis?', type: 'multiple-choice', options: ['1 Unze', '5 Unzen', '10 Unzen', '20 Unzen'], correctAnswer: 0, explanation: '1 Unze.' },
    { id: 'final-v15', text: 'Wann Große Armee?', type: 'multiple-choice', options: ['793', '841', '865', '900'], correctAnswer: 2, explanation: '865.' },
    { id: 'final-v16', text: 'Was ist Danelaw?', type: 'multiple-choice', options: ['Schiff', 'Wikingergebiet England', 'Münze', 'Waffe'], correctAnswer: 1, explanation: 'Gebiet unter skandinavischem Recht.' },
    { id: 'final-v17', text: 'York bei Wikingern?', type: 'multiple-choice', options: ['Londinium', 'Jorvik', 'Haithabu', 'Birka'], correctAnswer: 1, explanation: 'Jorvik.' },
    { id: 'final-v18', text: 'Ibn Fadlan?', type: 'multiple-choice', options: ['Wikinger', 'Arabischer Diplomat', 'Kaiser', 'Fürst'], correctAnswer: 1, explanation: 'Diplomat an Wolga.' },
    { id: 'final-v19', text: 'Sklavin beim Begräbnis?', type: 'multiple-choice', options: ['Freigelassen', 'Getötet und verbrannt', 'Verkauft', 'Befreit'], correctAnswer: 1, explanation: 'Getötet — «Begleitung».' },
    { id: 'final-v20', text: 'Zweite Ware?', type: 'multiple-choice', options: ['Waffen', 'Pelze', 'Getreide', 'Wein'], correctAnswer: 1, explanation: 'Pelze.' },
    { id: 'final-v21', text: 'Bernstein woher?', type: 'multiple-choice', options: ['Afrika', 'Ostsee', 'Indien', 'China'], correctAnswer: 1, explanation: 'Ostseeküsten.' },
    { id: 'final-v22', text: 'Was stoppte Handel?', type: 'multiple-choice', options: ['Krieg', 'Christianisierung', 'Pest', 'Hunger'], correctAnswer: 1, explanation: 'Kirche verbot.' },
    { id: 'final-v23', text: 'Englische Wörter?', type: 'multiple-choice', options: ['Sky, knife, law', 'Cat, dog', 'Sun, moon', 'King, queen'], correctAnswer: 0, explanation: 'Sky, knife, law, they.' },
    { id: 'final-v24', text: 'Gene wo?', type: 'multiple-choice', options: ['Nur Skandinavien', 'Irland, Schottland, Island', 'Nur Afrika', 'Nur Asien'], correctAnswer: 1, explanation: 'Irland, Schottland, Island.' },
    { id: 'final-v25', text: 'Amerika-Name?', type: 'multiple-choice', options: ['Neue Welt', 'Vinland', 'Grönland', 'Island'], correctAnswer: 1, explanation: 'Vinland.' },
    { id: 'final-v26', text: 'Raubzug = ?', type: 'multiple-choice', options: ['Krieg', 'Investition', 'Sport', 'Religion'], correctAnswer: 1, explanation: 'Geschäft mit Risiko.' },
    { id: 'final-v27', text: 'Warum Raubzüge?', type: 'multiple-choice', options: ['Langeweile', 'Überbevölkerung, Armut', 'Götterbefehl', 'Zufall'], correctAnswer: 1, explanation: 'Wirtschaftliche Gründe.' },
    { id: 'final-v28', text: 'Wie lange Sklavenhandel?', type: 'multiple-choice', options: ['50', '100', 'Ca. 200', '500'], correctAnswer: 2, explanation: '8.–10. Jh., ca. 200 Jahre.' },
    { id: 'final-v29', text: 'Hauptwährung?', type: 'multiple-choice', options: ['Gold', 'Silber', 'Kupfer', 'Eisen'], correctAnswer: 1, explanation: 'Silber nach Gewicht.' },
    { id: 'final-v30', text: 'Wikinger-Lehre?', type: 'multiple-choice', options: ['Nur Krieg', 'Handel = Ökonomie der Raubzüge', 'Nur Religion', 'Nichts'], correctAnswer: 1, explanation: 'Sklavenhandel und Silber — Wirtschaftsbasis.' }
  ]
}
