import { QuizBlock, Slide } from '../types/session'

// Deutsch B2: Schrift – Kontrolle und Macht

export const writingControlSlidesDE: Slide[] = [
  { id: 'w1', title: 'Sumer: Tempel- und Palastrechnung', content: 'Keilschrift in Südmesopotamien (3. Jt. v. Chr.) dokumentierte Steuern, Arbeitseinsätze, Speicher. Man schmückte damit nicht das Eliteleben – ohne Schrift war die Wirtschaft des Stadtstaats unsichtbar. Lesen und schreiben beherrschten nur Schreiber.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/01-sumer-tablets.jpg', title: 'Sumerische Tontafeln' }] },
  { id: 'w2', title: 'Schreiber: Beruf und Prestige', content: 'In mesopotamischen Lehrtexten rät man dem Sohn in das «Tafelhaus»: der Schreiber trägt saubere Kleidung, schleppt nicht wie der Erdarbeiter. Das ist didaktische Dichtung – aber der Kern stimmt: Schrift öffnete Dienst bei Hof und Tempel; die Mehrheit hing an fremden Eintragungen.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/02-scribe-statuette.jpg', title: 'Schreiber' }] },
  { id: 'w3', title: 'Edubba: Schule, Prügel, Hierarchie', content: 'In altbabylonischen «Tafelhäusern» kopierten Schüler Texte und paukten Silbenlisten. Literarische Schultafeln schildern Prügel und Neid auf den fleißigen Klassenkameraden – kein privates Tagebuch, sondern ein Genre, das den Preis des Eintritts in die Schreibergilde zeigt.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/03-edubba-school.jpg', title: 'Schreiberschule' }] },
  { id: 'q1', title: 'Quiz', content: '', duration: 2, media: [{ type: 'image', url: '/media/writing-control/quiz-manuscript.jpg', title: 'Quiz' }], questions: [
    { id: 'q-lit-1-1-de', text: 'Wo entstand frühe Keilschrift für Verwaltung und Buchhaltung?', type: 'multiple-choice', options: ['Ägypten', 'Südmesopotamien (Sumer)', 'China', 'Byzanz'], correctAnswer: 1, explanation: 'Mesopotamien: Tempel und Palast.' },
    { id: 'q-lit-1-2-de', text: 'Wie hieß die Schreiberschule in Babylon?', type: 'multiple-choice', options: ['Akademie', 'Edubba', 'Lyzeum', 'Stoa'], correctAnswer: 1, explanation: 'Edubba = «Tafelhaus».' },
    { id: 'q-lit-1-3-de', text: 'Wer bildete in frühen Staaten die kleine Schreibelite?', type: 'multiple-choice', options: ['Alle Bauern', 'Schreiber und Schreibkraft der Verwaltung', 'Nur indische Priester', 'Nur Krieger'], correctAnswer: 1, explanation: 'Spezialisten der Schrift.' }
  ]},
  { id: 'w4', title: 'Echtes Genre: Schultext über den Schulalltag', content: 'Die Literaturtafel «Schultage» (Altbabylonisch) lässt einen Schüler über Prügel und den fleißigen Klassenprimus klagen – literarischer Schultext, kein Privatbrief. Er gibt Atmosphäre: der Weg zur Schrift führte über Disziplin und Rangordnung.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/04-school-days-tablet.jpg', title: 'Babylonische Schule' }] },
  { id: 'w5', title: 'Ägypten: Hieroglyphe als Macht von Tempel und Hof', content: 'Die komplexe Schrift diente Kult- und Verwaltungstexten; breite Alphabetisierung gab es nicht. Hieratisch und voller Hieroglyphen erforderten langes Training – damit lag die Deutungshoheit über «richtige» heilige und staatliche Formeln bei wenigen.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/05-egyptian-scribe.jpg', title: 'Ägyptischer Schreiber' }] },
  { id: 'w6', title: 'Lehrgedicht der Überlieferung: «Spott der Berufe»', content: 'Mittelreich-Text («Spott der Berufe»): der Vater befiehlt, Schrift zu lernen, und zählt die Mühseligkeit von Soldat, Töpfer, Weber … Der Schreiber sitzt unter Würdenträgern. Lehrziel – aber sozial plausibel: Schrift öffnete Tisch und Nähe zur Macht.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/06-satire-trades.jpg', title: 'Papyrus / Schreiber' }] },
  { id: 'q2', title: 'Quiz', content: '', duration: 2, media: [{ type: 'image', url: '/media/writing-control/quiz-manuscript.jpg', title: 'Quiz' }], questions: [
    { id: 'q-lit-2-1-de', text: 'Welches ägyptische Lehrgedicht preist den Schreiber über andere Berufe?', type: 'multiple-choice', options: ['Totenbuch', '«Spott der Berufe»', 'Sinuhe-Erzählung', 'Hoheslied'], correctAnswer: 1, explanation: '«Spott der Berufe» (ägyptische Weisheit).' },
    { id: 'q-lit-2-2-de', text: 'Was beschreibt die Tafelgattung «Schultage»?', type: 'multiple-choice', options: ['Nur Astronomie', 'Schulalltag und Strafen', 'Codex Hammurapi', 'Handelsverträge'], correctAnswer: 1, explanation: 'Literarische Schultexte.' },
    { id: 'q-lit-2-3-de', text: 'Ägyptische Hieroglyphenschrift war vor allem Sache von…', type: 'multiple-choice', options: ['allen Bauern', 'eines kleinen Kreises ausgebildeter Schreiber', 'fremden Händlern', 'Kindern unter 7'], correctAnswer: 1, explanation: 'Langes Training, wenige Schreibkundige.' }
  ]},
  { id: 'w7', title: 'Stein von Rosette: dreifacher Text', content: 'Die Stele mit dem Memphis-Dekret von 196 v. Chr. trägt Hieroglyphen, Demotisch und Griechisch – ein Beschluss für verschiedene Leserkreise im hellenistischen Ägypten. Kein Märchen, sondern Politik: die Macht fixiert ihre Version in drei Schriften.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/07-rosetta-stone.jpg', title: 'Stein von Rosette' }] },
  { id: 'w8', title: 'Rom: tabula und Bürgerlisten', content: 'Republik und Imperium stützten sich auf Census, Militärrollen und in Westprovinzen tabellio-Verträge sowie Wachstafeln für Privatgeschäfte. Latein und Verfahren kannten vor allem Gebildete; der Analphabet setzte ein Kreuz und vertraute der Auslegung durch den Schreiber.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/08-roman-tablet.jpg', title: 'Römische Tafel' }] },
  { id: 'w9', title: 'Pergament, Testament und «treuer Kopist»', content: 'Spätantike und frühes Mittelalter: Rechtskraft hing von beglaubigter Schrift ab; die Klerikerliteratur stand neben mündlicher Alltagskultur. Für den Bauern las Priester oder Schreiber – Formular und Deutung lagen bei Schreibkundigen.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/09-medieval-charter.jpg', title: 'Urkunde' }] },
  { id: 'q3', title: 'Quiz', content: '', duration: 2, media: [{ type: 'image', url: '/media/writing-control/quiz-manuscript.jpg', title: 'Quiz' }], questions: [
    { id: 'q-lit-3-1-de', text: 'Welcher berühmte Stein trägt drei Schriftsysteme?', type: 'multiple-choice', options: ['Hammurapi-Stele', 'Stein von Rosette', 'Behistun-Inschrift', 'Osterinsel-Statue'], correctAnswer: 1, explanation: 'Rosette: Hieroglyphen, Demotisch, Griechisch.' },
    { id: 'q-lit-3-2-de', text: 'Wie konnte ein analphabetischer Römer «unterschreiben»?', type: 'multiple-choice', options: ['Nicken', 'Mit Kreuzzeichen (signum) vor Zeugen', 'Handabdruck', 'Nur beim tabellio'], correctAnswer: 1, explanation: 'Signum crucis; Text formulierte der Schreiber.' },
    { id: 'q-lit-3-3-de', text: 'Wessen Priesterdekret wird auf dem Stein von Rosette überliefert?', type: 'multiple-choice', options: ['Jupiter', 'Memphis-Priester (ptolemäische Zeit)', 'Konstantin', 'Nero'], correctAnswer: 1, explanation: 'Memphis-Dekret 196 v. Chr.' }
  ]},
  { id: 'w10', title: 'Geschichtliche Episode: Karl und Tafeln unter dem Kissen', content: 'Einhard berichtet in der «Vita Karoli», Karl der Große habe spät Schreiben gelernt und Wachstafeln unterschlafen gelegt, um nachts zu üben. Pointe weniger Witz als Beweis: selbst der Herrscher ringt um Buchstaben – Alphabetisierung noch nicht massenhaft.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/10-charlemagne-manuscript.jpg', title: 'Karolingische Handschrift' }] },
  { id: 'w11', title: 'Urkunde, Siegel und Kreuz', content: 'Mittelalterliche Urkunden trugen Siegel und Zeugen; wer nicht las, setzte ein Kreuz und hörte die Vorlesung. Kontrolle über den Wortlaut lag bei Notar oder Priester – wer Latein beherrschte, konnte interpretieren.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/11-seal-charter.jpg', title: 'Siegel und Urkunde' }] },
  { id: 'w12', title: 'Latein der Kirche und Bibelzugang', content: 'Im westlichen Mittelalter war Latein Sprache von Liturgie und Gelehrten; Laien hörten Schriftwort meist predigtweise. Nach den Albigenserkriegen verschärften Synoden (u. a. Toulouse 1229) die Furcht vor häretischer Lektüre und verschärften Kontrolle über Laienbücher.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/12-council-books.jpg', title: 'Konzil / Bücher' }] },
  { id: 'q4', title: 'Quiz', content: '', duration: 2, media: [{ type: 'image', url: '/media/writing-control/quiz-manuscript.jpg', title: 'Quiz' }], questions: [
    { id: 'q-lit-4-1-de', text: 'Wer beschrieb Karls des Großen Mühen beim Schreibenlernen?', type: 'multiple-choice', options: ['Beda', 'Einhard', 'Froissart', 'Augustinus'], correctAnswer: 1, explanation: 'Einhard, «Vita Karoli».' },
    { id: 'q-lit-4-2-de', text: 'Wie bestätigte oft der Analphabet in mittelalterlichen Urkunden?', type: 'multiple-choice', options: ['Siegel statt Hand', 'Kreuzzeichen', 'Lippenstift', 'Emoji'], correctAnswer: 1, explanation: 'Signum.' },
    { id: 'q-lit-4-3-de', text: 'Welche Sprache dominierte kirchliche Gelehrsamkeit im lateinischen Westen?', type: 'multiple-choice', options: ['Mittelhochdeutsch', 'Latein', 'Altisländisch', 'Koptisch'], correctAnswer: 1, explanation: 'Latein.' }
  ]},
  { id: 'w13', title: 'Druck: Vervielfältigung ersetzt nicht Lesekönnen', content: 'Gutenberg (Mitte 15. Jh.) senkte Buchkosten, doch Alphabetisierung wuchs langsam: ohne Schule bleibt der Band geschlossen. Neue Macht lag bei Druckern, Lizenz und Fürstenzensur.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/13-gutenberg-press.jpg', title: 'Druckpresse' }] },
  { id: 'w14', title: 'Luther und die deutsche Bibel', content: 'Luther übersetzte das Neue Testament (1522), die ganze Bibel folgte 1534 – verbreitet durch Druck. Das verschob die Gewichte zwischen priesterlicher Auslegung und lesendem Christen; Obrigkeit erlaubte oder verbot Ausgaben selektiv.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/14-luther-bible.jpg', title: 'Lutherbibel' }] },
  { id: 'w15', title: 'Index verbotener Bücher', content: 'Das Tridentinum etablierte den «Index librorum prohibitorum»; später pflegte ihn die Congregatio indicis. Lesekontrolle wurde Listenbürokratie – legal druckbar, was nicht indexiert war.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/15-index-librorum.jpg', title: 'Index' }] },
  { id: 'q5', title: 'Quiz', content: '', duration: 2, media: [{ type: 'image', url: '/media/writing-control/quiz-manuscript.jpg', title: 'Quiz' }], questions: [
    { id: 'q-lit-5-1-de', text: 'Was billigte Mitte des 15. Jh. die Textvervielfältigung?', type: 'multiple-choice', options: ['Fotografie', 'Bewegliche Lettern / Presse', 'Kompass', 'Flotte'], correctAnswer: 1, explanation: 'Buchdruck.' },
    { id: 'q-lit-5-2-de', text: 'Was übersetzte Luther Anfang der 1520er?', type: 'multiple-choice', options: ['Koran', 'Neues Testament (später ganze Bibel)', 'Ilias', 'Justinian'], correctAnswer: 1, explanation: 'NT 1522, Gesamtbibel 1534.' },
    { id: 'q-lit-5-3-de', text: 'Der «Index» war Kontrollinstrument welcher Institution?', type: 'multiple-choice', options: ['Fotoclub', 'Katholische Zensur', 'Bank of England', 'Pariser Commune'], correctAnswer: 1, explanation: 'Kirchenindex.' }
  ]},
  { id: 'w16', title: 'Douglass: Buchstaben und Sklaverei — unvereinbar', content: 'In Fredericks Douglass’ Autobiografie lehrt die Herrin zuerst ABC, bis der Herr scholastisch macht: ein lesender Sklave «zerbricht» das System. Dokumentierte Episode der Sklavenhaltergesellschaft: Lesen wurde gezielt erschwert.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/16-douglass.jpg', title: 'Frederick Douglass' }] },
  { id: 'w17', title: 'Anti-Lese-Gesetze im Süden der USA', content: 'Antebellum- und Reconstruction-Kodizes einzelner Staaten straften oder behinderten das Unterrichten von Sklaven und freien Schwarzen im Lesen. Gesetzestext ist ökonomische Fortsetzung: Analphabetismus erleichterte Kontrolle und Angst.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/17-anti-literacy-laws.jpg', title: 'Dokumente' }] },
  { id: 'w18', title: 'Lese-Tests für Wähler (USA)', content: 'Nach der Reconstruction dienten «literacy tests» formal neutralen Wahlrechts, praktisch aber zur Ausschlussdiskriminierung Schwarzer. Das geschriebene Regelwerk maskierte rassistische Hürden – der Beamte entschied über «genug» Alphabet.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/18-literacy-test.jpg', title: 'Wahllokal' }] },
  { id: 'q6', title: 'Quiz', content: '', duration: 2, media: [{ type: 'image', url: '/media/writing-control/quiz-manuscript.jpg', title: 'Quiz' }], questions: [
    { id: 'q-lit-6-1-de', text: 'Wer schildert das Verbot, ihn lesen zu lehren (Sklavenhalter-Süden)?', type: 'multiple-choice', options: ['Harriet Beecher Stowe', 'Frederick Douglass', 'Booker T. Washington', 'John Brown'], correctAnswer: 1, explanation: '«Narrative of the Life…».' },
    { id: 'q-lit-6-2-de', text: 'Wovor fürchtete man sich im Süden bezüglich Lesenunterricht?', type: 'multiple-choice', options: ['nur Musik', 'organisierte Schwarze / «gefährliches» Lesen', 'Stricken', 'Landwirtschaft'], correctAnswer: 1, explanation: 'Schrift als Weg zu Freiheit und Solidarität.' },
    { id: 'q-lit-6-3-de', text: 'Wen trafen «literacy tests» praktisch nach 1870 oft?', type: 'multiple-choice', options: ['nur Präsidenten', 'formell alle, faktisch Schwarze Wähler', 'nur Frauen', 'niemanden'], correctAnswer: 1, explanation: 'Diskriminierung schwarzer Wähler.' }
  ]},
  { id: 'w19', title: 'China: Kaiserprüfungen — Schrift als Aufstieg', content: 'Die klassische Beamtenprüfung wählte Mandarine nach Kanon und Stil; teures Training und riesiger Zeichenschatz teilten «die mit der Bürste» vom Volk, das auf den Eintrag der Behörde angewiesen blieb.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/19-imperial-examination.jpg', title: 'Prüfung' }] },
  { id: 'w20', title: 'Qin Shihuangdi: Bücherverbrennen in der Überlieferung', content: 'Sima Qian berichtet von Politik des vereinten Qin-Reiches: Vernichtung vieler Texte und Normierung der Schrift. Deutungen streiten – aber Muster «Macht—Bücher—eine Norm» bleibt: Text tritt gegen konkurrierende Schulen an.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/20-book-burning.jpg', title: 'Bücherverbrennen' }] },
  { id: 'w21', title: 'Osmanische Kanzlei', content: 'Die Diwan-Kanzlei führte Firmans und Defter auf Osmanisch, Persisch und Arabisch; Kadis arbeiteten schriftlich. Wissen lag bei Schreibern und Gelehrten, nicht beim analphabetischen Dorfbewohner.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/21-ottoman-calligraphy.jpg', title: 'Ferman / Kalligraphie' }] },
  { id: 'q7', title: 'Quiz', content: '', duration: 2, media: [{ type: 'image', url: '/media/writing-control/quiz-manuscript.jpg', title: 'Quiz' }], questions: [
    { id: 'q-lit-7-1-de', text: 'Welches System band in China Schrift und Beamtenlaufbahn?', type: 'multiple-choice', options: ['nur Militär', 'Kaiserliche Prüfungen (keju)', 'Gilden', 'Yarlik'], correctAnswer: 1, explanation: 'Prüfungssystem.' },
    { id: 'q-lit-7-2-de', text: 'Welche Dynastie wird mit Bücherverbrennung und Normierung verbunden?', type: 'multiple-choice', options: ['Tang', 'Qin', 'Song', 'Ming'], correctAnswer: 1, explanation: 'Qin laut späterer Überlieferung.' },
    { id: 'q-lit-7-3-de', text: 'Neben Arabisch und Persisch wozu diente im Osmanischen Reich die türkische Kanzleisprache?', type: 'multiple-choice', options: ['Sanskrit', 'Osmanisches Türkisch', 'Lateinisch', 'Gälisch'], correctAnswer: 1, explanation: 'Verwaltungstürkisch.' }
  ]},
  { id: 'w22', title: 'Rus’: Gramotas, Djak, Fürstenkreuz', content: 'Altrus’ und Moskowien führten Gramotas und Register — Bojar und Kaufmann lasen oft nur durch den Djak. Fürst oder Zar setzte das Kreuz; Bedeutung formulierte die Kanzlei.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/22-russian-gramota.jpg', title: 'Birkenrindentext / Urkunde' }] },
  { id: 'w23', title: 'Sowjetischer Likbez: Alphabetisierung nach Plan', content: '1920er–30er: Massenkampagne gegen Analphabetismus mit Lehrplänen und kanonisierten Fibeln. Hier ist Lesen Modernisierungs- und Propagandewerkzeug — der Staat definiert, was der Neue Leser liest.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/23-likbez-poster.jpg', title: 'Likbez-Plakat' }] },
  { id: 'w24', title: '«Prawda» und Deutungshoheit', content: 'Sowjetische Presse konzentrierte «offizielle» Lesarten; Lesen konnte aufklären oder blenden – je nach Zugang und Selbstzensur. Der Staat besaß Druckereien und Auflagen.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/24-pravda-newspaper.jpg', title: 'Zeitung' }] },
  { id: 'q8', title: 'Quiz', content: '', duration: 2, media: [{ type: 'image', url: '/media/writing-control/quiz-manuscript.jpg', title: 'Quiz' }], questions: [
    { id: 'q-lit-8-1-de', text: 'Wer führte in Rus’ die Kanzleischriften?', type: 'multiple-choice', options: ['Djaki und Schreiber', 'nur Waräger', 'nur Nonnen', 'US-Schüler'], correctAnswer: 0, explanation: 'Djak-Kanzlei.' },
    { id: 'q-lit-8-2-de', text: 'Wie hieß die sowjetische Alphabetisierungskampagne der 1920/30er?', type: 'multiple-choice', options: ['Likbez', 'Pabst', 'Glasnost', 'NEP'], correctAnswer: 0, explanation: 'Liquidation der Analphabeten.' },
    { id: 'q-lit-8-3-de', text: 'Funktion einer Staatszeitung wie «Prawda»?', type: 'multiple-choice', options: ['Kreuzworträtsel', 'offizielle Lesart', 'Werbung', 'nur Sport'], correctAnswer: 1, explanation: 'Offizielle Linie.' }
  ]},
  { id: 'w25', title: 'Kolonialverwaltung: Sprache des Befehls', content: 'Britische oder andere Kolonialämter erließen Order in Metropolensprache; Einheimische engagierten oft Lakaien oder Dolmetscher vor Gericht. Juristisches Englisch oder Französisch wurde Filter der «Gerechtigkeit».', duration: 3, media: [{ type: 'image', url: '/media/writing-control/25-colonial-office.jpg', title: 'Kolonialbüro' }] },
  { id: 'w26', title: 'Kuriosum: sumerische «Schenken»-Szene', content: 'Eine Tafel aus Nippur (Penn Museum, ca. 19. Jh. v. Chr.) zeigt eine Alltagsszene, die populärwissenschaftlich als einer der «ältesten Witz»-Texte gilt – unzufriedener Gast. Deutungen sind umstritten, klar aber: Schrift fixierte nicht nur Tempel, sondern auch Alltagsrepliken für Keilschriftleser.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/26-nippur-joke-tablet.jpg', title: 'Sumerische Tafel' }] },
  { id: 'w27', title: 'Heute: Vertrag, digitale Signatur, AGB', content: 'Moderne Wirtschaft ruht auf Schriftakt: Verträge, Richtlinien, EULA am Bildschirm. Wer juristische Sprache spricht, setzt Bedingungen; wer nicht liest, «akzeptiert» per Klick.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/27-digital-contract.jpg', title: 'Bildschirmvertrag' }] },
  { id: 'q9', title: 'Quiz', content: '', duration: 2, media: [{ type: 'image', url: '/media/writing-control/quiz-manuscript.jpg', title: 'Quiz' }], questions: [
    { id: 'q-lit-9-1-de', text: 'Welche Sprache dominierte in vielen kolonialen Gerichten?', type: 'multiple-choice', options: ['nur Sanskrit', 'Metropolensprache (z. B. Englisch)', 'Esperanto', 'überall nur Arabisch'], correctAnswer: 1, explanation: 'Sprache der Kolonialmacht.' },
    { id: 'q-lit-9-2-de', text: 'Wo liegt die strittige Nippur-Tafel «Schenke»?', type: 'multiple-choice', options: ['Eremitage', 'University of Pennsylvania Museum', 'Louvre', 'British Museum'], correctAnswer: 1, explanation: 'Philadelphia.' },
    { id: 'q-lit-9-3-de', text: 'Moderne Parallele zur «Schreibmacht» bei Apps?', type: 'multiple-choice', options: ['nur Passwort', 'AGB und Zustimmung (ToS)', 'Gesten', 'Stimme'], correctAnswer: 1, explanation: 'Vertragstext + Klick.' }
  ]},
  { id: 'w28', title: 'UNESCO: Alphabetisierung als Index', content: 'UN und UNESCO messen Alphabetisierung als Entwicklungsindikator: ohne Lesen sind Gesundheit, Rechte und Marktteilnahme schwerer. Staaten verordnen Schulpflicht – und formieren so Bürger des Gesetzestextes.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/28-literacy-unesco.jpg', title: 'Schule / Alphabetisierung' }] },
  { id: 'w29', title: 'Lektion: Wer schreibt, setzt den Rahmen', content: 'Vom sumerischen Silo bis zur Online-Richtlinie: geschriebenes Wort fixiert Norm, Datum, Verantwortung. Mündliche Kultur bleibt, aber Streit mit Staat oder Konzern braucht Schriftkundige oder Selbstbildung.', duration: 3, media: [{ type: 'image', url: '/media/writing-control/29-summary-writing-power.jpg', title: 'Schrift und Macht' }] },
  { id: 'w30', title: 'Abschluss: Ethik des Lesens', content: 'Lesen lehren öffnet Freiheit und führt in Texte der Macht. Geschichte mahnt: Quelle prüfen und fragen – wessen Worte lese ich und wer profitiert von meiner Nutzbarmachung nicht gelesen zu haben?', duration: 3, media: [{ type: 'image', url: '/media/writing-control/30-reading-future.jpg', title: 'Lesen heute' }] },
  { id: 'q10', title: 'Quiz', content: '', duration: 2, media: [{ type: 'image', url: '/media/writing-control/quiz-manuscript.jpg', title: 'Quiz' }], questions: [
    { id: 'q-lit-10-1-de', text: 'Welche Organisation misst weltweit Alphabetisierung?', type: 'multiple-choice', options: ['NATO', 'UNESCO', 'FIFA', 'IOC'], correctAnswer: 1, explanation: 'UNESCO-Statistiken.' },
    { id: 'q-lit-10-2-de', text: 'Kernaussage «Schrift und Macht»?', type: 'multiple-choice', options: ['Schrift ist immer neutral', 'Wer Schrift kontrolliert, setzt Regeln', 'Schrift wirkte nie auf Geschichte', 'nur Künstler schrieben'], correctAnswer: 1, explanation: 'Norm durch Zugang zu Text.' },
    { id: 'q-lit-10-3-de', text: 'Was symbolisiert das «Ethik»-Finale?', type: 'multiple-choice', options: ['Schule meiden', 'Quelle und Machtinteresse hinterfragen', 'nur Romane', 'erster Treffer im Netz'], correctAnswer: 1, explanation: 'Kritisches Lesen.' }
  ]}
]

export const writingControlFinalQuizDE: QuizBlock = {
  id: 'quiz-writing-control-de',
  title: 'Abschlussquiz: Schrift – Kontrolle und Macht',
  questions: [
    { id: 'q-lit-1-1-de', text: 'Wo entstand frühe Keilschrift für Verwaltung?', type: 'multiple-choice', options: ['Ägypten', 'Südmesopotamien', 'China', 'Byzanz'], correctAnswer: 1, explanation: 'Mesopotamien.' },
    { id: 'q-lit-2-1-de', text: 'Welches Lehrgedicht preist den Schreiberberuf?', type: 'multiple-choice', options: ['Totenbuch', '«Spott der Berufe»', 'Sinuhe', 'Hoheslied'], correctAnswer: 1, explanation: 'Ägyptische Lehrdichtung.' },
    { id: 'q-lit-3-1-de', text: 'Drei Schriften auf einem Stein?', type: 'multiple-choice', options: ['Hammurapi', 'Rosette', 'Behistun', 'Moai'], correctAnswer: 1, explanation: 'Rosette.' },
    { id: 'q-lit-4-1-de', text: 'Wer schrieb über Karls Schreibübungen?', type: 'multiple-choice', options: ['Beda', 'Einhard', 'Froissart', 'Augustinus'], correctAnswer: 1, explanation: 'Einhard.' },
    { id: 'q-lit-5-1-de', text: 'Was billigte Buchkopie im 15. Jh.?', type: 'multiple-choice', options: ['Foto', 'Letternpresse', 'Kompass', 'Flotte'], correctAnswer: 1, explanation: 'Druck.' },
    { id: 'q-lit-6-1-de', text: 'Wer berichtet über Leseverbot?', type: 'multiple-choice', options: ['Stowe', 'Douglass', 'Washington', 'Brown'], correctAnswer: 1, explanation: 'Douglass.' },
    { id: 'q-lit-7-1-de', text: 'Chinas System Beamten + Schrift?', type: 'multiple-choice', options: ['Militär', 'Prüfungen', 'Gilde', 'Yarlik'], correctAnswer: 1, explanation: 'Keju.' },
    { id: 'q-lit-8-1-de', text: 'Kanzlei in Rus’?', type: 'multiple-choice', options: ['Djaki', 'Waräger', 'Nonnen', 'Schüler'], correctAnswer: 0, explanation: 'Djaki.' },
    { id: 'q-lit-9-1-de', text: 'Sprache kolonialer Justiz?', type: 'multiple-choice', options: ['Sanskrit', 'Metropole', 'Esperanto', 'Arabisch überall'], correctAnswer: 1, explanation: 'Metropolensprache.' },
    { id: 'q-lit-10-1-de', text: 'Organisation für Alphabetisierungsdaten?', type: 'multiple-choice', options: ['NATO', 'UNESCO', 'FIFA', 'IOC'], correctAnswer: 1, explanation: 'UNESCO.' },
    { id: 'q-lit-1-2-de', text: 'Babylonische Schreiberschule?', type: 'multiple-choice', options: ['Akademie', 'Edubba', 'Lyzeum', 'Stoa'], correctAnswer: 1, explanation: 'Edubba.' },
    { id: 'q-lit-2-2-de', text: '«Schultage»-Genre?', type: 'multiple-choice', options: ['Astro', 'Schulalltag', 'Hammurapi', 'Vertrag'], correctAnswer: 1, explanation: 'Schule.' },
    { id: 'q-lit-3-2-de', text: 'Unterschrift Analphabet?', type: 'multiple-choice', options: ['Siegel', 'Kreuz', 'Lippenstift', 'Emoji'], correctAnswer: 1, explanation: 'Kreuz.' },
    { id: 'q-lit-4-2-de', text: 'Bestätigung im Mittelalter oft?', type: 'multiple-choice', options: ['Hand', 'Kreuz', 'Make-up', 'Emoji'], correctAnswer: 1, explanation: 'Kreuz.' },
    { id: 'q-lit-5-2-de', text: 'Luther früh 1520er?', type: 'multiple-choice', options: ['Koran', 'NT', 'Ilias', 'Codex'], correctAnswer: 1, explanation: 'NT.' },
    { id: 'q-lit-6-2-de', text: 'Süden USA fürchtete?', type: 'multiple-choice', options: ['Musik', 'Lesen/Organisation', 'Stricken', 'Farm'], correctAnswer: 1, explanation: 'Lesen.' },
    { id: 'q-lit-7-2-de', text: 'Dynastie Bücherverbrennung?', type: 'multiple-choice', options: ['Tang', 'Qin', 'Song', 'Ming'], correctAnswer: 1, explanation: 'Qin.' },
    { id: 'q-lit-8-2-de', text: 'Sowjetische Kampagne?', type: 'multiple-choice', options: ['Likbez', 'Pabst', 'Glasnost', 'NEP'], correctAnswer: 0, explanation: 'Likbez.' },
    { id: 'q-lit-9-2-de', text: 'Nippur-Tafel wo?', type: 'multiple-choice', options: ['Eremitage', 'Penn Museum', 'Louvre', 'BM'], correctAnswer: 1, explanation: 'Philadelphia.' },
    { id: 'q-lit-10-2-de', text: 'Hauptthese?', type: 'multiple-choice', options: ['neutral', 'Schriftkontrolle = Regeln', 'ohne Wirkung', 'nur Künstler'], correctAnswer: 1, explanation: 'Macht über Text.' },
    { id: 'q-lit-1-3-de', text: 'Frühe Schreibelite?', type: 'multiple-choice', options: ['Bauern', 'Schreiber/Verwaltung', 'ind. Priester', 'Krieger'], correctAnswer: 1, explanation: 'Schreiber.' },
    { id: 'q-lit-2-3-de', text: 'Ägypten Hieroglyphe?', type: 'multiple-choice', options: ['alle', 'kleiner Kreis', 'Händler', 'Kinder'], correctAnswer: 1, explanation: 'Schreiberkaste.' },
    { id: 'q-lit-3-3-de', text: 'Dekret Rosette?', type: 'multiple-choice', options: ['Jupiter', 'Memphis-Priester', 'Konstantin', 'Nero'], correctAnswer: 1, explanation: 'Memphis.' },
    { id: 'q-lit-4-3-de', text: 'Hochmittelalter Kirche?', type: 'multiple-choice', options: ['Deutsch', 'Latein', 'Isländisch', 'Koptisch'], correctAnswer: 1, explanation: 'Latein.' },
    { id: 'q-lit-5-3-de', text: 'Index-Instrument?', type: 'multiple-choice', options: ['Club', 'kath. Zensur', 'Bank', 'Kommune'], correctAnswer: 1, explanation: 'Kirche.' },
    { id: 'q-lit-6-3-de', text: 'Literacy tests trafen praktisch?', type: 'multiple-choice', options: ['Präsidenten', 'schwarze Wähler', 'Frauen', 'niemand'], correctAnswer: 1, explanation: 'Diskriminierung.' },
    { id: 'q-lit-7-3-de', text: 'Osmanische Kanzlei drittens?', type: 'multiple-choice', options: ['Sanskrit', 'Osmanisch', 'Latein', 'Gälisch'], correctAnswer: 1, explanation: 'Türkisch.' },
    { id: 'q-lit-8-3-de', text: 'Prawda?', type: 'multiple-choice', options: ['Rätsel', 'offizielle Linie', 'Werbung', 'Sport'], correctAnswer: 1, explanation: 'Staatslinie.' },
    { id: 'q-lit-9-3-de', text: 'App-Parallel?', type: 'multiple-choice', options: ['Passwort', 'ToS', 'Geste', 'Stimme'], correctAnswer: 1, explanation: 'Bedingungen.' },
    { id: 'q-lit-10-3-de', text: 'Finale symbolisch?', type: 'multiple-choice', options: ['Schule weg', 'Quelle prüfen', 'Romane', 'erster Link'], correctAnswer: 1, explanation: 'Kritik.' }
  ]
}
