# Skript zum Herunterladen von Turnier-Bildern
# Dieses Skript hilft beim Herunterladen der benötigten Bilder

Write-Host "Bitte laden Sie die folgenden Bilder manuell herunter:" -ForegroundColor Yellow
Write-Host ""
Write-Host "1. joust.jpg - Mittelalterliches Tjost/Turnier"
Write-Host "   Quelle: https://www.google.com/search?q=medieval+jousting&tbm=isch"
Write-Host ""
Write-Host "2. buhurt.jpg - Massenschlacht/Buhurt"
Write-Host "   Quelle: https://www.google.com/search?q=medieval+melee+tournament&tbm=isch"
Write-Host ""
Write-Host "3. melle.jpg - Schwertkampf"
Write-Host "   Quelle: https://www.google.com/search?q=medieval+sword+fight&tbm=isch"
Write-Host ""
Write-Host "4. armor.jpg - Rüstung"
Write-Host "   Quelle: https://www.google.com/search?q=medieval+armor&tbm=isch"
Write-Host ""
Write-Host "5. lance.jpg - Lanze"
Write-Host "   Quelle: https://www.google.com/search?q=jousting+lance&tbm=isch"
Write-Host ""
Write-Host "6. barrier.jpg - Turnierbarriere"
Write-Host "   Quelle: https://www.google.com/search?q=jousting+barrier&tbm=isch"
Write-Host ""
Write-Host "7. crowd.jpg - Zuschauer"
Write-Host "   Quelle: https://www.google.com/search?q=medieval+tournament+crowd&tbm=isch"
Write-Host ""
Write-Host "8. festival.jpg - Fest"
Write-Host "   Quelle: https://www.google.com/search?q=medieval+festival&tbm=isch"
Write-Host ""
Write-Host "9. early-tournament.jpg - Frühes Turnier"
Write-Host "   Quelle: https://www.google.com/search?q=early+medieval+tournament&tbm=isch"
Write-Host ""
Write-Host "10. accident.jpg - Unfall"
Write-Host "    Quelle: https://www.google.com/search?q=knight+fall+tournament&tbm=isch"
Write-Host ""
Write-Host "11. field-of-cloth-of-gold.jpg - Feld des Goldtuchs"
Write-Host "    Quelle: https://www.google.com/search?q=field+of+cloth+of+gold+1520&tbm=isch"
Write-Host ""
Write-Host "12. william-marshal.jpg - William Marshal"
Write-Host "    Quelle: https://www.google.com/search?q=william+marshal+earl+pembroke&tbm=isch"
Write-Host ""
Write-Host "13. training.jpg - Training"
Write-Host "    Quelle: https://www.google.com/search?q=medieval+knight+training&tbm=isch"
Write-Host ""
Write-Host "14. tournament-video.jpg - Video-Thumbnail"
Write-Host "    Quelle: https://www.google.com/search?q=medieval+tournament+video&tbm=isch"
Write-Host ""
Write-Host "Speichern Sie alle Bilder in: $PSScriptRoot" -ForegroundColor Green


