# -*- coding: utf-8 -*-
"""Rich medieval entities – Batch 4: Church reform, Scholasticism, Culture, Trade, Late MA."""
from medieval_entity_helper import e

BATCH_R4 = [
    e(
        "Cluniazensische Reform", "Клюнийская реформа", 910,
        "Kirche", "Церковь",
        "Klosterreformbewegung, die die mittelalterliche Kirche erneuerte", "монастырская реформа, обновившая средневековую церковь",
        "die Gründung von Cluny und die klösterliche Reformbewegung", "основание Клюни и монастырское реформаторское движение",
        "Cluny (Burgund)", "Клюни (Бургундия)",
        "Verfall des Mönchstums durch Laieninvestitur und Korruption",
        "упадок монашества из-за мирской инвеституры и коррупции",
        "Erneuerung des Mönchstums und Grundlage für die gregorianische Reform",
        "обновление монашества и основа для григорианской реформы",
        "910 gründete Wilhelm I. von Aquitanien die Abtei Cluny und stellte sie direkt unter den Papst – ohne Einmischung weltlicher Herren. Cluny wuchs zu einem Netzwerk von über 1 000 Klöstern. Die Mönche betonten Gebet, strenge Benediktsregel und Unabhängigkeit von lokalen Feudalherren.",
        "В 910 году герцог Вильгельм I Аквитанский основал аббатство Клюни, поставив его напрямую под папу — без вмешательства светских господ. Клюни разросся в сеть из более 1000 монастырей, настаивавших на молитве, строгом уставе и независимости от местных феодалов.",
        "Cluny baute die größte romanische Kirche Europas (Cluny III, 12. Jh.) – 187 m lang, fünf Türme. Sie wurde 1798 abgebrochen. Cluniazenser prägten das Papsttum: Viele Reformpäpste, darunter Gregor VII., waren von Cluny beeinflusst.",
        "Клюни построил крупнейшую романскую церковь Европы (Клюни III, XII в.) — 187 м длиной, пять башен. Снесена в 1798 году. Клюнийцы повлияли на папство: многие реформаторы, включая Григория VII, вышли из этого движения.",
        "Cluny löste sich selbst auf: Im 12. Jahrhundert wurde Cluny selbst reformbedürftig. Bernhard von Clairvaux kritisierte seinen Reichtum. Die Zisterzienser (gegr. 1098) ersetzten Cluny als führende Reformbewegung.",
        "Клюни пережил собственный закат: в XII веке он сам нуждался в реформе. Бернард Клервоский критиковал его богатство. Цистерцианцы (осн. 1098) заменили Клюни как ведущее реформаторское движение.",
        "Cluny-Reform 910", "Реформа Клюни 910",
        tags=["Kirche", "Mönchtum"],
    ),
    e(
        "Franz von Assisi", "Франциск Ассизский", 1209,
        "Ordenswesen", "Монашество",
        "Gründer der Franziskaner und Verkörperung der Armutsfrömmigkeit", "основатель францисканцев и воплощение нищенского благочестия",
        "die Gründung des Franziskanerordens und seinen Lebensweg", "основание ордена францисканцев",
        "Assisi / Rom", "Ассизи / Рим",
        "Kritik an Kirchenreichtum und Suche nach apostolischer Armut",
        "критика церковного богатства и поиск апостольской бедности",
        "Franziskanerorden als größter Bettelorden und Werkzeug der Glaubensverbreitung",
        "орден францисканцев — крупнейший нищенствующий орден",
        "Giovanni di Pietro di Bernardone (1181/82–1226), genannt Francesco, wuchs als Kaufmannssohn in Assisi auf, erlebte eine religiöse Bekehrung und verschenkte alles. 1209 genehmigte Papst Innozenz III. seine «Regel» – Armut, Keuschheit und Gehorsam. Franz erhielt 1224 die Stigmata (Wundmale Christi) und starb 1226.",
        "Джованни ди Пьетро ди Бернардоне (1181/82–1226), прозванный Франциском, вырос сыном купца в Ассизи, пережил религиозное обращение и раздал всё. В 1209 году Иннокентий III одобрил его «правило». Франциск получил стигматы в 1224 году и умер в 1226-м.",
        "Franz redete mit Vögeln, zähmte den Wolf von Gubbio (laut Legende) und sang den «Sonnengesang» – das erste bedeutende Gedicht in italienischer Volkssprache. Er ist Patron der Umwelt (seit 1979), der Tiere und Italiens. Papst Franziskus wählte seinen Namen zum Programm.",
        "Франциск разговаривал с птицами, приручил (по легенде) волка Губбио и сложил «Гимн Солнцу» — первое значительное стихотворение на итальянском народном языке. Папа Франциск выбрал его имя как программу своего понтификата.",
        "Der Franziskanerorden spaltete sich: Spirituale Franziskaner forderten absolute Armut (Usus pauper), Konventualen erlaubten Besitz. Papst Johannes XXII. verurteilte 1322 die radikale Armutsidee als Häresie. Franz' Erbe wurde zum Schlachtfeld um Kirchenbesitz und Reform.",
        "Орден францисканцев раскололся: «спиритуалы» требовали абсолютной бедности, конвентуалы допускали собственность. В 1322 году папа Иоанн XXII осудил крайнюю идею бедности как ересь. Наследие Франциска стало полем битвы.",
        tags=["Kirche", "Ordenswesen"],
    ),
    e(
        "Dominikus", "Доминик де Гусман", 1216,
        "Ordenswesen", "Монашество",
        "Gründer des Dominikanerordens, Predigerorden", "основатель доминиканского ордена",
        "die Gründung des Dominikanerordens als Antwort auf die Katharer-Häresie", "основание доминиканского ордена как ответ на ересь катаров",
        "Toulouse / Rom", "Тулуза / Рим",
        "Katharismus in Südfrankreich und Unfähigkeit bestehender Strukturen, ihn zu bekämpfen",
        "катаризм в Южной Франции и неспособность церкви с ним бороться",
        "Dominikaner als führender Predigerorden und Instrument der Inquisition",
        "доминиканцы — ведущий орден проповедников и инструмент инквизиции",
        "Dominikus de Guzmán (1170–1221) begründete 1216 den Predigerorden (Dominikaner) mit dem Ziel, durch Predigt und Bildung Häresien zu bekämpfen. Im Gegensatz zur militärischen Brutalität des Albigenserkreuzzugs setzte er auf intellektuelle Überzeugung. Der Orden wurde zur akademischen Elite – Thomas von Aquin, Albertus Magnus waren Dominikaner.",
        "Доминик де Гусман (1170–1221) в 1216 году основал орден проповедников с целью бороться с ересями через проповедь и образование. В отличие от военной жестокости альбигойского похода он делал ставку на интеллектуальное убеждение. Орден стал академической элитой — Фома Аквинский, Альберт Великий были доминиканцами.",
        "Die Dominikaner wurden Hauptträger der päpstlichen Inquisition (ab 1231): Gregor IX. betraute sie mit der Ketzerverfolgung. Das war ambivalent: Einerseits systematische Verfolgung, andererseits (im Vergleich zu Massentötungen) ein geregeltes Verfahren mit Anklage, Verhör und Urteil.",
        "Доминиканцы стали главной силой папской инквизиции (с 1231 года). Это амбивалентно: с одной стороны — систематическое преследование, с другой — регулярная процедура с обвинением и судом вместо массовых убийств.",
        "Dominikaner und Franziskaner rivalisierten um Universitätslehrstühle in Paris. Beide Orden prägten die mittelalterliche Wissenschaft. Ihre «Bettelordenstheologie» verband Armut mit akademischer Exzellenz – ein Paradoxon, das produktiv war.",
        "Доминиканцы и францисканцы соперничали за кафедры в Парижском университете. Оба ордена определили средневековую науку. Их «нищенствующая теология» сочетала бедность с академическим блеском — парадокс, оказавшийся продуктивным.",
        tags=["Kirche", "Ordenswesen", "Inquisition"],
    ),
    e(
        "Thomas von Aquin", "Фома Аквинский", 1265,
        "Scholastik", "Схоластика",
        "Größter Scholastiker, Kirchenlehrer der katholischen Kirche", "величайший схоласт, учитель католической церкви",
        "die Summa theologiae und die Vereinigung von Glaube und Vernunft", "«Сумма теологии» и синтез веры и разума",
        "Paris / Neapel", "Париж / Неаполь",
        "Wiederentdeckung von Aristoteles durch arabische Übersetzungen",
        "повторное открытие Аристотеля через арабские переводы",
        "Scholastik als System der katholischen Theologie und Philosophie (bis heute)",
        "схоластика как система католической теологии и философии",
        "Thomas von Aquin (1225–1274), Dominikaner, schrieb die «Summa theologiae» (1265–1274) – das Kompendium christlicher Theologie. Er vereinigte Aristoteles' Vernunftphilosophie mit dem christlichen Glauben: Glaube und Vernunft widersprechen sich nicht, sondern ergänzen sich. 1323 heiliggesprochen, 1879 von Leo XIII. als «Doktor der Kirche» proklamiert.",
        "Фома Аквинский (1225–1274), доминиканец, написал «Сумму теологии» (1265–1274) — компендиум христианской теологии. Он соединил разумную философию Аристотеля с христианской верой: вера и разум не противоречат, а дополняют друг друга. Канонизирован в 1323 году.",
        "Thomas' «quinque viae» (fünf Gottesbeweise) sind bis heute die bekanntesten: kosmologischer, ontologischer und teleologischer Beweis. Philosophen diskutieren sie noch immer. Der Beweis aus dem Beweger: «Alles Bewegte hat einen Beweger; das erste Bewegende ist Gott.»",
        "«Quinque viae» (пять доказательств бытия Бога) Фомы — по-прежнему самые известные в истории философии. Космологическое, онтологическое и телеологическое доказательства философы обсуждают по сей день.",
        "Thomas' Werk beeinflusst direkt das Kirchenrecht und die Sozialethik: Seine Lehre vom «gerechten Krieg» (bellum iustum) und vom «Gemeinwohl» (bonum commune) sind Grundlagen des heutigen Völkerrechts. Die UN-Charta greift implizit auf diese Traditionen zurück.",
        "Труды Фомы влияют на церковное право и социальную этику: его учение о справедливой войне (bellum iustum) и общем благе (bonum commune) — основы современного международного права.",
        tags=["Scholastik", "Philosophie", "Kirche"],
    ),
    e(
        "Hildegard von Bingen", "Хильдегарда Бингенская", 1151,
        "Frauengeschichte / Kirche", "Женская история / Церковь",
        "Äbtissin, Mystikerin, Komponistin und Naturwissenschaftlerin", "аббатиса, мистик, композитор и естествоиспытатель",
        "ihre Visionen und ihr wissenschaftliches Werk «Physica»", "её видения и труд «Physica»",
        "Bingen / Rupertsberg", "Бинген / Руперстберг",
        "Mystische Begabung und kirchliche Anerkennung weiblicher Gelehrsamkeit",
        "мистический дар и церковное признание женской учёности",
        "Einzigartiges Universalgenie des Mittelalters: Musik, Medizin, Theologie",
        "уникальный универсальный гений Средневековья: музыка, медицина, теология",
        "Hildegard von Bingen (1098–1179) war Äbtissin, schrieb theologische Werke («Scivias»), medizinische Enzyklopädien («Physica», «Causae et Curae») und komponierte über 70 Gesänge – die größte erhaltene Komposition eines Mittelalterkomponisten. Sie predigte öffentlich – für eine Frau unerhört. Bernhard von Clairvaux billigte ihre Visionen.",
        "Хильдегарда Бингенская (1098–1179) была аббатисой, писала богословские труды («Scivias»), медицинские энциклопедии («Physica», «Causae et Curae») и сочинила более 70 песнопений — крупнейший сохранившийся корпус средневекового композитора. Она публично проповедовала — беспрецедентно для женщины.",
        "Hildegards Visionen wurden von Papst Eugen III. (1148) offiziell anerkannt. Sie korrespondierte mit Kaisern, Päpsten und Bischöfen als deren spirituelle Ratgeberin. 2012 erklärte Papst Benedikt XVI. sie zur «Kirchenlehrerin» – eine von nur vier Frauen mit diesem Titel.",
        "Видения Хильдегарды одобрил папа Евгений III (1148). Она переписывалась с императорами, папами и епископами как духовный советник. В 2012 году папа Бенедикт XVI провозгласил её «Учителем Церкви» — одна из четырёх женщин с этим титулом.",
        "Hildegards medizinisches Werk enthält erstaunlich empirische Beobachtungen: Sie beschrieb den Kreislauf der vier Säfte, Krankheitsursachen und Heilpflanzen präzise. Einige ihrer Rezepte wurden von modernen Pharmakologinnen analysiert und als wirksam befunden.",
        "Медицинские труды Хильдегарды содержат удивительно эмпирические наблюдения: описание четырёх соков, причины болезней, лекарственные растения. Некоторые её рецепты современные фармакологи признали эффективными.",
        tags=["Kirche", "Frauen", "Kultur"],
    ),
    e(
        "Dante Alighieri", "Данте Алигьери", 1308,
        "Literatur", "Литература",
        "Dichter der Göttlichen Komödie, Vater der italienischen Literatur", "поэт «Божественной комедии», отец итальянской литературы",
        "die Göttliche Komödie und die Begründung der italienischen Literatursprache", "«Божественная комедия» и создание итальянского литературного языка",
        "Florenz / Ravenna (Exil)", "Флоренция / Равенна (ссылка)",
        "Politische Streitigkeiten in Florenz zwischen Guelfen und Ghibellinen",
        "политические распри во Флоренции между гвельфами и гибеллинами",
        "Begründung der italienischen Literatursprache; Weltliteratur",
        "создание итальянского литературного языка; мировая литература",
        "Dante Alighieri (1265–1321) schrieb die «Divina Commedia» im Florentiner Exil (nach 1302). Das Epos in drei Teilen (Inferno, Purgatorio, Paradiso) beschreibt eine Reise durch die Jenseitsreiche, geführt von Vergil und Beatrice. Dante schrieb auf Toskanisch, nicht Latein – das schuf die moderne italienische Literatursprache.",
        "Данте Алигьери (1265–1321) написал «Божественную комедию» в флорентийском изгнании (после 1302). Поэма в трёх частях (Ад, Чистилище, Рай) описывает путешествие по загробному миру, ведомое Вергилием и Беатриче. Написано на тосканском, а не по-латыни — это создало современный итальянский литературный язык.",
        "Das Inferno ist das bekannteste Werk: 34 Gesänge, 9 Kreise der Hölle. Dante platziert politische Feinde (Papst Bonifaz VIII., Kaiser Friedrich II.), Philosophen (Aristoteles, Sokrates im Limbus) und mythische Sünder nach einem System der Vergeltung. Es ist ein Politdokument, getarnt als Theologie.",
        "Ад — самая знаменитая часть: 34 песни, 9 кругов. Данте помещает туда политических врагов (папу Бонифация VIII, Фридриха II), философов (Аристотеля, Сократа в Лимбе) и мифических грешников по системе возмездия. Это политический документ, замаскированный под теологию.",
        "Dante beeinflusste alles: Michelangelo malte das Inferno-Motiv auf die Sixtinische Decke, Joyce schrieb Ulysses nach dem Muster der Commedia, Botticelli illustrierte es. Seit 2021 begehen die Italiener den «Dantedì» am 25. März, dem mythischen Tag von Dantes Hölleneingang.",
        "Данте повлиял на всё: Микеланджело изобразил Ад на Сикстинской капелле, Джойс построил «Улисса» по модели «Комедии», Боттичелли её иллюстрировал. С 2021 года 25 марта в Италии — «День Данте».",
        tags=["Literatur", "Italien"],
    ),
    e(
        "Johannes Gutenberg", "Иоганн Гутenberg", 1450,
        "Kultur", "Культура",
        "Erfinder des Buchdrucks mit beweglichen Lettern", "изобретатель книгопечатания с подвижным шрифтом",
        "den Buchdruck mit beweglichen Lettern und die Gutenberg-Bibel", "книгопечатание и Библия Гутенберга",
        "Mainz", "Майнц",
        "Teure Handschriften als Informationsmonopol; Bedarf an Bildung und Reformation",
        "дорогостоящие рукописи как монополия информации",
        "Massenverbreitung von Büchern; Grundlage für Reformation und Wissenschaftsrevolution",
        "массовое распространение книг; основа Реформации и научной революции",
        "Johannes Gutenberg (ca. 1400–1468) entwickelte ca. 1450 den Buchdruck mit beweglichen Metalllettern in Mainz. Die Gutenberg-Bibel (1452–1455) war sein Meisterwerk: 180 Exemplare in Lateinisch. Vorher gab es in ganz Europa vielleicht 30 000 Bücher – bis 1500 hatte der Druck 20 Millionen Exemplare produziert.",
        "Иоганн Гутenberg (ок. 1400–1468) около 1450 года разработал в Майнце книгопечатание с подвижными металлическими литерами. Библия Гутенберга (1452–1455) — его шедевр: 180 экземпляров на латыни. До изобретения во всей Европе было около 30 000 книг — к 1500 году печать произвела 20 миллионов экземпляров.",
        "Gutenberg wurde von seinem Investor Johannes Fust 1455 vor Gericht gebracht und verlor seine Druckerei. Er starb arm. Die Ironie: Er erfand eine Technologie, die die Welt veränderte, profitierte aber kaum davon. Das Muster «Erfinder ohne Profit» wiederholt sich in der Geschichte.",
        "В 1455 году инвестор Фуст отсудил у Гутенберга типографию. Он умер в бедности — изобрёл технологию, изменившую мир, но почти не получил выгоды. Этот паттерн «изобретатель без прибыли» повторяется в истории.",
        "Ohne Gutenberg keine Reformation: Luther konnte seine 95 Thesen (1517) nur deshalb europaweit verbreiten, weil der Druck existierte. Die katholische Kirche hatte das Informationsmonopol über Handschriften gehabt – Gutenberg brach es. Das war die erste Medienrevolution Europas.",
        "Без Гутенберга нет Реформации: Лютер мог распространить 95 тезисов (1517) по всей Европе именно потому, что уже существовало книгопечатание. Это была первая медийная революция Европы.",
        tags=["Kultur", "Technik"],
    ),
    e(
        "Marco Polo", "Марко Поло", 1271,
        "Handel / Entdeckung", "Торговля / Открытия",
        "Venezianischer Entdecker und Botschafter am Hof Kublai Khans", "венецианский путешественник при дворе Хубилай-хана",
        "seine Reise nach China und seinen Aufenthalt am Hof Kublai Khans", "путешествие в Китай и пребывание при дворе Хубилай-хана",
        "Peking / Konstantinopel / Venedig", "Пекин / Константинополь / Венеция",
        "Öffnung der Seidenstraße durch Pax Mongolica",
        "открытие Шёлкового пути благодаря монгольскому миру",
        "Wissensvermittlung über Asien; Inspiration für spätere Entdecker",
        "передача знаний об Азии; вдохновение для последующих путешественников",
        "Marco Polo (1254–1324) reiste 1271–1295 durch Zentralasien nach China. Er diente 17 Jahre am Hof Kublai Khans und bereiste weite Teile des Reiches. Sein Buch «Il Milione» (diktiert im Gefängnis, 1298–1299) beschreibt China, Persien, Japan und Indien. Kolumbus trug ein Exemplar auf seiner Reise 1492.",
        "Марко Поло (1254–1324) в 1271–1295 годах путешествовал через Центральную Азию в Китай. Семнадцать лет служил при дворе Хубилай-хана. Его книга «Il Milione» (продиктована в тюрьме, 1298–1299) описывает Китай, Персию, Японию и Индию. Колумб взял экземпляр с собой в плавание 1492 года.",
        "Il Milione war sofort Bestseller – und sofort umstritten: Zeitgenossen nannten Marco il Milione, weil er von Millionen sprach. Bis heute fragen Historiker: Hat Marco Polo wirklich alles gesehen? Manche bezweifeln, dass er in Peking war (keine Erwähnung der Chinesischen Mauer oder des Teetrinkens).",
        "«Il Milione» сразу стала бестселлером — и сразу вызвала споры. Историки по сей день спорят: видел ли Поло всё описанное? Некоторые сомневаются, что он вообще был в Пекине (нет упоминаний о Китайской стене и чаепитии).",
        "Marco Polo inspirierte Kolumbus direkt: Kolumbus suchte den westlichen Seeweg nach «Cathay» (China) und «Cipangu» (Japan), die Polo beschrieben hatte. Die falsche Vorstellung von Asiens Größe (Polo übertrieb nicht so weit) ließ Kolumbus glauben, er sei fast angekommen.",
        "Марко Поло непосредственно вдохновил Колумба: тот искал западный морской путь в «Катай» (Китай) и «Чипангу» (Япония), описанные Поло. Преуменьшенные расстояния заставили Колумба думать, что он почти прибыл.",
        tags=["Handel", "Entdeckungen", "Asien"],
    ),
    e(
        "Hanse", "Ганза", 1356,
        "Handel", "Торговля",
        "Kaufmännischer Städtebund der Nord- und Ostsee", "торговый союз городов Северного и Балтийского морей",
        "die Bildung der Hanse als organisiertem Städtebund", "образование Ганзы как организованного союза городов",
        "Lübeck / Hamburg / Bremen", "Любек / Гамбург / Бремен",
        "Unsicherheit des Fernhandels auf Nord- und Ostsee und Bedarf an gegenseitiger Schutz",
        "ненадёжность дальней торговли на Северном и Балтийском морях",
        "Beherrschung des Nordsee- und Ostseehandels für zwei Jahrhunderte",
        "господство в торговле Северного и Балтийского морей на два века",
        "Die Hanse war ein loses Bündnis von 70–200 Handelsstädten, das 1356 formell in Lübeck konstituiert wurde. Sie kontrollierte den Fernhandel zwischen England, Skandinavien, dem Baltikum und Russland. Heringshandel, Pelze, Bernstein, Tuch und Getreide waren ihre wichtigsten Waren.",
        "Ганза — неформальный союз 70–200 торговых городов, официально созданный в Любеке в 1356 году. Контролировала дальнюю торговлю между Англией, Скандинавией, Прибалтикой и Россией. Основные товары: сельдь, пушнина, янтарь, сукно и зерно.",
        "Die Hanse hatte Kontor in Bergen (Fischhandel), Brügge (Tuchwaren), London (Stahlhof) und Nowgorod (Pelze). Der Nowgorod-Kontor war am wertvollsten – russische Pelze waren in ganz Europa begehrt. Nach dem Untergang Nowgorods (1478, Ivan III.) verlor die Hanse ihren wichtigsten Handelspartner.",
        "У Ганзы были конторы в Бергене (рыба), Брюгге (сукно), Лондоне (Стилхоф) и Новгороде (пушнина). После захвата Новгорода Иваном III (1478) Ганза потеряла важнейшего партнёра.",
        "Die Hanse hatte keine gemeinsame Armee, keine gemeinsame Regierung: Ihre Macht war wirtschaftlich (Handelsboykott) und diplomatisch. Sie zog Kaiser und Könige mit Handelsprivilegien an ihre Seite. Das machte sie zum Modell moderner Wirtschaftsdiplomatie.",
        "У Ганзы не было общей армии или правительства: её сила была экономической (торговый бойкот) и дипломатической. Она привлекала королей торговыми привилегиями — модель современной экономической дипломатии.",
        tags=["Handel", "Städte"],
    ),
    e(
        "Avignon-Papsttum", "Авиньонское папство", 1309,
        "Kirche", "Церковь",
        "Periode des Papsttums in Avignon («Babylonische Gefangenschaft»)", "авиньонский период папства («Вавилонское пленение»)",
        "den Umzug des Papsttums nach Avignon und das Abhängigkeitsverhältnis von Frankreich", "перенос папства в Авиньон",
        "Avignon", "Авиньон",
        "Niederlage Bonifaz' VIII. gegenüber Philipp IV. und Wahl eines französischen Papstes",
        "поражение Бонифация VIII перед Филиппом IV и избрание французского папы",
        "Autoritätsverlust des Papsttums; Abendländisches Schisma folgt",
        "потеря авторитета папства; следует Западный раскол",
        "Von 1309 bis 1377 residierten sieben Päpste in Avignon statt in Rom – alle Franzosen, stark von der französischen Krone beeinflusst. Petrarca nannte das die «Babylonische Gefangenschaft der Kirche». 1377 kehrte Gregor XI. nach Rom zurück – aber ein Jahr später begann das Abendländische Schisma.",
        "С 1309 по 1377 год семь пап жили в Авиньоне, а не в Риме — все французы, сильно зависевшие от французской короны. Петрарка назвал это «Вавилонским пленением церкви». В 1377 году Григорий XI вернулся в Рим — но год спустя начался Западный раскол.",
        "Der Avignonpalast war prächtig: Clemens V. und seine Nachfolger bauten einen monumentalen Papstpalast. Avignon wurde zum Kunstzentrum, wo italienische Maler (Simone Martini) arbeiteten. Die Stadt gehörte bis 1791 dem Papst und wurde erst dann von Frankreich annektiert.",
        "Авиньонский дворец был великолепен: папы построили монументальный замок. Авиньон стал художественным центром с итальянскими мастерами (Симоне Мартини). Город оставался папской собственностью до 1791 года.",
        "Die Rückkehr nach Rom (1377) wurde von Katharina von Siena erzwungen – durch Briefe, in denen sie Gregor XI. direkt aufforderte, seinen Worten Taten folgen zu lassen. Eine Frau ohne offizielles Amt brachte den Papst dazu, nach Rom zurückzukehren.",
        "Возвращение в Рим (1377) было ускорено Екатериной Сиенской — письмами, в которых она требовала от Григория XI подкрепить слова делами. Женщина без официальных полномочий вынудила папу вернуться в Рим.",
        "Avignon-Papst 1309", "Авиньонский папа 1309",
        tags=["Kirche", "Papst", "Frankreich"],
    ),
    e(
        "Abendländisches Schisma", "Западный раскол", 1378,
        "Kirche", "Церковь",
        "Spaltung des Papsttums: zwei oder drei simultane Päpste", "раскол папства: два или три одновременных папы",
        "das Gleichzeitige Regieren zweier und dann dreier rivalisierender Päpste", "одновременное правление двух, затем трёх соперничающих пап",
        "Rom / Avignon / Pisa", "Рим / Авиньон / Пиза",
        "Rückkehr des Papstes nach Rom (1377) und Kardinals-Revolte",
        "возвращение папы в Рим (1377) und кардинальский бунт",
        "Autoritätskrise der Kirche; Konziliarismus und Kirchenreform folgen",
        "кризис авторитета церкви; соборность и церковная реформа",
        "1378 wählten Kardinäle nach dem Tod Gregors XI. zwei Päpste: Urban VI. in Rom und Clemens VII. in Avignon. 1409 wählte ein Konzil in Pisa einen dritten – nun gab es drei simultane Päpste. Erst das Konzil von Konstanz (1414–1418) beendete das Schisma durch Absetzung und Wahl Martins V.",
        "В 1378 году кардиналы после смерти Григория XI избрали двух пап: Урбана VI в Риме и Климента VII в Авиньоне. В 1409 году Пизанский собор избрал третьего — три папы одновременно. Лишь Констанцский собор (1414–1418) завершил раскол.",
        "Das Schisma hatte praktische Konsequenzen: Europa spaltete sich in Obedienzen – wer einem welchem Papst gehorchte, hing von Politik, nicht Theologie ab. Frankreich folgte Avignon, England und HRR meist Rom. Kirchensteuern gingen zweifach ein, Prälaten wurden doppelt ernannt.",
        "Раскол имел практические последствия: Европа раскололась — кто слушался какого папы, определяла политика, а не теология. Франция следовала Авиньону, Англия и HRR — обычно Риму. Церковные налоги собирались дважды.",
        "Das Schisma erschütterte das Vertrauen in die Kirche fundamental: Wenn zwei Päpste sich gegenseitig als Antichrist bezeichneten, musste einer falsch liegen. Das nährte Kritik von Wyclif, Hus und letztendlich Luther.",
        "Раскол подорвал доверие к церкви: если два папы называли друг друга антихристом, один явно лгал. Это питало критику Уиклифа, Гуса и в конечном счёте Лютера.",
        "Abendländisches Schisma 1378", "Западный раскол 1378",
        tags=["Kirche", "Papst"],
    ),
    e(
        "Reconquista-Abschluss Granada", "Завоевание Гранады 1492", 1492,
        "Spanien", "Испания",
        "Letztes maurisches Königreich Spaniens fällt an Isabella und Ferdinand", "последнее мавританское королевство сдаётся Изабелле и Фердинанду",
        "den Fall Granadas und die Vollendung der Reconquista", "падение Гранады и завершение реконкисты",
        "Granada", "Гранада",
        "Jahrhundertelange Reconquista und Machtzunahme Kastiliens",
        "многовековая реконкиста и усиление Кастилии",
        "Ende der islamischen Herrschaft auf der Iberischen Halbinsel; 1492 als Epochenjahr",
        "конец исламского правления на Пиренеях; 1492 как эпохальный год",
        "Am 2. Januar 1492 übergab der letzte Nassridenkönig Muhammad XII. (Boabdil) die Alhambra an Isabella und Ferdinand. Es endet 781 Jahre islamische Herrschaft in Teilen Spaniens (seit 711). Die Legende: Boabdil weinte beim Verlassen und seine Mutter sagte: «Du weinst wie eine Frau um das, was du nicht als Mann verteidigt hast.»",
        "2 января 1492 года последний насридский король Мухаммад XII (Боабдил) передал Альгамбру Изабелле и Фердинанду. Завершились 781 год исламской власти на части Испании (с 711 года). Легенда: Боабдил заплакал при отъезде, мать сказала: «Ты плачешь как женщина о том, что не смог защитить как мужчина».",
        "1492 war das Jahr der Umbrüche: Granada fiel (2. Januar), Alhambra-Edikt (31. März, Ausweisung der Juden), Kolumbus brach auf (3. August). In einem Jahr endeten 800 Jahre mittelalterliche Geschichte Spaniens und beginnt die Neuzeit.",
        "1492 — год переломов: пала Гранада (2 января), Альгамбрский эдикт (31 марта, высылка евреев), Колумб отплыл (3 августа). За один год завершилось 800 лет средневековой истории Испании и началась Новая история.",
        "Die Alhambra überlebte, weil Ferdinand und Isabella selbst dort einzogen. Die maurische Palastarchitektur wurde zur Touristenattraktion und ist heute UNESCO-Welterbe. Das Nasridenreich war 250 Jahre lang durch Tributzahlungen und Diplomatie überlebt – ein Zeugnis für islamische Anpassungsfähigkeit.",
        "Альгамбра уцелела, потому что Изабелла и Фердинанд сами там поселились. Мавританская дворцовая архитектура стала туристической достопримечательностью и сегодня — объект ЮНЕСКО.",
        "Fall von Granada 1492", "Падение Гранады 1492",
        tags=["Spanien", "Reconquista", "Islam"],
    ),
    e(
        "Bernhard von Clairvaux", "Бернард Клервоский", 1146,
        "Kirche", "Церковь",
        "Zisterziensermönch, Kirchenlehrer und Prediger des Zweiten Kreuzzugs", "цистерцианский монах, учитель церкви",
        "seinen Einfluss auf die Kirche und die Predigt des Zweiten Kreuzzugs", "влияние на церковь и проповедь второго крестового похода",
        "Clairvaux / Vézelay", "Клерво / Везле",
        "Kirchenreformbedarf und Bedrohung des Heiligen Landes nach Verlust von Edessa (1144)",
        "потребность в церковной реформе и угроза Святой земле",
        "Einflussreichster kirchlicher Reformator seiner Generation",
        "самый влиятельный церковный реформатор своего поколения",
        "Bernhard von Clairvaux (1090–1153) war Abt von Clairvaux und der einflussreichste Kirchenmann seiner Zeit. Er gründete 68 Klöster, bekämpfte Abaelard (seinen rationalen Theologen-Rivalen) und predigte 1146 in Vézelay so überzeugend für den Zweiten Kreuzzug, dass Ludwig VII. und Conrad III. aufbrachen.",
        "Бернард Клервоский (1090–1153) — аббат Клерво и самый влиятельный церковник своего времени. Основал 68 монастырей, боролся с Абеляром и в 1146 году в Везле так убедительно проповедовал Второй крестовый поход, что Людовик VII и Конрад III выступили в поход.",
        "Bernhards Konflikt mit Abaelard zeigt den Grundkonflikt des Mittelalters: Glaube vs. Vernunft. Bernhard: «Der Glaube glaubt; er sucht nicht zu verstehen.» Abaelard: «Ich verstehe, damit ich glauben kann.» Bernhard gewann – Abaelard wurde 1140 verurteilt. Aber die Scholastik, die Bernhard ablehnte, setzte sich durch.",
        "Конфликт Бернарда с Абеляром отражает фундаментальное противостояние Средневековья: вера против разума. Бернард победил — Абеляр осуждён в 1140 году. Но схоластика, которую Бернард отверг, в итоге восторжествовала.",
        "Der Zweite Kreuzzug (1147–1149) war ein Debakel: Ludwig VII. und Conrad III. koordinierten schlecht, litten unter byzantinischem Misstrauen und scheiterten vor Damaskus (1148). Bernhard schrieb daraufhin eine «Entschuldigung», in der er Gottes unerforschliche Wege als Erklärung anbot.",
        "Второй крестовый поход (1147–1149) оказался провалом: Людовик VII и Конрад III плохо координировались и потерпели неудачу под Дамаском (1148). Бернард написал «извинение», ссылаясь на неисповедимые пути Господни.",
        tags=["Kirche", "Kreuzzüge", "Mönchtum"],
    ),
    e(
        "Albigenserkreuzzug", "Альбигойский крестовый поход", 1209,
        "Kreuzzüge", "Крестовые походы",
        "Kreuzzug gegen die Katharer in Südfrankreich", "крестовый поход против катаров в Южной Франции",
        "den Albigenserkreuzzug und das Massaker von Béziers", "альбигойский поход и резня в Безье",
        "Béziers / Carcassonne", "Безье / Каркассон",
        "Katharer-Häresie und Unfähigkeit lokaler Bischöfe, sie zu bekämpfen",
        "ересь катаров и неспособность местных епископов с ней бороться",
        "Vernichtung der katharischen Häresie; politische Eingliederung Südfrankreichs",
        "уничтожение катарской ереси; политическое включение Юга Франции",
        "Papst Innocenz III. rief 1209 den Albigenserkreuzzug aus, um die Katharer in der Languedoc zu vernichten. Am 22. Juli 1209 massakrierten Kreuzfahrer Béziers – Einwohner, Flüchtlinge aus dem Umland, Katharer und Katholiken. Schätzungen: 7 000–20 000 Tote. Das Zitat «Tötet alle, Gott erkennt die Seinen» wurde legendär.",
        "Папа Иннокентий III в 1209 году провозгласил альбигойский поход против катаров в Лангедоке. 22 июля 1209 года крестоносцы устроили резню в Безье. Потери: 7000–20000 человек. Фраза «Убивайте всех, Бог распознает своих» стала легендарной.",
        "Die Katharer waren eine dualistische Sekte: Sie glaubten, die materielle Welt sei böse (Werk des bösen Gottes), und die geistige Welt gut. Das «Vollkommene» (Perfecti) lebten asketisch; gewöhnliche Katharer (Credentes) lebten normal. Die Bewegung hatte Frauenpriesterinnen – ein weiterer Grund für die Kirchenfeindschaft.",
        "Катары были дуалистической сектой: материальный мир — зло (творение злого бога), духовный — благо. «Совершенные» (perfecti) жили аскетично; рядовые катары (credentes) — обычной жизнью. Движение допускало женщин-священниц — ещё одна причина преследования.",
        "Der Kreuzzug dauerte 20 Jahre und hinterließ eine verwüstete Languedoc. Simon de Montfort dominierte die Feldzüge, starb aber 1218. Das Ergebnis: Die südfranzösische Kultur (Troubadoure, okzitanische Sprache) wurde dauerhaft geschwächt. Frankreichs Krone gewann den Süden.",
        "Поход длился 20 лет и опустошил Лангедок. Южнофранцузская культура (трубадуры, окситанский язык) была необратимо ослаблена. Французская корона получила Юг.",
        tags=["Kreuzzüge", "Kirche", "Häresie"],
    ),
    e(
        "Petrarca", "Петрарка", 1341,
        "Literatur / Humanismus", "Литература / Гуманизм",
        "Vater des Humanismus und erster moderner Dichter Europas", "отец гуманизма и первый современный поэт Европы",
        "seine Krönung zum Poeta Laureatus in Rom und sein humanistisches Werk", "коронация на Капитолии и гуманистический труд",
        "Avignon / Florenz / Rom", "Авиньон / Флоренция / Рим",
        "Begegnung mit der Antike und Unzufriedenheit mit der scholastischen Weltanschauung",
        "встреча с античностью и неудовлетворённость схоластикой",
        "Begründung des Humanismus als intellektuelles Programm der Renaissance",
        "основание гуманизма как интеллектуальной программы Ренессанса",
        "Francesco Petrarca (1304–1374) wurde 1341 in Rom zum Dichter gekrönt – das erste Mal seit der Antike. Er sammelte und kopierte lateinische Handschriften (Cicero), schrieb das «Canzoniere» über seine Liebe zu Laura und formulierte erstmals die Idee der «dunklen Jahrhunderte» (Medium Aevum) – das Mittelalter als Rückschritt.",
        "Франческо Петрарка (1304–1374) в 1341 году был коронован в Риме как поэт — впервые со времён античности. Он собирал рукописи Цицерона, писал «Канцоньере» о любви к Лауре и первым назвал Средние века «тёмными столетиями» (Medium Aevum) — регрессом.",
        "Petrarcas Besteigung des Mont Ventoux (1336) gilt als erste dokumentierte Bergwanderung aus reinem Vergnügen. Er beschreibt, wie er oben Augustinus' «Confessiones» aufschlägt und sich selbst reflektiert. Das war «modernes» Ichbewusstsein im mittelalterlichen Kontext.",
        "Восхождение Петрарки на Мон-Ванту (1336) — первая документированная прогулка в горы ради удовольствия. На вершине он открыл «Исповедь» Августина и взглянул в себя — «современное» самосознание в средневековом контексте.",
        "Petrarca beeinflusste die europäische Lyrik für Jahrhunderte: Das Sonett (14 Zeilen, ABBA-ABBA-CDE-CDE) wurde nach ihm «Petrarchan sonnet» genannt und von Shakespeare, Sidney und Spenser übernommen. Die Vorstellung der unerreichbaren Geliebten (Laura) prägte das romantische Frauenbild der Neuzeit.",
        "Петрарка повлиял на европейскую лирику столетиями: сонет (14 строк) назвали в его честь «петрарковским», его взяли Шекспир и Сидни. Образ недосягаемой возлюбленной (Лауры) определил романтический идеал женщины в Новое время.",
        tags=["Literatur", "Humanismus", "Italien"],
    ),
    e(
        "Lorenzo de' Medici", "Лоренцо де Медичи", 1469,
        "Italien / Renaissance", "Италия / Ренессанс",
        "Florentiner Herrscher und Förderer der Renaissance, «il Magnifico»", "правитель Флоренции, покровитель Ренессанса",
        "seine Herrschaft über Florenz und die Blüte der Renaissance", "правление Флоренцией и расцвет Ренессанса",
        "Florenz", "Флоренция",
        "Aufstieg der Medicis als Bankiers und politische Patrone",
        "возвышение Медичи как банкиров и политических патронов",
        "Florenz als Zentrum der europäischen Renaissance und Geburtsort der Moderne",
        "Флоренция как центр европейского Ренессанса",
        "Lorenzo de' Medici (1449–1492), genannt il Magnifico, regierte Florenz als faktischer Herrscher ohne offiziellen Titel. Er förderte Michelangelo (der als Junge in seinem Haushalt lebte), Botticelli, Leonardo da Vinci, Angelo Poliziano. Die Platonica Akademie unter Ficino war sein intellektuelles Zentrum.",
        "Лоренцо де Медичи (1449–1492), «Великолепный», управлял Флоренцией без официального титула. Покровительствовал Микеланджело (живший мальчиком в его доме), Боттичелли, Леонардо да Винчи, Полициано. Платоновская академия под руководством Фичино была его интеллектуальным центром.",
        "1478 überlebte Lorenzo den Pazzi-Verschwörungsanschlag im Florentiner Dom knapp – sein Bruder Giuliano starb. Lorenzo rächte sich brutal: Anführer wurden gehängt, Botschaften wurden gesendet. Dann machte er Frieden mit dem Papst – politischer Pragmatismus nach der Rache.",
        "В 1478 году Лоренцо едва пережил заговор Пацци во Флорентийском соборе — его брат Джулиано погиб. Лоренцо жестоко отомстил, а затем заключил мир с папой — политический прагматизм после мести.",
        "Lorenzo war auch Dichter: Er schrieb Karneval-Lieder, Hirtengedichte und philosophische Verse auf Toskanisch. Sein bekanntestes Gedicht endet: «Wer fröhlich sein will, sei es – denn die Zukunft ist ungewiss.» – ein humanistisches Manifest der Lebensfreude.",
        "Лоренцо был также поэтом: писал карнавальные песни и философские стихи. Его знаменитая строка: «Кто хочет радоваться, радуйся — ибо завущее неизвестно» — гуманистический манифест жизнерадости.",
        tags=["Italien", "Renaissance", "Humanismus"],
    ),
    e(
        "Heinrich der Seefahrer", "Генрих Мореплаватель", 1415,
        "Entdeckungen", "Открытия",
        "Portugiesischer Prinz und Organisator der frühen Entdeckungsfahrten", "португальский принц, организатор ранних плаваний",
        "seine Expeditionen entlang der afrikanischen Küste", "экспедиции вдоль африканского побережья",
        "Sagres / Kap Bojador", "Сагрес / Мыс Бохадор",
        "Wunsch nach Goldhandel und Umgehung der islamischen Zwischenhändler",
        "стремление к торговле золотом и обходу исламских посредников",
        "Systematische Erkundung Afrikas; Grundlage für Vasco da Gamas Fahrt (1498)",
        "систематическое исследование Африки; основа плавания Васко да Гамы (1498)",
        "Heinrich der Seefahrer (1394–1460) war portugiesischer Prinz und nahm selbst kaum an Fahrten teil – er war Organisator. Er baute in Sagres eine Navigationsschule auf, förderte Kartographen und schickte Expeditionen nach Westafrika. 1434 überquerte Gil Eanes als erster Europäer das Kap Bojador.",
        "Генрих Мореплаватель (1394–1460) — португальский принц, который сам почти не плавал. Он построил в Сагрише навигационную школу, поддерживал картографов и посылал экспедиции к западной Африке. В 1434 году Жил Эаниш первым из европейцев обогнул мыс Бохадор.",
        "Das Kap Bojador war eine psychologische Barriere: Seefahrer glaubten, dahinter koche das Meer und Seeungeheuer warteten. Als Eanes zurückkehrte und nichts als Ozean berichtete, begann die systematische Erkundung Afrikas. Fehlende Mythen können Erkundung beschleunigen.",
        "Мыс Бохадор был психологическим барьером: моряки верили, что за ним море кипит и живут чудовища. Когда Эаниш вернулся и сообщил об обычном океане, началось систематическое исследование Африки.",
        "Heinrich begann den Sklavenhandel: Erste afrikanische Sklaven wurden 1441 nach Portugal gebracht. Das war der Beginn des transatlantischen Sklavenhandels. Heinrichs «Entdeckungsreisen» hatten also auch diese dunkle Seite.",
        "Генрих начал работорговлю: первые африканские рабы привезены в Португалию в 1441 году. Это начало трансатлантической работорговли — тёмная сторона «путешествий открытий».",
        tags=["Entdeckungen", "Portugal"],
    ),
    e(
        "Nikolaus von Oresme", "Николай Орем", 1377,
        "Scholastik / Wissenschaft", "Схоластика / Наука",
        "Scholastiker, Mathematiker und Wegbereiter der modernen Wissenschaft", "схоласт, математик, предтеча современной науки",
        "seine mathematischen und physikalischen Schriften an der Universität Paris", "математические и физические труды в Парижском университете",
        "Paris", "Париж",
        "Wiederentdeckung von Aristoteles und die Suche nach Erklärungen natürlicher Phänomene",
        "переоткрытие Аристотеля и поиск объяснений природных явлений",
        "Vorläufer der Mechanik und astronomischen Revolution Kopernikus'",
        "предтеча механики и астрономической революции Коперника",
        "Nikolaus von Oresme (ca. 1320–1382) war Bischof von Lisieux und Berater Karls V. von Frankreich. Er erfand grafische Darstellungen von Geschwindigkeit und Beschleunigung (Vorläufer der Koordinatensysteme), argumentierte für die Möglichkeit einer rotierenden Erde und übersetzte Aristoteles ins Französische.",
        "Николай Орем (ок. 1320–1382) — епископ Лизьё и советник Карла V Французского. Он изобрёл графическое изображение скорости и ускорения (прообраз координатных систем), доказывал возможность вращения Земли и переводил Аристотеля на французский.",
        "Oremes Idee der Erdrotation wurde von Kopernikus über 150 Jahre später übernommen – ohne ihn zu nennen. Das zeigt, wie mittelalterliche Wissenschaft in die Renaissance überging: nicht als plötzlicher Bruch, sondern als Evolution.",
        "Идея вращения Земли была воспринята Коперником более чем 150 лет спустя — без упоминания Орема. Это показывает: средневековая наука перешла в Ренессанс не как внезапный разрыв, а как эволюция.",
        "Oresme kritisierte Alchemisten und Astrologen rational – nicht nur aus Glaubensgründen. Er verlangte empirische Belege. Das war modern. Er argumentierte: «Die Vernunft soll urteilen, nicht die Autorität.» – ein proto-wissenschaftlicher Grundsatz.",
        "Орем рационально критиковал алхимиков и астрологов, требуя эмпирических доказательств: «Разум должен судить, а не авторитет» — протонаучный принцип.",
        tags=["Scholastik", "Wissenschaft"],
    ),
    e(
        "Timur (Tamerlan)", "Тамерлан", 1402,
        "Zentralasien", "Центральная Азия",
        "Zentralasiatischer Eroberer und Zerstörer islamischer Städte", "центральноазиатский завоеватель",
        "die Schlacht bei Ankara und die Zerstörung des Osmanischen Reichs", "битва при Анкаре и разгром Османской державы",
        "Ankara / Samarkand", "Анкара / Самарканд",
        "Wiedergeburt des Mongolen-Anspruchs auf Zentralasien",
        "возрождение монгольских претензий на Центральную Азию",
        "Osmanisches Reich geschwächt; Europa zeitweilig von osmanischer Gefahr entlastet",
        "Османская держава ослаблена; Европа временно избавлена от угрозы",
        "Timur (Tamerlane, 1336–1405) schuf das letzte große Nomaden-Imperium: Er vernichtete Delhi (1398), besiegte Sultan Bayezid I. bei Ankara (1402) und nahm ihn gefangen. Schätzungsweise 17 Millionen Menschen fielen seinen Feldzügen zum Opfer – 5 % der Weltbevölkerung. Schädelpyramiden waren seine Signaturen.",
        "Тамерлан (1336–1405) создал последнюю великую кочевую империю. Он разгромил Дели (1398), победил Баязида I при Анкаре (1402) и взял его в плен. По оценкам, 17 миллионов человек погибли в его походах — 5% населения мира. Пирамиды из черепов были его «подписью».",
        "Timurs Reich zerfiel nach seinem Tod rasch: Seine Nachkommen (Timuriden) regierten das Kerngebiet (Samarkand, Herat) für ein Jahrhundert und wurden Mäzene der Kunst. Babur, sein Nachkomme, gründete 1526 das Mogulreich in Indien.",
        "Держава Тамерлана быстро распалась после его смерти, но Тимуриды правили в Самарканде и Герате ещё столетие и стали покровителями искусства. Потомок Тамерлана Бабур основал в 1526 году державу Великих Моголов в Индии.",
        "Timur ist zweideutig: In Usbekistan ist er Nationalheld (Samarkand war seine Hauptstadt), im Iran und im arabischen Raum ein Monster. Der Historikerstreit um seine «Bedeutung» zeigt, wie Geschichte von Siegerstandpunkten abhängt.",
        "Тамерлан неоднозначен: в Узбекистане он национальный герой (Самарканд — его столица), в Иране и арабском мире — чудовище. Спор об его «значении» показывает зависимость истории от точки зрения победителей.",
        tags=["Mongolen", "Zentralasien", "Militär"],
    ),
]
