# -*- coding: utf-8 -*-
from __future__ import annotations


def e(
    name_de: str,
    name_ru: str,
    year: int,
    cat_de: str,
    cat_ru: str,
    title_de: str,
    title_ru: str,
    event_de: str,
    event_ru: str,
    place_de: str,
    place_ru: str,
    cause_de: str,
    cause_ru: str,
    effect_de: str,
    effect_ru: str,
    expl_de: str,
    expl_ru: str,
    f1_de: str,
    f1_ru: str,
    f2_de: str,
    f2_ru: str,
    f3_de: str | None = None,
    f3_ru: str | None = None,
    event_short_de: str | None = None,
    event_short_ru: str | None = None,
    tags: list[str] | None = None,
) -> dict:
    return {
        "name_de": name_de,
        "name_ru": name_ru,
        "year": year,
        "cat_de": cat_de,
        "cat_ru": cat_ru,
        "title_de": title_de,
        "title_ru": title_ru,
        "event_de": event_de,
        "event_ru": event_ru,
        "event_short_de": event_short_de or event_de,
        "event_short_ru": event_short_ru or event_ru,
        "place_de": place_de,
        "place_ru": place_ru,
        "cause_de": cause_de,
        "cause_ru": cause_ru,
        "effect_de": effect_de,
        "effect_ru": effect_ru,
        "expl_de": expl_de,
        "expl_ru": expl_ru,
        "f1_de": f1_de,
        "f1_ru": f1_ru,
        "f2_de": f2_de,
        "f2_ru": f2_ru,
        "f3_de": f3_de or f2_de,
        "f3_ru": f3_ru or f2_ru,
        "tags": tags or [cat_de],
    }
