# -*- coding: utf-8 -*-
"""Rich medieval entities – Batch 2: Crusades, Byzantium, Islam, Iberia."""
from medieval_entity_helper import e

BATCH_R2 = [
    e(
        "Urban II.", "Урбан II", 1095,
        "Kreuzzüge", "Крестовые походы",
        "Papst und Ausrufer des Ersten Kreuzzugs", "папа, провозгласивший первый крестовый поход",
        "die Predigt in Clermont und den Aufruf zum Ersten Kreuzzug", "проповедь в Клермоне и призыв к первому крестовому походу",
        "Clermont (Frankreich)", "Клермон (Франция)",
        "Seldschukische Bedrohung Byzanz' und Bitte des Kaisers Alexios I. um Hilfe",
        "угроза сельджуков Византии и просьба Алексея I о помощи",
        "Aufbruch von 60 000 bis 100 000 Kreuzfahrern; Gründung der Kreuzfahrerstaaten",
        "поход 60–100 тысяч крестоносцев; основание крестоносных государств",
        "Am 27. November 1095 hielt Papst Urban II. auf dem Konzil von Clermont die berühmteste Rede des Mittelalters: Er rief zur Befreiung Jerusalems auf. Angeblich rief die Menge «Gott will es!» (Deus vult). Das Ergebnis war der Erste Kreuzzug (1096–1099), an dem schätzungsweise 60 000–100 000 Menschen teilnahmen.",
        "27 ноября 1095 года папа Урбан II произнёс на соборе в Клермоне знаменитейшую речь Средневековья: призвал освободить Иерусалим. Толпа якобы кричала «Так хочет Бог!» (Deus vult). Результат — первый крестовый поход (1096–1099), в котором участвовало 60–100 тысяч человек.",
        "Vor dem Ritterkreuzzug zog der «Volkskreuzzug» (1096) unter Peter dem Einsiedler los – Zehntausende unausgerüstete Pilger, Bauern und Arme. Sie plünderten jüdische Gemeinden am Rhein (Würzburg, Mainz, Worms), bevor die meisten in Kleinasien von den Seldschuken vernichtet wurden.",
        "До рыцарского похода выступил «крестовый поход бедноты» (1096) под руководством Петра Отшельника — тысячи безоружных крестьян. По дороге они погромили еврейские общины на Рейне, затем были уничтожены сельджуками в Анатолии.",
        "Die Kreuzzüge hatten langfristige Folgen für den West-Ost-Handel: Durch die Handelsrouten nach Palästina blühten Genua, Venedig und Pisa auf. Die Rückgabe von Wissen – arabische Medizin, Mathematik und Philosophie – in den Westen beschleunigte die europäische Wissenschaft.",
        "Крестовые походы стимулировали торговлю Запада с Востоком: расцвели Генуя, Венеция и Пиза. Передача арабских знаний — медицины, математики, философии — ускорила развитие европейской науки.",
        "Predigt in Clermont 1095", "Проповедь в Клермоне 1095",
        tags=["Kreuzzüge", "Papst"],
    ),
    e(
        "Gottfried von Bouillon", "Готфрид Бульонский", 1099,
        "Kreuzzüge", "Крестовые походы",
        "Anführer des Ersten Kreuzzugs und Herrscher von Jerusalem", "предводитель первого крестового похода",
        "die Einnahme Jerusalems und die Gründung des Königreichs", "взятие Иерусалима и основание королевства",
        "Jerusalem", "Иерусалим",
        "Jahrelanger Marsch und Belagerungen durch Europa und Kleinasien bis Palästina",
        "многолетний переход через Европу и Анатолию в Палестину",
        "Gründung des Königreichs Jerusalem und der anderen Kreuzfahrerstaaten",
        "основание Иерусалимского королевства и других крестоносных государств",
        "Am 15. Juli 1099 erstürmten Kreuzfahrer Jerusalem nach fünfwöchiger Belagerung. Die Chroniken berichten von einem Massaker: Muslime und Juden wurden erschlagen oder verbrannt. Gottfried von Bouillon lehnte den Königstitel ab und nannte sich «Hüter des Heiligen Grabes». Er regierte nur ein Jahr, bis er 1100 starb.",
        "15 июля 1099 года крестоносцы после пятинедельной осады ворвались в Иерусалим. Хроники сообщают о резне: мусульмане и евреи были убиты. Готфрид отверг королевский титул, назвавшись «Защитником Гроба Господня». Он правил лишь год и умер в 1100 году.",
        "Das Massaker von 1099 war keine Ausnahme, sondern die Regel für mittelalterliche Städteeroberungen. Dennoch war seine Intensität außergewöhnlich. Muslimische Chronisten berichteten über Berge von Toten und Leichen in den Straßen. Die Erinnerung daran bestimmte die islamische Sicht auf die Kreuzzüge für Jahrhunderte.",
        "Резня 1099 года была не исключением, а правилом при средневековых осадах. Тем не менее её масштаб был чрезвычайным. Мусульманские хронисты описывали горы трупов. Эта память определила исламский взгляд на крестовые походы на века.",
        "Das Königreich Jerusalem war politisch komplex: Es war ein Feudalstaat ohne starkes Königtum, mit konkurrierenden Ritterorden (Templer, Johanniter, Deutsche), Handelsstädten und Vasallen. Diese innere Schwäche machte es anfällig für äußere Bedrohungen.",
        "Иерусалимское королевство было сложным феодальным государством: слабое королевство, конкурирующие ордена (тамплиеры, иоанниты, немецкие), торговые города и вассалы. Эта внутренняя слабость делала его уязвимым.",
        tags=["Kreuzzüge", "Jerusalem"],
    ),
    e(
        "Saladin", "Саладин", 1187,
        "Kreuzzüge", "Крестовые походы",
        "Sultan Ägyptens und Syriens, Rückeroberung Jerusalems", "султан Египта и Сирии, отвоевавший Иерусалим",
        "die Rückeroberung Jerusalems nach dem Sieg bei den Hörnern von Hattin", "возвращение Иерусалима после победы при Хаттине",
        "Hattin / Jerusalem", "Хаттин / Иерусалим",
        "Militärische Schwäche des Königreichs Jerusalem und interne Machtkämpfe",
        "военная слабость Иерусалимского королевства и внутренние распри",
        "Verlust Jerusalems für die Kreuzfahrer und Auslösung des Dritten Kreuzzugs",
        "потеря Иерусалима крестоносцами и начало третьего крестового похода",
        "Saladin (Salah ad-Din, 1137/8–1193) vereinte Ägypten und Syrien unter ayyubidischer Herrschaft. Am 4. Juli 1187 vernichtete er das Heer des Königreichs Jerusalem bei den Hörnern von Hattin (Wasserentzug in der Hitze). Am 2. Oktober 1187 nahm er Jerusalem ein – ohne Massaker, im Gegensatz zu 1099.",
        "Саладин (1137/8–1193) объединил Египет и Сирию под аюбидской властью. 4 июля 1187 года при Хаттине он уничтожил армию Иерусалимского королевства (лишив её воды в жару). 2 октября 1187 года взял Иерусалим — без резни, в отличие от 1099 года.",
        "Saladins Ruf als ritterlicher Gegner beruhte auf christlicher Propaganda: Er behandelte Gefangene besser als es üblich war, ließ Bewohner Jerusalems gegen Lösegeld ziehen. Doch er ließ auch Tausende töten, z. B. nach der Belagerung von Akkon 1191. Das Idealbild war ein westliches Konstrukt.",
        "Репутация Саладина как рыцарского противника была частично западной конструкцией. Он обращался с пленными лучше обычного, позволил жителям Иерусалима уйти за выкуп. Но тысячи тоже погибли.",
        "Saladins Einigung des islamischen Nahen Ostens war instabil: Nach seinem Tod (1193) zerfiel das Ayyubidenreich schnell unter rivalisierenden Söhnen. Erst die Mamluken (1250) bildeten eine dauerhaft stabile islamische Macht im Nahen Osten.",
        "Объединение Саладина оказалось непрочным: после его смерти (1193) аюбидская держава быстро распалась. Лишь мамлюки (1250) создали устойчивую исламскую силу на Ближнем Востоке.",
        "Rückeroberung Jerusalems 1187", "Взятие Иерусалима 1187",
        tags=["Kreuzzüge", "Islam", "Militär"],
    ),
    e(
        "Dritter Kreuzzug", "Третий крестовый поход", 1189,
        "Kreuzzüge", "Крестовые походы",
        "Kreuzzug der drei Könige gegen Saladin", "крестовый поход трёх королей против Саладина",
        "die Belagerung Akkons und den Waffenstillstand von Ramla", "осаду Акры и перемирие при Рамле",
        "Akkon / Palästina", "Акра / Палестина",
        "Saladins Rückeroberung Jerusalems (1187) und päpstlicher Kreuzzugsaufruf",
        "возвращение Иерусалима Саладином (1187) и папский призыв к крестовому походу",
        "Rückeroberung Akkons; Jerusalem bleibt islamisch, Pilger erhalten Zugang",
        "отвоевание Акры; Иерусалим остаётся мусульманским, паломники получают доступ",
        "Der Dritte Kreuzzug (1189–1192) war der prominenteste: Drei Könige zogen aus – Friedrich I. Barbarossa (ertrank in der Türkei), Philipp II. August (kehrte früh zurück) und Richard I. Löwenherz (kämpfte am längsten). Richard gewann Akkon (1191), besiegte Saladin bei Arsouf, näherte sich zweimal Jerusalem, zog sich aber zurück.",
        "Третий поход (1189–1192) — самый знаменитый: три короля — Барбаросса (утонул в Турции), Филипп II (вернулся рано) и Ричард Львиное Сердце (воевал дольше всех). Ричард взял Акру (1191), победил при Арсуфе, дважды подходил к Иерусалиму, но отступил.",
        "Richard ließ nach der Einnahme Akkons 2 700 muslimische Geiseln hinrichten, weil Saladin das Lösegeld nicht rechtzeitig zahlte. Diese Episode zeigt, dass auch der «ritterliche» Kreuzzug ohne Grausamkeit nicht auskam.",
        "После взятия Акры Ричард казнил 2700 мусульманских заложников, так как Саладин не выплатил выкуп вовремя. Даже «рыцарский» поход не обходился без жестокости.",
        "Der Friede von Ramla (1192) erlaubte christlichen Pilgern den Zugang nach Jerusalem, sicherte Küstenstädte für die Kreuzfahrer, beendete aber keine fundamentale Spannung. Der Krieg um das Heilige Land dauerte bis 1291 (Fall von Akkon).",
        "Рамльский мир (1192) дал паломникам доступ в Иерусалим и укрепил крестоносцев на побережье, но не устранил фундаментального противоречия. Война за Святую землю продолжалась до 1291 года.",
        tags=["Kreuzzüge", "Militär"],
    ),
    e(
        "Vierter Kreuzzug", "Четвёртый крестовый поход", 1204,
        "Kreuzzüge", "Крестовые походы",
        "Kreuzzug, der Konstantinopel statt Jerusalem eroberte", "крестовый поход, завоевавший Константинополь вместо Иерусалима",
        "die Einnahme und Plünderung Konstantinopels durch Kreuzfahrer", "взятие и разграбление Константинополя крестоносцами",
        "Konstantinopel", "Константинополь",
        "Venezianische Schuldenforderungen und byzantinische Thronstreitigkeiten",
        "венецианские долговые требования и визант. распри за трон",
        "Gründung des Lateinischen Kaiserreichs; Spaltung der Christenheit vertieft sich",
        "основание Латинской империи; углубление разрыва между церквями",
        "Der Vierte Kreuzzug (1202–1204) endete als skandalöse Umleitung: Statt Ägypten anzugreifen, plünderten die Kreuzfahrer – verführt von Venedigs Dogen Enrico Dandolo – zunächst das christliche Zara (1202), dann Konstantinopel (1204). Die Plünderung dauerte drei Tage; Reliquien und Kunstschätze wurden geraubt.",
        "Четвёртый поход (1202–1204) закончился скандальным отклонением: вместо атаки на Египет крестоносцы — соблазнённые венецианским дожем Энрико Дандоло — сначала разграбили христианскую Зару (1202), затем Константинополь (1204). Грабёж длился три дня.",
        "Papst Innocenz III. war zunächst schockiert und exkommunizierte die Kreuzfahrer wegen Zaras Plünderung. Als Konstantinopel fiel, akzeptierte er aber das Ergebnis, weil er hoffte, damit die Kirchenunion zu erzwingen. Dieser Opportunismus vertiefte dauerhaft den Graben zwischen Ost- und Westkirche.",
        "Папа Иннокентий III сначала отлучил крестоносцев за разграбление Зары, но принял взятие Константинополя, надеясь на церковную унию. Этот оппортунизм навсегда углубил пропасть между церквями.",
        "Die Plünderung von Konstantinopel war ein kultureller Verlust unermesslichen Ausmaßes: Antike Bronzestatuen, Mosaiken, Handschriften und Reliquien wanderten nach Venedig, Frankreich und Deutschland. Die Pferde vom Markusdom in Venedig sind das bekannteste geraubte Stück.",
        "Разграбление Константинополя стало культурной катастрофой: античные статуи, мозаики, рукописи и реликвии уехали в Венецию, Францию, Германию. Лошади собора Св. Марка в Венеции — самый известный трофей.",
        "Plünderung Konstantinopels 1204", "Разграбление Константинополя 1204",
        tags=["Kreuzzüge", "Byzanz"],
    ),
    e(
        "Justinian I.", "Юстиниан I", 529,
        "Byzanz", "Византия",
        "Oströmischer Kaiser und Gesetzgeber des Mittelalters", "восточноримский император и законодатель",
        "den Codex Iustinianus und die Wiedereroberung des Westreichs", "Кодекс Юстиниана и реконкиста западных провинций",
        "Konstantinopel / Ravenna / Nordafrika", "Константинополь / Равенна / Северная Африка",
        "Zerfall des weströmischen Reiches und Reformbedarf im Rechtswesen",
        "распад Западной Римской империи и потребность в правовой реформе",
        "Corpus Iuris Civilis als Grundlage des europäischen Rechts bis heute",
        "Corpus Iuris Civilis как основа европейского права по сей день",
        "Justinian I. (reg. 527–565) ist der bedeutendste byzantinische Kaiser. Sein Corpus Iuris Civilis (529–534) – ein vollständiges Rechtssystem aus vier Teilen – wurde zur Grundlage des europäischen Zivilrechts. Sein General Belisar reconquistete Nordafrika und Italien. Der Nika-Aufstand (532) brachte ihn beinahe zu Fall – Theodora rettete ihn mit ihrer berühmten Rede.",
        "Юстиниан I (правил 527–565) — величайший византийский император. Его Corpus Iuris Civilis (529–534) стал основой европейского гражданского права. Его полководец Велизарий отвоевал Северную Африку и Италию. Восстание Ника (532) едва не свергло его — Феодора спасла трон своей знаменитой речью.",
        "Die Hagia Sophia (537) war Justinians architektonisches Meisterwerk: Die Kuppel (31 m Durchmesser) überragte alles Bekannte. Für ein Jahrtausend blieb sie das größte Gebäude Europas. Beim Erdbeben und Einsturz 558 ließ Justinian sie sofort wieder aufbauen.",
        "Собор Святой Софии (537) — архитектурный шедевр Юстиниана. Купол (31 м в диаметре) превосходил всё известное. Тысячу лет она оставалась крупнейшим зданием Европы.",
        "Justinians Westfeldzüge kosteten Unsummen: Die reconquistierte Gebiete wurden kaum gehalten. Nordafrika verlor Byzanz im 7. Jahrhundert an die Araber, Italien an die Langobarden (568) kurz nach Justinians Tod. Das Unternehmen schwächte Byzanz dauerhaft.",
        "Западные завоевания Юстиниана обошлись дорого и почти не удержались. Северная Африка потеряна в VII веке арабами, Италия отдана лангобардам (568) вскоре после его смерти.",
        tags=["Byzanz", "Recht"],
    ),
    e(
        "Theodora", "Феодора", 532,
        "Byzanz", "Византия",
        "Kaiserin Ostroms, Machtpartnerin Justinians", "императрица, соправительница Юстиниана",
        "die Niederschlagung des Nika-Aufstands durch ihre Entschlossenheit", "подавление восстания Ника благодаря её решимости",
        "Konstantinopel", "Константинополь",
        "Nika-Aufstand (532): Volksaufstand gegen Steuern und korrupte Beamte",
        "восстание Ника (532): народный бунт против налогов и коррупции",
        "Rettung des Throns und Stärkung von Justinians Herrschaft",
        "спасение трона и укрепление власти Юстиниана",
        "534 wurde der Nika-Aufstand zur größten Krise Justinians: Die Hippodrom-Parteien (Blaue und Grüne) vereinten sich gegen ihn. Als Justinian flüchten wollte, hielt Theodora ihn zurück: «Der Purpur ist das schönste Leichentuch.» Belisar schlachtete 30 000 Aufständische im Hippodrom nieder.",
        "Восстание Ника (532) стало крупнейшим кризисом Юстиниана: партии ипподрома объединились против него. Когда Юстиниан хотел бежать, Феодора остановила его: «Порфир — лучший саван». Велизарий уничтожил 30 000 бунтовщиков на ипподроме.",
        "Theodora war Gesetzgeberin: Sie erließ Gesetze gegen Zwangsprostitution, schützte verheiratete Frauen vor willkürlicher Scheidung und gab Witwen Rechte. Für das 6. Jahrhundert waren das revolutionäre soziale Reformen.",
        "Феодора была законодательницей: запретила принудительную проституцию, защитила замужних женщин от произвольного развода, дала права вдовам. Для VI века это были революционные социальные реформы.",
        "Theodoras Herkunft war umstritten: Prokop schrieb in seiner geheimen Geschichte («Anekdota») vernichtend über sie als ehemalige Schauspielerin und Mätresse. Ob das Wahrheit oder Verleumdung war, ist unklar. Die Anekdota war jahrhundertelang unveröffentlicht.",
        "Прокопий в «Тайной истории» (Anekdota) уничижительно писал о Феодоре как бывшей актрисе и куртизанке. Насколько это правда или клевета — неясно. «История» оставалась неопубликованной столетиями.",
        tags=["Byzanz", "Frauen"],
    ),
    e(
        "Herakleios", "Ираклий", 610,
        "Byzanz", "Византия",
        "Byzantinischer Kaiser und Bezwinger des Perserreichs", "византийский император, сокрушивший Персию",
        "seinen Feldzug gegen Persien und die arabische Invasion", "поход против Персии и арабское вторжение",
        "Konstantinopel / Ktesiphon", "Константинополь / Ктесифон",
        "Persischer Angriff: Sassaniden bedrohten Konstantinopel und nahmen Jerusalem",
        "персидский натиск: сасаниды угрожали Константинополю и захватили Иерусалим",
        "Vernichtung des Sasanidenreichs; dann sofortige arabische Invasion Syriens",
        "уничтожение Сасанидской Персии, затем немедленное арабское вторжение в Сирию",
        "Herakleios (reg. 610–641) rettete Byzanz zweimal: Zuerst wehrte er einen gleichzeitigen Angriff von Persern, Awaren und Slawen ab (626). Dann führte er einen brillanten Gegenschlag nach Persien, vernichtete das Sasanidenreich und holte das Heilige Kreuz zurück (628). Doch kaum war Persien besiegt, strömten arabische Heere aus der Wüste und nahmen Syrien, Palästina und Ägypten.",
        "Ираклий (правил 610–641) дважды спас Византию: в 626 году отразил одновременный удар персов, аваров и славян. Затем нанёс ответный удар по Персии, уничтожил Сасанидскую державу и вернул Святой Крест (628). Но едва Персия пала, как арабские армии захватили Сирию, Палестину и Египет.",
        "Herakleios hellenisierte Byzanz: Er ersetzte Latein als Amtssprache durch Griechisch und nannte sich «Basileus» statt «Imperator». Damit wurde Byzanz von einem spätantiken römischen Kaiserreich zu einem mittelalterlichen griechischen Staat.",
        "Ираклий эллинизировал Византию: заменил латынь греческим и принял титул «Басилевс» вместо «Императора». Так Византия превратилась из позднеантичной римской империи в средневековое греческое государство.",
        "Das Trauma der arabischen Invasion prägte Byzanz dauerhaft: Syrien, Palästina und Ägypten – die reichsten Provinzen – gingen verloren. Byzanz wurde ein kleineres, griechisches Ostreich. Es überlebte noch fast 800 Jahre – bis 1453.",
        "Потеря Сирии, Палестины и Египта — богатейших провинций — навсегда изменила Византию. Она стала меньшей греческой державой, но просуществовала ещё около 800 лет — до 1453 года.",
        tags=["Byzanz", "Militär"],
    ),
    e(
        "Schisma von 1054", "Великий раскол 1054 года", 1054,
        "Byzanz", "Byzantinisch-Lateinische Welt",
        "Dauerhafter Bruch zwischen Ost- und Westkirche", "постоянный разрыв между восточной и западной церковью",
        "die gegenseitige Exkommunikation von Papst und Patriarch", "взаимное отлучение папы и патриарха",
        "Konstantinopel / Rom", "Константинополь / Рим",
        "Theologische Differenzen (Filioque) und Machtkämpfe zwischen Papst und Patriarch",
        "богословские разногласия (филиокве) и борьба между папой и патриархом",
        "Spaltung der Christenheit in Römisch-Katholisch und Griechisch-Orthodox",
        "разделение христианства на католиков и православных",
        "Im Juli 1054 exkommunizierten sich päpstliche Gesandte und Patriarch Michael Kerullarios gegenseitig. Streitpunkte waren: Filioque-Klausel (geht der Heilige Geist vom Vater «und vom Sohn» aus?), Primat des Papstes und Liturgiefragen. Das Schisma war kein plötzlicher Bruch, sondern der Tiefpunkt einer jahrhundertelangen Entfremdung.",
        "В июле 1054 года папские легаты и патриарх Михаил Кируларий взаимно отлучили друг друга. Поводы: клаузула Filioque (исходит ли Дух от Отца «и Сына»?), примат папы, литургические разногласия. Раскол не был внезапным — это кульминация многовековой отчуждённости.",
        "Der Vierte Kreuzzug (1204) vertiefte den Graben unüberbrückbar: Die Kreuzfahrer plünderten Konstantinopel – für die Byzantiner Beweis westlicher Barbarei. Der Patriarch von Konstantinopel weigerte sich fortan, mit Rom zu verhandeln. Alle späteren Unionsversuche scheiterten.",
        "Четвёртый крестовый поход (1204) сделал пропасть непреодолимой: разграбление Константинополя стало для византийцев доказательством западного варварства. Все последующие попытки унии провалились.",
        "Die gegenseitigen Exkommunikationen wurden 1964 von Papst Paul VI. und Patriarch Athenagoras offiziell aufgehoben – nach 910 Jahren. Das Schisma selbst besteht aber fort: Orthodoxe und Katholiken sind bis heute getrennte Kirchen.",
        "В 1964 году, через 910 лет, папа Павел VI и патриарх Афинагор официально сняли взаимные отлучения. Однако раскол сохраняется: православные и католики по-прежнему разделены.",
        "Gegenseitige Exkommunikation 1054", "Взаимное отлучение 1054",
        tags=["Byzanz", "Kirche", "Schisma"],
    ),
    e(
        "Alexios I. Komnenos", "Алексей I Комнин", 1081,
        "Byzanz", "Византия",
        "Byzantinischer Kaiser, der den Ersten Kreuzzug anstieß", "византийский император, запустивший первый крестовый поход",
        "seinen Hilferuf an den Westen und den Beginn des Kreuzzugszeitalters", "призыв о помощи к Западу и начало эпохи крестовых походов",
        "Konstantinopel", "Константинополь",
        "Seldschukischer Vormarsch nach Kleinasien nach der Niederlage von Manzikert (1071)",
        "сельджукский натиск в Анатолию после поражения при Манцикерте (1071)",
        "Auslösung des Ersten Kreuzzugs; langfristig problematisches Verhältnis zu Kreuzfahrern",
        "запуск первого крестового похода; долгосрочно — сложные отношения с крестоносцами",
        "Alexios I. (reg. 1081–1118) bat 1095 Papst Urban II. um Söldner gegen die Seldschuken. Er rechnete mit ein paar tausend Kämpfern – stattdessen kamen Hunderttausende Kreuzfahrer. Das war ihm ungeheuer: Er konnte sie kaum versorgen und traute ihren Absichten nicht. Er ließ sie alle schwören, zurückgewonnene Gebiete Byzanz zu übergeben.",
        "Алексей I (правил 1081–1118) в 1095 году попросил папу Урбана II о наёмниках против сельджуков. Он рассчитывал на несколько тысяч воинов — вместо них пришли сотни тысяч крестоносцев. Он обязал их клятвой возвращать отвоёванные земли Византии.",
        "Alexios stabilisierte ein Reich am Rande des Abgrunds: Er schlug Normannen (Robert Guiscard), Petschenegen und Türken ab und erholte Kleinasien teilweise. Sein Werk «Alexias», verfasst von Tochter Anna Komnena, ist eine der besten mittelalterlichen Herrscherbiographien.",
        "Алексей стабилизировал империю на краю пропасти: отразил норманнов, печенегов и турок. «Алексиада» его дочери Анны Комниной — одна из лучших средневековых монархических биографий.",
        "Die Beziehung zu den Kreuzfahrern war misstrauisch: Alexios wollte keine «Befreier», sondern Söldner. Als die Kreuzfahrer weiter als abgesprochen zogen und eigene Staaten gründeten, fühlte er sich betrogen. Antioch wurde nie an Byzanz zurückgegeben.",
        "Отношения с крестоносцами были подозрительными: Алексей хотел наёмников, а не «освободителей». Когда они продвинулись дальше договорённого и основали собственные государства, он почувствовал себя обманутым.",
        tags=["Byzanz", "Kreuzzüge"],
    ),
    e(
        "Basileios II.", "Василий II Болгаробойца", 1018,
        "Byzanz", "Византия",
        "Byzantinischer Kaiser, Besieger Bulgariens und Gipfel byzantinischer Macht", "византийский император, победитель Болгарии",
        "die vernichtende Niederlage Bulgariens und Zwangseingliederung ins Reich", "разгром Болгарии и её включение в состав империи",
        "Kleidion / Bulgarien", "Клейдион / Болгария",
        "Jahrzehntelange bulgarisch-byzantinische Kriege und bulgarische Expansion",
        "болгаро-византийские войны и болгарская экспансия",
        "Vernichtung des Ersten Bulgarischen Reichs und Höchststand byzantinischer Macht",
        "уничтожение Первого Болгарского царства и пик мощи Византии",
        "Basileios II. (reg. 976–1025) besiegte 1014 bei Kleidion 15 000 bulgarische Krieger. Er ließ 99 von 100 Gefangenen blenden und den 100. einäugig lassen, um die Blinden zu führen. Als Zar Samuel den Zug der Blinden sah, soll er vor Schreck gestorben sein. Diese Grausamkeit gab Basileios den Beinamen «Bulgarentöter» (Bulgaroktonos).",
        "Василий II (правил 976–1025) в 1014 году при Клейдионе захватил 15 000 болгар. Он приказал ослепить 99 из 100 пленных, оставив каждому сотому один глаз — чтобы вести остальных. Увидев колонну слепых, царь Самуил скончался от потрясения. Отсюда прозвище — «Болгаробойца».",
        "Basileios heiratete seine Nichte dem Kiewer Fürsten Wladimir an, um ein Militärbündnis zu sichern. Als Preis musste Wladimir sich taufen lassen (988) – und die ganze Kiewer Rus mit ihm. So wurde das Ostchristentum in Russland eingeführt.",
        "Василий выдал племянницу за киевского князя Владимира ради военного союза. Плата: Владимир должен был принять крещение (988) — и вся Киевская Русь вместе с ним. Так православие пришло в Россию.",
        "Nach Basileios' Tod verfiel Byzanz rasch: Schwache Kaiser, Korruption und die Katastrophe von Manzikert (1071) folgten. Was er in 50 Jahren aufgebaut hatte, zerfiel in 50 Jahren. Sein Beiname «Bulgarentöter» überstrahlte sowohl seine Grausamkeit als auch seine Staatskraft.",
        "После смерти Василия Византия быстро пришла в упадок: слабые императоры, коррупция, катастрофа при Манцикерте (1071). За 50 лет распалось то, что строилось 50 лет.",
        tags=["Byzanz", "Militär", "Bulgarien"],
    ),
    e(
        "Mehmed II.", "Мехмед II Завоеватель", 1453,
        "Osmanen", "Османы",
        "Sultan, Eroberer Konstantinopels und Gründer des Osmanischen Sultanats", "султан, завоевавший Константинополь",
        "die Einnahme Konstantinopels und das Ende des Byzantinischen Reichs", "взятие Константинополя и конец Byzantine империи",
        "Konstantinopel", "Константинополь",
        "Kontinuierliche osmanische Expansion und Schwäche des byzantinischen Restkaisertums",
        "османская экспансия и слабость остатков Византии",
        "Ende des Byzantinischen Reichs (1 453 Jahre nach Gründung Roms 753 v. Chr.)",
        "конец Византийской империи, просуществовавшей более тысячи лет",
        "Am 29. Mai 1453 fiel Konstantinopel nach 53-tägiger Belagerung. Mehmed II. setzte erstmals Riesenkanonen (Orban-Kanone) ein. Kaiser Konstantin XI. starb kämpfend. Das Reich, das seit 330 n. Chr. existiert hatte, endete. Mehmed nannte sich «Kaiser der Römer» (Kayser-i Rum) und machte Konstantinopel zur osmanischen Hauptstadt Istanbul.",
        "29 мая 1453 года после 53-дневной осады пал Константинополь. Мехмед II впервые применил гигантские пушки (пушка Урбана). Последний император Константин XI погиб в бою. Государство, существовавшее с 330 года, завершило свой путь. Мехмед назвал себя «Кайсар-и Рум» и сделал город столицей — Стамбулом.",
        "Die Riesenkanone des Ungarn Orban war das entscheidende Mittel: Sie verschoss Steinkugeln von 600 kg. Byzanz hatte versucht, Orban anzuheuern, konnte ihn aber nicht bezahlen. Mehmed bezahlte ihn das Vierfache. Technologischer Vorteil entschied die Belagerung.",
        "Гигантская пушка венгра Урбана бросала каменные ядра по 600 кг. Византия пыталась нанять его, но не смогла заплатить. Мехмед заплатил вчетверо. Технологическое превосходство решило исход.",
        "Der Fall Konstantinopels gilt als Symbol für das Ende des Mittelalters: Griechische Gelehrte flohen nach Italien und brachten antike Manuskripte mit – ein Anstoß für die Renaissance. Außerdem blockierten die Osmanen Handelsrouten, was Europa zur Suche nach Seeweg nach Asien trieb.",
        "Падение Константинополя — символ конца Средневековья: греческие учёные бежали в Италию с античными рукописями — импульс для Ренессанса. Блокада торговых путей толкнула Европу искать морской путь в Азию.",
        "Fall Konstantinopels 1453", "Падение Константинополя 1453",
        tags=["Osmanen", "Byzanz"],
    ),
    e(
        "Osman I.", "Осман I", 1299,
        "Osmanen", "Османы",
        "Gründer des Osmanischen Reiches", "основатель Османской империи",
        "die Gründung des osmanischen Emirats in Bithynien", "основание Османского эмирата в Вифинии",
        "Bithynien (Kleinasien)", "Вифиния (Малая Азия)",
        "Zerfall der seldschukischen Macht in Anatolien und Druck der Mongolen",
        "распад сельджукской власти в Анатолии и монгольское давление",
        "Begründung einer Dynastrie, die 623 Jahre herrschte (bis 1922)",
        "основание династии, правившей 623 года (до 1922 года)",
        "Osman I. (ca. 1258–1326) war Anführer eines kleinen türkischen Stammes in Nordwestanatolien. Um 1299 erklärte er sich unabhängig vom Seldschukenreich. Er nutzte die Schwäche Byzanz' und die Mongolenstürme geschickt aus, um sein Gebiet auszudehnen. Die nach ihm benannte Osmanen-Dynastie regierte 623 Jahre.",
        "Осман I (ок. 1258–1326) — вождь небольшого тюркского племени в северо-западной Анатолии. Около 1299 года провозгласил независимость от сельджуков. Он умело использовал слабость Византии и монгольские удары для расширения своих владений. Основанная им династия Османов правила 623 года.",
        "Das Ghazi-Konzept war Osmans Legitimation: Er und seine Krieger sahen sich als Kämpfer für den Islam (Ghazis) an der Grenze zur christlichen Welt. Dadurch zogen ständig neue Kämpfer aus dem islamischen Osten zu ihm. Diese religiöse Energie war entscheidend für die osmanische Expansion.",
        "Концепция «газавата» была легитимацией Османа: он и его воины считали себя борцами за ислам (газиями) на границе с христианским миром. Это привлекало новых бойцов со всего мусульманского Востока.",
        "Die osmanische Expansion nutzte byzantinische Schwäche systematisch: Städte kapitulierten oft freiwillig gegen günstige Bedingungen. Bursa (1326), Nikaia (1331) und schließlich Konstantinopel (1453) – die Osmanen zeigten, wie man ein Reich nicht durch Massengewalt, sondern durch kluge Integration aufbaut.",
        "Османская экспансия систематически использовала слабость Византии: многие города сдавались добровольно на выгодных условиях. Бурса (1326), Никея (1331) и наконец Константинополь (1453) — пример умной интеграции, а не тотального насилия.",
        tags=["Osmanen"],
    ),
    e(
        "Murad I.", "Мурад I", 1389,
        "Osmanen", "Османы",
        "Osmanischer Sultan, Begründer des Balkan-Reichs", "османский султан, завоеватель Балкан",
        "die Entscheidungsschlacht auf dem Amselfeld und die Balkanherrschaft", "битва на Косовом поле и власть на Балканах",
        "Amselfeld (Kosovo)", "Косово поле",
        "Widerstand der serbischen und balkanischen Fürsten gegen osmanische Expansion",
        "сопротивление сербских и балканских князей осм. экспансии",
        "Osmanische Kontrolle über den Balkan; Tod Murads und serbischer Stagnation",
        "османский контроль над Балканами; гибель Мурада и сербский упадок",
        "Murad I. (reg. 1362–1389) errichtete das erste dauerhafte osmanische Reich auf dem Balkan. Er reorganisierte die Armee mit den Janitscharen (christliche Kindersoldaten). 1389 besiegte er auf dem Amselfeld (Kosovo Polje) eine christliche Koalition – wurde aber nach der Bataille von einem serbischen Ritter ermordet.",
        "Мурад I (правил 1362–1389) создал первую постоянную османскую державу на Балканах. Он реорганизовал армию, введя янычар (христианских мальчиков-солдат). В 1389 году на Косовом поле разбил христианскую коалицию — и был убит сербским рыцарем после битвы.",
        "Die Janitscharen waren eine einzigartige Institution: Christliche Knaben wurden im «devshirme»-System als Sklaven des Sultans aufgezogen, zum Islam bekehrt und zu Elitesoldaten ausgebildet. Ihre persönliche Loyalität zum Sultan machte sie zur verlässlichsten Truppe des Reiches.",
        "Янычары — уникальный институт: христианских мальчиков по системе «девширме» воспитывали как рабов султана, обращали в ислам и готовили в элитных солдат. Личная преданность султану делала их надёжнейшей силой.",
        "Die Schlacht auf dem Amselfeld (1389) wurde zum serbischen Nationalmythos: Zar Lazar fiel, der serbische Staat wurde Vasall. Die Erinnerung an Kosovo prägte die serbische Identität bis zum 20. Jahrhundert und spielte eine Rolle im Jugoslawienkonflikt.",
        "Битва на Косовом поле (1389) стала сербским национальным мифом: царь Лазарь погиб, государство стало вассалом. Память о Косово формировала сербскую идентичность вплоть до XX века.",
        tags=["Osmanen", "Balkan", "Militär"],
    ),
    e(
        "El Cid", "Сид Кампеадор", 1094,
        "Spanien / Reconquista", "Испания / Реконкиста",
        "Kastilischer Ritter und Herrscher Valencias", "кастильский рыцарь и правитель Валенсии",
        "die Einnahme Valencias und seine Herrschaft als autonomer Fürst", "взятие Валенсии и самостоятельное правление",
        "Valencia", "Валенсия",
        "Macht vacuuum in al-Andalus nach Zerfall des Kalifats und Christen-Muslimkonflikte",
        "вакуум власти в аль-Андалусе после распада Кордовского халифата",
        "Muster der Reconquista: Einzelne Anführer schufen eigene Herrschaften",
        "паттерн реконкисты: отдельные полководцы создавали собственные владения",
        "Rodrigo Díaz de Vivar (El Cid, ca. 1043–1099) war weder einfach christlicher Ritter noch Muslim – er kämpfte für beide Seiten, je nach Interessenlage. Er diente zeitweise dem Maurenkönig al-Muktadir von Zaragoza. 1094 nahm er Valencia ein und herrschte dort autonom bis zu seinem Tod.",
        "Родриго Диас де Вивар (Сид, ок. 1043–1099) не был просто христианским рыцарем — он воевал на обеих сторонах, в зависимости от интереса. Временно служил мавританскому королю аль-Муктадиру Сарагосскому. В 1094 году захватил Валенсию и правил там автономно до смерти.",
        "Der Name «Cid» kommt vom arabischen «Sayyid» (Herr) – seine maurischen Feinde nannten ihn so respektvoll. Der Beiname «Campeador» (Kämpfer) ist kastilisch. Die Kombination beider zeigt die kulturelle Verflechtung der iberischen Reconquista.",
        "Имя «Сид» происходит от арабского «Сеййид» (господин) — так его уважительно называли мавры. Прозвище «Кампеадор» (Боец) — кастильское. Это сочетание отражает культурное переплетение реконкисты.",
        "Das «Cantar de Mio Cid» (um 1200) ist das älteste erhaltene spanische Epos und idealisiert El Cid. Der echte Rodrigo war opportunistischer, brutaler und komplexer als der Held des Gedichts. Das Epos schuf die nationale Figur des spanischen Ritters.",
        "«Песнь о моём Сиде» (ок. 1200) — старейший сохранившийся испанский эпос, идеализирующий героя. Реальный Родриго был оппортунистичнее, жёстче и сложнее. Поэма создала образ испанского рыцаря.",
        tags=["Spanien", "Reconquista", "Militär"],
    ),
    e(
        "Alfonso VI. von Kastilien", "Альфонсо VI Кастильский", 1085,
        "Spanien / Reconquista", "Испания / Реконкиста",
        "König von Kastilien-León, Eroberer Toledos", "король Кастилии-Леона, завоеватель Толедо",
        "die Einnahme Toledos und die Expansion der Reconquista", "взятие Толедо и расширение реконкисты",
        "Toledo", "Толедо",
        "Zerfall des Khalifats von Córdoba in kleine Taifas und Schwächung al-Andalus",
        "распад Кордовского халифата на мелкие тайфы и ослабление аль-Андалуса",
        "Toledo als wichtigste Rückeroberung der Reconquista und Zentrum des Wissenstransfers",
        "Толедо — важнейшее завоевание реконкисты и центр передачи знаний",
        "Alfonso VI. (reg. 1065–1109) nahm 1085 Toledo ein – ohne Blutvergießen, durch Verhandlung. Die ehemalige Westgotenhauptstadt war politisch und symbolisch bedeutsam: Toledo war die erste große Stadt, die wieder christlich wurde. Damit wurde die Reconquista zum strukturellen Projekt.",
        "Альфонсо VI (правил 1065–1109) взял Толедо в 1085 году — без кровопролития, путём переговоров. Бывшая вестготская столица была политически и символически важна: это первый крупный город, вернувшийся под христианскую власть.",
        "Toledo wurde zum Zentrum der Übersetzerschule: Im 12. Jahrhundert übersetzten Gelehrte arabische Handschriften ins Lateinische – Aristoteles, Euklid, Ptolemaios und arabische Medizin. Dieser Wissenstransfer löste die «wissenschaftliche Renaissance» des 12. Jahrhunderts aus.",
        "Толедо стал центром переводческой школы: в XII веке учёные переводили арабские рукописи на латынь — Аристотеля, Евклида, Птолемея, арабскую медицину. Этот трансфер знаний вызвал «научный ренессанс» XII века.",
        "Alfonso nannte sich «Kaiser der ganzen Hispania» – ein Anspruch, den die christlichen Könige des Nordens teils anerkannten, teils nicht. Die Idee einer iberischen Einheit war real und blieb politisches Ideal bis zur Vereinigung 1469.",
        "Альфонсо именовал себя «Императором всей Испании» — амбиция, частично признанная христианскими королями севера. Идея иберийского единства оставалась политическим идеалом вплоть до объединения в 1469 году.",
        tags=["Spanien", "Reconquista"],
    ),
    e(
        "Las Navas de Tolosa", "Битва при Лас-Навас-де-Толоса", 1212,
        "Spanien / Reconquista", "Испания / Реконкиста",
        "Entscheidungsschlacht der Reconquista", "решающее сражение реконкисты",
        "die Entscheidungsschlacht bei Las Navas de Tolosa gegen die Almohaden", "сражение с Альмохадами при Лас-Навас-де-Толоса",
        "Las Navas de Tolosa (Andalusien)", "Лас-Навас-де-Толоса (Андалусия)",
        "Almohaden-Invasionen aus Nordafrika und Bedrohung der christlichen Reiche",
        "вторжение Альмохадов из Северной Африки и угроза христианским королевствам",
        "Wendepunkt der Reconquista; muslimische Macht in Iberia dauerhaft gebrochen",
        "перелом реконкисты; мусульманская мощь в Иберии необратимо подломлена",
        "Am 16. Juli 1212 besiegten die vereinten Heere Kastiliens, Aragóns, Navarras und Portugals die Almohaden-Armee bei Las Navas de Tolosa. Es war eine der größten Schlachten des mittelalterlichen Spaniens. Die Almohaden verloren danach ihre Dominanz; die Reconquista gewann an Dynamik.",
        "16 июля 1212 года объединённые армии Кастилии, Арагона, Наварры и Португалии разгромили альмохадов при Лас-Навас. Это одно из крупнейших сражений средневековой Испании. После него альмохады потеряли гdomination, и реконкиста ускорилась.",
        "Die Bedeutung lag im Symbol: Für die erste Mal kämpften fast alle christlichen Könige Iberiens gemeinsam – mit päpstlichem Segen als «Kreuzzug». Der Almohaden-Kalif Muhammad al-Nasir floh. Córdoba fiel 1236, Sevilla 1248. Nur Granada blieb bis 1492.",
        "Символическое значение велико: впервые почти все христианские короли Иберии воевали вместе — под папским благословением как «крестовый поход». Халиф бежал. Кордова пала в 1236-м, Севилья — в 1248-м. Лишь Гранада держалась до 1492 года.",
        "Die Almohaden kamen ursprünglich aus Nordafrika und hatten die vorherige Partikularherrschaft (Taifas) abgelöst. Las Navas zeigte: Außerhalb Nordafrikas war islamische Macht in Iberia nicht mehr zu halten. Das war die eigentliche historische Weiche.",
        "Альмохады пришли из Северной Африки, сменив раздробленные тайфы. Битва показала: вне Африки исламская власть в Иберии неустойчива. Это и был исторический перелом.",
        "Las Navas de Tolosa 1212", "Битва при Лас-Навас 1212",
        tags=["Spanien", "Reconquista", "Militär"],
    ),
    e(
        "Isabella I. von Kastilien", "Изабелла I Кастильская", 1492,
        "Spanien", "Испания",
        "Königin, die Spanien einte, Granada gewann und Kolumbus finanzierte", "королева, объединившая Испанию",
        "die Reconquista-Vollendung und Kolumbus' erste Reise", "завершение реконкисты и первое плавание Колумба",
        "Granada / Palos de la Frontera", "Гранада / Палос-де-ла-Фронтера",
        "Letztes maurisches Königreich Granada und dynastische Einigung von Kastilien und Aragón",
        "последнее мавританское королевство Гранада и династическое единство",
        "Vollendung der Reconquista, Beginn der spanischen Weltherrschaft",
        "завершение реконкисты, начало испанского мирового господства",
        "Isabella I. (1451–1504) heiratete 1469 Ferdinand II. von Aragón – die Vereinigung der Kronen. 1492 fielen Granada (2. Januar) und Kolumbus brach auf (3. August). Im selben Jahr wurde auch das Edikt von Alhambra erlassen: alle Juden mussten Spanien verlassen oder sich taufen. Isabelllas Herrschaft war das Fundament des Spanischen Weltreichs.",
        "Изабелла I (1451–1504) вышла в 1469 году за Фердинанда II Арагонского — объединение корон. В 1492 году пала Гранада (2 января), Колумб отплыл (3 августа), и был издан Альгамбрский эдикт: все евреи обязаны покинуть Испанию или принять крещение. Правление Изабеллы — фундамент испанской мировой империи.",
        "Die Spanische Inquisition (1478) war Isabelllas Instrument zur Kontrolle der «Conversos» (getauften Juden und Muslimen). Unter Torquemada wurden Tausende gefoltert und hingerichtet. Die Inquisition war staatliches Werkzeug religiöser Kontrolle, nicht nur kirchliches.",
        "Испанская инквизиция (1478) была инструментом контроля над «конверсос» (крещёными евреями и мусульманами). Под руководством Торквемады тысячи пытали и казнили. Инквизиция была государственным, а не только церковным орудием.",
        "Isabelllas Finanzierung von Kolumbus war riskant: Sie erhielt ihn zu einem Drittel der Gewinne. Der Ertrag übertraf alle Erwartungen: Gold, Silber und Sklavenhandel machten Spanien zur reichsten Macht Europas für ein Jahrhundert.",
        "Финансирование Колумба было рискованным: он получил треть доходов. Результат превзошёл все ожидания: золото, серебро и работорговля сделали Испанию богатейшей державой Европы на столетие.",
        tags=["Spanien", "Reconquista"],
    ),
    e(
        "Harun ar-Raschid", "Харун ар-Рашид", 786,
        "Islam / Abbasiden", "Ислам / Аббасиды",
        "Kalif der Abbasiden, Zeitgenosse Karls des Großen", "халиф Аббасидов, современник Карла Великого",
        "den Höhepunkt der abbasidischen Zivilisation und den Austausch mit Karl dem Großen", "расцвет аббасидской цивилизации",
        "Bagdad", "Багдад",
        "Gründung Bagdads (762) als Zentrum islamischer Wissenschaft und Kultur",
        "основание Багдада (762) как центра исламской науки и культуры",
        "Goldenes Zeitalter des Islam mit Übersetzungsschule und Wissenschaften",
        "золотой век ислама с переводческой школой и науками",
        "Harun ar-Raschid (reg. 786–809) regierte im Goldenen Zeitalter des Abbasidenkalifats. Bagdad war mit 500 000 Einwohnern die größte Stadt der Welt. Das «Haus der Weisheit» (Bayt al-Hikma) übersetzte griechische Werke ins Arabische – Aristoteles, Hippokrates, Euklid. Karl der Große sandte 802 Gesandte nach Bagdad.",
        "Харун ар-Рашид (правил 786–809) правил в золотой век Аббасидского халифата. Багдад с 500 000 жителей был крупнейшим городом мира. «Дом мудрости» (Байт аль-Хикма) переводил греческие труды — Аристотеля, Гиппократа, Евклида. В 802 году Карл Великий послал послов в Багдад.",
        "Die Tausendundeine Nacht (1001 Nacht) spielte in Haruns Hof – aber die Geschichten entstanden über Jahrhunderte. Harun selbst wurde als gerechter Herrscher idealisiert. Er ist das bekannteste islamische Herrscherbild im europäischen Bewusstsein.",
        "«Тысяча и одна ночь» разворачивается при дворе Харуна — но истории создавались на протяжении столетий. Сам Харун был идеализирован как справедливый правитель. Он — самый известный исламский государь в европейском сознании.",
        "Das Abbasidenreich zerbrach im 9./10. Jahrhundert: Türkische Soldaten (Ghulam) wurden mächtiger als die Herrscher. 1258 zerstörten die Mongolen Bagdad und töteten den letzten Kalifen. Das war das Ende des «Goldenen Zeitalters».",
        "Аббасидский халифат распался в IX–X веках: тюркские гулямы стали сильнее халифов. В 1258 году монголы уничтожили Багдад и убили последнего халифа. Конец золотого века.",
        tags=["Islam", "Kultur"],
    ),
    e(
        "Averroes (Ibn Rushd)", "Аверроэс (Ибн Рушд)", 1190,
        "Islam / Scholastik", "Ислам / Схоластика",
        "Arabischer Philosoph und Kommentator Aristoteles'", "арабский философ, комментатор Аристотеля",
        "seine Kommentare zu Aristoteles und den Einfluss auf die europäische Scholastik", "комментарии к Аристотелю и влияние на европейскую схоластику",
        "Córdoba / Marrakesch", "Кордова / Марракеш",
        "Suche nach der Vereinbarkeit von Vernunft und Glauben im Islam",
        "поиск согласования разума и веры в исламе",
        "Systematische Übertragung des aristotelischen Denkens in die christliche Scholastik",
        "систематическая передача аристотелевского мышления в христианскую схоластику",
        "Ibn Rushd (1126–1198), bekannt als Averroes, war Arzt, Jurist und Philosoph in Córdoba und Marrakesch. Seine Kommentare zu Aristoteles wurden im 13. Jahrhundert ins Lateinische übersetzt und prägten Thomas von Aquin, Albertus Magnus und die gesamte Scholastik. Er wurde am Ende seines Lebens von Almohaden verfolgt.",
        "Ибн Рушд (1126–1198), известный как Аверроэс, был врачом, правоведом и философом в Кордове и Марракеше. Его комментарии к Аристотелю, переведённые в XIII веке на латынь, оказали влияние на Фому Аквинского, Альберта Великого и всю схоластику.",
        "Averroes' Lehre der «doppelten Wahrheit» – philosophische und religiöse Wahrheit können getrennt existieren – war im Mittelalter umstritten. Die Kirche verurteilte «Averroismus» als Häresie; dennoch beeinflusste er das westliche Denken grundlegend.",
        "Учение Аверроэса о «двойственной истине» — философская и религиозная истина могут существовать раздельно — было спорным. Церковь осудила «аверроизм», но он фундаментально повлиял на западную мысль.",
        "In der islamischen Welt hatte Averroes wenig Einfluss: Seine rationalistische Philosophie wurde vom konservativeren Denken al-Ghazalis (1058–1111) verdrängt. Die Ironie: Im Islam verloren, in der christlichen Scholastik gerettet.",
        "В исламском мире Аверроэс почти не имел влияния: его рационализм был вытеснен консервативным мышлением аль-Газали (1058–1111). Ирония: потерян в исламе, сохранён христианской схоластикой.",
        tags=["Islam", "Philosophie", "Scholastik"],
    ),
    e(
        "Genghis Khan", "Чингисхан", 1206,
        "Mongolen", "Монголы",
        "Gründer des Mongolischen Reichs und welthistorischer Eroberer", "основатель Монгольской империи",
        "die Gründung des Mongolischen Reichs und die Welteroberung", "основание Монгольской империи и мировое завоевание",
        "Mongolische Steppe / Karakorum", "Монгольская степь / Каракорум",
        "Stammesfehden in der mongolischen Steppe und Hunger nach Ressourcen",
        "межплеменные войны в степи и жажда ресурсов",
        "Größtes zusammenhängendes Landreich der Geschichte (24 Millionen km²)",
        "крупнейшая в истории сухопутная держава (24 млн км²)",
        "Temüdschin (ca. 1162–1227) einte die mongolischen Stämme und ließ sich 1206 als Genghis Khan (universeller Herrscher) ausrufen. Sein Reich wuchs von der Mandschurei bis Persien. Er vernichtete gegnerische Städte, schuf aber ein effizientes Rechtssystem (Yasa) und eine Poststraße (Yam).",
        "Тэмуджин (ок. 1162–1227) объединил монгольские племена и в 1206 году был провозглашён Чингисханом. Его держава простёрлась от Маньчжурии до Персии. Он уничтожал враждебные города, но создал эффективную правовую систему (яса) и почтовую сеть (ям).",
        "Genghis Khans Kriegsführung war revolutionär: Bewegliche Reiterei, dezentrale Kommandostruktur, psychologische Kriegführung (totale Vernichtung bei Widerstand, Schonung bei Kapitulation), Nutzung von Spionen und Überläufern. Er besiegte praktisch jede Armee seiner Zeit.",
        "Военное искусство Чингисхана было революционным: мобильная конница, децентрализованное командование, психологическая война (полное уничтожение при сопротивлении, пощада при сдаче), разведка и перебежчики.",
        "Der Schwarze Tod erreichte Europa über die Mongolischen Handels- und Kriegsrouten: Die Seidenstraße, die Genghis Khan öffnete (Pax Mongolica), ermöglichte auch die Pest-Ausbreitung. Schätzungsweise 30–60 % der europäischen Bevölkerung starb 1347–1351.",
        "Чёрная смерть достигла Европы по монгольским торговым и военным путям: «Монгольский мир» (Pax Mongolica), открывший Шёлковый путь, облегчил также распространение чумы.",
        "Mongolensturm 1206", "Монгольское завоевание 1206",
        tags=["Mongolen", "Militär"],
    ),
    e(
        "Hulagu Khan und Bagdad", "Хулагу-хан и Багдад", 1258,
        "Mongolen", "Монголы",
        "Mongolischer Khan, Zerstörer des Abbasidenkalifats", "монгольский хан, уничтоживший Аббасидский халифат",
        "die Zerstörung Bagdads und das Ende des Abbasidenkalifats", "разрушение Багдада и конец Аббасидского халифата",
        "Bagdad", "Багдад",
        "Mongolische Westexpansion und Weigerung des Kalifen zu kapitulieren",
        "монгольская экспансия на запад и отказ халифа капитулировать",
        "Ende des Goldenen Zeitalters des Islam; Bagdad wird Provinzstadt",
        "конец золотого века ислама; Багдад превращается в провинциальный город",
        "Hulagu Khan (1217–1265), Enkel Genghis Khans, vernichtete 1258 Bagdad in einer Katastrophe unvorstellbaren Ausmaßes: Der letzte Abbasidenkalif al-Mustaschim wurde in Filz gerollt und zu Tode getrampelt (mongolischer Brauch: kein Blut eines Fürsten vergießen). Die Bibliotheken brannten, der Tigris soll von Tinte schwarz geworden sein.",
        "Хулагу-хан (1217–1265), внук Чингисхана, в 1258 году уничтожил Багдад. Последний аббасидский халиф аль-Мустасим был завёрнут в войлок и затоптан (монгольский обычай: не проливать кровь князя). Библиотеки сгорели; говорят, Тигр стал чёрным от чернил.",
        "Die historische Forschung relativiert das Ausmaß der Katastrophe: Bagdad erholte sich, aber als Provinzstadt, nicht als Metropole. Schätzungen über die Opferzahl variieren von 90 000 bis 800 000 – die höheren sind wahrscheinlich übertrieben.",
        "Историки уточняют масштаб катастрофы: Багдад восстановился, но уже как провинциальный город. Оценки потерь варьируются от 90 000 до 800 000 — завышенные цифры, вероятно, преувеличены.",
        "Die Mamluken Ägyptens stoppten die Mongolen bei Ain Dschalut (1260) – die erste entscheidende mongolische Niederlage. Ägypten blieb das letzte große islamische Reich des Nahen Ostens und bewahrte die islamische Kultur.",
        "Мамлюки Египта остановили монголов при Айн-Джалуте (1260) — первое значительное поражение монголов. Египет остался последней великой исламской державой Ближнего Востока.",
        tags=["Mongolen", "Islam"],
    ),
]
