# -*- coding: utf-8 -*-
from medieval_entity_helper import e

BATCH1 = [
    e(
        "Karl der Große", "Карл Великий", 800,
        "Frankenreich", "Франкское государство",
        "König der Franken und römischer Kaiser", "король франков и римский император",
        "die Kaiserkrönung Karls des Großen in Rom", "коронация Карла Великого в Риме",
        "Rom", "Рим",
        "die Einigung großer Teile Westeuropas unter frankischer Herrschaft",
        "объединение большей части Западной Европы под властью франков",
        "Stärkung der Verbindung von Kirche und Herrschaft im lateinischen Westen",
        "укрепление связи церкви и власти в латинском Западе",
        "Karl der Große wurde 800 in Rom vom Papst gekrönt und gilt als Begründer eines neuen Kaisertums im Westen.",
        "Карла Великого короновали в 800 году в Риме; его правление считают началом новой имперской традиции на Западе.",
        "Sein Hof in Aachen war Zentrum von Bildung, Recht und Kirche; Gelehrte wie Alkuin prägten die karolingische Renaissance.",
        "Двор в Ахене стал центром образования, права и церкви; учёные вроде Алкуина создали каролингское возрождение.",
        "Nach seinem Tod 814 teilten die Söhne das Reich im Vertrag von Verdun (843) – ein Meilenstein der europäischen Staatengeschichte.",
        "После смерти в 814 году сыновья разделили империю в Вердене (843) — важный этап истории европейских государств.",
        "Die Kaiserkrönung 800", "Коронация 800 года",
    ),
    e(
        "Otto I.", "Оттон I", 962,
        "Heiliges Römisches Reich", "Священная Римская империя",
        "Ostfränkischer König und Kaiser", "восточнофранкский король и император",
        "die Kaiserkrönung Ottos I. in Rom", "коронация Оттона I в Риме",
        "Rom", "Рим",
        "militärische Siege über ungarische und slawische Angriffe",
        "военные победы над венграми и славянами",
        "Festigung des Kaisertums in Mitteleuropa", "укрепление империи в Центральной Европе",
        "962 krönte Papst Johannes XII. Otto I. zum Kaiser – Beginn des Heiligen Römischen Reiches.",
        "В 962 году папа Иоанн XII короновал Оттона I — традиционно это считают началом Священной Римской империи.",
        "Die Schlacht auf dem Lechfeld (955) beendete die ungarische Bedrohung und stärkte Ottos Autorität.",
        "Лехфельдская битва (955) остановила набеги венгров и усилила власть Оттона.",
        "Otto förderte Bistümer und Klöster als Stützen der Reichsverwaltung.",
        "Оттон опирался на епископов и монастыри как на опору имперского управления.",
        "Kaiserkrönung 962", "Коронация 962 года",
    ),
    e(
        "Wilhelm der Eroberer", "Вильгельм Завоеватель", 1066,
        "England", "Англия",
        "Herzog der Normandie und König von England", "герцог Нормандии и король Англии",
        "die Schlacht bei Hastings", "битва при Гастингсе",
        "Hastings", "Гастингс",
        "Streit um den englischen Thron nach dem Tod Eduards des Bekenners",
        "спор о престоле после смерти Эдуарда Исповедника",
        "normannische Herrschaft über England", "нормандское правление в Англии",
        "1066 besiegte Wilhelm bei Hastings König Harald II. und begründete die normannische Dynastie.",
        "В 1066 году Вильгельм разбил Гарольда II при Гастингсе и основал нормандскую династию.",
        "Das Domesday Book (1086) erfasste Besitz und Abgaben – frühe Form landesweiter Verwaltung.",
        "«Книга Страшного суда» (1086) зафиксировала владения и подати — ранняя всеобщая перепись.",
        "Normannische Adelige, Sprache und Recht veränderten England langfristig.",
        "Нормандские аристократы, язык и право надолго изменили Англию.",
        "Schlacht bei Hastings", "Гастингс",
    ),
    e(
        "Friedrich I. Barbarossa", "Фридрих I Барбаросса", 1189,
        "Staufer", "Штауфены",
        "Kaiser des Heiligen Römischen Reiches", "император Священной Римской империи",
        "der dritte Kreuzzug", "третий крестовый поход",
        "Kleinasiens", "Малая Азия",
        "Auseinandersetzungen mit Papst und italienischen Städten",
        "конфликты с папой и итальянскими городами",
        "Symbol staufischer Macht und Kreuzzugsideal", "символ власти штауфенов и идеала крестового похода",
        "Barbarossa führte 1189 den Dritten Kreuzzug an und ertrank 1190 im Saleph.",
        "Барбаросса возглавил третий поход (1189) и утонул в 1190 году в реке Салеф.",
        "Seine Politik verband Reichsgewalt, Italiens Städte und die Kurie.",
        "Его политика связывала империю, итальянские города и курию.",
        "Mythen um Barbarossa prägten das deutsche Mittelalter bis in die Neuzeit.",
        "Мифы о Барбароссе влияли на немецкую культуру до Нового времени.",
        "Dritter Kreuzzug", "Третий крестовый поход",
    ),
    e(
        "Richard Löwenherz", "Ричард Львиное Сердце", 1191,
        "Kreuzzüge", "Крестовые походы",
        "König von England", "король Англии",
        "die Belagerung von Akkon", "осада Акры",
        "Akkon", "Акра",
        "Verlust Jerusalems an Saladin", "потеря Иерусалима Саладином",
        "Vorstoß der Kreuzfahrer an die palästinensische Küste", "наступление крестоносцев на побережье Палестины",
        "Richard eroberte 1191 Akkon, konnte Jerusalem aber nicht dauerhaft zurückgewinnen.",
        "Ричард взял Акру в 1191 году, но не вернул Иерусалим надолго.",
        "Der Vertrag von Ramla (1192) sicherte Pilgern Zugang zu heiligen Stätten.",
        "Рамльский договор (1192) обеспечил паломникам доступ к святыням.",
        "Richard verbrachte nur wenige Monate in England – sein Ruf lebt vom Kreuzzug.",
        "Ричард провёл в Англии мало времени — слава связана с походом.",
        "Belagerung von Akkon", "Осада Акры",
    ),
    e(
        "Saladin", "Саладин", 1187,
        "Kreuzzüge", "Крестовые походы",
        "Sultan der Ayyubiden", "султан айюбидов",
        "die Rückeroberung Jerusalems", "возвращение Иерусалима",
        "Jerusalem", "Иерусалим",
        "Schwäche der Kreuzfahrerstaaten nach der Schlacht bei Hattin",
        "ослабление крестоносных государств после Хаттина",
        "Auslöser des Dritten Kreuzzugs", "повод для третьего крестового похода",
        "Saladin schlug 1187 die Kreuzfahrer bei Hattin und eroberte Jerusalem.",
        "Саладин разбил крестоносцев при Хаттине (1187) и взял Иерусалим.",
        "Er galt auch bei Christen als ehrenhafter Gegner.",
        "Даже у христиан его считали достойным противником.",
        "Ayyubidische Herrschaft verband Ägypten und Syrien.",
        "Власть айюбидов объединяла Египет и Сирию.",
        "Schlacht bei Hattin", "Хаттин",
    ),
    e(
        "Papst Urban II.", "папа Урбан II", 1095,
        "Kreuzzüge", "Крестовые походы",
        "Papst", "папа римский",
        "der Aufruf zum Ersten Kreuzzug in Clermont", "призыв к первому крестовому походу в Клермоне",
        "Clermont", "Клермон",
        "Byzantinische Bitte um Hilfe gegen die Seldschuken",
        "византийская просьба о помощи против сельджуков",
        "Massenbewegung aus Westeuropa gen Jerusalem", "массовое движение из Западной Европы к Иерусалиму",
        "1095 rief Urban II. in Clermont zum Kreuzzug auf – Beginn der großen Kreuzzüge.",
        "В 1095 году Урбан II призвал к походу в Клермоне — начало эпохи крестовых походов.",
        "Der Ruf verband religiöse, politische und soziale Motive.",
        "Призыв сочетал религиозные, политические и социальные мотивы.",
        "Der Erste Kreuzzug endete 1099 mit der Eroberung Jerusalems.",
        "Первый поход завершился взятием Иерусалима в 1099 году.",
        "Kreuzzugsaufruf Clermont", "Призыв в Клермоне",
    ),
    e(
        "Johanna von Orléans", "Жанна д'Арк", 1429,
        "Hundertjähriger Krieg", "Столетняя война",
        "Bauernmädchen und Heerführerin", "крестьянка и полководец",
        "die Erhebung der Belagerung von Orléans", "снятие осады Орлеана",
        "Orléans", "Орлеан",
        "Englische Vorstöße im Hundertjährigen Krieg", "наступление англичан в Столетней войне",
        "Wendepunkt zugunsten des französischen Königs", "перелом в пользу французского короля",
        "1429 führte Johanna französische Truppen und befreite Orléans.",
        "В 1429 году Жанна вывела французов и сняла осаду Орлеана.",
        "1431 wurde sie in Rouen als Ketzerin verbrannt.",
        "В 1431 году её сожгли в Руане как еретицу.",
        "1920 heiliggesprochen – Symbol französischer Nation.", "В 1920 году канонизирована — символ Франции.",
        "Belagerung von Orléans", "Осада Орлеана",
    ),
    e(
        "Edward III. von England", "Эдуард III", 1346,
        "Hundertjähriger Krieg", "Столетняя война",
        "König von England", "король Англии",
        "die Schlacht von Crécy", "битва при Креси",
        "Crécy", "Креси",
        "Streit um den französischen Thron", "спор о французском престоле",
        "englische Langbogen-Taktik im Krieg", "тактика длинного лука в войне",
        "1346 siegte England bei Crécy mit Langbogenschützen gegen französische Ritter.",
        "В 1346 году англичане победили при Креси благодаря лучникам.",
        "Der Krieg dauerte bis 1453 mit wechselnden Siegen.", "Война шла до 1453 года с переменным успехом.",
        "Crécy gilt als Wendepunkt der mittelalterlichen Kriegsführung.", "Креси — перелом в военном деле Средневековья.",
        "Schlacht von Crécy", "Креси",
    ),
    e(
        "König Johann Ohneland", "Иоанн Безземельный", 1215,
        "England", "Англия",
        "König von England", "король Англии",
        "die Unterzeichnung der Magna Carta", "подписание Великой хартии вольностей",
        "Runnymede", "Раннимид",
        "Konflikt mit Baronen und hohe Steuern", "конфликт с баронами и высокие налоги",
        "Begrenzung königlicher Macht durch Recht", "ограничение королевской власти законом",
        "1215 zwangen Barone Johann zur Magna Carta – Grundstein des englischen Rechts.",
        "В 1215 году бароны заставили Иоанна подписать Магну Карту — основа английского права.",
        "Nicht alle Klauseln galten lange, das Prinzip blieb.", "Не все статьи действовали долго, принцип остался.",
        "Die Charte wurde mehrfach erneuert.", "Хартию неоднократно подтверждали.",
        "Magna Carta", "Магна Карта",
    ),
]
