# -*- coding: utf-8 -*-
"""Standalone definition/concept questions for medieval section."""

EXTRA_CONCEPTS: list[dict] = [
    {
        "q_de": "Was versteht man unter dem Feudalsystem im Mittelalter?",
        "q_ru": "Что понимают под феодальной системой в Средневековье?",
        "ans_de": "Ein Herrschafts- und Besitzsystem auf Lehen und Treue",
        "ans_ru": "Система власти и владения на основе ленов и верности",
        "wrong_de": ["Nur Sklaverei", "Nur Städteautonomie", "Nur Papstmonarchie"],
        "wrong_ru": ["Только рабство", "Только городская автономия", "Только папская монархия"],
        "expl_de": "Feudalismus verband Grundherrschaft, Lehen und persönliche Treue zwischen Herr und Vasall.",
        "expl_ru": "Феодализм связывал земельную власть, лены и личную верность сеньора и вассала.",
        "year": 1100,
        "type": "definition",
        "difficulty": "medium",
        "tags": ["Feudalismus", "Gesellschaft"],
        "facts": [
            {"de": "Lehen konnte Land, Rechte oder Einkünfte sein; der Vasall schwor Treue und militärischen Beistand.", "ru": "Леном могли быть земля, права или доходы; вассал клялся в верности и военной помощи."},
            {"de": "Das System war regional verschieden – Frankreich, England und das Reich entwickelten eigene Formen.", "ru": "Система различалась по регионам — Франция, Англия и империя имели свои формы."},
            {"de": "Städte und Könige schwächten den Feudalismus später durch Geld und stehende Heere.", "ru": "Города и короли позже ослабляли феодализм через деньги и постоянные армии."},
        ],
    },
    {
        "q_de": "Was war ein Lehen im Mittelalter?",
        "q_ru": "Что такое лен в Средневековье?",
        "ans_de": "Vom Herrn überlassener Besitz gegen Dienste und Treue",
        "ans_ru": "Переданное сеньором владение в обмен на службу и верность",
        "wrong_de": ["Ein Kirchengeschenk ohne Pflichten", "Eine Steuer der Städte", "Ein Kriegsbeuteanteil"],
        "wrong_ru": ["Церковный дар без обязанностей", "Городской налог", "Доля военной добычи"],
        "expl_de": "Das Lehen war kein Eigentum im modernen Sinn, sondern ein Nutzungsrecht mit Pflichten.",
        "expl_ru": "Лен — не собственность в современном смысле, а право пользования с обязанностями.",
        "year": 1050,
        "type": "definition",
        "difficulty": "easy",
        "tags": ["Lehen", "Feudalismus"],
        "facts": [
            {"de": "Lehen konnte bei Treuebruch entzogen werden – ein wichtiger politischer Hebel.", "ru": "Лен могли отобрать за измену — важный политический рычаг."},
            {"de": "Unterlehen verbanden mehrere Ebenen: König – Herzog – Graf – Ritter.", "ru": "Подлены создавали цепочку: король — герцог — граф — рыцарь."},
            {"de": "In England sprach man oft von 'Tenure' und 'Homage'.", "ru": "В Англии говорили о «tenure» и «homage»."},
        ],
    },
    {
        "q_de": "Was kennzeichnete die Investiturstreitigkeit?",
        "q_ru": "Чем характеризовалась инвеститурная схватка?",
        "ans_de": "Streit um die Einsetzung von Bischöfen zwischen Papst und Kaiser",
        "ans_ru": "Спор о назначении епископов между папой и императором",
        "wrong_de": ["Streit um Kreuzzüge", "Streit um Zünfte", "Streit um Buchdruck"],
        "wrong_ru": ["Спор о крестовых походах", "Спор о цехах", "Спор о печати"],
        "expl_de": "Papst und Kaiser stritten, wer Bischöfe ernennt und investiert – Symbol für Kirche vs. Staat.",
        "expl_ru": "Папа и император спорили, кто поставляет епископов — символ борьбы церкви и государства.",
        "year": 1076,
        "type": "institution",
        "difficulty": "hard",
        "tags": ["Kirche", "Reich"],
        "facts": [
            {"de": "Heinrich IV. und Gregor VII. stehen für den Höhepunkt des Konflikts.", "ru": "Генрих IV и Григорий VII — вершина конфликта."},
            {"de": "Der Wormser Konkordat (1122) beendete den Streit vorläufig.", "ru": "Вормсский конкордат (1122) временно завершил спор."},
            {"de": "Canossa 1077 wurde zum politischen Mythos.", "ru": "Каносса 1077 стала политическим мифом."},
        ],
    },
    {
        "q_de": "Was war der Große Schisma (1378–1417)?",
        "q_ru": "Что такое Великая схизма (1378–1417)?",
        "ans_de": "Zeit mit mehreren rivalisierenden Päpsten",
        "ans_ru": "Период с несколькими соперничающими папами",
        "wrong_de": ["Trennung von Ost- und Westkirche 1054", "Reformation", "Konstanzer Konzil allein"],
        "wrong_ru": ["Разделение 1054 года", "Реформация", "Только Констанцский собор"],
        "expl_de": "Avignon und Rom hatten zeitweise je einen Papst; erst Konstanz beendete die Spaltung.",
        "expl_ru": "В Авиньоне и Риме были соперники; схизму преодолели в Констанце.",
        "year": 1378,
        "type": "institution",
        "difficulty": "hard",
        "tags": ["Kirche", "Schisma"],
        "facts": [
            {"de": "Die Kirchenspaltung schwächte die moralische Autorität der Kurie.", "ru": "Раскол ослабил моральный авторитет курии."},
            {"de": "Könige nutzten das Schisma für eigene Politik.", "ru": "Короли использовали схизму в своей политике."},
            {"de": "Martin V. wurde 1417 als einheitlicher Papst gewählt.", "ru": "В 1417 году избрали Мартина V единым папой."},
        ],
    },
    {
        "q_de": "Was versteht man unter Scholastik?",
        "q_ru": "Что такое схоластика?",
        "ans_de": "Mittelalterliche Methode: Glaube und Vernunft systematisch verbinden",
        "ans_ru": "Средневековый метод систематического соединения веры и разума",
        "wrong_de": ["Nur Klosterkunst", "Nur Ritterepik", "Nur Buchdruck"],
        "wrong_ru": ["Только монастырское искусство", "Только рыцарские эпосы", "Только книгопечатание"],
        "expl_de": "Scholastiker wie Thomas von Aquin ordneten Theologie mit aristotelischer Logik.",
        "expl_ru": "Схоласты вроде Фомы Аквинского соединяли теологию с логикой Аристотеля.",
        "year": 1250,
        "type": "definition",
        "difficulty": "medium",
        "tags": ["Scholastik", "Bildung"],
        "facts": [
            {"de": "Universitäten wie Paris und Oxford wurden Zentren der Scholastik.", "ru": "Париж и Оксфорд стали центрами схоластики."},
            {"de": "Disputationen waren zentrales Lehrformat.", "ru": "Диспуты были главной формой обучения."},
            {"de": "Aristoteles kam über arabische und jüdische Vermittler nach Europa.", "ru": "Аристотель пришёл в Европу через арабских и еврейских посредников."},
        ],
    },
    {
        "q_de": "Was war die Hanse?",
        "q_ru": "Что такое Ганза?",
        "ans_de": "Städtebund für Handel und Schutz in Nord- und Ostsee",
        "ans_ru": "Союз городов для торговли и защиты на Северном и Балтийском морях",
        "wrong_de": ["Ritterorden", "Bauernbund", "Kreuzfahrerstaat"],
        "wrong_ru": ["Рыцарский орден", "Крестьянский союз", "Крестоносное государство"],
        "expl_de": "Lübeck, Hamburg und viele andere Städte kooperierten im mittelalterlichen Fernhandel.",
        "expl_ru": "Любек, Гамбург и другие города сотрудничали в дальней торговле.",
        "year": 1356,
        "type": "economy",
        "difficulty": "medium",
        "tags": ["Handel", "Städte"],
        "facts": [
            {"de": "Die Hanse hatte Kontore in Brügge, London und Nowgorod.", "ru": "У Ганзы были конторы в Брюгге, Лондоне и Новгороде."},
            {"de": "Handel mit Fisch, Holz, Wachs und Tuch war zentral.", "ru": "Торговали рыбой, лесом, воском и тканями."},
            {"de": "Der Höhepunkt lag etwa im 14.–15. Jahrhundert.", "ru": "Расцвет пришёлся на XIV–XV века."},
        ],
    },
    {
        "q_de": "Was war die Schwarze Pest (1347 ff.)?",
        "q_ru": "Что такое Чёрная смерть (1347 и далее)?",
        "ans_de": "Eine verheerende Pestpandemie in Europa",
        "ans_ru": "Разрушительная чумная пандемия в Европе",
        "wrong_de": ["Nur Hungersnot in Irland", "Nur Krieg in Italien", "Nur Pocken im 18. Jh."],
        "wrong_ru": ["Только голод в Ирландии", "Только война в Италии", "Только оспа XVIII века"],
        "expl_de": "Die Pest tötete einen großen Teil der Bevölkerung und veränderte Wirtschaft und Gesellschaft.",
        "expl_ru": "Чума убила большую часть населения и изменила экономику и общество.",
        "year": 1347,
        "type": "cause_effect",
        "difficulty": "easy",
        "tags": ["Seuche", "Gesellschaft"],
        "facts": [
            {"de": "Folgen: Arbeitskräftemangel, Lohnsteigerungen, soziale Unruhen.", "ru": "Следствия: нехватка рабочих, рост плат, волнения."},
            {"de": "Flagellanten und religiöse Deutungen verbreiteten sich.", "ru": "Распространились флагелланты и религиозные толкования."},
            {"de": "Erreger heute: Yersinia pestis; Debatte über Übertragungswege.", "ru": "Возбудитель — Yersinia pestis; споры о путях передачи."},
        ],
    },
    {
        "q_de": "Was war ein Kreuzzug?",
        "q_ru": "Что такое крестовый поход?",
        "ans_de": "Vom Papst gebilligter Kriegszug ins Heilige Land",
        "ans_ru": "Одобренный папой поход на Святую землю",
        "wrong_de": ["Nur Wikingerfahrt", "Nur Hussitenkrieg", "Nur Städtekrieg"],
        "wrong_ru": ["Только поход викингов", "Только гуситская война", "Только городская война"],
        "expl_de": "Ab 1095 zogen christliche Heere nach Palästina; es gab mehrere große Kreuzzüge.",
        "expl_ru": "С 1095 года христианские войска шли в Палестину; было несколько больших походов.",
        "year": 1095,
        "type": "definition",
        "difficulty": "easy",
        "tags": ["Kreuzzüge", "Kirche"],
        "facts": [
            {"de": "Motivation: Religion, Ruhm, Land, Handel – oft gemischt.", "ru": "Мотивы: религия, слава, земля, торговля."},
            {"de": "Kreuzfahrerstaaten entstanden in Syrien und Palästina.", "ru": "Возникли крестоносные государства в Сирии и Палестине."},
            {"de": "Der Vierte Kreuzzug endete 1204 mit dem Angriff auf Konstantinopel.", "ru": "Четвёртый поход завершился захватом Константинополя в 1204."},
        ],
    },
    {
        "q_de": "Was war die Magna Carta (1215)?",
        "q_ru": "Что такое Магна Карта (1215)?",
        "ans_de": "Von König Johann unter Druck anerkannte Freiheitsrechte",
        "ans_ru": "Права, которые король Иоанн признал под давлением",
        "wrong_de": ["Vertrag von Verdun", "Goldene Bulle", "Wormser Konkordat"],
        "wrong_ru": ["Верденский договор", "Золотая булла", "Вормсский конкордат"],
        "expl_de": "Barone zwangen Johann zur Anerkennung von Rechten und Verfahrensregeln.",
        "expl_ru": "Бароны заставили Иоанна признать права и процедуры.",
        "year": 1215,
        "type": "institution",
        "difficulty": "medium",
        "tags": ["England", "Recht"],
        "facts": [
            {"de": "Nicht alle Klauseln galten dauerhaft, das Prinzip der Begrenzung der Krone blieb.", "ru": "Не все статьи действовали вечно, принцип ограничения короны остался."},
            {"de": "Die Charte wurde mehrfach bestätigt und ergänzt.", "ru": "Хартию неоднократно подтверждали."},
            {"de": "Sie gilt als wichtiger Schritt zur Rechtsstaatlichkeit.", "ru": "Считается шагом к верховенству права."},
        ],
    },
    {
        "q_de": "Was war die Goldene Bulle (1356)?",
        "q_ru": "Что такое Золотая булла (1356)?",
        "ans_de": "Reichsgesetz zur Kaiserwahl durch sieben Kurfürsten",
        "ans_ru": "Имперский закон о выборах императора семью курфюрстами",
        "wrong_de": ["Englische Charte", "Päpstliches Dekret", "Stadtrecht von Lübeck"],
        "wrong_ru": ["Английская хартия", "Папская булла", "Любекское право"],
        "expl_de": "Karl IV. regelte die Wahl des römisch-deutschen Königs/Kaisers stabil.",
        "expl_ru": "Карл IV закрепил порядок избрания римско-германского короля/императора.",
        "year": 1356,
        "type": "institution",
        "difficulty": "hard",
        "tags": ["Reich", "Recht"],
        "facts": [
            {"de": "Sieben Kurfürsten hatten das Wahlrecht – ein Kern des Reichsverfassungsrechts.", "ru": "Семь курфюрстов избирали императора — основа имперской конституции."},
            {"de": "Die Bulle sollte Machtkämpfe nach dem Interregnum eindämmen.", "ru": "Булла должна сдержать борьбу после интеррегнума."},
            {"de": "Sie blieb bis zum Reichsende 1806 grundlegend.", "ru": "Действовала до конца империи в 1806 году."},
        ],
    },
]
