# -*- coding: utf-8 -*-
"""Rich medieval entities – Batch 3: Russia, E.Europe, Vikings, England late, Mongols."""
from medieval_entity_helper import e

BATCH_R3 = [
    e(
        "Wladimir der Heilige", "Владимир Святой", 988,
        "Kiewer Rus", "Киевская Русь",
        "Kiewer Fürst und Taufherr der Rus", "киевский князь, крестивший Русь",
        "die Taufe der Kiewer Rus und die Einführung des Christentums", "крещение Руси и принятие христианства",
        "Kiew / Cherson", "Киев / Херсонес",
        "Politischer Bedarf an Legitimation und Bündnis mit Byzanz",
        "политическая потребность в легитимации и союзе с Византией",
        "Dauerhafte Verbindung der Rus mit der orthodoxen Kirche und byzantinischer Kultur",
        "постоянная связь Руси с православной церковью и Byzantine культурой",
        "Wladimir I. (ca. 958–1015) war zunächst Heide und hatte nach Berichten fünf Frauen und 800 Konkubinen. Nach dem Chronik befragte er Gesandte über Islam, Judentum, Rom und Byzanz – und wählte das griechische Christentum wegen seiner Schönheit. 988 ließ er sich und Kiew taufen; als Brautpreis erhielt er die byzantinische Prinzessin Anna.",
        "Владимир I (ок. 958–1015) поначалу был язычником и, по летописям, имел пять жён и 800 наложниц. Он якобы расспросил послов об исламе, иудаизме, западном и восточном христианстве — и выбрал греческое за красоту богослужения. В 988 году крестился сам и крестил Киев; в качестве свадебного подарка получил принцессу Анну.",
        "Die «Prüfung der Glaubensrichtungen» (Povest' vremennych let) ist wahrscheinlich legendär, zeigt aber das politische Kalkül: Byzanz war das reichste Reich in Reichweite; die Ehe mit einer Prinzessin verschaffte Legitimität. Der Islam wurde abgelehnt wegen des Alkoholverbots – «Die Freude der Rus ist das Trinken», soll Wladimir gesagt haben.",
        "«Испытание вер» (из «Повести временных лет») — вероятно, легенда, но отражает политический расчёт: Византия — богатейшая держава в досягаемости. Ислам отвергли из-за запрета алкоголя: «Руси есть веселие пити», — якобы сказал Владимир.",
        "Das Christentum veränderte die Kiewer Rus fundamental: Kyrillische Schrift (aus dem Bulgarischen übernommen), Kirchenbau, Bildung und Gesetzgebung nach byzantinischem Vorbild folgten. Kiew wurde zum «dritten Rom» in der Selbstwahrnehmung des späteren Moskau.",
        "Христианство фундаментально изменило Русь: кириллица, строительство церквей, образование и право по византийскому образцу. Позднее Москва провозгласит себя «третьим Римом».",
        tags=["Kiewer Rus", "Kirche", "Byzanz"],
    ),
    e(
        "Jaroslaw der Weise", "Ярослав Мудрый", 1019,
        "Kiewer Rus", "Киевская Русь",
        "Großfürst von Kiew, Höhepunkt der Kiewer Rus", "великий князь Киева, расцвет Киевской Руси",
        "den Höhepunkt der Kiewer Rus und das Rechtsbuch Russkaja Prawda", "расцвет Киевской Руси и «Русская Правда»",
        "Kiew", "Киев",
        "Bürgerkrieg nach Wladimirs Tod und Konsolidierung der Herrschaft",
        "гражданская война после смерти Владимира и укрепление власти",
        "Rechtsstaat, Kathedral-Bau, internationale Dynast-Heiraten",
        "правовое государство, строительство соборов, международные браки",
        "Jaroslaw der Weise (reg. 1019–1054) regierte Kiew auf seinem Höhepunkt: Er baute die Sophienkathedrale (nach Hagia Sophia), erließ die erste russische Gesetzessammlung (Russkaja Prawda) und vernetzte Kiew dynastisch mit Europa – Töchter wurden Königinnen in Frankreich, Norwegen und Ungarn.",
        "Ярослав Мудрый (правил 1019–1054) правил Киевом в расцвет: построил Софийский собор (по образцу Святой Софии), издал первый русский свод законов («Русская Правда») и связал Киев с Европой брачными союзами — дочери стали королевами Франции, Норвегии и Венгрии.",
        "Die Russkaja Prawda (ca. 1037) war ein modernes Gesetzbuch: Sie begrenzte Blutrache, regelte Erbschaft, Eigentumsrechte und Schulden. Sie zeigt eine komplexe Gesellschaft mit Kaufleuten, Handwerkern und Sklaven. Jaroslaw brach mit dem Prinzip «Auge um Auge» und führte Geldbußen ein.",
        "«Русская Правда» (ок. 1037) — современный для своего времени свод: ограничила кровную месть, регулировала наследство и долги. Она отказалась от принципа «око за око» и ввела денежные штрафы.",
        "Nach Jaroslaws Tod 1054 begann die Fragmentierung: Er teilte das Reich unter fünf Söhne. Das «Lehnsystem» der Rus führte zu konstantem Bruderzwist. 1240, beim Mongolensturm, war Kiew nur noch eine Zweitrangstadt; die politische Schwerkraft hatte sich nach Norden (Nowgorod) und Nordosten (Wladimir-Susdal) verlagert.",
        "После смерти Ярослава в 1054 году началась фрагментация: он разделил державу между пятью сыновьями. Постоянные усобицы ослабили Русь, и к 1240 году, при монгольском нашествии, Киев был лишь второстепенным городом.",
        tags=["Kiewer Rus", "Recht"],
    ),
    e(
        "Alexander Newski", "Александр Невский", 1242,
        "Kiewer Rus / Nowgorod", "Русь / Новгород",
        "Fürst von Nowgorod, Sieger auf dem Eis und Diplomat gegenüber den Mongolen", "новгородский князь, победитель на льду",
        "den Sieg auf dem Eis des Peipussees gegen den Deutschen Orden", "победу на льду Чудского озера",
        "Peipussee", "Чудское озеро",
        "Gleichzeitige Bedrohung aus Westen (Deutsche Ritter) und Osten (Mongolen)",
        "одновременная угроза с запада (немецкие рыцари) и востока (монголы)",
        "Erhalt Nowgorods vor Germanisierung; Unterwerfung unter mongolisches Joch",
        "сохранение Новгорода от германизации; подчинение монгольскому игу",
        "Alexander Newski (1220–1263) gewann 1240 die Newa-Schlacht gegen Schweden und 1242 die Eisschlacht (Bitwa na Ledowom Polische) gegen den Livländischen Orden. Beide Siege schützten Nowgorod. Zugleich unterwarf er sich den Mongolen, um Tribute zu zahlen statt zu kämpfen – eine pragmatische Entscheidung, die Russland vor der Vernichtung rettete.",
        "Александр Невский (1220–1263) в 1240 году выиграл Невскую битву против шведов, в 1242 году — Ледовое побоище против Ливонского ордена. Оба победы защитили Новгород. Одновременно он подчинился монголам, предпочтя платить дань вместо борьбы — прагматичное решение, спасшее Русь.",
        "Die Eisschlacht (1242) ist in der russischen Erinnerungskultur überlebensgroß: Eisenstein verfilmte sie 1938 im NS-Kontext als Warnung vor Deutschland. Historisch waren die Kämpfe kleiner als im Film: ein paar Tausend Kämpfer auf beiden Seiten, keine riesige Eiskatastrophe für die Ritter.",
        "Ледовое побоище (1242) огромно в русской культуре памяти: Эйзенштейн экранизировал его в 1938 году как предупреждение о германской угрозе. Исторически масштаб был меньше: несколько тысяч воинов с каждой стороны.",
        "Alexander wurde 1547 heiliggesprochen und 2008 von Russen zum «größten Russen aller Zeiten» gewählt. Er verkörpert das russische Bild des Staatsmanns: Nein zu westlichen Einfluss, Ja zu östlichen Anpassung – eine Vorlage für spätere russische Politik.",
        "В 2008 году россияне назвали Александра «величайшим русским всех времён». Он олицетворяет образ русского государственника: нет западному влиянию, да — восточному прагматизму.",
        tags=["Kiewer Rus", "Militär"],
    ),
    e(
        "Dmitri Donskoi", "Дмитрий Донской", 1380,
        "Russland / Goldene Horde", "Россия / Золотая Орда",
        "Fürst von Moskau, erster Sieger über die Mongolen auf dem Kulikowo Feld", "московский князь, первая победа над монголами",
        "den Sieg auf dem Kulikowo Feld und den Beginn des Endes des Mongolenjochs", "победу на Куликовом поле и начало конца монгольского ига",
        "Kulikowo Feld (Don)", "Куликово поле (Дон)",
        "Schwächung der Goldenen Horde durch Bürgerkriege und Aufstieg Moskaus",
        "ослабление Золотой Орды из-за усобиц и рост Москвы",
        "Erster militärischer Sieg der Rus über die Goldene Horde; Aufstieg Moskaus",
        "первая военная победа Руси над Золотой Ордой; возвышение Москвы",
        "Dmitri Donskoi (1350–1389) besiegte 1380 am Kulikowo Feld den Heerführer Mamai der Goldenen Horde – der erste große russische Sieg über die Mongolen. Es war kein endgültiger Sieg: 1382 brannte Toktamysch Moskau nieder. Aber der Mythos des Sieges stärkte das russische Nationalbewusstsein dauerhaft.",
        "Дмитрий Донской (1350–1389) в 1380 году разбил на Куликовом поле темника Мамая — первая большая победа над монголами. Окончательной она не стала: в 1382 году Тохтамыш сжёг Москву. Но миф этой победы навсегда укрепил русское национальное самосознание.",
        "Die Vorgeschichte: Dmitri baute Moskauer Kreml aus Kalkstein (1367) und zog Bojaren aus dem ganzen nordöstlichen Russland an. Er schaffte eine loyale, zentralisierte Führungsstruktur. Das war die Grundlage für den militärischen Sieg.",
        "Предыстория: Дмитрий построил Московский Кремль из белого камня (1367) и привлёк бояр из всего северо-восточного улуса. Это централизованное управление стало основой военной победы.",
        "Abt Sergius von Radonesch segnete Dmitris Armee vor Kulikowo. Diese Verbindung von Kirche und Militär wurde zum russischen Muster: Die Kirche legitimiert den Kampf des Fürsten, der Fürst schützt die Kirche.",
        "Игумен Сергий Радонежский благословил армию Дмитрия перед походом. Этот союз церкви и военной власти стал русским образцом на века.",
        tags=["Russland", "Mongolen", "Militär"],
    ),
    e(
        "Iwan III.", "Иван III Великий", 1480,
        "Russland", "Россия",
        "Großfürst von Moskau, «Sammler der russischen Länder»", "великий князь, «собиратель русских земель»",
        "das Ende des mongolischen Jochs und die Bildung des russischen Staates", "конец монгольского ига и создание российского государства",
        "Moskau", "Москва",
        "Schwächung der Goldenen Horde und Aufstieg Moskaus als politisches Zentrum",
        "ослабление Золотой Орды и возвышение Москвы",
        "Ende des mongolischen Jochs; Moskau als Erbe Byzanz' und «Drittes Rom»",
        "конец монгольского ига; Москва как наследница Византии, «третий Рим»",
        "Iwan III. (reg. 1462–1505) verdreifachte das Moskauer Fürstentum und beendete 1480 das mongolische Joch ohne Schlachtentscheidung: Er und Khan Achmat standen sich am Fluss Ugra gegenüber – und Ahmad zog ab. Iwan heiratete Sophia Palaiologos, Nichte des letzten byzantinischen Kaisers, und übernahm den Doppeladler als Wappen.",
        "Иван III (правил 1462–1505) утроил Московское княжество и в 1480 году завершил монгольское иго без сражения: «Стояние на Угре» — войска смотрели друг на друга, хан Ахмат ушёл. Иван женился на Софье Палеолог, племяннице последнего византийского императора, и принял двуглавого орла как герб.",
        "Das Konzept des «Dritten Roms» entstand nach Konstantinopels Fall (1453): Philotheus von Pskow schrieb um 1510, Moskau sei «das Dritte Rom» – Rom fiel, Konstantinopel fiel, Moskau wird nicht fallen. Das legitimierte Iwans Anspruch auf universale Herrschaft.",
        "Концепция «третьего Рима» возникла после 1453 года: монах Филофей писал, что Москва — «третий Рим» — Рим пал, Константинополь пал, Москва не падёт. Это легитимировало претензии Ивана на универсальную власть.",
        "Iwan war der erste russische Herrscher, der sich «Zar» (Caesar) nannte – offiziell erst sein Enkel Iwan IV. Die Umbenennung war politisch: «Zar» bedeutete Gleichstellung mit Byzanz und dem HRR.",
        "Иван первым из русских правителей именовал себя «царём» (Caesar), хотя официально этот титул закрепился при внуке Иване IV. Это политически уравнивало Москву с Византией и Священной Римской империей.",
        tags=["Russland", "Mongolen"],
    ),
    e(
        "Batu Khan", "Батый", 1237,
        "Mongolen / Goldene Horde", "Монголы / Золотая Орда",
        "Gründer der Goldenen Horde, Mongolen-Invasion Russlands und Europas", "основатель Золотой Орды, монгольское нашествие",
        "die Mongoleninvasion Russlands und Europas und die Gründung der Goldenen Horde", "монгольское нашествие на Русь и Европу",
        "Wolga / Osteuropa", "Волга / Восточная Европа",
        "Mongolische Westexpansion nach dem Tod Ögedei Khans",
        "монгольская экспансия на запад",
        "Mongolische Herrschaft über die Rus für 240 Jahre (bis 1480)",
        "монгольская власть над Русью в течение 240 лет (до 1480 года)",
        "Batu Khan (ca. 1205–1255), Enkel Genghis Khans, überquerte 1237 die Wolga und vernichtete die russischen Fürstentümer: Rjazan, Wladimir, Kiew (1240). 1241 drang er bis Legnica (Schlesien) und Mohi (Ungarn) vor – und zog sich dann zurück, weil Ögedei Khan gestorben war. Batu gründete die Goldene Horde an der Wolga.",
        "Батый (ок. 1205–1255), внук Чингисхана, в 1237 году перешёл Волгу и уничтожил русские княжества: Рязань, Владимир, Киев (1240). В 1241 году дошёл до Легницы (Силезия) и Мохи (Венгрия) — и отступил из-за смерти Угэдэя. Батый основал Золотую Орду на Волге.",
        "Legnica (1241) war eine Katastrophe für den polnischen Adel: Herzog Heinrich II. der Fromme fiel. Doch die Mongolen zogen ab, bevor sie das Reich weiter verheerten. Historiker streiten: War es wirklich der Tod des Großkhans, oder waren die Mongolen an ihrer Versorgungsgrenze angelangt?",
        "Легница (1241) стала катастрофой для польского дворянства: погиб герцог Генрих II Благочестивый. Историки спорят: причиной отхода монголов стала смерть Великого хана или они достигли предела снабжения?",
        "Die Goldene Horde war tolerant in Religionsfragen: Muslimische, christliche und buddhistische Untertanen wurden gleich behandelt. Erst im 14. Jahrhundert islamisierte sich die Horde vollständig. Dieser Pragmatismus erklärt die Langlebigkeit des Reiches.",
        "Золотая Орда была веротерпима: мусульмане, христиане и буддисты в её составе были равны. Лишь в XIV веке орда полностью исламизировалась. Этот прагматизм объясняет долговечность государства.",
        tags=["Mongolen", "Russland"],
    ),
    e(
        "Rurik", "Рюрик", 862,
        "Kiewer Rus", "Киевская Русь",
        "Gründer der Rus-Herrschaft in Nowgorod", "основатель варяжской власти в Новгороде",
        "die Gründung des ersten russischen Fürstentums in Nowgorod", "основание первого русского княжества в Новгороде",
        "Nowgorod", "Новгород",
        "Stammesfehden unter slawischen Stämmen und Einladung normannischer Herrscher",
        "межплеменные раздоры и приглашение варяжских правителей",
        "Begründung der Rurikiden-Dynastie (bis 1598) als Grundlage des russischen Staates",
        "основание Рюриковичей (до 1598 года) — фундамента русской государственности",
        "Laut Nestorchronik luden slawische Stämme 862 die Waräger unter Rurik ein: «Unser Land ist groß und reich, aber es gibt keine Ordnung darin.» Rurik ließ sich in Nowgorod nieder; sein Nachfolger Oleg zog 882 nach Kiew. Die Rurikiden regierten Russland bis 1598.",
        "По Нестеровской летописи, в 862 году славяне пригласили варягов под Рюриком: «Земля наша велика и обильна, а наряда в ней нет». Рюрик осел в Новгороде; его преемник Олег в 882 году захватил Киев. Рюриковичи правили Россией до 1598 года.",
        "Die historische Realität ist komplex: Waräger waren nordische Händler und Krieger (Wikinger), die die russischen Flüsse benutzten. Ihre Integration in die slawische Gesellschaft war schnell – schon in zweiter Generation wurden slawische Namen gebräuchlich. «Rus» leitet sich möglicherweise vom finnischen Ruotsi (Ruderer/Schweden) ab.",
        "Историческая реальность сложнее: варяги — скандинавские торговцы и воины, использовавшие русские реки. Они быстро ассимилировались: уже второе поколение носило славянские имена. «Русь» возможно происходит от финского Ruotsi (гребцы/шведы).",
        "Die Diskussion, ob die Rus «germanische» oder «slawische» Wurzeln hat, war politisch aufgeladen: Die «normannische Theorie» wurde im 19. Jahrhundert von deutschen Historikern betont und von russischen Nationalisten abgelehnt. Heute gilt ein Kompromiss: Die Waräger brachten Herrschaftsstrukturen, aber die Rus war immer slawisch-geprägt.",
        "Дискуссия о «норманнской теории» была политически острой: немецкие историки XIX века подчёркивали скандинавские корни, русские националисты отвергали. Сегодня компромисс: варяги принесли структуры власти, но Русь всегда была славянской по характеру.",
        tags=["Kiewer Rus"],
    ),
    e(
        "Alfred der Große", "Альфред Великий", 878,
        "England", "Англия",
        "König von Wessex, Retter Englands vor den Wikingern", "король Уэссекса, спаситель Англии от викингов",
        "den Frieden von Wedmore und die Stabilisierung Englands gegen die Wikinger", "мир в Ведморе и стабилизация Англии",
        "Wessex / Äthandun", "Уэссекс / Этандун",
        "Dänische Wikinger-Invasionen, die England fast vollständig kontrollierten",
        "датские набеги, почти полностью захватившие Англию",
        "Erhalt des angelsächsischen Englands; Grundlage für spätere Einigung",
        "сохранение англосаксонской Англии; основа будущего объединения",
        "Alfred der Große (849–899) war 878 nahe am Ende: Wikinger jagten ihn durch die Sümpfe von Somerset. Er sammelte Kräfte, besiegte die Dänen bei Äthandun und schloss mit Dänenführer Guthrum den Frieden von Wedmore – Guthrum ließ sich taufen. Alfred baute ein System von Burgen (burhs) und eine Marine auf.",
        "Альфред Великий (849–899) в 878 году был близок к краху: викинги гнали его по болотам Сомерсета. Он собрал силы, победил датчан при Этандуне и заключил мир в Ведморе — датский вождь Гутрум крестился. Альфред построил систему крепостей (бёрхов) и флот.",
        "Alfred war auch Bildungsreformer: Er übersetzte selbst lateinische Werke ins Altenglische (Gregor der Große, Boethius, Beda) und schuf ein Netz von Schulen. Das war Europa einzigartig – ein König als Schriftsteller und Übersetzer.",
        "Альфред был ещё и реформатором просвещения: лично переводил латинские труды на древнеанглийский (Григорий Великий, Боэций, Беда) и создал сеть школ. Единственный в Европе случай: король-писатель и переводчик.",
        "Alfred gab England eine Verfassung (Doom Book) und ein Rechtssystem. Sein Sohn Edward der Ältere und sein Enkel Äthelstan vollendeten die Einigung Englands. Der Beiname «der Große» wurde ihm erst im 16. Jahrhundert gegeben – der einzige englische König mit diesem Titel.",
        "Альфред дал Англии законодательство (Doom Book). Его сын Эдуард Старший и внук Этельстан завершили объединение. Прозвище «Великий» дано ему лишь в XVI веке — единственный английский король с таким титулом.",
        tags=["England", "Wikinger"],
    ),
    e(
        "Leif Eriksson", "Лейф Эрикссон", 1000,
        "Wikinger", "Викинги",
        "Normannischer Entdecker, erster Europäer in Amerika", "норманнский мореплаватель, первый европеец в Америке",
        "die Entdeckung Vinlands (Nordamerika) ca. 1000 n. Chr.", "открытие Винланда (Северная Америка) около 1000 года",
        "Vinland (Nordamerika)", "Винланд (Северная Америка)",
        "Wikinger-Expansion und Erkundungsfahrten über Island und Grönland hinaus",
        "викингская экспансия и разведывательные плавания",
        "Erste europäische Siedlung in Amerika (L'Anse aux Meadows, Neufundland)",
        "первое европейское поселение в Америке (Л'Ансе-о-Медоуз, Ньюфаундленд)",
        "Leif Eriksson (ca. 970–1020) segelte ca. 1000 n. Chr. von Grönland nach Vinland – heute identifiziert mit Neufundland (L'Anse aux Meadows). Die archäologische Stätte (entdeckt 1960) beweist normannische Präsenz. Die Kolonie wurde aufgegeben wegen Konflikten mit Einheimischen (Skraelings).",
        "Лейф Эрикссон (ок. 970–1020) около 1000 года отплыл из Гренландии в Винланд — ныне отождествляемый с Ньюфаундлендом (Л'Ансе-о-Медоуз). Археологический памятник (открыт в 1960 году) доказывает норманнское присутствие. Колония оставлена из-за конфликтов с местными жителями.",
        "L'Anse aux Meadows (entdeckt von Helge und Anne Ingstad 1960) ist die einzige archäologisch gesicherte normannische Siedlung in Amerika. Sie wurde UNESCO-Welterbe. Die Sagas (Grönländersaga, Saga von den Grönländern) beschreiben Vinland als fruchtbares Land mit Wildwein.",
        "Л'Ансе-о-Медоуз (открыт Хельге и Анной Ингстад в 1960 году) — единственное археологически подтверждённое норманнское поселение в Америке. Саги описывают Винланд как плодородный край с диким виноградом.",
        "Kolumbus' Entdeckung 1492 hatte dauerhafte Folgen – Leifs nicht. Warum? Keine Seuchen-Immunität der Europäer (noch), kein Metallvorteil, keine Überbevölkerung, kein direkter Wirtschaftsanreiz. Amerika hatte für die Wikinger keine verwertbaren Anreize in ausreichendem Maß.",
        "Открытие Лейфа не имело долгосрочных последствий — в отличие от Колумба. Причины: отсутствие экономических стимулов, металлургическое равенство с местными жителями, малая численность викингов.",
        tags=["Wikinger", "Entdeckungen"],
    ),
    e(
        "Rollo", "Ролло", 911,
        "Normannen", "Нормандия",
        "Wikinger-Anführer, Gründer der Normandie", "предводитель викингов, основатель Нормандии",
        "den Vertrag von Saint-Clair-sur-Epte und die Gründung der Normandie", "договор в Нормандии и основание Нормандии",
        "Normandie", "Нормандия",
        "Wikinger-Überfälle auf Frankreich und Unfähigkeit des Königs, sie zu stoppen",
        "набеги викингов на Францию и неспособность короля их остановить",
        "Normandie als mächtiges Herzogtum, Ursprung der normannischen Expansion",
        "Нормандия как мощное герцогство, источник норманнской экспансии",
        "Rollo (ca. 860–930) belagerte 911 Paris erfolglos, akzeptierte dann den Vertrag von Saint-Clair-sur-Epte: König Karl der Einfältige übergab ihm die Normandie als Lehen; Rollo ließ sich taufen, heiratete die Königstochter und schwor Treue. Seine Nachkommen wurden die mächtigsten Normannen Europas.",
        "Ролло (ок. 860–930) в 911 году осадил Париж, но неудачно, затем принял договор: король Карл Простоватый уступил ему Нормандию как лен; Ролло крестился, женился на королевской дочери и принёс присягу. Его потомки стали самыми могущественными норманнами Европы.",
        "Rollo integrierte sich schnell: Die Normannen übernahmen Französisch als Sprache und wurden innerhalb von zwei bis drei Generationen vollständig romanisiert. Rollofs Urenkel Wilhelm der Eroberer sprach kein Altnordisch mehr. Das zeigt die erstaunliche Anpassungsfähigkeit nordischer Einwanderer.",
        "Ролло и его потомки быстро ассимилировались: нормандцы перешли на французский и за два-три поколения полностью романизировались. Правнук Вильгельм Завоеватель уже не знал древнескандинавского.",
        "Von Rollof kommen Wilhelms der Eroberer und damit die englische Königsdynastie Plantagenet (durch Ehen). Rollo ist der Urururahn von Elisabeth II. von England – ein wikingisches Blut, das in Westminster überlebte.",
        "От Ролло происходит Вильгельм Завоеватель, а значит — вся английская королевская линия Плантагенетов. Ролло — предок Елизаветы II: викингская кровь, дожившая до Вестминстера.",
        tags=["Normannen", "Wikinger", "Frankreich"],
    ),
    e(
        "Knut der Große", "Кнуд Великий", 1016,
        "England / Skandinavien", "Англия / Скандинавия",
        "König von England, Dänemark und Norwegen", "король Англии, Дании и Норвегии",
        "seine Herrschaft über das Nordseereich und die Integration Englands", "управление Северным морским королевством",
        "London / Kopenhagen", "Лондон / Копенгаген",
        "Tod des englischen Königs Æthelred und dänische Invasion Englands",
        "смерть Этельреда и датское вторжение в Англию",
        "Nordseereich: erste transnationale Monarchie Nordeuropas",
        "Северное морское королевство: первая транснациональная монархия Северной Европы",
        "Knut der Große (ca. 995–1035) war König von England (1016), Dänemark (1018) und Norwegen (1028). Er regierte fair: Er behielt angelsächsische Gesetze, förderte die Kirche und stabilisierte England nach Jahrzehnten der Wikinger-Invasionen. Die «Knut-Legende» (er befahl dem Meer zurückzuweichen) illustriert seine Demut vor Gott.",
        "Кнуд Великий (ок. 995–1035) был королём Англии (1016), Дании (1018) и Норвегии (1028). Правил справедливо: сохранил англосаксонские законы, поддерживал церковь. Легенда о «волнах» (он приказал морю отступить) иллюстрирует его смирение перед Богом.",
        "Knuts Reich war ein persönliches Konstrukt ohne institutionelle Grundlagen. Nach seinem frühen Tod (1035, 40 Jahre) zerfiel es sofort. England fiel an seine Söhne, die unfähig waren; schließlich bestieg Eadward der Bekenner (ein Angelsachse) den Thron – was 1066 zur Normalen-Invasion führte.",
        "Держава Кнуда была личной конструкцией без институциональных основ. После его ранней смерти (1035, в ~40 лет) немедленно распалась. Англия перешла к неспособным сыновьям; на трон вернулся Эдуард Исповедник — что в 1066 году привело к норманнскому завоеванию.",
        "Knut war der erste dänische König, der nach Rom pilgerte und den Papst traf. Er handelte Handelsprivilegien für Dänen und Engländer aus. Er war mehr Staatsmann als Krieger – und wurde von späteren Chronisten als Ideal des «christianisierten Wikingerkönigs» dargestellt.",
        "Кнуд первым из датских королей совершил паломничество в Рим. Он договорился о торговых привилегиях для датчан и англичан. Образ «христианизированного викинга-короля» стал идеалом в позднейших хрониках.",
        tags=["England", "Wikinger", "Skandinavien"],
    ),
    e(
        "Bolesław I. Chrobry", "Болеслав I Храбрый", 1025,
        "Polen", "Польша",
        "Erster König Polens", "первый польский король",
        "die Krönung zum ersten König Polens", "коронация первого короля Польши",
        "Gnesen / Krakau", "Гнезно / Краков",
        "Gründung des polnischen Herzogstums und Rivalität mit dem HRR",
        "основание польского герцогства и соперничество со Священной Римской империей",
        "Polens Unabhängigkeit als Königreich und Aufnahme in die europäische Staatenfamilie",
        "независимость Польши как королевства и вступление в европейскую семью государств",
        "Bolesław I. Chrobry (967–1025) war der erste König Polens (gekrönt 1025 kurz vor seinem Tod). Er nutzte Kaiser Ottos III. Pilgerfahrt nach Gnesen (1000) – beim Gnesen-Kongress erhielt er Anerkennung als Herrscher. Er erweiterte Polen bis an die Oder, die Elbe und nach Böhmen.",
        "Болеслав I Храбрый (967–1025) — первый польский король (коронован в 1025 году незадолго до смерти). Он воспользовался паломничеством Оттона III в Гнезно (1000) — Гнезненский съезд принёс ему международное признание. Польша расширилась до Одера, Эльбы и Богемии.",
        "Der Gnesen-Kongress (1000) war ein diplomatisches Meisterstück: Bolesław empfing Kaiser Otto III. so prachtvoll, dass der Kaiser bewegt war. Otto legte die Krone seines Vorgängers auf Bolesławs Haupt – nicht als Unterwerfung, sondern als Gleichstellung. So entstand das Erzbistum Gnesen als polnische Kirchenprovinz.",
        "Гнезненский съезд (1000) был дипломатическим шедевром: Болеслав принял Оттона III так пышно, что тот был растроган. Оттон возложил на него свою корону — не как подчинение, а как равенство. Так возникло архиепископство Гнезно.",
        "Polen unter Bolesław war vorübergehend: Sein Nachfolger Mieszko II. verlor die meisten Gebiete. Die innere Schwäche – Adel gegen König, Heidnischer Aufstand 1037 – drückte Polen für ein Jahrhundert in die Zweitrangigkeit. Die Krönung 1025 blieb aber Fundament polnischer Nationalsagenhaftigkeit.",
        "Польша при Болеславе была временным явлением: его преемник Мешко II потерял большинство земель. Бунты знати и языческое восстание 1037 года надолго ослабили страну. Тем не менее коронация 1025 года стала основой польской национальной мифологии.",
        tags=["Polen", "Reich"],
    ),
    e(
        "Władysław II. Jagiełło", "Владислав II Ягайло", 1410,
        "Polen-Litauen", "Польша-Литва",
        "König von Polen-Litauen, Sieger von Grunwald", "король Польши-Литвы, победитель при Грюнвальде",
        "die Entscheidungsschlacht bei Grunwald gegen den Deutschen Orden", "решающее сражение при Грюнвальде против Тевтонского ордена",
        "Grunwald / Tannenberg", "Грюнвальд / Танненберг",
        "Konflikt mit dem Deutschen Orden um Gebiete Polens und Litauens",
        "конфликт с Тевтонским орденом за польские и литauische земли",
        "Schwächung des Deutschen Ordens; Polen-Litauen als stärkste Macht Ostmitteleuropas",
        "ослабление Тевтонского ордена; Польша-Литва — крупнейшая держава Восточной Европы",
        "Am 15. Juli 1410 besiegte Jagiełło bei Grunwald (Tannenberg) den Deutschen Orden in einer der größten Schlachten des Mittelalters. Die Ordensarmee wurde vernichtet; Hochmeister Ulrich von Jungingen fiel. Polen-Litauen war damit die dominante Macht Ostmitteleuropas. Der Sieg wurde 1914 von Hindenburg als «Tannenberg» propagandistisch überschrieben.",
        "15 июля 1410 года Ягайло при Грюнвальде (Танненберге) разгромил Тевтонский орден в одном из крупнейших сражений Средневековья. Орденская армия уничтожена, Великий магистр Ульрих фон Юнгинген погиб. Польша-Литва стала крупнейшей державой Восточной Европы.",
        "Die Jagiellonen wurden durch die polnisch-litauische Union (Krevo 1385) begründet: Jagiełło heiratete die polnische Königin Jadwiga und konvertierte Litauen zum Christentum. Das Bündnis veränderte Osteuropa dauerhaft und schuf eine Großmacht, die das HRR und Russland herausforderte.",
        "Ягеллоны возникли благодаря польско-литauской унии (Крево, 1385): Ягайло женился на польской королеве Ядвиге и обратил Литву в христианство. Союз создал державу, вызвавшую на спор и HRR, и Россию.",
        "Grunwald war kein Ende des Deutschen Ordens: Im Frieden von Thorn (1411) zahlte der Orden Lösegeld und verlor kaum Territorium. Erst der Zweite Thorner Frieden (1466) machte den Orden zum polnischen Vasallen. Der militärische Sieg war nicht sofort politisch umgesetzt.",
        "Грюнвальд не стал концом Тевтонского ордена: по Торнскому миру (1411) орден заплатил выкуп, но сохранил территории. Лишь в 1466 году орден стал польским вассалом.",
        tags=["Polen-Litauen", "Militär", "Deutschordensstaat"],
    ),
    e(
        "Jan Hus", "Ян Гус", 1415,
        "Hussitismus", "Гуситство",
        "Reformator, Märtyrer und Vorläufer der Reformation", "реформатор, мученик и предшественник Реформации",
        "seine Verurteilung und Verbrennung auf dem Konzil von Konstanz", "осуждение и сожжение на Констанцском соборе",
        "Konstanz", "Констанц",
        "Kirchenkritik und Forderung nach Reform (Simonie, Laienkelch, Ablässe)",
        "критика церкви и требование реформы (симония, чаша для мирян, индульгенции)",
        "Hussitische Revolution in Böhmen; Vorläufer der Reformation",
        "гуситская революция в Богемии; предтеча Реформации",
        "Jan Hus (ca. 1369–1415) war Dekan der Prager Universität und Prediger, beeinflusst von Wyclif. Er kritisierte Simonie, päpstliche Macht und verlangte den Laienkelch (Kommunion in beiden Arten). Kaiser Sigismund gab ihm freies Geleit nach Konstanz – und ließ ihn dennoch verbrennen (6. Juli 1415). Das löste die Hussitenkriege aus.",
        "Ян Гус (ок. 1369–1415) — декан Пражского университета, проповедник под влиянием Уиклифа. Критиковал симонию, папскую власть, требовал чашу для мирян. Император Сигизмунд дал ему охранную грамоту до Констанца — и всё равно позволил сжечь его (6 июля 1415). Это вызвало гуситские войны.",
        "Der Verrat an Hus war ein Politikum: Das Konzil von Konstanz stellte das Prinzip «Versprechen an Ketzer verpflichten nicht» auf. Kaiser Sigismund hoffte, mit Hus' Tod die böhmische Häresie zu beenden. Das Gegenteil trat ein: Hus wurde zum Märtyrer und Symbol.",
        "Предательство Гуса было политическим актом: собор утвердил принцип «обещания еретикам не обязывают». Сигизмунд надеялся покончить с чешской ересью — произошло обратное: Гус стал мучеником и символом.",
        "Luther besuchte 100 Jahre später Worms. Bevor er Worms betrat, sagte er: «Wenn auch so viele Teufel in Worms wären wie Ziegel auf dem Dach, ich würde dennoch hinein.» Hus hatte dasselbe gemacht – und verloren. Luther überlebte, weil der politische Kontext sich verändert hatte.",
        "За сто лет до Лютера Гус пришёл на собор с теми же убеждениями — и проиграл. Лютер выжил, потому что политический контекст изменился.",
        tags=["Hussitismus", "Kirche", "Böhmen"],
    ),
    e(
        "Jan Žižka", "Ян Жижка", 1420,
        "Hussitenkriege", "Гуситские войны",
        "Hussitischer Feldherr, der fünf Kreuzzüge zurückschlug", "гуситский полководец, отразивший пять крестовых походов",
        "die Wagenburg-Taktik und den Sieg bei Vítkov gegen den kaiserlichen Kreuzzug", "тактику вагенбурга и победу при Витков",
        "Böhmen / Prag", "Богемия / Прага",
        "Kaiserliche Kreuzzüge gegen hussitische Böhmen nach der Verbrennung von Hus",
        "имперские крестовые походы против гуситской Богемии",
        "Alle fünf Kreuzzüge scheiterten; hussitische Reformation überlebte",
        "все пять крестовых походов провалились; гуситская реформация выжила",
        "Jan Žižka (ca. 1360–1424) war fast blind, als er die Hussitenarmeen führte – am Ende völlig erblindet. Seine militärische Innovation war die Wagenburg (Fahrzeugfestung aus Wagen, Haken und Kanonen). Mit ihr schlug er 1420 die erste kaiserliche Kreuzzugsarmee bei Vítkov und gewann weitere vier Schlachten. Er starb an der Pest, besiegt nie.",
        "Ян Жижка (ок. 1360–1424) командовал армией гуситов, будучи почти слепым, а в конце — полностью незрячим. Его военная инновация — вагенбург (передвижная крепость из повозок, крюков и пушек). В 1420 году при Витков он разбил первую имперскую армию, затем выиграл ещё четыре сражения. Умер от чумы непобеждённым.",
        "Žižkas Wagenburg war eine Revolution im Kriegswesen: Sie machte Fußvolk gegen Ritterkavallerie effektiv, nutzte frühe Feuerwaffen und Artillerie systematisch. Diese Taktik beeinflusste spätere Militärstrategen und war Vorläufer moderner gepanzerter Taktik.",
        "Вагенбург Жижки был революцией в военном деле: сделал пехоту эффективной против рыцарской конницы, систематически использовал огнестрельное оружие и артиллерию. Эта тактика повлияла на последующих стратегов.",
        "Žižka hinterließ keine Biographie, nur Schlachtberichte. Sein Testament war militärisch: Er befahl, seine Haut zu einer Trommel zu gerben, damit er seine Feinde auch nach dem Tod erschrecke. Ob das stimmt, ist unklar – aber der Mythos ist real.",
        "Жижка не оставил биографии — только отчёты о сражениях. По преданию, в завещании он велел сделать из его кожи барабан, чтобы пугать врагов после смерти. Правда ли это — неизвестно, но миф жив.",
        tags=["Hussitenkriege", "Militär", "Böhmen"],
    ),
    e(
        "Schwarze Pest", "Чёрная смерть", 1347,
        "Pest", "Чума",
        "Die schlimmste Pandemie des Mittelalters", "самая страшная пандемie Средневековья",
        "die Pestwelle von 1347–1351 in Europa", "чумная волна 1347–1351 годов в Европе",
        "Sizilien / ganz Europa", "Сицилия / вся Европа",
        "Einschleppung der Pest durch Handelsschiffe aus dem Schwarzmeerraum",
        "занос чумы торговыми судами из Причерноморья",
        "Tod von 30–60 % der europäischen Bevölkerung; sozialer Wandel",
        "гибель 30–60% населения Европы; социальные перемены",
        "1347 brachten genuesische Schiffe aus der Krim die Pest nach Sizilien. Innerhalb von vier Jahren starben schätzungsweise 25–50 Millionen Europäer – 30–60 % der Bevölkerung. Ganze Dörfer wurden ausgelöscht. Die Ursache – Yersinia pestis, übertragen durch Flöhe auf Ratten – wurde erst 1894 entdeckt.",
        "В 1347 году генуэзские суда из Крыма занесли чуму в Сицилию. За четыре года погибло 25–50 миллионов европейцев — 30–60% населения. Целые деревни опустели. Возбудитель — Yersinia pestis, передаваемая блохами с крыс — открыт лишь в 1894 году.",
        "Die Juden wurden als Sündenböcke verfolgt: Angeblich hätten sie die Brunnen vergiftet. Pogrome vernichteten jüdische Gemeinden in Mainz, Straßburg, Frankfurt und vielen anderen Städten, bevor die Pest überhaupt ankam. Papst Clemens VI. erklärte die Juden für unschuldig – der Pöbel ignorierte das.",
        "Евреи стали козлами отпущения: якобы они отравили колодцы. Погромы уничтожили еврейские общины в Майнце, Страсбурге, Франкфурте — ещё до прихода чумы. Папа Климент VI объявил евреев невиновными — толпа проигнорировала это.",
        "Die sozialen Folgen waren immens: Arbeitermangel stärkte Bauern, die Löhne verlangen konnten. Leibeigenschaft wurde unrentabel. Der Totentanz (Danse Macabre) wurde zum Kunstmotiv. Die Kirche verlor Ansehen, weil Gebete nicht halfen. Flagellanten (Selbstgeißeler) zogen durch Europa.",
        "Социальные последствия были огромны: нехватка рабочих рук усилила крестьян. Крепостное право стало невыгодным. «Пляска смерти» (Danse Macabre) вошла в искусство. Церковь потеряла авторитет. По дорогам Европы бродили флагелланты.",
        "Pest-Epidemie 1347", "Чумная эпидемия 1347",
        tags=["Pest", "Gesellschaft"],
    ),
    e(
        "Hundertjähriger Krieg", "Столетняя война", 1337,
        "Hundertjähriger Krieg", "Столетняя война",
        "Längster Krieg des Mittelalters zwischen England und Frankreich", "длиннейшая война Средневековья",
        "den Ausbruch des Hundertjährigen Kriegs zwischen England und Frankreich", "начало Столетней войны между Англией и Францией",
        "Crécy / Orléans / Azincourt", "Креси / Орлеан / Азенкур",
        "Dynastischer Anspruch Eduards III. auf den französischen Thron",
        "наследственные претензии Эдуарда III на французский трон",
        "Ende: Frankreich behält alles außer Calais; englisches Frankreich-Projekt scheitert",
        "итог: Франция сохраняет всё, кроме Кале; английский проект провалился",
        "Der Hundertjährige Krieg (1337–1453) war kein ununterbrochener Kampf, sondern eine Serie von Kriegen. Drei Phasen: Englische Dominanz (Crécy 1346, Poitiers 1356), Französische Erholung (Bertrand du Guesclin), Englische Wiedergewinnung (Azincourt 1415) und endgültige französische Rückeroberung (Johanna von Orléans, Artillerie).",
        "Столетняя война (1337–1453) — не непрерывный конфликт, а серия войн. Три фазы: английское господство (Креси 1346, Пуатье 1356), французское восстановление (Бертран дю Геклен), английское возвращение (Азенкур 1415) и окончательная французская реконкиста (Жанна, артиллерия).",
        "Das Longbow-System revolutionierte den Krieg: Englische Bogenschützen konnten 12 Pfeile pro Minute schießen, durchdringen schwere Rüstungen auf 100 m und trafen Pferde. Bei Crécy (1346) wurden schätzungsweise 1 500 bis 2 000 französische Ritter getötet. Das Ende des Ritteradels als Kriegsentscheider begann hier.",
        "Английский длинный лук революционизировал войну: 12 стрел в минуту, пробивал доспехи на 100 м. При Креси (1346) убито 1500–2000 французских рыцарей. Здесь началось конец рыцарства как военной силы.",
        "Der Krieg kostete England sein Frankreich-Imperium – aber er schuf zwei Nationen: England und Frankreich wurden durch gemeinsamen Feind zu Nationalstaaten. Joan of Arc ist das Symbol der einen, das Longbow und der «Band of Brothers» das Symbol der anderen.",
        "Война стоила Англии её французской империи — но создала два нации. Франция и Англия сформировались как национальные государства через общего врага. Жанна — символ одной, длинный лук — другой.",
        "Kriegsausbruch 1337", "Начало войны 1337",
        tags=["Hundertjähriger Krieg", "England", "Frankreich"],
    ),
    e(
        "Edward III. von England", "Эдуард III Английский", 1346,
        "Hundertjähriger Krieg", "Столетняя война",
        "König von England, Sieger von Crécy und Begründer des Hosenbandordens", "король, победитель при Креси",
        "den Sieg bei Crécy und die Belagerung von Calais", "победу при Креси и осаду Кале",
        "Crécy / Calais", "Креси / Кале",
        "Ansprüche auf den französischen Thron durch Abstammung von Philipp IV.",
        "претензии на французский трон через родство с Филиппом IV",
        "Englische Militärdominanz; Calais als Stützpunkt bis 1558",
        "английское военное господство; Кале как опорный пункт до 1558 года",
        "Edward III. (reg. 1327–1377) besiegte 1346 bei Crécy die zahlenmäßig überlegene Französische Armee und nahm 1347 Calais nach langer Belagerung ein. Er gründete den Hosenbandorden (Orden vom Strumpfband, 1348) als Ritterorden. Sein Sohn, der Schwarze Prinz, gewann 1356 bei Poitiers.",
        "Эдуард III (правил 1327–1377) в 1346 году при Креси разгромил французскую армию, численно превосходившую его, и в 1347 году взял Кале после долгой осады. Он основал орден Подвязки (1348). Его сын, Чёрный принц, выиграл при Пуатье (1356).",
        "Crécy war eine Überraschung: Die Engländer mit 12 000 Mann besiegten 35 000–40 000 Franzosen. Die Überlegenheit des Langbogens war entscheidend; die Franzosen griffen unkoordiniert 15–16 mal an und wurden gemäht. König Johann von Böhmen starb dabei – sein Motto «Ich dien» übernahm der Schwarze Prinz als Prinz von Wales.",
        "Креси было сюрпризом: 12 000 англичан победили 35–40 тысяч французов. Длинный лук решил всё. Король Богемии Иоанн погиб в бою — его девиз «Ich dien» («Я служу») стал девизом принца Уэльского.",
        "Der Hosenbandorden ist der älteste erhaltene Ritterorden Englands (gegründet 1348). Die Legende: König Edward hob den entfallenen Strumpfband der Komtesse von Salisbury auf und sprach: «Honi soit qui mal y pense» (Schmach dem, der Böses dabei denkt). Das Motto blieb.",
        "Орден Подвязки (1348) — старейший сохранившийся рыцарский орден Англии. Легенда: Эдуард поднял упавшую подвязку графини Солсбери со словами «Honi soit qui mal y pense» («Позор тому, кто плохо об этом думает»).",
        tags=["England", "Hundertjähriger Krieg", "Militär"],
    ),
    e(
        "Sigismund von Luxemburg", "Сигизмунд Люксембургский", 1414,
        "Konstanzer Konzil", "Констанцский собор",
        "Kaiser und Organisator des Konzils von Konstanz", "император и организатор Констанцского собора",
        "das Konzil von Konstanz und die Beendigung des Papstschismas", "Констанцский собор и конец раскола папства",
        "Konstanz", "Констанц",
        "Drei simultane Päpste und Krise der Kirchenautorität",
        "три одновременных папы и кризис авторитета церкви",
        "Ende des Abendländischen Schismas; Wahl Martins V. als allgemein anerkannter Papst",
        "конец Западного раскола; избрание Мартина V как общепризнанного папы",
        "Das Konzil von Konstanz (1414–1418) war das größte Ereignis Europas seiner Zeit: 600 Prälaten, Tausende Kleriker und Adlige versammelten sich. Es beendete das Abendländische Schisma (drei simultane Päpste), verurteilte Hus und Wyclif und proklamierte die Konzilsüberordnung (Konziliarismus).",
        "Констанцский собор (1414–1418) — крупнейшее событие Европы той эпохи: 600 прелатов, тысячи клириков и дворян. Он завершил Западный раскол (три одновременных папы), осудил Гуса и Уиклифа, провозгласил превосходство собора над папой (соборность).",
        "Sigismunds Leistung: Er überredete alle drei Päpste (oder ihre Anhänger) zur Teilnahme oder Abdankung. Johannes XXIII. (der unmoralischste) wurde abgesetzt, Gregor XII. trat ab, Benedikt XIII. wurde ignoriert. 1417 wählte das Konzil Martin V. – ein Ende des Schismas nach 39 Jahren.",
        "Заслуга Сигизмунда: убедил всех трёх пап (или их сторонников) участвовать или отречься. Иоанн XXIII (самый порочный) отстранён, Григорий XII отрёкся, Бенедикт XIII игнорирован. В 1417 году собор избрал Мартина V — конец 39-летнего раскола.",
        "Das Verfahren gegen Hus (1415) war ein Justizskandal: Sigismunds Geleitbrief schützte Hus nicht. Das Konzil erklärte: Versprechen an Ketzer sind nicht bindend. Hus' Verbrennung entfachte die Hussitischen Kriege und schwächte Sigismunds Autorität in Böhmen dauerhaft.",
        "Процесс над Гусом был судебным скандалом: охранная грамота Сигизмунда не защитила. Собор заявил: обещания еретикам не обязательны. Сожжение Гуса вызвало гуситские войны и навсегда подорвало авторитет Сигизмунда в Богемии.",
        tags=["Reich", "Kirche", "Konstanzer Konzil"],
    ),
    e(
        "Matthias Corvinus", "Матьяш Корвин", 1458,
        "Ungarn", "Венгрия",
        "König von Ungarn, Renaissance-Herrscher in Mitteleuropa", "король Венгрии, ренессансный правитель",
        "seine Herrschaft als König und den Aufbau Ungarns zur Großmacht", "правление как короля и превращение Венгрии в великую державу",
        "Buda / Wien", "Буда / Вена",
        "Schwäche Ungarns nach Türkeneinfällen und innere Instabilität",
        "слабость Венгрии после турецких набегов и внутренняя нестабильность",
        "Ungarn als stärkste Macht Mitteleuropas und Renaissance-Zentrum",
        "Венгрия как сильнейшая держава Центральной Европы и центр Ренессанса",
        "Matthias Corvinus (reg. 1458–1490) war einer der bedeutendsten spätmittelalterlichen Herrscher: Er bezwang Wien (1485) und regierte es sechs Jahre. Er schuf die erste stehende Armee Mitteleuropas (die «Schwarze Armee»), förderte die Renaissance und sammelte über 2 000 Handschriften in der Bibliotheca Corviniana.",
        "Матьяш Корвин (правил 1458–1490) — один из крупнейших позднесредневековых правителей. Он завоевал Вену (1485) и правил там шесть лет. Создал первую постоянную армию Центральной Европы («Чёрную армию»), покровительствовал Ренессансу и собрал более 2000 рукописей в Bibliotheca Corviniana.",
        "Matthias war Humanist: Er lud italienische Gelehrte und Künstler an seinen Hof, ließ Bücher drucken und sprach Latein fließend. Buda wurde zu einem Zentrum der Renaissance nördlich der Alpen. Nach seinem Tod (1490) ohne Erben zerfiel alles: die Armee aufgelöst, die Bibliothek zerstreut.",
        "Матьяш был гуманистом: приглашал итальянских учёных и художников, печатал книги, свободно говорил по-латыни. Буда стала центром Ренессанса к северу от Альп. После смерти в 1490 году без наследника всё рухнуло.",
        "Das ungarische Volk liebte Matthias: Das Sprichwort «Matthias ist tot, Gerechtigkeit ist tot» zeugt davon. Er war für Bauern zugänglich, begrenzte adligen Willkür und reformierte das Recht. Sein Tod bedeutete das Ende der ungarischen Großmacht; 1526 folgte die Katastrophe von Mohács.",
        "Народ любил Матьяша: пословица «Матьяш умер — справедливость умерла» это отражает. После его смерти Венгрия пошла к упадку; в 1526 году последовала катастрофа при Мохаче.",
        tags=["Ungarn", "Renaissance"],
    ),
]
