# -*- coding: utf-8 -*-
"""Rich medieval entities – Batch 1: Franks, HRE, England, France to ~1300."""
from medieval_entity_helper import e

BATCH_R1 = [
    e(
        "Karl Martell", "Карл Мартелл", 732,
        "Frankenreich", "Франкское государство",
        "Hausmeier und Sieger von Poitiers", "майордом и победитель при Пуатье",
        "die Entscheidungsschlacht bei Tours und Poitiers", "битва при Пуатье",
        "Tours / Poitiers", "Тур / Пуатье",
        "Vordringen eines arabisch-berberischen Heeres über die Pyrenäen nach Gallien",
        "натиск арабо-берберских войск через Пиренеи в Галлию",
        "Stopp der islamischen Expansion nördlich der Pyrenäen",
        "остановка исламской экспансии к северу от Пиренеев",
        "Karl Martell schlug 732 bei Poitiers ein arabisch-berberisches Heer aus Spanien und stoppte den Vormarsch des Umayyaden-Kalifats in Westeuropa. Als Hausmeier herrschte er de facto über das Frankenreich, ohne König zu sein. Sein Beiname «Martell» (Hammer) verdankt er seinem Kampfstil und seiner militärischen Entschlossenheit.",
        "В 732 году Карл Мартелл разбил при Пуатье арабо-берберское войско из Испании и остановил продвижение Омейядского халифата. Будучи майордомом, он фактически правил Франкским государством без королевского титула. Прозвище «Мартелл» (Молот) отражает его боевую манеру.",
        "Karl Martell finanzierte sein Heer durch eine radikale Maßnahme: Er säkularisierte massenhaft Kirchengüter und gab sie Kriegern als Lehen. Das war eine Frühform des Feudalsystems. Bischöfe akzeptierten dies widerwillig als zeitweilige «Leihe» – doch viele Güter kamen nie zurück.",
        "Карл финансировал войско, конфисковав церковное имущество и раздав его воинам как лены — ранняя форма феодализма. Епископы приняли это как временный «займ», но многое так и не вернулось.",
        "Neuere Historiker streiten über das Ausmaß der Bedrohung: Möglicherweise war es kein strategischer Angriff, sondern ein großer Plünderungszug. Dennoch gilt der Sieg als Wendepunkt, der weitere arabische Vorstöße verhinderte und die karolingische Herrschaft religiös legitimierte.",
        "Историки спорят: возможно, это был не стратегический поход, а масштабный набег. Тем не менее победа предотвратила дальнейшие вторжения и дала каролингской власти религиозную легитимность.",
        "Sieg bei Poitiers 732", "Победа при Пуатье 732",
        tags=["Frankenreich", "Militär"],
    ),
    e(
        "Pippin III.", "Пипин III Короткий", 751,
        "Frankenreich", "Франкское государство",
        "Erster karolingischer König, Sohn Karl Martells", "первый Каролинг-король, сын Карла Мартелла",
        "die Absetzung der Merowinger und die päpstliche Salbung zum König", "отстранение Меровингов и папское помазание",
        "Soissons / Rom", "Суасон / Рим",
        "Machtlosigkeit der letzten Merowingerkönige und Suche nach Legitimation",
        "бессилие последних Меровингов и поиск легитимации",
        "Begründung der karolingischen Königsdynastie und des päpstlich-fränkischen Bündnisses",
        "основание каролингской династии и союза папства с франками",
        "Pippin III. ließ sich 751 von Papst Zacharias legitimieren und anschließend von Bischof Bonifatius salben – eine Innovation: Nicht Blut, sondern Gottes Segen begründete die Herrschaft. Den letzten Merowinger Childerich III. schickte er ins Kloster. Als Gegenleistung schenkte Pippin dem Papst das Exarchat von Ravenna – Grundlage des Kirchenstaats.",
        "В 751 году Пипин III получил одобрение папы Захарии и был помазан Бонифацием — новшество: не кровь, а Божье благословение легитимирует власть. Последнего Меровинга Хильдерика III он заключил в монастырь. В ответ Пипин подарил папе Равеннский экзархат — основу папского государства.",
        "Der «Pippinische Schenkung» (754–756) schuf erstmals ein weltliches Herrschaftsgebiet der Kirche in Mittelitalien. Diese Schenkung wurde im Mittelalter durch die gefälschte «Konstantinische Schenkung» nachträglich legitimiert. Das Papsttum behielt diesen Besitz – mit Unterbrechungen – bis 1870.",
        "«Пипинов дар» (754–756) впервые создал светское владение церкви в Средней Италии. Это имущество папство держало — с перерывами — вплоть до 1870 года.",
        "Pippins Sohn wurde Karl der Große. Das System des päpstlich-fränkischen Bündnisses – militärischer Schutz gegen religiöse Legitimation – prägte die europäische Politik für Jahrhunderte.",
        "Сыном Пипина стал Карл Великий. Система союза — военная защита в обмен на религиозную легитимацию — определяла европейскую политику столетиями.",
        "Pippin legte den Grundstein der Karolinger: Ohne seine Legitimationsinnovation (Salbung statt Geblütsrecht) hätte Karls Kaisertum nicht die sakrale Basis gehabt. Die Formel «Gottesgnaden-Königtum» (Dei gratia rex) – die bis heute in Königstiteln nachwirkt – ist Pippins Erbe.",
        "Пипин заложил фундамент Каролингов: без его инновации — помазания вместо права крови — у Карла не было бы сакральной основы для императорской власти. Формула «Божьей милостью король» (Dei gratia rex) — его наследие.",
        tags=["Frankenreich", "Kirche"],
    ),
    e(
        "Karl der Große", "Карл Великий", 800,
        "Frankenreich", "Франкское государство",
        "König der Franken und erster westlicher Kaiser", "король франков и первый западный император",
        "die Kaiserkrönung durch Papst Leo III. in Rom", "коронация Карла Великого папой Львом III",
        "Rom", "Рим",
        "Einigung Westeuropas unter fränkischer Herrschaft und päpstliches Schutzbedürfnis",
        "объединение Западной Европы под франкской властью",
        "Begründung des westlichen Kaisertums und Grundlage europäischer Staatlichkeit",
        "основание западного императорского титула и европейской государственности",
        "Am 25. Dezember 800 krönte Papst Leo III. Karl in der Peterskirche zum Kaiser – eine Überraschung laut Einhard, aber sorgfältig geplant. Karl regierte ein Reich von der Nordsee bis zum Ebro und Tiber, führte über 50 Feldzüge und reformierte Recht, Kirche und Bildung. Sein Aachener Hof wurde zum kulturellen Zentrum Europas – die «karolingische Renaissance» mit Alkuin, Einhard und Angilbert.",
        "25 декабря 800 года папа Лев III короновал Карла в Петровском соборе. Карл правил от Северного моря до Эбро и Тибра, провёл более 50 походов и реформировал право, церковь и образование. Его двор в Ахене с Алкуином, Эйнхардом и Ангильбертом стал центром «каролингского возрождения».",
        "Die Christianisierung der Sachsen (772–804) war brutal: Nach dem Aufstand von 782 ließ Karl laut Reichsannalen bei Verden 4 500 Gefangene enthaupten. Erst der Vertrag von Salz (803) beendete den Widerstand. Widukind, der Anführer der Sachsen, ließ sich taufen und diente fortan am fränkischen Hof.",
        "Христианизация саксов (772–804) была жестокой: в 782 году в Вердене казнили 4500 заложников. Вождь саксов Видукинд принял крещение и поступил на франкскую службу.",
        "Karls Hof erfand die karolingische Minuskel – eine lesbare Handschrift, die heutigen Druckbuchstaben zugrunde liegt. Der Begriff «Europa» erscheint in karolingischen Quellen erstmals als politisches Konzept für Karls Reich. Nach 814 teilten seine Enkel das Reich im Vertrag von Verdun (843) – Vorläufer von Frankreich, Deutschland und Italien.",
        "Двор Карла изобрёл каролингский минускул — почерк, ставший основой современных шрифтов. Слово «Европа» впервые употреблено в каролингских текстах как политический термин. После 843 года Верденский договор разделил державу на прообразы Франции, Германии и Италии.",
        "Kaiserkrönung 800", "Коронация 800 года",
        tags=["Frankenreich", "Kaiser", "Kirche"],
    ),
    e(
        "Vertrag von Verdun", "Верденский договор", 843,
        "Karolingerreich", "Каролингская империя",
        "Grundurkunde der europäischen Teilung", "основополагающий акт раздела Европы",
        "die Dreiteilung des Karolingerreichs unter den Enkeln Karls des Großen", "раздел державы Карлингов между внуками Карла",
        "Verdun", "Верден",
        "Erbstreitigkeiten nach dem Tod Ludwigs des Frommen und Bürgerkriege der Söhne",
        "наследственные споры после смерти Людовика Благочестивого",
        "Entstehung von Vorläufern moderner Nationen: Frankreich, Deutschland, Italien",
        "зарождение прообразов Франции, Германии и Италии",
        "843 einigten sich Karls Enkel Lothar I., Ludwig der Deutsche und Karl der Kahle auf die Dreiteilung des Frankenreichs. West-, Mittel- und Ostfrankreich entstanden. Das Mittelreich zerfiel nach Lothars Tod weiter; West- und Ostfrankreich wurden Kern der späteren Nationen. Europas heutige Staatengrenzen hängen indirekt von diesem Vertrag ab.",
        "В 843 году внуки Карла — Лотарь I, Людовик Немецкий и Карл Лысый — разделили империю на три части. Срединное королевство после смерти Лотаря распалось дальше; западная и восточная части стали основой будущих Франции и Германии.",
        "Die Straßburger Eide (842) – Vorläufer des Vertrags – wurden erstmals auf Altfranzösisch und Althochdeutsch geschworen, damit die Soldaten des jeweils anderen Bruders sie verstanden. Diese Eide sind die ältesten erhaltenen Texte in romanischer und germanischer Volkssprache.",
        "Страсбургские клятвы (842) — предшественник договора — принесены впервые на старофранцузском и древневерхненемецком. Это древнейшие сохранившиеся тексты на романском и германском народных языках.",
        "Das «Frankenreich» war nie ein echter Nationalstaat: Regionale Identitäten, Sprachgrenzen und ethnische Unterschiede existierten längst. Der Vertrag von Verdun machte aus einer Fiktion mehrere Realitäten.",
        "Договор показал: «Франкская империя» никогда не была единым государством. Региональные идентичности, языковые границы и этнические различия уже существовали.",
        tags=["Karolingerreich", "Teilung"],
    ),
    e(
        "Otto I.", "Оттон I Великий", 962,
        "Heiliges Römisches Reich", "Священная Римская империя",
        "Begründer des Heiligen Römischen Reiches", "основатель Священной Римской империи",
        "die Kaiserkrönung in Rom und die Schaffung des HRR", "коронация в Риме и основание Священной Римской империи",
        "Rom", "Рим",
        "Stabilisierung des ostfränkischen Reiches nach Ungarnüberfällen",
        "стабилизация государства после набегов венгров",
        "Begründung des deutsch-römischen Kaisertums als Grundlage des HRR bis 1806",
        "основание германо-римского императорского титула",
        "Am 2. Februar 962 krönte Papst Johannes XII. Otto I. zum Kaiser – traditionell Gründungsdatum des Heiligen Römischen Reiches. Otto hatte 955 auf dem Lechfeld die ungarischen Reiter vernichtend geschlagen und damit eine 50-jährige Bedrohung beendet. Er stützte sich auf Bischöfe und Äbte als Reichsverwalter – das «ottonische Reichskirchensystem».",
        "2 февраля 962 года папа Иоанн XII короновал Оттона I — традиционная дата основания Священной Римской империи. В 955 году Оттон разгромил венгров на Лехфельде, положив конец пятидесятилетней угрозе. Его «оттоновская имперская церковь» опиралась на епископов как государственных администраторов.",
        "Die Lechfeld-Schlacht (955) war der entscheidende Sieg: Sieben Stammesherzogtümer kämpften vereint. Teile des ungarischen Heers wurden gefangen und gehenkt. Dieser Sieg festigte Ottos Autorität und wurde später als Rettung des christlichen Abendlands gefeiert.",
        "На Лехфельде (955) семь племенных герцогств сражались вместе. Победа укрепила авторитет Оттона и была прославлена как спасение христианского Запада.",
        "Das HRR blieb Wahlmonarchie: Könige wurden von Fürsten gewählt, nicht vererbt. Diese Besonderheit unterschied es grundlegend von Frankreich und England und blieb bis 1806 strukturbestimmend.",
        "Священная Римская империя оставалась выборной монархией — в отличие от Франции и Англии — вплоть до 1806 года.",
        "Kaiserkrönung 962", "Коронация 962 года",
        tags=["Kaiser", "Heiliges Römisches Reich"],
    ),
    e(
        "Heinrich IV.", "Генрих IV", 1077,
        "Investiturstreit", "Инвеститурный спор",
        "Kaiser im Investiturstreit, Gang nach Canossa", "emperor in the Investiture Controversy",
        "den Bußgang nach Canossa vor Papst Gregor VII.", "покаяние в Каноссе перед папой Григорием VII",
        "Canossa", "Каносса",
        "Streit um das Recht, Bischöfe einzusetzen – Kaiser gegen Papst",
        "спор о праве назначать епископов — император против папы",
        "Aufhebung des Kirchenbans; langfristig Wormser Konkordat (1122)",
        "снятие отлучения; долгосрочно — Вормсский конкордат (1122)",
        "1076 exkommunizierte Papst Gregor VII. Heinrich IV. und entband seine Untertanen vom Treueid – ein nie dagewesener Schritt. Im Januar 1077 erschien Heinrich als büßender Pilger vor Burg Canossa und stand drei Tage barfuß im Schnee, bis Gregor die Exkommunikation aufhob. Der «Gang nach Canossa» wurde zum Sinnbild öffentlicher Demütigung.",
        "В 1076 году папа Григорий VII отлучил Генриха IV и освободил подданных от присяги. В январе 1077 года Генрих явился в Каноссу кающимся паломником и три дня стоял босой на снегу, пока папа не снял отлучение. «Поход в Каноссу» стал символом публичного унижения.",
        "Gregor VII. war in einer Zwickmühle: Als Seelsorger musste er dem Büßer vergeben, verlor dabei politisch. Heinrich nutzte das clever – der Bann war weg, die deutschen Fürsten fanden keinen neuen König. Wenig später vertrieb Heinrich Gregor aus Rom; der Papst starb 1085 in Salerno im Exil.",
        "Григорий оказался в ловушке: как пастырь обязан простить кающегося, но политически проиграл. Генрих умело использовал ситуацию — отлучение снято, а потом он изгнал папу из Рима. Григорий умер в 1085 году в Салерно.",
        "Bismarcks Ausspruch «Nach Canossa gehen wir nicht» (1872) im Kulturkampf machte das Ereignis zum deutschen Politikmythos. Der Begriff bezeichnet bis heute jede öffentliche Unterwerfung unter eine überlegene Macht.",
        "Слова Бисмарка «В Каноссу мы не пойдём» (1872) превратили это событие в немецкий политический миф. Выражение обозначает любое публичное подчинение превосходящей силе.",
        tags=["Investiturstreit", "Kaiser"],
    ),
    e(
        "Gregor VII.", "Григорий VII", 1075,
        "Papst", "Папство",
        "Reformpapst und Architekt der gregorianischen Reform", "реформатор-папа, архитектор григорианской реформы",
        "den Dictatus Papae und die Durchsetzung päpstlicher Suprematie", "Диктат папы и утверждение папского верховенства",
        "Rom", "Рим",
        "Simonie, Nikolaitismus und Laieninvestitur als Korrumpierung der Kirche",
        "симония, николаитизм и мирская инвеститура как коррупция церкви",
        "Begründung des unabhängigen Reformpapsttums und päpstlicher Vorrang über Könige",
        "основание независимого реформированного папства с верховенством над королями",
        "Gregor VII. (Hildebrand) veröffentlichte 1075 den «Dictatus Papae» – 27 Thesen päpstlicher Allgewalt: Nur der Papst ernennt Bischöfe, setzt Kaiser ab, beruft Konzilien. Diese Radikalpositionen provozierten den Investiturstreit mit Heinrich IV. Gregor starb 1085 im Exil in Salerno mit den Worten: «Ich liebte Gerechtigkeit und hasste Ungerechtigkeit – deshalb sterbe ich in der Verbannung.»",
        "Григорий VII (Гильдебранд) опубликовал в 1075 году «Диктат папы» — 27 тезисов о всевластии папы: только папа назначает епископов, низлагает императоров, созывает соборы. Это спровоцировало спор с Генрихом IV. Папа умер в 1085 году в изгнании: «Я любил справедливость и ненавидел неправду — потому умираю в изгнании».",
        "Gregor reformierte Kirchenzucht: Er bestand auf Zölibat und verbot Simonie. Tausende verheirateter Priester und käuflicher Bischöfe widersetzten sich – aber langfristig setzte die Reform durch. Das Konklav (beschlossen 1059) als Papstwahl durch Kardinäle ist ebenfalls sein Erbe.",
        "Григорий настаивал на целибате и запрете симонии. Тысячи женатых священников и купленных епископов сопротивлялись, но реформа в итоге победила. Конклав (1059) как форма папских выборов — тоже его наследие.",
        "Gregorianische Reform bedeutete: Die Kirche ist kein Teil des Feudalstaats. Dieser Grundsatz schuf die bis heute gültige Trennung zwischen kirchlicher und weltlicher Verwaltung in Europa.",
        "Григорианская реформа утвердила: церковь — не часть феодального государства. Этот принцип создал разделение церковного и светского управления, действующее в Европе по сей день.",
        tags=["Papst", "Investiturstreit"],
    ),
    e(
        "Wormser Konkordat", "Вормсский конкордат", 1122,
        "Investiturstreit", "Инвеститурный спор",
        "Kompromiss über die Bischofseinsetzung und Ende des Investiturstreits", "компромисс об инвеституре и конец инвеститурного спора",
        "den Abschluss des Wormser Konkordats zwischen Kaiser und Papst", "заключение Вормсского конкордата",
        "Worms", "Вормс",
        "Fünfzigjähriger Kampf zwischen Kaiser und Papst um das Recht der Bischofseinsetzung",
        "пятидесятилетний конфликт о праве назначения епископов",
        "Trennung geistlicher und weltlicher Investitur als dauerhaftes Prinzip",
        "разграничение духовной и светской инвеституры как постоянный принцип",
        "Das Wormser Konkordat (1122) zwischen Heinrich V. und Papst Calixt II. löste den Investiturstreit durch eine intelligente Unterscheidung: Der Kaiser verleiht dem Bischof das weltliche Amt mit dem Zepter, aber erst nach der kirchlichen Weihe durch den Papst. Damit behielt der Papst die geistliche, der Kaiser die weltliche Seite – ein Kompromiss, der niemanden voll befriedigte, aber Bestand hatte.",
        "Конкордат (1122) между Генрихом V и Каллистом II разрешил спор умным разграничением: король вручает скипетр уже после церковного посвящения. Духовная сторона — за папой, светская — за королём. Никто не был вполне доволен, но договор устоял.",
        "In Deutschland blieben Kaiser de facto einflussreich bei der Bischofswahl: Bischöfe blieben Reichsfürsten und Berater des Kaisers. In Italien verlor der Kaiser mehr: Norditalienische Bischöfe orientierten sich stärker an Rom. Das Konkordat spaltete damit die Wirkung des Investiturstreits regional.",
        "В Германии императоры сохранили реальное влияние на выборы епископов. В Италии потеряли больше: северноитальянские епископы тяготели к Риму. Конкордат по-разному подействовал в разных регионах.",
        "Der Investiturstreit etablierte ein Grundprinzip der westlichen Zivilisation: Kirche und Staat sind getrennte Sphären. Ohne Gregor und Canossa hätte Europa möglicherweise eine Theokratie oder eine vollständig staatliche Kirche entwickelt.",
        "Спор установил базовый принцип: церковь и государство — разные сферы. Без Григория и Каноссы Европа могла бы пойти по пути теократии или государственной церкви.",
        tags=["Investiturstreit", "Recht"],
    ),
    e(
        "Friedrich I. Barbarossa", "Фридрих I Барбаросса", 1152,
        "Staufer", "Штауфены",
        "Kaiser des Heiligen Römischen Reiches, «Rotbart»", "германский император, «Краснобородый»",
        "seine sechs Italienfeldzüge und die Niederlage bei Legnano", "шесть итальянских походов и поражение при Леньяно",
        "Oberitalien / Legnano", "Северная Италия / Леньяно",
        "Machtkämpfe zwischen Kaiser, Lombardischem Städtebund und Papst",
        "соперничество между императором, Ломбардской лигой и папой",
        "Schwächung der Kaiserautorität in Italien; Friede von Konstanz (1183)",
        "ослабление имперской власти в Италии; Констанцский мир (1183)",
        "Friedrich I. Barbarossa (reg. 1152–1190) unternahm sechs Züge nach Italien und kämpfte gegen den Lombardischen Städtebund. 1176 schlug ihn das Städteheer bei Legnano vernichtend – erstmals besiegte ein städtisches Fußvolk schwere Ritterkavallerie. Der Friede von Konstanz (1183) gewährte den Städten faktische Autonomie. 1190 ertrank Friedrich auf dem Weg zum Dritten Kreuzzug im Fluss Saleph.",
        "Фридрих I Барбаросса (правил 1152–1190) шесть раз ходил в Италию. В 1176 году Ломбардская лига разгромила его при Леньяно — впервые городская пехота победила тяжёлую рыцарскую конницу. Констанцский мир (1183) дал городам фактическую автономию. В 1190 году Барбаросса утонул в реке Салеф.",
        "Die Niederlage bei Legnano war ein militärischer Paradigmenwechsel: Die «unbesiegbare» schwere Kavallerie verlor gegen disziplinierte Infanterie. Es war ein Vorgeschmack auf das Ende der ritterlichen Dominanz im Krieg, die erst mit den Schlachten von Crécy (1346) und Azincourt (1415) vollendet wurde.",
        "Поражение при Леньяно стало военным переломом: «непобедимая» тяжёлая конница проиграла дисциплинированной пехоте — предвестник конца рыцарского господства в войне.",
        "Der Barbarossa-Mythos entstand im 19. Jahrhundert: Er schlafe im Kyffhäuser-Berg und kehre zurück, wenn Deutschland ihn braucht. Kaiser Wilhelm I. ließ dort ein Denkmal errichten. Die Hitler-Armee nannte ihren Russland-Überfall 1941 «Unternehmen Barbarossa».",
        "Миф XIX века: Барбаросса спит в горе Кюффхойзер и вернётся в нужный момент. Операция нацистской Германии против СССР в 1941 году называлась «Барбаросса».",
        tags=["Staufer", "Kaiser", "Kreuzzüge"],
    ),
    e(
        "Heinrich der Löwe", "Генрих Лев", 1180,
        "Staufer", "Штауфены",
        "Herzog von Sachsen und Bayern, mächtigster Fürst neben dem Kaiser", "герцог Саксонии и Баварии",
        "seine Absetzung durch Kaiser Barbarossa und den Verlust seiner Herzogtümer", "отстранение от власти Барбароссой",
        "Goslar / Chiavenna", "Гослар / Кьявенна",
        "Verweigerung der Heerfolge durch Heinrich beim Italienzug (1176)",
        "отказ Генриха следовать за императором в Италию (1176)",
        "Zerschlagung der Welfen-Hausmacht und neue Ordnung der deutschen Fürstenlandschaft",
        "разгром вельфской власти и новый порядок среди германских князей",
        "Heinrich der Löwe war der mächtigste weltliche Fürst des HRR neben Barbarossa. 1176 verweigerte er dem Kaiser die Heerfolge nach Italien – was zur Niederlage bei Legnano beitrug. 1180 verurteilte Barbarossa ihn auf dem Reichstag zu Gelnhausen: Verlust aller Lehen, dreijähriges Exil. Heinrich lebte am englischen Hof seines Schwiegervaters Heinrich II.",
        "Генрих Лев был самым могущественным светским князем рядом с Барбароссой. В 1176 году он отказал императору в военной помощи — что способствовало поражению при Леньяно. В 1180 году Барбаросса лишил его всех ленов и отправил в трёхлетнее изгнание.",
        "Heinrichs Ostpolitik war bedeutsam: Er gründete München (1158) und förderte die Kolonisation slawischer Gebiete östlich der Elbe. Der Dom zu Braunschweig und die Welfen-Bibliothek sind sein kulturelles Erbe.",
        "Генрих основал Мюнхен (1158) и содействовал колонизации славянских земель за Эльбой. Брауншвейгский собор и Вельфская библиотека — его культурное наследие.",
        "Nach Heinrichs Sturz wurden Sachsen und Bayern unter kleinere Fürsten aufgeteilt – das endete die beiden großen Stammesherzogtümer. Deutschland entwickelte sich zur Vielstaaterei, während Frankreich und England zentralisiert wurden. Das hatte langfristige Folgen bis ins 19. Jahrhundert.",
        "После падения Генриха Саксония и Бавария были разделены — конец двух великих племенных герцогств. Германия пошла по пути политической раздробленности, тогда как Франция и Англия централизовались.",
        tags=["Staufer", "Fürstentum"],
    ),
    e(
        "Friedrich II.", "Фридрих II Штауфен", 1220,
        "Staufer", "Штауфены",
        "Kaiser, König von Jerusalem, «Staunen der Welt»", "император, «чудо света»",
        "die diplomatische Rückgewinnung Jerusalems ohne Kreuzzugskampf", "дипломатическое возвращение Иерусалима без боя",
        "Jerusalem / Palermo", "Иерусалим / Палермо",
        "Exkommunikation und Druck zur Kreuzzugs-Teilnahme trotz Konflikt mit dem Papst",
        "отлучение и давление с требованием участия в крестовом походе",
        "Vertrag von Jaffa: Jerusalem für zehn Jahre unter Christenmacht",
        "Яффский договор: Иерусалим на десять лет под властью христиан",
        "Friedrich II. – dreisprachig (Latein, Arabisch, Deutsch) und Naturwissenschaftler – zog 1228 als Exkommunizierter zum Sechsten Kreuzzug. Statt zu kämpfen, verhandelte er mit Sultan al-Kamil: Der Vertrag von Jaffa (1229) sicherte Jerusalem, Bethlehem und Nazareth für zehn Jahre. Papst Gregor IX. war entsetzt über diesen Dialog mit dem «Feind».",
        "Фридрих II — трёхязычный (латынь, арабский, немецкий) учёный — в 1228 году отправился в поход, уже будучи отлучён. Вместо войны он договорился с султаном аль-Камилем: Яффский договор (1229) вернул Иерусалим, Вифлеем и Назарет на десять лет. Папа Григорий IX был возмущён диалогом с «врагом».",
        "Friedrich gründete 1224 die Universität Neapel – die erste staatliche Universität Europas. Sein Palermitaner Hof verband arabische Wissenschaft, normannische Verwaltung und christliche Kultur. Er hielt Elefanten und exotische Tiere und schrieb das erste wissenschaftliche Werk über Falknerei.",
        "В 1224 году Фридрих основал Неаполитанский университет — первый государственный вуз Европы. Его двор в Палермо сочетал арабскую науку, нормандское управление и христианскую культуру.",
        "Friedrich starb 1250; sein letzter Enkel Konradin wurde 1268 in Neapel öffentlich hingerichtet. Mit den Staufern endete das mittelalterliche Universalkaisertum in Italien. Das Süditalien fiel an Karl von Anjou.",
        "После смерти в 1250 году последний Штауфен Конрадин был публично казнён в 1268 году. Со Штауфенами закончилось средневековое универсальное господство в Италии.",
        tags=["Staufer", "Kaiser", "Kreuzzüge"],
    ),
    e(
        "Rudolf I. von Habsburg", "Рудольф I Габсбург", 1273,
        "Habsburg", "Габсбурги",
        "Erster Habsburger als römisch-deutscher König", "первый Габсбург на германском троне",
        "seine Wahl zum König und den Sieg bei Dürnkrut", "избрание королём и победа при Дюрнкруте",
        "Dürnkrut (Österreich)", "Дюрнкрут (Австрия)",
        "Zwanzigjähriges Interregnum und Chaos im Reich nach dem Ende der Staufer",
        "двадцатилетний интеррегнум после конца Штауфенов",
        "Begründung habsburgischer Hausmacht in Österreich als Grundlage eines Weltreichs",
        "основание Габсбургской власти в Австрии",
        "Nach dem Tod Konradins (1268) regierte das HRR zwanzig Jahre ohne anerkannten König. Die Kurfürsten wählten 1273 den schwachen Habsburger Rudolf als «Kontrollmonarch». Doch Rudolf schlug 1278 bei Dürnkrut den böhmischen König Přemysl Ottokar II. und vergab Österreich als Lehen an seine Söhne. Der Habsburger Aufstieg zur Weltmacht hatte begonnen.",
        "После гибели Конрадина (1268) двадцать лет не было признанного государя. В 1273 году Рудольф Габсбург избран «контрольным монархом». Но в 1278 году при Дюрнкруте он разгромил Пшемысла Оттокара II и передал Австрию сыновьям. Начался габсбургский путь к мировой державе.",
        "Rudolfs Strategie war Heiraten statt Kriege: Die Habsburger erweiterten ihr Reich durch geschickte Verbindungen. Das Sprichwort «Bella gerant alii, tu felix Austria nube» (Kriege führen andere – du glückliches Österreich heirate) fasst Jahrhunderte habsburgischer Außenpolitik zusammen.",
        "Стратегия Рудольфа: браки, а не войны. Пословица «Bella gerant alii, tu felix Austria nube» — «Пусть воюют другие, ты, счастливая Австрия, женись» — суммирует столетия Габсбургской внешней политики.",
        "Das HRR blieb Wahlmonarchie; andere Fürsten beneideten die Habsburger. Karl IV. ordnete 1356 in der Goldenen Bulle: Sieben Kurfürsten wählen den König. Das verhinderte eine automatische Habsburg-Erbfolge, die Habsburger gewannen sie aber trotzdem fast immer.",
        "Священная Римская империя осталась выборной. В 1356 году Золотая булла закрепила: семь курфюрстов избирают короля. Всё равно почти всегда побеждали Габсбурги.",
        tags=["Habsburg", "Reich"],
    ),
    e(
        "Karl IV.", "Карл IV Люксембургский", 1346,
        "Luxemburger", "Люксембурги",
        "Kaiser und Vater Böhmens", "император и «отец Богемии»",
        "die Goldene Bulle und die Kodifizierung der Königswahl", "Золотая булла и кодификация выборов короля",
        "Nürnberg / Prag", "Нюрнберг / Прага",
        "Unsicherheit der Königswahl und Machtkämpfe zwischen Fürsten",
        "нестабильность выборов и соперничество между князьями",
        "Verfassungsrechtliche Ordnung des HRR durch die Goldene Bulle (bis 1806)",
        "конституционный порядок в Священной Римской империи (до 1806 года)",
        "Karl IV. (reg. 1346–1378) erließ 1356 die Goldene Bulle – das Grundgesetz des HRR. Sie regelte: Sieben Kurfürsten wählen den König (drei geistliche: Mainz, Köln, Trier; vier weltliche: Böhmen, Pfalz, Sachsen, Brandenburg). Mehrheitswahl, keine päpstliche Bestätigung nötig. Das Gesetz blieb bis 1806 verbindlich.",
        "Карл IV (правил 1346–1378) в 1356 году издал Золотую буллу. Она установила: семь курфюрстов избирают короля (три духовных и четыре светских). Большинство голосов, без папского утверждения. Закон действовал до 1806 года.",
        "Karl machte Prag zur prachtvollen Hauptstadt Europas: Er gründete 1348 die erste Universität Mitteleuropas (Karls-Universität), baute den Veitsdom, die Karlsbrücke und das Karls-Schloss. Er sprach fünf Sprachen und gilt als «Böhmens Vater» (otec vlasti).",
        "Карл превратил Прагу в великолепную европейскую столицу. В 1348 году основал первый университет Центральной Европы, строил собор Св. Вита и Карлов мост. Говорил на пяти языках.",
        "Die Goldene Bulle ignorierte bewusst das Papsttum: Jahrhundertelang hatte die Kirche das Recht beansprucht, Königswahlen zu bestätigen. Karl schnitt diesen Anspruch still ab. Der Papst protestierte – vergebens.",
        "Золотая булла намеренно проигнорировала папство, многовека претендовавшее на утверждение выборов. Папа протестовал — безрезультатно.",
        tags=["Luxemburger", "Reich", "Recht"],
    ),
    e(
        "Wilhelm der Eroberer", "Вильгельм Завоеватель", 1066,
        "England", "Англия",
        "Herzog der Normandie und König von England", "герцог Нормандии и король Англии",
        "die Invasion Englands und die Entscheidungsschlacht bei Hastings", "завоевание Англии и битва при Гастингсе",
        "Hastings", "Гастингс",
        "Streit um den englischen Thron nach dem Tod König Eduards des Bekenners ohne Erben",
        "спор о троне после смерти бездетного Эдуарда Исповедника",
        "Begründung der normannisch-englischen Monarchie und des englischen Feudalsystems",
        "основание норманно-английской монархии и феодальной системы в Англии",
        "Am 14. Oktober 1066 schlug Wilhelm bei Hastings König Harald II., der durch einen Pfeil ums Leben kam. Harald hatte zuvor die Norweger bei Stamford Bridge besiegt und war erschöpft. Am 25. Dezember 1066 krönte sich Wilhelm in Westminster Abbey zum König. Das Domesday Book (1086) war sein Verwaltungsmeisterstück – eine landesweite Volkszählung.",
        "14 октября 1066 года Вильгельм разбил Гарольда II при Гастингсе. До этого Гарольд победил норвежцев при Стамфорд-Бридж и пришёл измотанным. 25 декабря 1066 года Вильгельм короновался в Вестминстере. «Книга страшного суда» (1086) — его шедевр управления.",
        "Das Domesday Book (1086) war beispiellos: Eine vollständige Bestandsaufnahme aller Ländereien, Besitzer und Abgaben Englands. Kein anderes europäisches Land des 11. Jahrhunderts besitzt ein ähnliches Dokument. Es ermöglichte die systematische Besteuerung und ist heute eine einzigartige historische Quelle.",
        "«Книга страшного суда» (1086) не имела аналогов: полная перепись всех земель, владельцев и повинностей Англии. Ни одна другая европейская страна XI века не имеет подобного документа.",
        "Wilhelms Sieg veränderte England sprachlich: Normannisch-Französisch wurde Sprache des Hofes, Rechts und der Oberschicht; Englisch blieb Sprache des Volkes. Die Vermischung beider schuf das reiche Vokabular des modernen Englisch.",
        "Победа Вильгельма изменила Англию лингвистически: нормандский французский стал языком власти, английский — языком народа. Их смешение создало богатый словарь современного английского.",
        "Hastings 1066", "Гастингс 1066",
        tags=["England", "Normannen", "Militär"],
    ),
    e(
        "Thomas Becket", "Томас Бекет", 1170,
        "England", "Англия",
        "Erzbischof von Canterbury und Märtyrer", "архиепископ Кентерберийский и мученик",
        "seine Ermordung im Hohen Dom zu Canterbury", "убийство в Кентерберийском соборе",
        "Canterbury", "Кентербери",
        "Konflikt um die Gerichtsbarkeit über Kleriker zwischen König Heinrich II. und der Kirche",
        "конфликт о суде над духовенством между Генрихом II и церковью",
        "Stärkung der kirchlichen Unabhängigkeit von der englischen Krone",
        "укрепление независимости церкви от английской короны",
        "Becket war zunächst Heinrichs II. engster Freund und Kanzler. 1162 zum Erzbischof ernannt, wechselte er die Seiten. Er widersetzte sich den Konstitutionen von Clarendon (1164), die Kleriker der weltlichen Gerichtsbarkeit unterwerfen wollten. Im Dezember 1170 erschlugen vier Ritter ihn im Dom – vermutlich nach Heinrichs Wort: «Wer befreit mich von diesem lästigen Priester?»",
        "Бекет был другом и канцлером Генриха II, но после назначения архиепископом в 1162 году стал защищать права церкви. Он отверг Кларендонские конституции (1164). В декабре 1170 года четыре рыцаря убили его в соборе — предположительно после слов Генриха: «Кто избавит меня от этого беспокойного священника?»",
        "Beckets Tod wurde sofort als Martyrium gewertet: 1173 heiliggesprochen. Canterbury zog Pilger aus ganz Europa an. Geoffrey Chaucer nutzte eine Pilgerreise dorthin als Rahmen für seine «Canterbury Tales» (1387–1400). Das Grab wurde zu einem der reichsten Wallfahrtsorte Europas.",
        "Смерть Бекета немедленно назвали мученичеством: канонизирован в 1173 году. Кентербери привлёк паломников со всей Европы. Чосер использовал паломничество туда как рамку «Кентерберийских рассказов».",
        "Heinrich II. musste 1172 öffentlich büßen: Er zog barfuß nach Canterbury und ließ sich von Mönchen geißeln – symbolische Unterwerfung unter das heilige Recht. Trotzdem blieb er König. Becket wurde erst unter Heinrich VIII. 1538 dekanonisiert und seine Gebeine vernichtet.",
        "В 1172 году Генрих публично покаялся: пришёл в Кентербери босым. Святым статусом Бекета пользовались все, кроме Генриха VIII, который в 1538 году деканонизировал его.",
        tags=["England", "Kirche"],
    ),
    e(
        "Eleonore von Aquitanien", "Алиенора Аквитанская", 1152,
        "Frankreich / England", "Франция / Англия",
        "Königin von Frankreich und England, mächtigste Frau des Mittelalters", "королева Франции и Англии",
        "ihre politische Rolle zwischen Ludwig VII. und Heinrich II.", "её политическая роль между двумя королями",
        "Paris / London / Poitiers", "Париж / Лондон / Пуатье",
        "Heiraten und Machtpolitik der feudalen Eliten",
        "браки и политика феодальных элит",
        "Verbindung Aquitaniens mit England und Förderung der höfischen Kultur",
        "соединение Аквитании с Англией и покровительство куртуазной культуре",
        "Eleonore (ca. 1122–1204) heiratete zuerst Ludwig VII. von Frankreich, nahm am Zweiten Kreuzzug (1147) teil und ließ sich 1152 wegen «Blutsverwandtschaft» scheiden. Acht Wochen später heiratete sie Heinrich II. von England und brachte das riesige Aquitanien mit. Sie war Mutter von Richard Löwenherz und Johann Ohneland. Heinrich ließ sie 1173–1189 in Haft, weil sie ihre Söhne gegen ihn aufgewiegelt hatte.",
        "Алиенора (ок. 1122–1204) сначала вышла за Людовика VII, участвовала во втором крестовом походе (1147) и в 1152 году развелась. Восемь недель спустя вышла за Генриха II, принеся Аквитанию. Она мать Ричарда Львиное Сердце и Иоанна. Генрих держал её в заточении в 1173–1189 за поддержку мятежных сыновей.",
        "Eleonore war Patronin der Troubadour-Kultur: Ihr Hof in Poitiers wurde zum Zentrum der Minnedichtung. Bernart de Ventadorn, einer der berühmtesten Troubadoure, war ihr Höfling. Ihr Hof institutionalisierte die «Liebesgerichte» – literarische Debatten über höfische Liebe.",
        "Двор Алиеноры в Пуатье стал центром куртуазной любовной лирики. Знаменитый трубадур Бернарт де Вентадорн был её придворным. Там же возникли «суды любви» — литературные дебаты о куртуазии.",
        "Eleonore starb 1204 mit etwa 82 Jahren – ungewöhnlich alt für das Mittelalter. Noch kurz zuvor hatte sie die Pyrenäen überquert, um ihrer Enkelin eine gute Heirat zu sichern. Sie ist in der Abtei Fontevraud begraben, neben Heinrich II. und Richard.",
        "Алиенора умерла около 1204 года в 82 года — редкость для Средневековья. Перед смертью перешла Пиренеи, чтобы устроить брак внучки. Похоронена в Фонтевро рядом с Генрихом II и Ричардом.",
        tags=["Frankreich", "England", "Frauengeschichte"],
    ),
    e(
        "Philipp II. August", "Филипп II Август", 1180,
        "Frankreich", "Франция",
        "König, der Frankreich zur Großmacht machte", "король, превративший Францию в великую державу",
        "die Schlacht bei Bouvines und die Ausdehnung der Krondomäne", "битва при Бувине и расширение королевского домена",
        "Bouvines", "Бувин",
        "Übergewicht englisch-normannischer Macht auf französischem Territorium",
        "преобладание англо-нормандской мощи на французской земле",
        "Frankreich zur stärksten Monarchie Westeuropas nach Bouvines (1214)",
        "Франция — сильнейшая монархия Западной Европы после Бувина (1214)",
        "Philipp II. (reg. 1180–1223) verdreifachte die Krondomäne. Er nutzte Konflikte innerhalb der Plantagenets: 1202–1204 konfiszierte er englische Besitzungen in Frankreich. Am 27. Juli 1214 schlug er bei Bouvines die Koalition aus Kaiser Otto IV., König Johann und flandrischen Grafen – der erste große «nationale» Sieg Frankreichs.",
        "Филипп II (правил 1180–1223) утроил королевский домен, используя конфликты Плантагенетов. 27 июля 1214 года при Бувине разгромил коалицию — Оттона IV, Иоанна и фламандцев. Первая великая «национальная» победа Франции.",
        "Bouvines war außergewöhnlich: Philipp kämpfte selbst mit und wurde kurz gefangen genommen – dann von seinem Gefolge befreit. Erstmals kämpften Ritter und Fußvolk gemeinsam als «Franzosen». Die Engländer flohen; Johanns Niederlage stärkte die Barone und führte zur Magna Carta (1215).",
        "При Бувине Филипп лично дрался и был ненадолго захвачен. Впервые рыцари и пехота сражались как «французы». Поражение Иоанна подтолкнуло баронов к Магне Карте (1215).",
        "Philipp erbaute die erste Befestigung des Louvre und ließ Paris pflastern – die Stadthauptstraße war berüchtigt für Schlamm. Er förderte die Pariser Universität und machte Paris zur wichtigsten Stadt nördlich der Alpen.",
        "Филипп построил первые укрепления Лувра и вымостил улицы Парижа, известного своей грязью. Он сделал Париж важнейшим городом к северу от Альп.",
        "Bouvines 1214", "Битва при Бувине 1214",
        tags=["Frankreich", "Militär", "Kapetinger"],
    ),
    e(
        "Richard I. Löwenherz", "Ричард I Львиное Сердце", 1189,
        "Kreuzzüge", "Крестовые походы",
        "König von England und Anführer des Dritten Kreuzzugs", "король Англии и предводитель третьего крестового похода",
        "den Dritten Kreuzzug und die Belagerung von Akkon", "третий крестовый поход и осада Акры",
        "Akkon / Palästina", "Акра / Палестина",
        "Saladins Rückeroberung Jerusalems (1187) und der päpstliche Ruf zum Kreuzzug",
        "возвращение Иерусалима Саладином (1187) и призыв папы к походу",
        "Waffenstillstand mit Saladin: Pilgerzugang nach Jerusalem ohne Rückeroberung",
        "перемирие с Саладином: паломничество без возвращения Иерусалима",
        "Richard I. gilt als Inbegriff des Kreuzfahrers, verbrachte aber kaum sechs Monate in England. Er eroberte Zypern (1191) und Akkon, besiegte Saladin bei Arsouf und kam zweimal bis auf 12 km an Jerusalem heran – zog sich aber zurück, weil eine Belagerung ohne Nachschub sinnlos war. Der Frieden von Ramla (1192) sicherte Pilgern Zugang.",
        "Ричард — воплощение крестоносца, хотя провёл в Англии едва шесть месяцев. Он взял Кипр и Акру, победил Саладина при Арсуфе и дважды подходил к Иерусалиму на 12 км — и отступал, понимая бессмысленность осады без снабжения. Рамльский мир (1192) обеспечил паломникам доступ.",
        "Auf dem Heimweg wurde Richard von Herzog Leopold von Österreich gefangen genommen – den er in Akkon öffentlich beleidigt hatte. Er wurde Kaiser Heinrich VI. übergeben. Das Lösegeld betrug 150 000 Silbermark – fast das Dreifache des englischen Jahreseinkommens. Es wurde durch Sondersteuern aufgebracht.",
        "На обратном пути Ричард попал в плен к герцогу Леопольду Австрийскому — которого публично оскорбил в Акре — и был передан Генриху VI. Выкуп — 150 000 марок серебра, втрое больше годового дохода Англии.",
        "Richard starb 1199 bei der Belagerung eines unbedeutenden Schlosses in Frankreich durch einen Armbrustbolzen. Sein Herz wurde in der Kathedrale von Rouen begraben, sein Leib in Fontevraud. Trotz seiner kurzen Zeit in England wurde er zur nationalen Legende.",
        "Ричард умер в 1199 году от арбалетного болта при осаде незначительного замка. Его сердце похоронено в Руане, тело — в Фонтевро. Несмотря на краткое пребывание в Англии, стал национальной легендой.",
        tags=["England", "Kreuzzüge", "Militär"],
    ),
    e(
        "Magna Carta", "Магна Карта", 1215,
        "England", "Англия",
        "Grundurkunde der englischen Freiheiten", "основополагающая хартия английских свобод",
        "die Unterzeichnung der Magna Carta durch König Johann in Runnymede", "подписание хартии королём Иоанном",
        "Runnymede", "Раннимид",
        "Willkürliche Besteuerung und Feudalrechtsverletzungen durch König Johann Ohneland",
        "произвол Иоанна в налогах и нарушение феодальных прав",
        "Begrenzung der Königsmacht durch Recht und Verfahren; Vorläufer des Rechtsstaats",
        "ограничение королевской власти законом; предтеча правового государства",
        "Im Juni 1215 erzwangen englische Barone König Johann die Unterzeichnung der Magna Carta. Die 63 Klauseln schützten Feudalrechte, verboten willkürliche Verhaftung und stellten den König unter das Gesetz. Johann widerrief sofort mit päpstlichem Segen – doch nach seinem Tod 1216 wurde die Charta wiederholt bestätigt und wurde Verfassungsgrundlage.",
        "В июне 1215 года бароны вынудили Иоанна Безземельного подписать хартию. Её 63 статьи защищали феодальные права, запрещали произвольный арест и ставили короля под закон. Иоанн немедленно аннулировал документ, но после его смерти (1216) хартию неоднократно подтверждали.",
        "Klausel 39 ist die wichtigste: «Kein freier Mann soll verhaftet, eingesperrt, enteignet... werden ohne ein rechtmäßiges Urteil seiner Standesgenossen oder das Gesetz des Landes.» Dieses Prinzip lebt in allen modernen Verfassungen, dem Habeas-Corpus-Akt (1679) und der UN-Menschenrechtserklärung (1948) fort.",
        "Статья 39 — важнейшая: «Ни один свободный человек не будет арестован... иначе как по законному приговору равных ему или по закону страны». Этот принцип живёт в конституциях, «Хабеас Корпус» (1679) и Декларации ООН (1948).",
        "Nur vier Exemplare der ursprünglichen Urkunde sind erhalten. Im 17. Jahrhundert beriefen sich Parlamentarier auf sie im Kampf gegen Karl I. – und schufen den Mythos, der 1215 zur Geburtsstunde moderner Demokratie erklärte. Historisch war sie ein Feudaldokument, das nur freie Männer schützte.",
        "Сохранились четыре оригинала. В XVII веке парламентарии ссылались на хартию в борьбе с Карлом I — и создали миф. Исторически она была феодальным документом, защищавшим лишь свободных мужчин.",
        tags=["England", "Recht", "Freiheit"],
    ),
    e(
        "Innocenz III.", "Иннокентий III", 1198,
        "Papst", "Папство",
        "mächtigster Papst des Mittelalters", "самый могущественный папа Средневековья",
        "das Vierte Laterankonzil und die Ausübung päpstlicher Suprematie", "IV Латеранский собор и утверждение папского верховенства",
        "Rom", "Рим",
        "Stärkung des Reformpapsttums und Schwäche der weltlichen Macht",
        "усиление реформированного папства",
        "Höhepunkt mittelalterlicher Theokratie: Papst setzt Kaiser ab und verleiht Lehen",
        "вершина средневековой теократии: папа низлагает королей",
        "Innocenz III. (1198–1216) war einer der einflussreichsten Päpste der Geschichte. Er setzte Kaiser Otto IV. ab, erklärte England zum päpstlichen Lehen, rief den Vierten (1202), den Albigenserkreuzzug (1209) und den Kinderkreuzzug (1212) aus. Das Vierte Laterankonzil (1215) war sein Meisterwerk: Transsubstantiation, Jahresbeichte, Inquisition und Kennzeichnung von Juden.",
        "Иннокентий III (1198–1216) — один из самых влиятельных пап. Низложил Оттона IV, объявил Англию папским леном, инициировал четвёртый крестовый поход (1202) и альбигойский (1209). IV Латеранский собор (1215) закрепил пресуществление, ежегодную исповедь, инквизицию и ношение знаков евреями.",
        "Der Albigenserkreuzzug (1209–1229) – von Innocenz initiiert – vernichtete die Katharer-Häresie und den südfranzösischen Kulturraum. Bei der Einnahme von Béziers 1209 soll der päpstliche Legat gesagt haben: «Tötet alle – Gott erkennt die Seinen.» Ob echt oder nicht – er zeigt den Geist des Unternehmens.",
        "Альбигойский крестовый поход (1209–1229) уничтожил катаров и южнофранцузскую культуру. При взятии Безье (1209) папский легат якобы сказал: «Убивайте всех — Бог распознает своих».",
        "Innocenz formulierte die Theorie, Könige seien Vasallen des Papstes. Er nannte sich erstmals konsequent «Vicarius Christi» (Stellvertreter Christi) – ein theologischer Anspruch auf unbeschränkte Suprematie. Diese Theorie blieb bis zur Reformation das Hauptschlachtfeld zwischen Kirche und weltlichen Herrschern.",
        "Иннокентий последовательно именовал себя «Vicarius Christi» — богословская претензия на верховную власть. Эта теория оставалась главным полем битвы церкви и светских правителей вплоть до Реформации.",
        tags=["Papst", "Kirche", "Kreuzzüge"],
    ),
    e(
        "Ludwig IX. der Heilige", "Людовик IX Святой", 1226,
        "Frankreich", "Франция",
        "König und Heiliger, Ideal des mittelalterlichen christlichen Herrschers", "король и святой, идеал христианского правителя",
        "den Siebten Kreuzzug und seine Gefangenschaft in Ägypten", "седьмой крестовый поход и плен в Египте",
        "Ägypten / Damiette", "Египет / Дамиетта",
        "Religiöser Idealismus und Wunsch nach Rückeroberung des Heiligen Landes",
        "религиозный идеализм и стремление вернуть Святую землю",
        "Scheitern des Kreuzzugsgedankens und Ludwigs Tod in Tunis",
        "крах идеи крестового похода и гибель Людовика под Тунисом",
        "Ludwig IX. (reg. 1226–1270) baute die Sainte-Chapelle für die Dornenkrone, reformierte Justiz und Verwaltung, verbannte Prostitution und Glücksspiel. 1248 brach er zum Siebten Kreuzzug auf, wurde bei al-Mansura (1250) von den Mamluken gefangen, zahlte 400 000 Livres Lösegeld und blieb noch vier Jahre in Palästina. 1270 starb er an Typhus vor Tunis.",
        "Людовик IX построил Сен-Шапель для тернового венца, реформировал правосудие. В 1248 году отправился в седьмой поход, при аль-Мансуре (1250) попал в плен к мамлюкам, заплатил 400 000 ливров выкупа. В 1270 году умер от тифа под Тунисом.",
        "Die Niederlage bei al-Mansura (1250) war eine militärische Katastrophe: Das gesamte Heer und der König wurden gefangen. Ludwig lehnte an, die Türme Damiettes zu tauschen, aber die Mamluken bestanden auf dem vollen Lösegeld. Er kam vier Jahre nach Palästina, um die Kreuzfahrerstaaten zu stärken.",
        "Разгром при аль-Мансуре (1250) был полной катастрофой: вся армия и король в плену. Людовик провёл четыре года в Палестине после выкупа, укрепляя крестоносные государства.",
        "Ludwig wurde 1297 heiliggesprochen – schnell. Seine Heiligkeit war politisch nützlich: Sie adelte die kapetingische Dynastie. Sein Bild vom «allerchristen König» (rex christianissimus) blieb das Leitbild französischer Könige bis zur Revolution.",
        "Канонизирован в 1297 году — быстро. Его святость легитимировала Капетингов. Образ «христианнейшего короля» оставался идеалом французских государей до Революции.",
        tags=["Frankreich", "Kreuzzüge", "Religion"],
    ),
    e(
        "Philipp IV. der Schöne", "Филипп IV Красивый", 1285,
        "Frankreich", "Франция",
        "König, der den Templerorden vernichtete und das Papsttum nach Avignon zwang", "король, уничтоживший тамплиеров",
        "die Verhaftung und Vernichtung des Templerordens", "арест и уничтожение ордена тамплиеров",
        "Paris / Avignon", "Париж / Авиньон",
        "Schulden des Königs beim Templerorden und Machtkämpfe mit dem Papst",
        "долги короля тамплиерам и борьба с папой",
        "Ende des Templerordens und Avignonisches Exil des Papsttums (1309–1377)",
        "конец ордена тамплиеров и авиньонский период папства (1309–1377)",
        "Philipp IV. (reg. 1285–1314) ließ am 13. Oktober 1307 alle Templer Frankreichs verhaften, unter Folter als Ketzer beschuldigt und 1312 den Orden aufgelöst. Großmeister Jakob de Molay starb 1314 auf dem Scheiterhaufen. Zuvor hatte Philipp 1303 Papst Bonifaz VIII. in Anagni verhaften lassen und den Papst nach Avignon gebracht.",
        "Филипп IV 13 октября 1307 года велел арестовать всех тамплиеров Франции, под пытками обвинить в ереси. В 1312 году орден распущен, Великий магистр Жак де Моле сожжён в 1314 году. Ранее в 1303 году Филипп арестовал Бонифация VIII в Ананьи и перенёс папский двор в Авиньон.",
        "Die «Verhaftung von Anagni» (1303) schockte Europa: Philipps Söldner tätlich angriffen die Papst-Delegation. Bonifaz VIII. starb Wochen später. Es war das erste Mal, dass ein Papst so offen misshandelt wurde – ein Symbol für das Ende der mittelalterlichen Theokratie.",
        "Арест в Ананьи (1303) потряс Европу: папских посланцев избили наёмники Филиппа. Бонифаций VIII умер вскоре. Впервые папа так открыто унижен — символ заката средневековой теократии.",
        "De Molays angeblicher Sterbensfluch – er zitierte König und Papst vor Gottes Gericht – faszinierte die Nachwelt: Clemens V. starb sieben Wochen später, Philipp im selben Jahr. Die «Fluch der Templer»-Legende wurde zum beliebtesten Verschwörungsmythos der Geschichte.",
        "Предсмертное «проклятие де Моле» — он призвал короля и папу на суд Бога — захватило воображение потомков: Климент V умер через семь недель, Филипп — в том же году.",
        tags=["Frankreich", "Kirche", "Ordenswesen"],
    ),
    e(
        "Johanna von Orléans", "Жанна д'Арк", 1429,
        "Hundertjähriger Krieg", "Столетняя война",
        "Jungfrau von Orléans und Nationalheilige Frankreichs", "Орлеанская дева, национальная святая Франции",
        "die Entsetzung Orléans und die Krönung Karls VII.", "снятие осады Орлеана и коронация Карла VII",
        "Orléans / Reims", "Орлеан / Реймс",
        "Englische Belagerung von Orléans und Krise der französischen Herrschaft",
        "английская осада Орлеана и кризис французской власти",
        "Wende im Hundertjährigen Krieg zugunsten Frankreichs",
        "перелом в Столетней войне в пользу Франции",
        "Johanna (ca. 1412–1431) hörte Stimmen von Heiligen, die ihr befahlen, Frankreich zu retten. 1429 überredete sie den Dauphin Karl, ihr ein Heer anzuvertrauen. Sie befreite Orléans und führte Karl zur Krönung in Reims. 1430 von den Burgundern gefangen, wurde sie von den Engländern als Ketzerin verurteilt und auf dem Scheiterhaufen verbrannt.",
        "Жанна (ок. 1412–1431) слышала голоса святых, велевших ей спасти Францию. В 1429 году убедила дофина Карла дать ей войско. Она освободила Орлеан и привела Карла к коронации в Реймсе. В 1430 году захвачена бургундцами, осуждена англичанами как еретичка и сожжена.",
        "Johannas Verurteilung war ein Schauprozess: Das englisch-burgundische Tribunal wollte politisch legitimieren, was militärisch nicht gelungen war. 1456 annullierte ein päpstlicher Prozess das Urteil posthum. 1920 wurde Johanna heiliggesprochen.",
        "Процесс над Жанной был политическим: трибунал хотел легитимизировать то, чего не удалось добиться военным путём. В 1456 году папа посмертно отменил приговор. В 1920 году Жанна канонизирована.",
        "Johanna wurde zum Nationalsymbol: Napoleon nutzte sie, die Republikaner, die Monarchisten und später das Vichy-Regime beanspruchten sie alle für sich. Sie zeigt, wie eine historische Figur zum Spielball nationaler Mythen wird.",
        "Жанна стала национальным символом: Наполеон, республиканцы, монархисты и режим Виши — все её присваивали. Пример того, как историческая личность превращается в инструмент национальных мифов.",
        tags=["Hundertjähriger Krieg", "Frankreich", "Frauen"],
    ),
    e(
        "Heinrich V. von England", "Генрих V Английский", 1415,
        "Hundertjähriger Krieg", "Столетняя война",
        "König und Sieger von Azincourt", "король и победитель при Азенкуре",
        "die Schlachtfeldsieg bei Azincourt und den Vertrag von Troyes", "победа при Азенкуре и Труасский договор",
        "Azincourt / Troyes", "Азенкур / Труа",
        "Dynastische Ansprüche der englischen Krone auf den französischen Thron",
        "наследственные претензии Англии на французский трон",
        "Vertrag von Troyes (1420): Heinrich als Erbe des französischen Throns",
        "Труасский договор (1420): Генрих — наследник французского трона",
        "Am 25. Oktober 1415 besiegte Heinrich V. bei Azincourt ein weit überlegenes französisches Ritterheer mit englischen Langbogenschützen. Die Verluste: ca. 6 000 Franzosen, unter 500 Engländer. Der Vertrag von Troyes (1420) machte Heinrich zum Erben Frankreichs und Ehemann der Prinzessin Katharina. Er starb 1422, bevor er König werden konnte.",
        "25 октября 1415 года при Азенкуре английские лучники уничтожили превосходящую французскую рыцарскую армию. Потери: около 6000 французов, менее 500 англичан. Труасский договор (1420) сделал Генриха наследником Франции. Он умер в 1422 году, не успев стать королём.",
        "Azincourt war eine Katastrophe für den französischen Adel: Drei Herzöge, neun Grafen und über 1 500 Ritter fielen. Das englische Langbogensystem, das Ritter im Schlamm aufhielt und dann systematisch tötete, bewies wieder: Technologie und Disziplin schlagen Standesarroganz.",
        "Азенкур стал катастрофой для французского дворянства: три герцога, девять графов, более 1500 рыцарей погибли. Английские луки снова доказали: технология и дисциплина побеждают рыцарскую спесь.",
        "Shakespeare verewigte Azincourt in «Heinrich V.» (ca. 1599) mit der «Band of Brothers»-Rede. Diese literarische Verklärung machte den Sieg zum Mythos englischer nationaler Identität, der bis heute fortwirkt.",
        "Шекспир увековечил Азенкур в «Генрихе V» (ок. 1599) с речью «братства по оружию». Эта поэтизация превратила победу в миф английской национальной идентичности.",
        tags=["England", "Hundertjähriger Krieg", "Militär"],
    ),
    e(
        "Karl VII. von Frankreich", "Карл VII Французский", 1429,
        "Hundertjähriger Krieg", "Столетняя война",
        "König von Frankreich, der den Hundertjährigen Krieg gewann", "король, выигравший Столетнюю войну",
        "die Krönung in Reims und die endgültige Vertreibung der Engländer", "коронация в Реймсе и изгнание англичан",
        "Reims / Bordeaux", "Реймс / Бордо",
        "Englisch-burgundische Kontrolle großer Teile Frankreichs",
        "англо-бургундский контроль над большей частью Франции",
        "Ende des Hundertjährigen Krieges und Frankreich als geeinte Monarchie",
        "конец Столетней войны и Франция как единая монархия",
        "Karl VII. (reg. 1422–1461) wurde durch Johannas Eingriff 1429 in Reims gekrönt – politisch entscheidend, weil Krönung in Reims die Legitimität sicherte. Er nutzte den Tod Philipps des Guten, um ein Abkommen mit Burgund zu schließen. 1453 fiel Bordeaux – das Ende des Hundertjährigen Krieges. Nur Calais blieb englisch.",
        "Карл VII (правил 1422–1461) коронован в Реймсе в 1429 году благодаря Жанне. В 1453 году пал Бордо — конец Столетней войны. Лишь Кале остался в руках Англии.",
        "Karl reformierte das Militär grundlegend: Er schuf das erste stehende Berufsheer Frankreichs mit regulär bezahlten Soldaten. Die neue Artillerie (Bureau-Brüder) war entscheidend für die Rückeroberung der Normandie (1450) und Aquitaniens (1453).",
        "Карл реформировал армию: создал первое постоянное войско с профессиональными солдатами. Новая артиллерия братьев Бюро сыграла решающую роль в отвоевании Нормандии (1450) и Аквитании (1453).",
        "Der Hundertjährige Krieg (1337–1453) war kein ununterbrochener Kampf: Er bestand aus mehreren Waffenstillständen und Phasen. Er forderte Hunderttausende Todesopfer durch Kämpfe, Pest und Hunger und formte das Nationalbewusstsein Frankreichs und Englands.",
        "Столетняя война (1337–1453) — не непрерывная борьба, а серия конфликтов с перемириями. Она унесла сотни тысяч жизней и сформировала национальное сознание Франции и Англии.",
        tags=["Frankreich", "Hundertjähriger Krieg"],
    ),
]
